(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite2 - satellite
	instrument13 - instrument
	instrument14 - instrument
	satellite3 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite4 - satellite
	instrument21 - instrument
	instrument22 - instrument
	satellite5 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite6 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite7 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	satellite8 - satellite
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	satellite9 - satellite
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	image1 - mode
	thermograph3 - mode
	thermograph4 - mode
	thermograph0 - mode
	thermograph2 - mode
	Star4 - direction
	GroundStation2 - direction
	Star1 - direction
	Star0 - direction
	Star3 - direction
	Phenomenon5 - direction
	Planet6 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 thermograph2)
	(supports instrument0 image1)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 thermograph3)
	(supports instrument1 thermograph0)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 Star4)
	(supports instrument2 thermograph0)
	(supports instrument2 thermograph3)
	(calibration_target instrument2 Star4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 Star3)
	(supports instrument4 thermograph3)
	(calibration_target instrument4 GroundStation2)
	(supports instrument5 thermograph2)
	(calibration_target instrument5 Star4)
	(supports instrument6 image1)
	(supports instrument6 thermograph4)
	(supports instrument6 thermograph3)
	(calibration_target instrument6 Star4)
	(supports instrument7 thermograph2)
	(supports instrument7 thermograph4)
	(supports instrument7 thermograph3)
	(calibration_target instrument7 Star1)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 Star0)
	(supports instrument9 thermograph2)
	(calibration_target instrument9 Star0)
	(supports instrument10 image1)
	(supports instrument10 thermograph3)
	(calibration_target instrument10 Star1)
	(supports instrument11 thermograph3)
	(supports instrument11 image1)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 Star4)
	(supports instrument12 thermograph2)
	(calibration_target instrument12 Star4)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet6)
	(supports instrument13 thermograph0)
	(supports instrument13 thermograph2)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 Star4)
	(supports instrument14 image1)
	(calibration_target instrument14 Star4)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon5)
	(supports instrument15 thermograph4)
	(supports instrument15 image1)
	(supports instrument15 thermograph2)
	(calibration_target instrument15 Star1)
	(supports instrument16 image1)
	(calibration_target instrument16 Star1)
	(supports instrument17 image1)
	(supports instrument17 thermograph2)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 Star4)
	(supports instrument18 image1)
	(calibration_target instrument18 Star3)
	(supports instrument19 thermograph2)
	(calibration_target instrument19 Star4)
	(supports instrument20 thermograph0)
	(calibration_target instrument20 Star3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star0)
	(supports instrument21 image1)
	(supports instrument21 thermograph0)
	(calibration_target instrument21 Star0)
	(supports instrument22 thermograph3)
	(supports instrument22 thermograph2)
	(calibration_target instrument22 Star0)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star1)
	(supports instrument23 image1)
	(calibration_target instrument23 Star3)
	(supports instrument24 thermograph4)
	(supports instrument24 thermograph3)
	(calibration_target instrument24 Star0)
	(supports instrument25 thermograph2)
	(supports instrument25 thermograph4)
	(supports instrument25 thermograph3)
	(calibration_target instrument25 Star1)
	(supports instrument26 image1)
	(calibration_target instrument26 Star0)
	(supports instrument27 thermograph3)
	(calibration_target instrument27 Star3)
	(supports instrument28 image1)
	(calibration_target instrument28 Star4)
	(supports instrument29 thermograph0)
	(supports instrument29 image1)
	(supports instrument29 thermograph4)
	(calibration_target instrument29 Star0)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star4)
	(supports instrument30 thermograph0)
	(supports instrument30 image1)
	(supports instrument30 thermograph2)
	(calibration_target instrument30 Star3)
	(supports instrument31 thermograph0)
	(supports instrument31 image1)
	(supports instrument31 thermograph4)
	(calibration_target instrument31 GroundStation2)
	(supports instrument32 thermograph4)
	(supports instrument32 thermograph2)
	(supports instrument32 thermograph0)
	(calibration_target instrument32 Star4)
	(supports instrument33 thermograph2)
	(supports instrument33 thermograph3)
	(supports instrument33 thermograph0)
	(calibration_target instrument33 Star4)
	(supports instrument34 thermograph4)
	(calibration_target instrument34 Star1)
	(supports instrument35 thermograph0)
	(supports instrument35 thermograph4)
	(calibration_target instrument35 Star4)
	(supports instrument36 thermograph2)
	(supports instrument36 thermograph3)
	(supports instrument36 thermograph4)
	(calibration_target instrument36 Star1)
	(supports instrument37 image1)
	(calibration_target instrument37 Star4)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet6)
	(supports instrument38 thermograph2)
	(supports instrument38 thermograph4)
	(calibration_target instrument38 Star4)
	(supports instrument39 thermograph3)
	(supports instrument39 thermograph4)
	(calibration_target instrument39 Star4)
	(supports instrument40 image1)
	(calibration_target instrument40 Star1)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star3)
	(supports instrument41 thermograph0)
	(calibration_target instrument41 Star4)
	(supports instrument42 thermograph0)
	(supports instrument42 thermograph3)
	(calibration_target instrument42 GroundStation2)
	(supports instrument43 thermograph2)
	(calibration_target instrument43 Star3)
	(supports instrument44 thermograph4)
	(supports instrument44 image1)
	(supports instrument44 thermograph3)
	(calibration_target instrument44 GroundStation2)
	(supports instrument45 thermograph0)
	(supports instrument45 image1)
	(calibration_target instrument45 Star4)
	(supports instrument46 thermograph3)
	(supports instrument46 thermograph0)
	(calibration_target instrument46 Star0)
	(supports instrument47 thermograph0)
	(supports instrument47 image1)
	(calibration_target instrument47 Star0)
	(supports instrument48 thermograph0)
	(calibration_target instrument48 GroundStation2)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star1)
	(supports instrument49 thermograph4)
	(calibration_target instrument49 Star0)
	(supports instrument50 thermograph3)
	(calibration_target instrument50 GroundStation2)
	(supports instrument51 thermograph4)
	(supports instrument51 thermograph0)
	(supports instrument51 thermograph2)
	(calibration_target instrument51 Star3)
	(supports instrument52 thermograph3)
	(calibration_target instrument52 Star1)
	(supports instrument53 thermograph2)
	(calibration_target instrument53 Star0)
	(supports instrument54 thermograph3)
	(calibration_target instrument54 Star0)
	(supports instrument55 thermograph2)
	(supports instrument55 thermograph0)
	(supports instrument55 thermograph4)
	(calibration_target instrument55 Star3)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon5)
)
(:goal (and
	(pointing satellite1 Phenomenon5)
	(pointing satellite2 Star4)
	(pointing satellite8 GroundStation2)
	(pointing satellite9 GroundStation2)
	(have_image Phenomenon5 thermograph4)
))

)
