(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite2 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite3 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite4 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite5 - satellite
	instrument36 - instrument
	instrument37 - instrument
	satellite6 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite7 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	satellite8 - satellite
	instrument58 - instrument
	instrument59 - instrument
	satellite9 - satellite
	instrument60 - instrument
	infrared1 - mode
	image3 - mode
	spectrograph0 - mode
	image2 - mode
	image4 - mode
	GroundStation2 - direction
	Star0 - direction
	Star3 - direction
	GroundStation1 - direction
	GroundStation4 - direction
	Star5 - direction
	Planet6 - direction
)
(:init
	(supports instrument0 spectrograph0)
	(supports instrument0 image4)
	(calibration_target instrument0 Star0)
	(supports instrument1 infrared1)
	(supports instrument1 image3)
	(supports instrument1 image4)
	(calibration_target instrument1 Star3)
	(supports instrument2 image4)
	(calibration_target instrument2 GroundStation4)
	(supports instrument3 image4)
	(supports instrument3 image2)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 image3)
	(supports instrument4 image4)
	(calibration_target instrument4 GroundStation4)
	(supports instrument5 infrared1)
	(supports instrument5 image4)
	(calibration_target instrument5 GroundStation1)
	(supports instrument6 image4)
	(supports instrument6 spectrograph0)
	(supports instrument6 image2)
	(calibration_target instrument6 GroundStation1)
	(supports instrument7 image3)
	(supports instrument7 infrared1)
	(supports instrument7 image2)
	(calibration_target instrument7 GroundStation4)
	(supports instrument8 image3)
	(supports instrument8 image2)
	(calibration_target instrument8 GroundStation4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation1)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 GroundStation4)
	(supports instrument10 image4)
	(supports instrument10 spectrograph0)
	(calibration_target instrument10 GroundStation4)
	(supports instrument11 infrared1)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 Star3)
	(supports instrument12 image2)
	(supports instrument12 image4)
	(calibration_target instrument12 GroundStation4)
	(supports instrument13 infrared1)
	(calibration_target instrument13 GroundStation4)
	(supports instrument14 infrared1)
	(supports instrument14 spectrograph0)
	(supports instrument14 image3)
	(calibration_target instrument14 GroundStation2)
	(supports instrument15 image3)
	(supports instrument15 image4)
	(supports instrument15 infrared1)
	(calibration_target instrument15 Star0)
	(supports instrument16 image2)
	(supports instrument16 image3)
	(calibration_target instrument16 GroundStation2)
	(supports instrument17 image3)
	(supports instrument17 image4)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 GroundStation1)
	(supports instrument18 image2)
	(supports instrument18 spectrograph0)
	(supports instrument18 infrared1)
	(calibration_target instrument18 GroundStation4)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(on_board instrument17 satellite1)
	(on_board instrument18 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet6)
	(supports instrument19 image4)
	(supports instrument19 infrared1)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 image3)
	(supports instrument20 spectrograph0)
	(supports instrument20 image2)
	(calibration_target instrument20 GroundStation1)
	(supports instrument21 image4)
	(calibration_target instrument21 GroundStation1)
	(supports instrument22 image2)
	(calibration_target instrument22 Star0)
	(supports instrument23 image3)
	(calibration_target instrument23 GroundStation1)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(on_board instrument22 satellite2)
	(on_board instrument23 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument24 spectrograph0)
	(supports instrument24 image3)
	(calibration_target instrument24 GroundStation4)
	(supports instrument25 image2)
	(supports instrument25 spectrograph0)
	(calibration_target instrument25 GroundStation1)
	(supports instrument26 image2)
	(supports instrument26 spectrograph0)
	(calibration_target instrument26 Star0)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star0)
	(supports instrument27 image2)
	(supports instrument27 infrared1)
	(supports instrument27 image3)
	(calibration_target instrument27 GroundStation4)
	(supports instrument28 spectrograph0)
	(supports instrument28 image3)
	(supports instrument28 infrared1)
	(calibration_target instrument28 Star3)
	(supports instrument29 spectrograph0)
	(calibration_target instrument29 Star3)
	(supports instrument30 image3)
	(supports instrument30 image2)
	(calibration_target instrument30 Star3)
	(supports instrument31 spectrograph0)
	(calibration_target instrument31 Star0)
	(supports instrument32 image4)
	(supports instrument32 infrared1)
	(supports instrument32 spectrograph0)
	(calibration_target instrument32 Star3)
	(supports instrument33 spectrograph0)
	(supports instrument33 image4)
	(supports instrument33 image2)
	(calibration_target instrument33 GroundStation2)
	(supports instrument34 infrared1)
	(supports instrument34 image3)
	(supports instrument34 image2)
	(calibration_target instrument34 Star0)
	(supports instrument35 infrared1)
	(supports instrument35 image2)
	(supports instrument35 spectrograph0)
	(calibration_target instrument35 Star0)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation4)
	(supports instrument36 image4)
	(calibration_target instrument36 Star0)
	(supports instrument37 image3)
	(supports instrument37 infrared1)
	(calibration_target instrument37 GroundStation4)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation4)
	(supports instrument38 spectrograph0)
	(supports instrument38 infrared1)
	(supports instrument38 image2)
	(calibration_target instrument38 Star0)
	(supports instrument39 image4)
	(calibration_target instrument39 Star0)
	(supports instrument40 image3)
	(calibration_target instrument40 GroundStation4)
	(supports instrument41 image2)
	(calibration_target instrument41 GroundStation4)
	(supports instrument42 spectrograph0)
	(supports instrument42 image4)
	(calibration_target instrument42 GroundStation1)
	(supports instrument43 image2)
	(supports instrument43 image3)
	(calibration_target instrument43 Star0)
	(supports instrument44 spectrograph0)
	(supports instrument44 image3)
	(calibration_target instrument44 Star0)
	(supports instrument45 image3)
	(calibration_target instrument45 GroundStation2)
	(supports instrument46 image3)
	(supports instrument46 spectrograph0)
	(supports instrument46 image2)
	(calibration_target instrument46 GroundStation2)
	(supports instrument47 image4)
	(supports instrument47 image3)
	(calibration_target instrument47 Star3)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(on_board instrument46 satellite6)
	(on_board instrument47 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star5)
	(supports instrument48 image3)
	(supports instrument48 spectrograph0)
	(calibration_target instrument48 GroundStation2)
	(supports instrument49 image2)
	(calibration_target instrument49 GroundStation1)
	(supports instrument50 image4)
	(supports instrument50 image2)
	(calibration_target instrument50 Star0)
	(supports instrument51 image4)
	(calibration_target instrument51 GroundStation4)
	(supports instrument52 infrared1)
	(calibration_target instrument52 Star0)
	(supports instrument53 image4)
	(calibration_target instrument53 Star3)
	(supports instrument54 infrared1)
	(supports instrument54 spectrograph0)
	(calibration_target instrument54 GroundStation1)
	(supports instrument55 infrared1)
	(supports instrument55 image2)
	(calibration_target instrument55 GroundStation4)
	(supports instrument56 image2)
	(supports instrument56 image3)
	(calibration_target instrument56 GroundStation1)
	(supports instrument57 image2)
	(supports instrument57 image3)
	(calibration_target instrument57 GroundStation1)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(on_board instrument53 satellite7)
	(on_board instrument54 satellite7)
	(on_board instrument55 satellite7)
	(on_board instrument56 satellite7)
	(on_board instrument57 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation2)
	(supports instrument58 spectrograph0)
	(supports instrument58 image4)
	(calibration_target instrument58 Star3)
	(supports instrument59 image2)
	(supports instrument59 spectrograph0)
	(supports instrument59 image3)
	(calibration_target instrument59 GroundStation1)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star3)
	(supports instrument60 image4)
	(supports instrument60 image2)
	(supports instrument60 spectrograph0)
	(calibration_target instrument60 GroundStation4)
	(on_board instrument60 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation1)
)
(:goal (and
	(pointing satellite4 Star5)
	(pointing satellite8 GroundStation1)
	(have_image Star5 spectrograph0)
	(have_image Planet6 infrared1)
))

)
