(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite2 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite3 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite4 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite5 - satellite
	instrument38 - instrument
	instrument39 - instrument
	satellite6 - satellite
	instrument40 - instrument
	instrument41 - instrument
	satellite7 - satellite
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	satellite8 - satellite
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	satellite9 - satellite
	instrument55 - instrument
	instrument56 - instrument
	thermograph3 - mode
	thermograph0 - mode
	spectrograph4 - mode
	infrared2 - mode
	image1 - mode
	GroundStation1 - direction
	Star2 - direction
	Star0 - direction
	Planet3 - direction
	Planet4 - direction
)
(:init
	(supports instrument0 image1)
	(supports instrument0 infrared2)
	(calibration_target instrument0 Star0)
	(supports instrument1 image1)
	(supports instrument1 thermograph3)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 image1)
	(calibration_target instrument2 Star2)
	(supports instrument3 infrared2)
	(calibration_target instrument3 Star0)
	(supports instrument4 image1)
	(calibration_target instrument4 GroundStation1)
	(supports instrument5 spectrograph4)
	(supports instrument5 infrared2)
	(calibration_target instrument5 GroundStation1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(supports instrument6 thermograph3)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 Star2)
	(supports instrument7 infrared2)
	(supports instrument7 spectrograph4)
	(calibration_target instrument7 Star2)
	(supports instrument8 image1)
	(calibration_target instrument8 GroundStation1)
	(supports instrument9 thermograph0)
	(supports instrument9 infrared2)
	(calibration_target instrument9 Star0)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 image1)
	(supports instrument11 thermograph0)
	(calibration_target instrument11 GroundStation1)
	(supports instrument12 image1)
	(supports instrument12 spectrograph4)
	(calibration_target instrument12 Star2)
	(supports instrument13 infrared2)
	(supports instrument13 thermograph3)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 GroundStation1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet3)
	(supports instrument14 thermograph3)
	(calibration_target instrument14 Star2)
	(supports instrument15 thermograph3)
	(supports instrument15 thermograph0)
	(supports instrument15 infrared2)
	(calibration_target instrument15 GroundStation1)
	(supports instrument16 thermograph3)
	(supports instrument16 image1)
	(supports instrument16 spectrograph4)
	(calibration_target instrument16 Star0)
	(supports instrument17 thermograph0)
	(supports instrument17 image1)
	(supports instrument17 infrared2)
	(calibration_target instrument17 GroundStation1)
	(supports instrument18 thermograph0)
	(supports instrument18 spectrograph4)
	(supports instrument18 image1)
	(calibration_target instrument18 Star2)
	(supports instrument19 spectrograph4)
	(supports instrument19 thermograph3)
	(supports instrument19 thermograph0)
	(calibration_target instrument19 Star2)
	(supports instrument20 thermograph0)
	(supports instrument20 infrared2)
	(calibration_target instrument20 GroundStation1)
	(supports instrument21 thermograph0)
	(calibration_target instrument21 Star2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet4)
	(supports instrument22 image1)
	(supports instrument22 infrared2)
	(supports instrument22 thermograph3)
	(calibration_target instrument22 Star0)
	(supports instrument23 thermograph0)
	(calibration_target instrument23 Star0)
	(supports instrument24 spectrograph4)
	(calibration_target instrument24 GroundStation1)
	(supports instrument25 thermograph0)
	(supports instrument25 image1)
	(supports instrument25 spectrograph4)
	(calibration_target instrument25 Star2)
	(supports instrument26 image1)
	(calibration_target instrument26 GroundStation1)
	(supports instrument27 infrared2)
	(supports instrument27 spectrograph4)
	(calibration_target instrument27 Star0)
	(supports instrument28 thermograph3)
	(calibration_target instrument28 Star2)
	(supports instrument29 thermograph3)
	(calibration_target instrument29 GroundStation1)
	(supports instrument30 spectrograph4)
	(calibration_target instrument30 GroundStation1)
	(supports instrument31 spectrograph4)
	(calibration_target instrument31 Star2)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(on_board instrument30 satellite3)
	(on_board instrument31 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet3)
	(supports instrument32 spectrograph4)
	(supports instrument32 infrared2)
	(supports instrument32 image1)
	(calibration_target instrument32 Star2)
	(supports instrument33 thermograph0)
	(calibration_target instrument33 Star0)
	(supports instrument34 thermograph3)
	(supports instrument34 infrared2)
	(supports instrument34 image1)
	(calibration_target instrument34 Star2)
	(supports instrument35 thermograph0)
	(supports instrument35 thermograph3)
	(calibration_target instrument35 Star2)
	(supports instrument36 infrared2)
	(calibration_target instrument36 Star0)
	(supports instrument37 thermograph3)
	(supports instrument37 thermograph0)
	(calibration_target instrument37 GroundStation1)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(on_board instrument37 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet3)
	(supports instrument38 spectrograph4)
	(supports instrument38 thermograph0)
	(supports instrument38 image1)
	(calibration_target instrument38 Star2)
	(supports instrument39 image1)
	(calibration_target instrument39 Star0)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet3)
	(supports instrument40 infrared2)
	(supports instrument40 thermograph3)
	(calibration_target instrument40 Star0)
	(supports instrument41 infrared2)
	(calibration_target instrument41 GroundStation1)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet3)
	(supports instrument42 infrared2)
	(supports instrument42 thermograph0)
	(calibration_target instrument42 Star2)
	(supports instrument43 image1)
	(supports instrument43 spectrograph4)
	(supports instrument43 thermograph0)
	(calibration_target instrument43 GroundStation1)
	(supports instrument44 spectrograph4)
	(supports instrument44 image1)
	(supports instrument44 infrared2)
	(calibration_target instrument44 GroundStation1)
	(supports instrument45 thermograph0)
	(supports instrument45 image1)
	(calibration_target instrument45 Star0)
	(supports instrument46 image1)
	(calibration_target instrument46 Star0)
	(supports instrument47 thermograph0)
	(calibration_target instrument47 Star0)
	(supports instrument48 image1)
	(calibration_target instrument48 Star2)
	(supports instrument49 thermograph0)
	(supports instrument49 image1)
	(calibration_target instrument49 Star0)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet3)
	(supports instrument50 thermograph0)
	(supports instrument50 thermograph3)
	(supports instrument50 infrared2)
	(calibration_target instrument50 Star2)
	(supports instrument51 thermograph0)
	(supports instrument51 thermograph3)
	(supports instrument51 image1)
	(calibration_target instrument51 Star0)
	(supports instrument52 image1)
	(supports instrument52 thermograph0)
	(calibration_target instrument52 Star0)
	(supports instrument53 spectrograph4)
	(supports instrument53 infrared2)
	(calibration_target instrument53 Star2)
	(supports instrument54 image1)
	(calibration_target instrument54 Star2)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation1)
	(supports instrument55 infrared2)
	(calibration_target instrument55 Star2)
	(supports instrument56 image1)
	(supports instrument56 infrared2)
	(calibration_target instrument56 Star0)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet4)
)
(:goal (and
	(pointing satellite0 Planet4)
	(pointing satellite2 Planet3)
	(pointing satellite5 Planet4)
	(pointing satellite7 Planet4)
	(pointing satellite9 GroundStation1)
	(have_image Planet3 spectrograph4)
	(have_image Planet4 infrared2)
))

)
