(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite5 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite6 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite7 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	satellite8 - satellite
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite9 - satellite
	instrument37 - instrument
	instrument38 - instrument
	image1 - mode
	image0 - mode
	infrared3 - mode
	infrared4 - mode
	infrared2 - mode
	GroundStation0 - direction
	Star1 - direction
	GroundStation2 - direction
	Star3 - direction
	Planet4 - direction
)
(:init
	(supports instrument0 infrared2)
	(supports instrument0 image1)
	(supports instrument0 image0)
	(calibration_target instrument0 GroundStation2)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star1)
	(supports instrument1 infrared4)
	(supports instrument1 infrared3)
	(calibration_target instrument1 GroundStation0)
	(supports instrument2 infrared3)
	(supports instrument2 image1)
	(supports instrument2 image0)
	(calibration_target instrument2 GroundStation0)
	(supports instrument3 infrared3)
	(supports instrument3 infrared4)
	(supports instrument3 image1)
	(calibration_target instrument3 GroundStation2)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star3)
	(supports instrument4 image0)
	(supports instrument4 infrared4)
	(calibration_target instrument4 GroundStation2)
	(supports instrument5 image1)
	(supports instrument5 infrared2)
	(supports instrument5 image0)
	(calibration_target instrument5 GroundStation2)
	(supports instrument6 infrared2)
	(supports instrument6 image1)
	(calibration_target instrument6 GroundStation0)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument7 image1)
	(calibration_target instrument7 Star1)
	(supports instrument8 image0)
	(supports instrument8 infrared2)
	(supports instrument8 infrared4)
	(calibration_target instrument8 Star1)
	(supports instrument9 image0)
	(supports instrument9 infrared3)
	(calibration_target instrument9 Star1)
	(supports instrument10 infrared2)
	(calibration_target instrument10 Star1)
	(supports instrument11 image0)
	(calibration_target instrument11 GroundStation0)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star3)
	(supports instrument12 infrared4)
	(supports instrument12 image1)
	(calibration_target instrument12 GroundStation0)
	(supports instrument13 infrared3)
	(calibration_target instrument13 GroundStation0)
	(supports instrument14 infrared4)
	(calibration_target instrument14 Star1)
	(supports instrument15 infrared2)
	(supports instrument15 image0)
	(calibration_target instrument15 Star1)
	(supports instrument16 infrared2)
	(calibration_target instrument16 Star1)
	(supports instrument17 infrared4)
	(supports instrument17 infrared2)
	(supports instrument17 infrared3)
	(calibration_target instrument17 GroundStation2)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation0)
	(supports instrument18 image1)
	(supports instrument18 infrared3)
	(supports instrument18 image0)
	(calibration_target instrument18 Star1)
	(supports instrument19 infrared3)
	(supports instrument19 infrared4)
	(calibration_target instrument19 Star1)
	(supports instrument20 infrared2)
	(calibration_target instrument20 GroundStation2)
	(supports instrument21 image1)
	(supports instrument21 image0)
	(supports instrument21 infrared4)
	(calibration_target instrument21 GroundStation2)
	(supports instrument22 image0)
	(calibration_target instrument22 GroundStation2)
	(supports instrument23 image1)
	(calibration_target instrument23 Star1)
	(supports instrument24 infrared3)
	(supports instrument24 image0)
	(calibration_target instrument24 Star1)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation2)
	(supports instrument25 image0)
	(supports instrument25 image1)
	(calibration_target instrument25 Star1)
	(supports instrument26 infrared3)
	(calibration_target instrument26 Star1)
	(supports instrument27 image1)
	(supports instrument27 infrared2)
	(supports instrument27 image0)
	(calibration_target instrument27 GroundStation2)
	(on_board instrument25 satellite6)
	(on_board instrument26 satellite6)
	(on_board instrument27 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation2)
	(supports instrument28 infrared2)
	(supports instrument28 infrared4)
	(supports instrument28 image0)
	(calibration_target instrument28 GroundStation0)
	(supports instrument29 infrared2)
	(calibration_target instrument29 Star1)
	(supports instrument30 image0)
	(supports instrument30 infrared2)
	(supports instrument30 image1)
	(calibration_target instrument30 Star1)
	(on_board instrument28 satellite7)
	(on_board instrument29 satellite7)
	(on_board instrument30 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet4)
	(supports instrument31 infrared4)
	(calibration_target instrument31 GroundStation2)
	(supports instrument32 infrared4)
	(supports instrument32 infrared2)
	(supports instrument32 infrared3)
	(calibration_target instrument32 GroundStation2)
	(supports instrument33 infrared2)
	(supports instrument33 image0)
	(supports instrument33 infrared4)
	(calibration_target instrument33 GroundStation0)
	(supports instrument34 image0)
	(supports instrument34 infrared2)
	(calibration_target instrument34 GroundStation0)
	(supports instrument35 infrared2)
	(supports instrument35 infrared3)
	(supports instrument35 infrared4)
	(calibration_target instrument35 GroundStation0)
	(supports instrument36 infrared3)
	(calibration_target instrument36 GroundStation0)
	(on_board instrument31 satellite8)
	(on_board instrument32 satellite8)
	(on_board instrument33 satellite8)
	(on_board instrument34 satellite8)
	(on_board instrument35 satellite8)
	(on_board instrument36 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation0)
	(supports instrument37 infrared2)
	(supports instrument37 infrared3)
	(supports instrument37 image0)
	(calibration_target instrument37 Star1)
	(supports instrument38 infrared2)
	(supports instrument38 infrared4)
	(calibration_target instrument38 GroundStation2)
	(on_board instrument37 satellite9)
	(on_board instrument38 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star1)
)
(:goal (and
	(pointing satellite1 Planet4)
	(pointing satellite3 Star1)
	(pointing satellite7 GroundStation2)
	(pointing satellite9 GroundStation2)
	(have_image Star3 infrared2)
))

)
