(define (problem pb2)
	(:domain blocks)
	(:objects block1 block2 block3 block4)
	(:init (on block1 block4) (ontable block2) (on block3 block1) (clear block3) (on block4 block2) (handempty))
	(:goal (and (on block1 block4) (clear block1) (on block2 block3) (ontable block3) (on block4 block2))))