(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2 block3 block4)
	(:init (on block1 block4) (clear block1) (ontable block2) (clear block2) (ontable block3) (on block4 block3) (handempty))
	(:goal (and (ontable block1) (on block2 block4) (clear block2) (on block3 block1) (on block4 block3))))