(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4)
	(:init (on block1 block2) (clear block1) (on block2 block4) (ontable block3) (clear block3) (ontable block4) (handempty))
	(:goal (and (ontable block1) (clear block1) (on block2 block4) (clear block2) (ontable block3) (on block4 block3))))