(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3)
	(:init (ontable block1) (on block2 block1) (clear block2) (ontable block3) (clear block3) (handempty))
	(:goal (and (on block1 block3) (on block2 block1) (clear block2) (ontable block3))))