(define (problem pb8)
	(:domain blocks)
	(:objects block1 block2 block3)
	(:init (on block1 block2) (clear block1) (ontable block2) (ontable block3) (clear block3) (handempty))
	(:goal (and (on block1 block3) (clear block1) (ontable block2) (clear block2) (ontable block3))))