(define (problem pb5)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11 block12)
	(:init (ontable block1) (clear block1) (on block2 block3) (ontable block3) (on block4 block10) (on block5 block11) (ontable block6) (clear block6) (ontable block7) (clear block7) (on block8 block2) (on block9 block5) (clear block9) (ontable block10) (on block11 block4) (on block12 block8) (clear block12) (handempty))
	(:goal (and (on block1 block10) (clear block1) (on block2 block5) (clear block2) (on block3 block9) (on block4 block8) (clear block4) (on block5 block7) (ontable block6) (ontable block7) (on block8 block6) (ontable block9) (on block10 block3) (ontable block11) (clear block11) (ontable block12) (clear block12))))