(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	satellite2 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite5 - satellite
	instrument15 - instrument
	satellite6 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite7 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite8 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite9 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	spectrograph0 - mode
	infrared2 - mode
	thermograph4 - mode
	thermograph3 - mode
	infrared1 - mode
	Star3 - direction
	Star2 - direction
	GroundStation20 - direction
	Star12 - direction
	GroundStation18 - direction
	GroundStation13 - direction
	Star25 - direction
	GroundStation9 - direction
	Star8 - direction
	Star19 - direction
	Star22 - direction
	Star0 - direction
	Star6 - direction
	GroundStation23 - direction
	GroundStation7 - direction
	Star14 - direction
	GroundStation10 - direction
	Star21 - direction
	GroundStation24 - direction
	GroundStation1 - direction
	Star4 - direction
	GroundStation11 - direction
	GroundStation16 - direction
	GroundStation17 - direction
	Star5 - direction
	GroundStation15 - direction
	Planet26 - direction
	Star27 - direction
)
(:init
	(supports instrument0 thermograph3)
	(calibration_target instrument0 Star4)
	(calibration_target instrument0 Star6)
	(calibration_target instrument0 Star2)
	(calibration_target instrument0 GroundStation23)
	(calibration_target instrument0 GroundStation18)
	(calibration_target instrument0 GroundStation17)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation10)
	(supports instrument1 infrared1)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 Star6)
	(calibration_target instrument1 Star14)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 GroundStation17)
	(calibration_target instrument1 GroundStation16)
	(calibration_target instrument1 Star12)
	(calibration_target instrument1 Star21)
	(on_board instrument1 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star4)
	(supports instrument2 infrared2)
	(calibration_target instrument2 Star6)
	(calibration_target instrument2 Star4)
	(calibration_target instrument2 GroundStation16)
	(calibration_target instrument2 GroundStation15)
	(calibration_target instrument2 Star14)
	(calibration_target instrument2 Star22)
	(calibration_target instrument2 Star8)
	(supports instrument3 thermograph3)
	(supports instrument3 spectrograph0)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 Star22)
	(calibration_target instrument3 GroundStation1)
	(calibration_target instrument3 Star8)
	(calibration_target instrument3 Star12)
	(calibration_target instrument3 GroundStation10)
	(calibration_target instrument3 GroundStation13)
	(calibration_target instrument3 GroundStation7)
	(supports instrument4 infrared2)
	(calibration_target instrument4 GroundStation13)
	(calibration_target instrument4 GroundStation23)
	(calibration_target instrument4 GroundStation16)
	(calibration_target instrument4 GroundStation10)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 Star25)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 Star5)
	(calibration_target instrument5 Star14)
	(calibration_target instrument5 GroundStation15)
	(calibration_target instrument5 GroundStation24)
	(calibration_target instrument5 Star22)
	(calibration_target instrument5 Star19)
	(calibration_target instrument5 GroundStation10)
	(on_board instrument2 satellite2)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star27)
	(supports instrument6 infrared2)
	(calibration_target instrument6 Star5)
	(calibration_target instrument6 Star19)
	(calibration_target instrument6 GroundStation7)
	(calibration_target instrument6 Star14)
	(calibration_target instrument6 GroundStation10)
	(calibration_target instrument6 Star21)
	(calibration_target instrument6 GroundStation13)
	(supports instrument7 spectrograph0)
	(supports instrument7 infrared2)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 Star4)
	(calibration_target instrument7 Star6)
	(calibration_target instrument7 GroundStation17)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 GroundStation16)
	(calibration_target instrument8 Star8)
	(calibration_target instrument8 GroundStation10)
	(calibration_target instrument8 Star25)
	(calibration_target instrument8 GroundStation11)
	(calibration_target instrument8 GroundStation1)
	(calibration_target instrument8 GroundStation23)
	(calibration_target instrument8 Star4)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation11)
	(supports instrument9 infrared1)
	(supports instrument9 thermograph3)
	(calibration_target instrument9 GroundStation1)
	(calibration_target instrument9 Star22)
	(calibration_target instrument9 GroundStation16)
	(calibration_target instrument9 Star6)
	(supports instrument10 thermograph3)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 GroundStation7)
	(calibration_target instrument10 Star25)
	(calibration_target instrument10 Star21)
	(calibration_target instrument10 Star22)
	(supports instrument11 infrared1)
	(calibration_target instrument11 Star2)
	(calibration_target instrument11 GroundStation11)
	(calibration_target instrument11 GroundStation24)
	(calibration_target instrument11 GroundStation16)
	(calibration_target instrument11 Star0)
	(supports instrument12 infrared1)
	(supports instrument12 thermograph3)
	(calibration_target instrument12 Star14)
	(calibration_target instrument12 Star2)
	(calibration_target instrument12 Star19)
	(calibration_target instrument12 GroundStation9)
	(calibration_target instrument12 Star8)
	(calibration_target instrument12 GroundStation7)
	(calibration_target instrument12 GroundStation10)
	(supports instrument13 infrared1)
	(supports instrument13 infrared2)
	(supports instrument13 spectrograph0)
	(calibration_target instrument13 GroundStation1)
	(calibration_target instrument13 Star19)
	(calibration_target instrument13 Star21)
	(calibration_target instrument13 GroundStation10)
	(calibration_target instrument13 GroundStation11)
	(supports instrument14 thermograph3)
	(supports instrument14 infrared1)
	(supports instrument14 infrared2)
	(calibration_target instrument14 GroundStation20)
	(calibration_target instrument14 GroundStation13)
	(calibration_target instrument14 Star6)
	(calibration_target instrument14 GroundStation7)
	(calibration_target instrument14 Star25)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star6)
	(supports instrument15 spectrograph0)
	(supports instrument15 thermograph3)
	(calibration_target instrument15 Star22)
	(calibration_target instrument15 GroundStation10)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation24)
	(supports instrument16 thermograph4)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 Star21)
	(supports instrument17 infrared2)
	(supports instrument17 thermograph3)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 Star25)
	(calibration_target instrument17 Star12)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 Star14)
	(calibration_target instrument17 Star4)
	(supports instrument18 infrared2)
	(supports instrument18 thermograph3)
	(supports instrument18 infrared1)
	(calibration_target instrument18 GroundStation15)
	(calibration_target instrument18 Star2)
	(calibration_target instrument18 GroundStation17)
	(calibration_target instrument18 Star21)
	(calibration_target instrument18 GroundStation10)
	(calibration_target instrument18 Star4)
	(supports instrument19 thermograph4)
	(supports instrument19 infrared1)
	(calibration_target instrument19 GroundStation10)
	(calibration_target instrument19 GroundStation7)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation7)
	(supports instrument20 infrared2)
	(supports instrument20 thermograph3)
	(calibration_target instrument20 GroundStation20)
	(calibration_target instrument20 Star4)
	(calibration_target instrument20 Star19)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 GroundStation13)
	(supports instrument22 infrared1)
	(supports instrument22 spectrograph0)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 GroundStation15)
	(calibration_target instrument22 GroundStation17)
	(supports instrument23 infrared2)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 GroundStation18)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(on_board instrument23 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation15)
	(supports instrument24 infrared2)
	(supports instrument24 thermograph4)
	(calibration_target instrument24 GroundStation15)
	(calibration_target instrument24 GroundStation23)
	(calibration_target instrument24 Star21)
	(calibration_target instrument24 Star22)
	(calibration_target instrument24 GroundStation13)
	(supports instrument25 infrared1)
	(supports instrument25 thermograph3)
	(calibration_target instrument25 GroundStation13)
	(calibration_target instrument25 Star14)
	(calibration_target instrument25 GroundStation23)
	(calibration_target instrument25 GroundStation18)
	(calibration_target instrument25 Star12)
	(supports instrument26 infrared2)
	(calibration_target instrument26 GroundStation10)
	(calibration_target instrument26 Star25)
	(calibration_target instrument26 Star6)
	(calibration_target instrument26 Star0)
	(supports instrument27 spectrograph0)
	(calibration_target instrument27 GroundStation16)
	(calibration_target instrument27 Star25)
	(supports instrument28 infrared2)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 GroundStation11)
	(calibration_target instrument28 Star8)
	(calibration_target instrument28 GroundStation9)
	(on_board instrument24 satellite8)
	(on_board instrument25 satellite8)
	(on_board instrument26 satellite8)
	(on_board instrument27 satellite8)
	(on_board instrument28 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation10)
	(supports instrument29 infrared2)
	(supports instrument29 infrared1)
	(calibration_target instrument29 Star22)
	(calibration_target instrument29 GroundStation1)
	(calibration_target instrument29 Star14)
	(calibration_target instrument29 Star0)
	(calibration_target instrument29 Star19)
	(calibration_target instrument29 GroundStation10)
	(calibration_target instrument29 Star6)
	(supports instrument30 thermograph4)
	(supports instrument30 thermograph3)
	(calibration_target instrument30 GroundStation17)
	(supports instrument31 thermograph4)
	(supports instrument31 infrared2)
	(supports instrument31 thermograph3)
	(calibration_target instrument31 Star4)
	(calibration_target instrument31 GroundStation7)
	(calibration_target instrument31 GroundStation23)
	(calibration_target instrument31 Star21)
	(calibration_target instrument31 Star6)
	(calibration_target instrument31 GroundStation15)
	(calibration_target instrument31 GroundStation11)
	(calibration_target instrument31 Star0)
	(supports instrument32 thermograph3)
	(supports instrument32 thermograph4)
	(supports instrument32 infrared2)
	(calibration_target instrument32 GroundStation16)
	(calibration_target instrument32 GroundStation11)
	(calibration_target instrument32 Star4)
	(calibration_target instrument32 GroundStation1)
	(calibration_target instrument32 GroundStation24)
	(calibration_target instrument32 Star21)
	(calibration_target instrument32 GroundStation10)
	(calibration_target instrument32 Star14)
	(supports instrument33 infrared1)
	(supports instrument33 thermograph3)
	(supports instrument33 thermograph4)
	(calibration_target instrument33 GroundStation15)
	(calibration_target instrument33 Star5)
	(calibration_target instrument33 GroundStation17)
	(on_board instrument29 satellite9)
	(on_board instrument30 satellite9)
	(on_board instrument31 satellite9)
	(on_board instrument32 satellite9)
	(on_board instrument33 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation18)
)
(:goal (and
	(pointing satellite0 Star19)
	(pointing satellite2 Star22)
	(pointing satellite4 Star2)
	(pointing satellite9 GroundStation9)
	(have_image Planet26 thermograph4)
	(have_image Star27 thermograph3)
))

)
