(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite2 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite3 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite4 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite5 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite6 - satellite
	instrument48 - instrument
	satellite7 - satellite
	instrument49 - instrument
	instrument50 - instrument
	satellite8 - satellite
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	satellite9 - satellite
	instrument61 - instrument
	instrument62 - instrument
	spectrograph1 - mode
	spectrograph2 - mode
	image3 - mode
	infrared0 - mode
	spectrograph4 - mode
	GroundStation1 - direction
	Star0 - direction
	GroundStation4 - direction
	Star8 - direction
	Star7 - direction
	Star3 - direction
	GroundStation2 - direction
	Star5 - direction
	GroundStation6 - direction
	Phenomenon9 - direction
	Planet10 - direction
)
(:init
	(supports instrument0 image3)
	(supports instrument0 spectrograph4)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 GroundStation4)
	(supports instrument1 spectrograph4)
	(calibration_target instrument1 Star0)
	(supports instrument2 spectrograph1)
	(supports instrument2 infrared0)
	(supports instrument2 image3)
	(calibration_target instrument2 Star8)
	(supports instrument3 image3)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 GroundStation4)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 GroundStation4)
	(supports instrument5 infrared0)
	(calibration_target instrument5 Star0)
	(supports instrument6 infrared0)
	(supports instrument6 spectrograph4)
	(calibration_target instrument6 GroundStation1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star7)
	(supports instrument7 spectrograph4)
	(supports instrument7 spectrograph2)
	(calibration_target instrument7 Star7)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 Star8)
	(supports instrument9 spectrograph2)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 GroundStation4)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 infrared0)
	(supports instrument10 spectrograph1)
	(supports instrument10 image3)
	(calibration_target instrument10 GroundStation2)
	(supports instrument11 spectrograph2)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 Star3)
	(supports instrument12 infrared0)
	(calibration_target instrument12 GroundStation1)
	(supports instrument13 spectrograph4)
	(supports instrument13 infrared0)
	(calibration_target instrument13 GroundStation6)
	(calibration_target instrument13 GroundStation4)
	(calibration_target instrument13 Star8)
	(supports instrument14 spectrograph1)
	(supports instrument14 image3)
	(calibration_target instrument14 Star8)
	(calibration_target instrument14 GroundStation6)
	(supports instrument15 spectrograph2)
	(supports instrument15 image3)
	(supports instrument15 infrared0)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 Star5)
	(calibration_target instrument15 GroundStation4)
	(supports instrument16 spectrograph1)
	(supports instrument16 image3)
	(supports instrument16 spectrograph2)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 Star8)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation1)
	(supports instrument17 image3)
	(supports instrument17 spectrograph2)
	(supports instrument17 spectrograph1)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 GroundStation6)
	(supports instrument18 infrared0)
	(supports instrument18 spectrograph4)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 Star3)
	(supports instrument19 image3)
	(supports instrument19 spectrograph4)
	(supports instrument19 spectrograph2)
	(calibration_target instrument19 Star5)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 image3)
	(supports instrument20 spectrograph4)
	(supports instrument20 infrared0)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 GroundStation4)
	(calibration_target instrument20 GroundStation1)
	(supports instrument21 spectrograph4)
	(calibration_target instrument21 Star5)
	(calibration_target instrument21 Star0)
	(supports instrument22 spectrograph4)
	(calibration_target instrument22 Star3)
	(calibration_target instrument22 Star5)
	(calibration_target instrument22 Star8)
	(supports instrument23 infrared0)
	(supports instrument23 spectrograph4)
	(supports instrument23 spectrograph2)
	(calibration_target instrument23 Star5)
	(supports instrument24 spectrograph2)
	(supports instrument24 infrared0)
	(supports instrument24 spectrograph4)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 Star8)
	(calibration_target instrument24 Star5)
	(supports instrument25 image3)
	(supports instrument25 spectrograph1)
	(calibration_target instrument25 GroundStation2)
	(calibration_target instrument25 Star7)
	(calibration_target instrument25 Star3)
	(supports instrument26 infrared0)
	(supports instrument26 spectrograph1)
	(supports instrument26 image3)
	(calibration_target instrument26 Star8)
	(calibration_target instrument26 GroundStation1)
	(calibration_target instrument26 GroundStation4)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(on_board instrument22 satellite2)
	(on_board instrument23 satellite2)
	(on_board instrument24 satellite2)
	(on_board instrument25 satellite2)
	(on_board instrument26 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet10)
	(supports instrument27 infrared0)
	(supports instrument27 spectrograph1)
	(supports instrument27 spectrograph4)
	(calibration_target instrument27 Star8)
	(supports instrument28 infrared0)
	(supports instrument28 image3)
	(calibration_target instrument28 Star8)
	(supports instrument29 spectrograph4)
	(calibration_target instrument29 GroundStation1)
	(calibration_target instrument29 Star5)
	(calibration_target instrument29 Star3)
	(supports instrument30 spectrograph1)
	(supports instrument30 image3)
	(calibration_target instrument30 Star0)
	(calibration_target instrument30 GroundStation1)
	(calibration_target instrument30 Star5)
	(supports instrument31 infrared0)
	(supports instrument31 spectrograph1)
	(calibration_target instrument31 GroundStation2)
	(calibration_target instrument31 Star0)
	(calibration_target instrument31 GroundStation6)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(on_board instrument30 satellite3)
	(on_board instrument31 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star3)
	(supports instrument32 spectrograph4)
	(supports instrument32 infrared0)
	(supports instrument32 image3)
	(calibration_target instrument32 Star8)
	(calibration_target instrument32 Star0)
	(calibration_target instrument32 GroundStation6)
	(supports instrument33 spectrograph1)
	(calibration_target instrument33 GroundStation6)
	(calibration_target instrument33 GroundStation1)
	(supports instrument34 image3)
	(supports instrument34 spectrograph4)
	(supports instrument34 spectrograph1)
	(calibration_target instrument34 Star8)
	(calibration_target instrument34 Star7)
	(calibration_target instrument34 Star5)
	(supports instrument35 image3)
	(calibration_target instrument35 GroundStation6)
	(calibration_target instrument35 Star8)
	(calibration_target instrument35 Star3)
	(supports instrument36 spectrograph4)
	(calibration_target instrument36 GroundStation4)
	(calibration_target instrument36 Star8)
	(calibration_target instrument36 GroundStation6)
	(supports instrument37 spectrograph2)
	(supports instrument37 spectrograph1)
	(supports instrument37 infrared0)
	(calibration_target instrument37 GroundStation1)
	(calibration_target instrument37 GroundStation4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(on_board instrument37 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation6)
	(supports instrument38 spectrograph1)
	(supports instrument38 image3)
	(calibration_target instrument38 GroundStation4)
	(calibration_target instrument38 GroundStation2)
	(calibration_target instrument38 Star0)
	(supports instrument39 image3)
	(supports instrument39 spectrograph2)
	(calibration_target instrument39 Star3)
	(calibration_target instrument39 GroundStation1)
	(calibration_target instrument39 Star5)
	(supports instrument40 spectrograph2)
	(supports instrument40 spectrograph4)
	(supports instrument40 infrared0)
	(calibration_target instrument40 GroundStation4)
	(supports instrument41 infrared0)
	(supports instrument41 spectrograph2)
	(calibration_target instrument41 Star3)
	(calibration_target instrument41 Star0)
	(supports instrument42 spectrograph4)
	(calibration_target instrument42 GroundStation4)
	(calibration_target instrument42 Star8)
	(calibration_target instrument42 Star3)
	(supports instrument43 image3)
	(calibration_target instrument43 GroundStation6)
	(supports instrument44 image3)
	(supports instrument44 infrared0)
	(supports instrument44 spectrograph4)
	(calibration_target instrument44 GroundStation6)
	(supports instrument45 image3)
	(supports instrument45 spectrograph1)
	(calibration_target instrument45 GroundStation4)
	(supports instrument46 spectrograph4)
	(supports instrument46 spectrograph2)
	(supports instrument46 spectrograph1)
	(calibration_target instrument46 Star8)
	(calibration_target instrument46 Star5)
	(supports instrument47 spectrograph1)
	(calibration_target instrument47 Star5)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(on_board instrument41 satellite5)
	(on_board instrument42 satellite5)
	(on_board instrument43 satellite5)
	(on_board instrument44 satellite5)
	(on_board instrument45 satellite5)
	(on_board instrument46 satellite5)
	(on_board instrument47 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(supports instrument48 spectrograph4)
	(supports instrument48 spectrograph1)
	(calibration_target instrument48 GroundStation1)
	(on_board instrument48 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star8)
	(supports instrument49 spectrograph1)
	(supports instrument49 spectrograph4)
	(supports instrument49 infrared0)
	(calibration_target instrument49 GroundStation1)
	(calibration_target instrument49 Star3)
	(calibration_target instrument49 Star0)
	(supports instrument50 image3)
	(supports instrument50 spectrograph4)
	(calibration_target instrument50 Star0)
	(calibration_target instrument50 GroundStation6)
	(calibration_target instrument50 GroundStation1)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
	(supports instrument51 spectrograph4)
	(supports instrument51 spectrograph2)
	(supports instrument51 spectrograph1)
	(calibration_target instrument51 Star7)
	(supports instrument52 infrared0)
	(calibration_target instrument52 GroundStation6)
	(supports instrument53 spectrograph4)
	(calibration_target instrument53 Star8)
	(calibration_target instrument53 Star3)
	(calibration_target instrument53 Star0)
	(supports instrument54 infrared0)
	(calibration_target instrument54 Star0)
	(calibration_target instrument54 GroundStation2)
	(supports instrument55 infrared0)
	(supports instrument55 spectrograph2)
	(calibration_target instrument55 Star3)
	(calibration_target instrument55 Star8)
	(supports instrument56 spectrograph4)
	(supports instrument56 image3)
	(supports instrument56 infrared0)
	(calibration_target instrument56 Star8)
	(calibration_target instrument56 GroundStation4)
	(supports instrument57 spectrograph1)
	(supports instrument57 spectrograph4)
	(supports instrument57 infrared0)
	(calibration_target instrument57 Star3)
	(supports instrument58 infrared0)
	(calibration_target instrument58 Star3)
	(calibration_target instrument58 GroundStation2)
	(supports instrument59 spectrograph1)
	(calibration_target instrument59 Star0)
	(supports instrument60 image3)
	(supports instrument60 spectrograph2)
	(supports instrument60 spectrograph1)
	(calibration_target instrument60 Star7)
	(calibration_target instrument60 Star8)
	(calibration_target instrument60 GroundStation4)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(on_board instrument60 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation4)
	(supports instrument61 spectrograph2)
	(supports instrument61 spectrograph1)
	(supports instrument61 infrared0)
	(calibration_target instrument61 Star5)
	(calibration_target instrument61 GroundStation2)
	(calibration_target instrument61 Star3)
	(supports instrument62 spectrograph4)
	(supports instrument62 infrared0)
	(supports instrument62 image3)
	(calibration_target instrument62 GroundStation6)
	(on_board instrument61 satellite9)
	(on_board instrument62 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation2)
)
(:goal (and
	(pointing satellite1 Star7)
	(pointing satellite2 GroundStation6)
	(pointing satellite7 Star7)
	(have_image Phenomenon9 spectrograph2)
	(have_image Planet10 image3)
))

)
