(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite5 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite6 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite7 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	satellite8 - satellite
	instrument47 - instrument
	instrument48 - instrument
	satellite9 - satellite
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	spectrograph0 - mode
	spectrograph1 - mode
	spectrograph2 - mode
	thermograph4 - mode
	infrared3 - mode
	Star6 - direction
	Star7 - direction
	Star1 - direction
	GroundStation4 - direction
	Star8 - direction
	Star0 - direction
	GroundStation2 - direction
	GroundStation5 - direction
	GroundStation3 - direction
	Phenomenon9 - direction
	Star10 - direction
)
(:init
	(supports instrument0 spectrograph1)
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 GroundStation3)
	(calibration_target instrument0 Star6)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 thermograph4)
	(supports instrument1 spectrograph1)
	(calibration_target instrument1 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation3)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 GroundStation3)
	(calibration_target instrument2 Star1)
	(calibration_target instrument2 Star7)
	(supports instrument3 spectrograph0)
	(supports instrument3 thermograph4)
	(supports instrument3 spectrograph2)
	(calibration_target instrument3 GroundStation4)
	(supports instrument4 thermograph4)
	(supports instrument4 spectrograph2)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 Star1)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 Star7)
	(supports instrument5 spectrograph0)
	(supports instrument5 thermograph4)
	(supports instrument5 spectrograph1)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 Star8)
	(supports instrument6 spectrograph2)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 Star1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star10)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star1)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star10)
	(supports instrument8 spectrograph0)
	(calibration_target instrument8 Star1)
	(supports instrument9 spectrograph1)
	(supports instrument9 spectrograph2)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 GroundStation4)
	(supports instrument10 spectrograph1)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 GroundStation3)
	(calibration_target instrument10 Star6)
	(supports instrument11 thermograph4)
	(supports instrument11 spectrograph0)
	(supports instrument11 spectrograph2)
	(calibration_target instrument11 Star6)
	(calibration_target instrument11 GroundStation4)
	(calibration_target instrument11 Star0)
	(supports instrument12 spectrograph0)
	(supports instrument12 spectrograph1)
	(supports instrument12 infrared3)
	(calibration_target instrument12 GroundStation5)
	(supports instrument13 thermograph4)
	(supports instrument13 spectrograph2)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 GroundStation4)
	(supports instrument14 spectrograph0)
	(supports instrument14 spectrograph2)
	(calibration_target instrument14 Star7)
	(calibration_target instrument14 Star0)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 Star6)
	(calibration_target instrument15 GroundStation5)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star10)
	(supports instrument16 infrared3)
	(supports instrument16 spectrograph1)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 GroundStation5)
	(calibration_target instrument16 Star7)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 Star7)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 Star8)
	(calibration_target instrument18 GroundStation5)
	(supports instrument19 thermograph4)
	(supports instrument19 spectrograph2)
	(calibration_target instrument19 GroundStation3)
	(supports instrument20 infrared3)
	(supports instrument20 thermograph4)
	(supports instrument20 spectrograph2)
	(calibration_target instrument20 Star1)
	(supports instrument21 spectrograph2)
	(supports instrument21 thermograph4)
	(calibration_target instrument21 GroundStation4)
	(supports instrument22 spectrograph0)
	(supports instrument22 spectrograph2)
	(calibration_target instrument22 GroundStation4)
	(supports instrument23 infrared3)
	(calibration_target instrument23 GroundStation2)
	(supports instrument24 spectrograph0)
	(supports instrument24 spectrograph2)
	(supports instrument24 infrared3)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 GroundStation4)
	(calibration_target instrument24 GroundStation3)
	(supports instrument25 spectrograph0)
	(calibration_target instrument25 Star1)
	(calibration_target instrument25 Star7)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument26 spectrograph2)
	(supports instrument26 spectrograph1)
	(calibration_target instrument26 GroundStation2)
	(calibration_target instrument26 GroundStation3)
	(supports instrument27 infrared3)
	(calibration_target instrument27 Star0)
	(supports instrument28 spectrograph0)
	(supports instrument28 thermograph4)
	(supports instrument28 spectrograph2)
	(calibration_target instrument28 Star0)
	(calibration_target instrument28 GroundStation2)
	(supports instrument29 spectrograph0)
	(calibration_target instrument29 Star1)
	(calibration_target instrument29 Star6)
	(calibration_target instrument29 GroundStation3)
	(supports instrument30 infrared3)
	(supports instrument30 thermograph4)
	(calibration_target instrument30 GroundStation5)
	(calibration_target instrument30 Star7)
	(calibration_target instrument30 GroundStation4)
	(supports instrument31 thermograph4)
	(supports instrument31 spectrograph0)
	(calibration_target instrument31 Star7)
	(calibration_target instrument31 Star6)
	(supports instrument32 spectrograph1)
	(supports instrument32 infrared3)
	(calibration_target instrument32 Star8)
	(calibration_target instrument32 Star1)
	(calibration_target instrument32 GroundStation4)
	(supports instrument33 spectrograph2)
	(supports instrument33 infrared3)
	(supports instrument33 spectrograph0)
	(calibration_target instrument33 GroundStation3)
	(calibration_target instrument33 GroundStation2)
	(supports instrument34 spectrograph2)
	(calibration_target instrument34 Star1)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation4)
	(supports instrument35 spectrograph2)
	(calibration_target instrument35 Star0)
	(calibration_target instrument35 GroundStation5)
	(supports instrument36 spectrograph1)
	(supports instrument36 infrared3)
	(calibration_target instrument36 GroundStation4)
	(calibration_target instrument36 Star6)
	(supports instrument37 infrared3)
	(calibration_target instrument37 Star6)
	(calibration_target instrument37 GroundStation4)
	(calibration_target instrument37 GroundStation5)
	(supports instrument38 spectrograph1)
	(supports instrument38 thermograph4)
	(calibration_target instrument38 Star1)
	(supports instrument39 spectrograph1)
	(supports instrument39 spectrograph0)
	(supports instrument39 spectrograph2)
	(calibration_target instrument39 Star7)
	(calibration_target instrument39 Star8)
	(calibration_target instrument39 GroundStation3)
	(supports instrument40 spectrograph2)
	(calibration_target instrument40 Star1)
	(calibration_target instrument40 Star0)
	(calibration_target instrument40 GroundStation5)
	(supports instrument41 spectrograph2)
	(calibration_target instrument41 GroundStation5)
	(calibration_target instrument41 GroundStation4)
	(calibration_target instrument41 Star8)
	(supports instrument42 thermograph4)
	(calibration_target instrument42 GroundStation4)
	(calibration_target instrument42 Star7)
	(supports instrument43 spectrograph2)
	(supports instrument43 thermograph4)
	(calibration_target instrument43 GroundStation4)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation5)
	(supports instrument44 spectrograph2)
	(supports instrument44 spectrograph0)
	(supports instrument44 thermograph4)
	(calibration_target instrument44 GroundStation3)
	(calibration_target instrument44 Star7)
	(calibration_target instrument44 Star6)
	(supports instrument45 thermograph4)
	(supports instrument45 infrared3)
	(supports instrument45 spectrograph0)
	(calibration_target instrument45 Star7)
	(calibration_target instrument45 Star1)
	(calibration_target instrument45 Star0)
	(supports instrument46 thermograph4)
	(supports instrument46 spectrograph0)
	(calibration_target instrument46 GroundStation3)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star1)
	(supports instrument47 infrared3)
	(calibration_target instrument47 GroundStation5)
	(calibration_target instrument47 GroundStation4)
	(calibration_target instrument47 GroundStation2)
	(supports instrument48 thermograph4)
	(calibration_target instrument48 GroundStation4)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation4)
	(supports instrument49 infrared3)
	(supports instrument49 spectrograph1)
	(supports instrument49 spectrograph0)
	(calibration_target instrument49 Star8)
	(supports instrument50 thermograph4)
	(supports instrument50 spectrograph2)
	(calibration_target instrument50 Star8)
	(calibration_target instrument50 Star0)
	(supports instrument51 spectrograph2)
	(calibration_target instrument51 GroundStation4)
	(supports instrument52 spectrograph2)
	(supports instrument52 infrared3)
	(supports instrument52 thermograph4)
	(calibration_target instrument52 GroundStation4)
	(calibration_target instrument52 Star8)
	(supports instrument53 spectrograph2)
	(calibration_target instrument53 Star8)
	(calibration_target instrument53 Star1)
	(calibration_target instrument53 GroundStation3)
	(supports instrument54 infrared3)
	(supports instrument54 thermograph4)
	(calibration_target instrument54 Star0)
	(calibration_target instrument54 Star8)
	(calibration_target instrument54 GroundStation4)
	(supports instrument55 infrared3)
	(supports instrument55 thermograph4)
	(supports instrument55 spectrograph2)
	(calibration_target instrument55 GroundStation3)
	(calibration_target instrument55 GroundStation5)
	(calibration_target instrument55 GroundStation2)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star1)
)
(:goal (and
	(pointing satellite3 GroundStation3)
	(pointing satellite8 Phenomenon9)
	(have_image Star10 spectrograph1)
))

)
