(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite4 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite5 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite6 - satellite
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite7 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	satellite8 - satellite
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	instrument61 - instrument
	satellite9 - satellite
	instrument62 - instrument
	instrument63 - instrument
	instrument64 - instrument
	instrument65 - instrument
	instrument66 - instrument
	instrument67 - instrument
	instrument68 - instrument
	instrument69 - instrument
	instrument70 - instrument
	thermograph4 - mode
	image3 - mode
	image0 - mode
	spectrograph1 - mode
	spectrograph2 - mode
	Star1 - direction
	Star7 - direction
	GroundStation4 - direction
	GroundStation0 - direction
	GroundStation2 - direction
	GroundStation6 - direction
	Star5 - direction
	GroundStation3 - direction
	GroundStation8 - direction
	Phenomenon9 - direction
	Phenomenon10 - direction
)
(:init
	(supports instrument0 spectrograph2)
	(supports instrument0 spectrograph1)
	(supports instrument0 image3)
	(calibration_target instrument0 GroundStation0)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 GroundStation6)
	(supports instrument1 image0)
	(supports instrument1 image3)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 GroundStation8)
	(calibration_target instrument1 GroundStation3)
	(supports instrument2 thermograph4)
	(supports instrument2 spectrograph2)
	(calibration_target instrument2 GroundStation3)
	(calibration_target instrument2 GroundStation6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation0)
	(supports instrument3 spectrograph1)
	(supports instrument3 thermograph4)
	(supports instrument3 spectrograph2)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 Star5)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 Star7)
	(calibration_target instrument4 GroundStation0)
	(supports instrument5 image0)
	(calibration_target instrument5 GroundStation6)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 GroundStation8)
	(calibration_target instrument6 GroundStation6)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument7 image0)
	(supports instrument7 spectrograph1)
	(supports instrument7 spectrograph2)
	(calibration_target instrument7 GroundStation8)
	(calibration_target instrument7 GroundStation2)
	(supports instrument8 image0)
	(supports instrument8 image3)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 GroundStation0)
	(supports instrument9 image3)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 Star1)
	(calibration_target instrument9 GroundStation0)
	(calibration_target instrument9 GroundStation4)
	(supports instrument10 spectrograph1)
	(supports instrument10 image3)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 GroundStation8)
	(calibration_target instrument10 GroundStation6)
	(supports instrument11 thermograph4)
	(supports instrument11 image3)
	(supports instrument11 image0)
	(calibration_target instrument11 GroundStation8)
	(calibration_target instrument11 GroundStation2)
	(supports instrument12 spectrograph2)
	(calibration_target instrument12 GroundStation3)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation3)
	(supports instrument13 image0)
	(supports instrument13 spectrograph2)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 GroundStation6)
	(supports instrument14 spectrograph2)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation0)
	(calibration_target instrument14 Star1)
	(supports instrument15 image0)
	(calibration_target instrument15 GroundStation8)
	(calibration_target instrument15 GroundStation3)
	(supports instrument16 spectrograph2)
	(supports instrument16 image0)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 GroundStation3)
	(calibration_target instrument16 GroundStation6)
	(calibration_target instrument16 GroundStation4)
	(supports instrument17 image3)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 Star1)
	(supports instrument18 spectrograph1)
	(supports instrument18 image3)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 Star5)
	(calibration_target instrument18 GroundStation6)
	(supports instrument19 image0)
	(calibration_target instrument19 Star5)
	(supports instrument20 spectrograph1)
	(supports instrument20 image3)
	(supports instrument20 thermograph4)
	(calibration_target instrument20 GroundStation4)
	(calibration_target instrument20 GroundStation2)
	(supports instrument21 image3)
	(supports instrument21 spectrograph1)
	(supports instrument21 thermograph4)
	(calibration_target instrument21 GroundStation4)
	(calibration_target instrument21 GroundStation8)
	(supports instrument22 spectrograph2)
	(supports instrument22 image3)
	(calibration_target instrument22 GroundStation0)
	(calibration_target instrument22 Star5)
	(calibration_target instrument22 Star1)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star5)
	(supports instrument23 spectrograph1)
	(supports instrument23 image3)
	(supports instrument23 spectrograph2)
	(calibration_target instrument23 GroundStation6)
	(calibration_target instrument23 GroundStation4)
	(calibration_target instrument23 Star5)
	(supports instrument24 spectrograph2)
	(supports instrument24 image3)
	(calibration_target instrument24 GroundStation0)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 Star5)
	(supports instrument25 image3)
	(supports instrument25 spectrograph1)
	(calibration_target instrument25 Star1)
	(calibration_target instrument25 Star7)
	(supports instrument26 spectrograph1)
	(calibration_target instrument26 GroundStation2)
	(calibration_target instrument26 GroundStation4)
	(supports instrument27 image0)
	(supports instrument27 thermograph4)
	(calibration_target instrument27 Star5)
	(calibration_target instrument27 GroundStation4)
	(calibration_target instrument27 GroundStation3)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon10)
	(supports instrument28 spectrograph1)
	(calibration_target instrument28 Star1)
	(calibration_target instrument28 GroundStation2)
	(supports instrument29 image3)
	(supports instrument29 spectrograph1)
	(supports instrument29 spectrograph2)
	(calibration_target instrument29 Star7)
	(calibration_target instrument29 GroundStation4)
	(supports instrument30 image3)
	(supports instrument30 spectrograph1)
	(supports instrument30 image0)
	(calibration_target instrument30 GroundStation2)
	(supports instrument31 thermograph4)
	(calibration_target instrument31 GroundStation4)
	(calibration_target instrument31 GroundStation0)
	(supports instrument32 spectrograph2)
	(calibration_target instrument32 Star1)
	(supports instrument33 image0)
	(supports instrument33 spectrograph2)
	(supports instrument33 image3)
	(calibration_target instrument33 GroundStation4)
	(calibration_target instrument33 GroundStation2)
	(supports instrument34 thermograph4)
	(calibration_target instrument34 GroundStation8)
	(calibration_target instrument34 GroundStation3)
	(supports instrument35 spectrograph1)
	(calibration_target instrument35 Star7)
	(calibration_target instrument35 GroundStation6)
	(supports instrument36 image3)
	(supports instrument36 thermograph4)
	(calibration_target instrument36 GroundStation0)
	(calibration_target instrument36 GroundStation8)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation2)
	(supports instrument37 thermograph4)
	(supports instrument37 image3)
	(supports instrument37 spectrograph2)
	(calibration_target instrument37 GroundStation0)
	(calibration_target instrument37 GroundStation2)
	(supports instrument38 thermograph4)
	(supports instrument38 image3)
	(calibration_target instrument38 Star5)
	(calibration_target instrument38 GroundStation0)
	(calibration_target instrument38 Star7)
	(supports instrument39 image0)
	(supports instrument39 thermograph4)
	(supports instrument39 image3)
	(calibration_target instrument39 GroundStation8)
	(calibration_target instrument39 Star1)
	(calibration_target instrument39 GroundStation0)
	(supports instrument40 spectrograph2)
	(calibration_target instrument40 GroundStation8)
	(supports instrument41 spectrograph2)
	(supports instrument41 thermograph4)
	(calibration_target instrument41 GroundStation2)
	(supports instrument42 image3)
	(calibration_target instrument42 GroundStation3)
	(calibration_target instrument42 Star7)
	(calibration_target instrument42 Star1)
	(supports instrument43 image0)
	(supports instrument43 image3)
	(calibration_target instrument43 Star5)
	(calibration_target instrument43 GroundStation0)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star5)
	(supports instrument44 image0)
	(supports instrument44 image3)
	(supports instrument44 thermograph4)
	(calibration_target instrument44 GroundStation6)
	(supports instrument45 thermograph4)
	(calibration_target instrument45 Star7)
	(calibration_target instrument45 Star5)
	(supports instrument46 thermograph4)
	(calibration_target instrument46 GroundStation2)
	(calibration_target instrument46 GroundStation6)
	(supports instrument47 image3)
	(calibration_target instrument47 GroundStation6)
	(calibration_target instrument47 GroundStation0)
	(supports instrument48 spectrograph2)
	(supports instrument48 image0)
	(supports instrument48 thermograph4)
	(calibration_target instrument48 Star1)
	(supports instrument49 thermograph4)
	(calibration_target instrument49 GroundStation2)
	(calibration_target instrument49 Star1)
	(supports instrument50 thermograph4)
	(supports instrument50 spectrograph1)
	(supports instrument50 spectrograph2)
	(calibration_target instrument50 GroundStation6)
	(calibration_target instrument50 GroundStation4)
	(calibration_target instrument50 Star5)
	(supports instrument51 image3)
	(supports instrument51 spectrograph2)
	(calibration_target instrument51 GroundStation8)
	(calibration_target instrument51 GroundStation6)
	(calibration_target instrument51 GroundStation4)
	(supports instrument52 spectrograph2)
	(supports instrument52 thermograph4)
	(calibration_target instrument52 GroundStation3)
	(calibration_target instrument52 GroundStation8)
	(calibration_target instrument52 GroundStation2)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation4)
	(supports instrument53 spectrograph1)
	(supports instrument53 image3)
	(supports instrument53 image0)
	(calibration_target instrument53 GroundStation6)
	(calibration_target instrument53 Star5)
	(calibration_target instrument53 GroundStation2)
	(supports instrument54 image3)
	(supports instrument54 thermograph4)
	(supports instrument54 image0)
	(calibration_target instrument54 GroundStation8)
	(calibration_target instrument54 Star1)
	(supports instrument55 image0)
	(supports instrument55 spectrograph1)
	(supports instrument55 spectrograph2)
	(calibration_target instrument55 GroundStation8)
	(supports instrument56 image3)
	(supports instrument56 spectrograph1)
	(supports instrument56 image0)
	(calibration_target instrument56 Star1)
	(supports instrument57 image0)
	(calibration_target instrument57 GroundStation6)
	(calibration_target instrument57 Star7)
	(calibration_target instrument57 GroundStation2)
	(supports instrument58 image3)
	(supports instrument58 image0)
	(supports instrument58 thermograph4)
	(calibration_target instrument58 GroundStation3)
	(supports instrument59 spectrograph2)
	(supports instrument59 spectrograph1)
	(calibration_target instrument59 GroundStation8)
	(calibration_target instrument59 Star1)
	(calibration_target instrument59 GroundStation3)
	(supports instrument60 thermograph4)
	(supports instrument60 image0)
	(supports instrument60 spectrograph2)
	(calibration_target instrument60 Star7)
	(calibration_target instrument60 GroundStation4)
	(supports instrument61 image0)
	(supports instrument61 spectrograph1)
	(calibration_target instrument61 Star5)
	(calibration_target instrument61 GroundStation2)
	(calibration_target instrument61 GroundStation8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(on_board instrument60 satellite8)
	(on_board instrument61 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon10)
	(supports instrument62 spectrograph2)
	(supports instrument62 image3)
	(calibration_target instrument62 Star7)
	(calibration_target instrument62 GroundStation6)
	(calibration_target instrument62 GroundStation0)
	(supports instrument63 thermograph4)
	(calibration_target instrument63 GroundStation8)
	(calibration_target instrument63 GroundStation2)
	(calibration_target instrument63 Star5)
	(supports instrument64 spectrograph1)
	(supports instrument64 spectrograph2)
	(supports instrument64 image0)
	(calibration_target instrument64 GroundStation3)
	(calibration_target instrument64 GroundStation0)
	(calibration_target instrument64 GroundStation4)
	(supports instrument65 spectrograph1)
	(supports instrument65 image3)
	(calibration_target instrument65 GroundStation0)
	(calibration_target instrument65 GroundStation2)
	(supports instrument66 image3)
	(supports instrument66 image0)
	(calibration_target instrument66 GroundStation2)
	(calibration_target instrument66 GroundStation6)
	(supports instrument67 image0)
	(supports instrument67 image3)
	(calibration_target instrument67 GroundStation3)
	(supports instrument68 image0)
	(supports instrument68 spectrograph1)
	(supports instrument68 image3)
	(calibration_target instrument68 GroundStation3)
	(supports instrument69 spectrograph1)
	(supports instrument69 image0)
	(calibration_target instrument69 GroundStation6)
	(calibration_target instrument69 GroundStation8)
	(supports instrument70 spectrograph2)
	(calibration_target instrument70 GroundStation8)
	(calibration_target instrument70 GroundStation3)
	(calibration_target instrument70 Star5)
	(on_board instrument62 satellite9)
	(on_board instrument63 satellite9)
	(on_board instrument64 satellite9)
	(on_board instrument65 satellite9)
	(on_board instrument66 satellite9)
	(on_board instrument67 satellite9)
	(on_board instrument68 satellite9)
	(on_board instrument69 satellite9)
	(on_board instrument70 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation0)
)
(:goal (and
	(pointing satellite0 Star5)
	(pointing satellite4 Star5)
	(pointing satellite7 GroundStation0)
	(pointing satellite8 GroundStation2)
	(pointing satellite9 GroundStation4)
	(have_image Phenomenon9 image0)
	(have_image Phenomenon10 spectrograph2)
))

)
