(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite2 - satellite
	instrument17 - instrument
	satellite3 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite4 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite5 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite6 - satellite
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	satellite7 - satellite
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite8 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	satellite9 - satellite
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	instrument61 - instrument
	instrument62 - instrument
	instrument63 - instrument
	instrument64 - instrument
	instrument65 - instrument
	instrument66 - instrument
	spectrograph2 - mode
	image3 - mode
	spectrograph4 - mode
	spectrograph1 - mode
	infrared0 - mode
	GroundStation1 - direction
	Star0 - direction
	Planet2 - direction
	Star3 - direction
)
(:init
	(supports instrument0 infrared0)
	(supports instrument0 image3)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 spectrograph2)
	(supports instrument1 spectrograph1)
	(supports instrument1 infrared0)
	(calibration_target instrument1 Star0)
	(supports instrument2 infrared0)
	(calibration_target instrument2 Star0)
	(supports instrument3 image3)
	(supports instrument3 spectrograph1)
	(supports instrument3 infrared0)
	(calibration_target instrument3 Star0)
	(supports instrument4 spectrograph2)
	(supports instrument4 infrared0)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 GroundStation1)
	(supports instrument5 infrared0)
	(supports instrument5 spectrograph1)
	(supports instrument5 spectrograph2)
	(calibration_target instrument5 GroundStation1)
	(supports instrument6 image3)
	(supports instrument6 spectrograph2)
	(supports instrument6 spectrograph4)
	(calibration_target instrument6 GroundStation1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 Star0)
	(supports instrument8 spectrograph2)
	(supports instrument8 image3)
	(calibration_target instrument8 Star0)
	(supports instrument9 infrared0)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 Star0)
	(supports instrument10 spectrograph4)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 spectrograph4)
	(calibration_target instrument11 GroundStation1)
	(supports instrument12 spectrograph1)
	(calibration_target instrument12 Star0)
	(supports instrument13 spectrograph2)
	(supports instrument13 spectrograph1)
	(supports instrument13 image3)
	(calibration_target instrument13 GroundStation1)
	(supports instrument14 spectrograph2)
	(supports instrument14 spectrograph4)
	(calibration_target instrument14 Star0)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 GroundStation1)
	(supports instrument16 spectrograph4)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 GroundStation1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument17 infrared0)
	(calibration_target instrument17 Star0)
	(on_board instrument17 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument18 spectrograph4)
	(supports instrument18 image3)
	(supports instrument18 infrared0)
	(calibration_target instrument18 GroundStation1)
	(supports instrument19 infrared0)
	(supports instrument19 spectrograph2)
	(supports instrument19 image3)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 infrared0)
	(supports instrument20 spectrograph1)
	(calibration_target instrument20 Star0)
	(supports instrument21 infrared0)
	(supports instrument21 image3)
	(calibration_target instrument21 GroundStation1)
	(supports instrument22 image3)
	(supports instrument22 spectrograph1)
	(supports instrument22 spectrograph2)
	(calibration_target instrument22 Star0)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation1)
	(supports instrument23 spectrograph2)
	(supports instrument23 image3)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 spectrograph1)
	(supports instrument24 spectrograph2)
	(calibration_target instrument24 GroundStation1)
	(supports instrument25 spectrograph4)
	(calibration_target instrument25 GroundStation1)
	(supports instrument26 image3)
	(supports instrument26 infrared0)
	(calibration_target instrument26 Star0)
	(supports instrument27 infrared0)
	(calibration_target instrument27 Star0)
	(supports instrument28 infrared0)
	(supports instrument28 spectrograph2)
	(supports instrument28 spectrograph4)
	(calibration_target instrument28 GroundStation1)
	(supports instrument29 spectrograph4)
	(supports instrument29 image3)
	(supports instrument29 spectrograph1)
	(calibration_target instrument29 GroundStation1)
	(supports instrument30 spectrograph2)
	(supports instrument30 spectrograph4)
	(calibration_target instrument30 GroundStation1)
	(supports instrument31 spectrograph2)
	(supports instrument31 spectrograph1)
	(supports instrument31 spectrograph4)
	(calibration_target instrument31 GroundStation1)
	(supports instrument32 image3)
	(supports instrument32 spectrograph1)
	(supports instrument32 spectrograph2)
	(calibration_target instrument32 Star0)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation1)
	(supports instrument33 image3)
	(supports instrument33 spectrograph1)
	(supports instrument33 spectrograph2)
	(calibration_target instrument33 Star0)
	(supports instrument34 spectrograph2)
	(supports instrument34 image3)
	(supports instrument34 spectrograph4)
	(calibration_target instrument34 GroundStation1)
	(supports instrument35 infrared0)
	(supports instrument35 spectrograph4)
	(calibration_target instrument35 Star0)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(supports instrument36 spectrograph4)
	(supports instrument36 infrared0)
	(calibration_target instrument36 GroundStation1)
	(supports instrument37 spectrograph1)
	(supports instrument37 spectrograph2)
	(supports instrument37 infrared0)
	(calibration_target instrument37 Star0)
	(supports instrument38 infrared0)
	(supports instrument38 spectrograph2)
	(supports instrument38 spectrograph1)
	(calibration_target instrument38 GroundStation1)
	(supports instrument39 infrared0)
	(supports instrument39 spectrograph4)
	(supports instrument39 spectrograph2)
	(calibration_target instrument39 Star0)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star0)
	(supports instrument40 spectrograph4)
	(calibration_target instrument40 Star0)
	(supports instrument41 spectrograph2)
	(supports instrument41 infrared0)
	(supports instrument41 spectrograph4)
	(calibration_target instrument41 GroundStation1)
	(supports instrument42 spectrograph1)
	(supports instrument42 image3)
	(calibration_target instrument42 Star0)
	(supports instrument43 image3)
	(supports instrument43 spectrograph1)
	(calibration_target instrument43 Star0)
	(supports instrument44 spectrograph1)
	(supports instrument44 image3)
	(calibration_target instrument44 GroundStation1)
	(supports instrument45 spectrograph2)
	(calibration_target instrument45 GroundStation1)
	(supports instrument46 spectrograph1)
	(supports instrument46 spectrograph2)
	(supports instrument46 infrared0)
	(calibration_target instrument46 GroundStation1)
	(supports instrument47 image3)
	(supports instrument47 spectrograph4)
	(supports instrument47 spectrograph1)
	(calibration_target instrument47 Star0)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star3)
	(supports instrument48 infrared0)
	(supports instrument48 spectrograph1)
	(supports instrument48 spectrograph2)
	(calibration_target instrument48 Star0)
	(supports instrument49 image3)
	(supports instrument49 infrared0)
	(calibration_target instrument49 Star0)
	(supports instrument50 spectrograph1)
	(supports instrument50 infrared0)
	(supports instrument50 spectrograph2)
	(calibration_target instrument50 Star0)
	(supports instrument51 spectrograph1)
	(calibration_target instrument51 GroundStation1)
	(supports instrument52 spectrograph4)
	(calibration_target instrument52 Star0)
	(supports instrument53 image3)
	(supports instrument53 spectrograph1)
	(calibration_target instrument53 GroundStation1)
	(supports instrument54 image3)
	(supports instrument54 infrared0)
	(calibration_target instrument54 GroundStation1)
	(supports instrument55 infrared0)
	(supports instrument55 spectrograph2)
	(supports instrument55 spectrograph4)
	(calibration_target instrument55 GroundStation1)
	(supports instrument56 spectrograph4)
	(supports instrument56 infrared0)
	(calibration_target instrument56 GroundStation1)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation1)
	(supports instrument57 spectrograph4)
	(calibration_target instrument57 GroundStation1)
	(supports instrument58 spectrograph2)
	(calibration_target instrument58 GroundStation1)
	(supports instrument59 spectrograph4)
	(supports instrument59 spectrograph1)
	(calibration_target instrument59 GroundStation1)
	(supports instrument60 spectrograph2)
	(supports instrument60 spectrograph4)
	(calibration_target instrument60 Star0)
	(supports instrument61 infrared0)
	(supports instrument61 spectrograph2)
	(calibration_target instrument61 GroundStation1)
	(supports instrument62 infrared0)
	(supports instrument62 spectrograph1)
	(calibration_target instrument62 GroundStation1)
	(supports instrument63 spectrograph1)
	(supports instrument63 image3)
	(calibration_target instrument63 GroundStation1)
	(supports instrument64 infrared0)
	(calibration_target instrument64 Star0)
	(supports instrument65 spectrograph1)
	(supports instrument65 infrared0)
	(supports instrument65 spectrograph4)
	(calibration_target instrument65 GroundStation1)
	(supports instrument66 infrared0)
	(supports instrument66 spectrograph1)
	(supports instrument66 spectrograph4)
	(calibration_target instrument66 Star0)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(on_board instrument59 satellite9)
	(on_board instrument60 satellite9)
	(on_board instrument61 satellite9)
	(on_board instrument62 satellite9)
	(on_board instrument63 satellite9)
	(on_board instrument64 satellite9)
	(on_board instrument65 satellite9)
	(on_board instrument66 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star3)
)
(:goal (and
	(pointing satellite2 Planet2)
	(pointing satellite3 Planet2)
	(pointing satellite8 Planet2)
	(pointing satellite9 Star0)
	(have_image Planet2 infrared0)
	(have_image Star3 image3)
))

)
