(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (on block1 block5) (ontable block2) (clear block2) (on block3 block4) (clear block3) (on block4 block1) (ontable block5) (handempty))
	(:goal (and (on block1 block2) (clear block1) (on block2 block3) (on block3 block4) (on block4 block5) (ontable block5))))