(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (on block1 block4) (ontable block2) (clear block2) (on block3 block1) (ontable block4) (on block5 block3) (clear block5) (handempty))
	(:goal (and (ontable block1) (on block2 block5) (clear block2) (on block3 block4) (clear block3) (ontable block4) (on block5 block1))))