(define (problem pb5)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (ontable block1) (on block2 block4) (clear block2) (on block3 block1) (on block4 block5) (on block5 block3) (handempty))
	(:goal (and (on block1 block5) (ontable block2) (on block3 block1) (clear block3) (on block4 block2) (clear block4) (ontable block5))))