(define (problem pb2)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (on block1 block2) (clear block1) (on block2 block4) (on block3 block5) (on block4 block3) (ontable block5) (handempty))
	(:goal (and (on block1 block3) (on block2 block5) (clear block2) (ontable block3) (ontable block4) (clear block4) (on block5 block1))))