(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	satellite3 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite4 - satellite
	instrument19 - instrument
	instrument20 - instrument
	satellite5 - satellite
	instrument21 - instrument
	satellite6 - satellite
	instrument22 - instrument
	satellite7 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite8 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	satellite9 - satellite
	instrument31 - instrument
	spectrograph0 - mode
	spectrograph3 - mode
	infrared4 - mode
	image2 - mode
	infrared1 - mode
	Star2 - direction
	GroundStation20 - direction
	Star35 - direction
	Star8 - direction
	GroundStation10 - direction
	Star37 - direction
	GroundStation40 - direction
	GroundStation4 - direction
	Star15 - direction
	Star9 - direction
	GroundStation16 - direction
	Star34 - direction
	Star28 - direction
	GroundStation0 - direction
	Star27 - direction
	Star19 - direction
	Star39 - direction
	Star23 - direction
	GroundStation6 - direction
	GroundStation3 - direction
	GroundStation7 - direction
	GroundStation18 - direction
	Star13 - direction
	Star5 - direction
	Star36 - direction
	Star42 - direction
	GroundStation1 - direction
	Star26 - direction
	GroundStation43 - direction
	Star32 - direction
	Star30 - direction
	Star17 - direction
	Star25 - direction
	Star29 - direction
	Star21 - direction
	GroundStation41 - direction
	Star38 - direction
	Star12 - direction
	GroundStation33 - direction
	Star14 - direction
	Star11 - direction
	GroundStation24 - direction
	Star31 - direction
	GroundStation22 - direction
	Planet44 - direction
	Phenomenon45 - direction
)
(:init
	(supports instrument0 infrared1)
	(calibration_target instrument0 GroundStation6)
	(supports instrument1 spectrograph3)
	(supports instrument1 spectrograph0)
	(supports instrument1 infrared4)
	(calibration_target instrument1 Star30)
	(calibration_target instrument1 GroundStation33)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 Star36)
	(calibration_target instrument1 Star31)
	(calibration_target instrument1 Star29)
	(calibration_target instrument1 GroundStation24)
	(calibration_target instrument1 GroundStation20)
	(calibration_target instrument1 Star19)
	(calibration_target instrument1 Star39)
	(calibration_target instrument1 GroundStation3)
	(calibration_target instrument1 GroundStation18)
	(supports instrument2 infrared1)
	(supports instrument2 infrared4)
	(supports instrument2 image2)
	(calibration_target instrument2 GroundStation1)
	(calibration_target instrument2 GroundStation0)
	(calibration_target instrument2 GroundStation4)
	(calibration_target instrument2 Star39)
	(calibration_target instrument2 Star11)
	(calibration_target instrument2 GroundStation20)
	(supports instrument3 infrared1)
	(calibration_target instrument3 Star27)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 GroundStation33)
	(calibration_target instrument3 Star31)
	(calibration_target instrument3 Star23)
	(calibration_target instrument3 GroundStation16)
	(calibration_target instrument3 Star14)
	(calibration_target instrument3 Star36)
	(calibration_target instrument3 Star30)
	(calibration_target instrument3 Star21)
	(calibration_target instrument3 Star13)
	(calibration_target instrument3 GroundStation40)
	(supports instrument4 infrared1)
	(calibration_target instrument4 Star42)
	(calibration_target instrument4 Star8)
	(supports instrument5 image2)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 Star23)
	(calibration_target instrument5 Star35)
	(calibration_target instrument5 GroundStation43)
	(supports instrument6 spectrograph0)
	(supports instrument6 spectrograph3)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star15)
	(calibration_target instrument6 Star9)
	(calibration_target instrument6 GroundStation22)
	(calibration_target instrument6 Star12)
	(calibration_target instrument6 GroundStation20)
	(calibration_target instrument6 GroundStation7)
	(supports instrument7 image2)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 GroundStation43)
	(calibration_target instrument7 GroundStation3)
	(calibration_target instrument7 GroundStation6)
	(calibration_target instrument7 Star15)
	(calibration_target instrument7 Star28)
	(calibration_target instrument7 GroundStation10)
	(calibration_target instrument7 Star11)
	(calibration_target instrument7 Star8)
	(calibration_target instrument7 Star37)
	(calibration_target instrument7 Star17)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation18)
	(supports instrument8 spectrograph3)
	(supports instrument8 image2)
	(supports instrument8 infrared1)
	(calibration_target instrument8 Star34)
	(calibration_target instrument8 GroundStation18)
	(calibration_target instrument8 Star21)
	(calibration_target instrument8 Star39)
	(calibration_target instrument8 GroundStation24)
	(calibration_target instrument8 Star37)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation4)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 Star14)
	(calibration_target instrument9 GroundStation20)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 GroundStation33)
	(calibration_target instrument9 Star13)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 GroundStation0)
	(calibration_target instrument9 Star28)
	(calibration_target instrument9 Star19)
	(calibration_target instrument9 Star31)
	(calibration_target instrument9 Star39)
	(calibration_target instrument9 Star12)
	(calibration_target instrument9 Star17)
	(calibration_target instrument9 Star26)
	(on_board instrument9 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star31)
	(supports instrument10 image2)
	(supports instrument10 infrared4)
	(supports instrument10 spectrograph3)
	(calibration_target instrument10 GroundStation10)
	(calibration_target instrument10 GroundStation22)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 GroundStation41)
	(calibration_target instrument10 GroundStation3)
	(calibration_target instrument10 Star15)
	(calibration_target instrument10 Star19)
	(calibration_target instrument10 GroundStation20)
	(calibration_target instrument10 Star34)
	(supports instrument11 spectrograph3)
	(supports instrument11 infrared1)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 Star31)
	(calibration_target instrument11 Star14)
	(calibration_target instrument11 GroundStation20)
	(calibration_target instrument11 Star8)
	(calibration_target instrument11 Star30)
	(calibration_target instrument11 GroundStation4)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 GroundStation33)
	(calibration_target instrument11 Star11)
	(calibration_target instrument11 Star42)
	(calibration_target instrument11 GroundStation22)
	(calibration_target instrument11 GroundStation18)
	(calibration_target instrument11 Star13)
	(calibration_target instrument11 Star9)
	(supports instrument12 infrared4)
	(supports instrument12 image2)
	(supports instrument12 infrared1)
	(calibration_target instrument12 Star8)
	(calibration_target instrument12 Star14)
	(calibration_target instrument12 Star29)
	(calibration_target instrument12 GroundStation33)
	(calibration_target instrument12 GroundStation3)
	(calibration_target instrument12 GroundStation4)
	(calibration_target instrument12 GroundStation7)
	(calibration_target instrument12 Star36)
	(calibration_target instrument12 GroundStation22)
	(calibration_target instrument12 GroundStation18)
	(calibration_target instrument12 Star31)
	(calibration_target instrument12 Star35)
	(calibration_target instrument12 GroundStation40)
	(supports instrument13 spectrograph0)
	(supports instrument13 infrared4)
	(calibration_target instrument13 Star38)
	(calibration_target instrument13 GroundStation18)
	(calibration_target instrument13 Star23)
	(supports instrument14 spectrograph0)
	(calibration_target instrument14 Star8)
	(calibration_target instrument14 Star36)
	(calibration_target instrument14 GroundStation24)
	(supports instrument15 image2)
	(supports instrument15 spectrograph3)
	(calibration_target instrument15 GroundStation43)
	(calibration_target instrument15 Star26)
	(calibration_target instrument15 GroundStation40)
	(calibration_target instrument15 Star37)
	(calibration_target instrument15 Star23)
	(calibration_target instrument15 Star28)
	(calibration_target instrument15 Star17)
	(calibration_target instrument15 Star31)
	(calibration_target instrument15 Star14)
	(calibration_target instrument15 Star34)
	(calibration_target instrument15 Star13)
	(calibration_target instrument15 Star25)
	(supports instrument16 spectrograph3)
	(supports instrument16 spectrograph0)
	(supports instrument16 infrared4)
	(calibration_target instrument16 GroundStation18)
	(calibration_target instrument16 Star12)
	(supports instrument17 infrared4)
	(supports instrument17 spectrograph0)
	(supports instrument17 infrared1)
	(calibration_target instrument17 Star9)
	(calibration_target instrument17 Star37)
	(calibration_target instrument17 Star12)
	(calibration_target instrument17 Star17)
	(calibration_target instrument17 GroundStation40)
	(calibration_target instrument17 Star30)
	(calibration_target instrument17 Star21)
	(calibration_target instrument17 GroundStation16)
	(calibration_target instrument17 Star32)
	(supports instrument18 infrared4)
	(calibration_target instrument18 Star11)
	(calibration_target instrument18 Star36)
	(calibration_target instrument18 Star26)
	(calibration_target instrument18 Star8)
	(calibration_target instrument18 Star35)
	(calibration_target instrument18 Star38)
	(calibration_target instrument18 Star37)
	(calibration_target instrument18 Star2)
	(calibration_target instrument18 Star25)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star13)
	(supports instrument19 spectrograph0)
	(supports instrument19 spectrograph3)
	(supports instrument19 image2)
	(calibration_target instrument19 GroundStation1)
	(calibration_target instrument19 Star13)
	(calibration_target instrument19 Star15)
	(calibration_target instrument19 Star12)
	(calibration_target instrument19 Star11)
	(calibration_target instrument19 Star14)
	(calibration_target instrument19 GroundStation20)
	(calibration_target instrument19 Star8)
	(calibration_target instrument19 Star28)
	(supports instrument20 infrared1)
	(supports instrument20 spectrograph0)
	(supports instrument20 spectrograph3)
	(calibration_target instrument20 GroundStation22)
	(calibration_target instrument20 Star5)
	(calibration_target instrument20 Star13)
	(calibration_target instrument20 GroundStation10)
	(calibration_target instrument20 Star8)
	(calibration_target instrument20 Star23)
	(calibration_target instrument20 Star29)
	(calibration_target instrument20 Star32)
	(calibration_target instrument20 GroundStation43)
	(calibration_target instrument20 Star35)
	(calibration_target instrument20 Star9)
	(calibration_target instrument20 Star19)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation24)
	(supports instrument21 spectrograph0)
	(supports instrument21 infrared1)
	(supports instrument21 infrared4)
	(calibration_target instrument21 Star30)
	(calibration_target instrument21 Star25)
	(calibration_target instrument21 GroundStation10)
	(calibration_target instrument21 Star9)
	(calibration_target instrument21 Star42)
	(calibration_target instrument21 Star26)
	(calibration_target instrument21 Star8)
	(on_board instrument21 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation10)
	(supports instrument22 spectrograph3)
	(supports instrument22 spectrograph0)
	(calibration_target instrument22 Star21)
	(calibration_target instrument22 Star5)
	(calibration_target instrument22 Star23)
	(on_board instrument22 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation22)
	(supports instrument23 infrared4)
	(supports instrument23 spectrograph0)
	(calibration_target instrument23 Star14)
	(calibration_target instrument23 GroundStation4)
	(calibration_target instrument23 Star28)
	(calibration_target instrument23 GroundStation7)
	(calibration_target instrument23 Star21)
	(calibration_target instrument23 GroundStation40)
	(calibration_target instrument23 GroundStation18)
	(calibration_target instrument23 Star13)
	(calibration_target instrument23 Star37)
	(calibration_target instrument23 Star17)
	(calibration_target instrument23 GroundStation16)
	(calibration_target instrument23 Star29)
	(supports instrument24 infrared1)
	(supports instrument24 infrared4)
	(supports instrument24 image2)
	(calibration_target instrument24 Star42)
	(calibration_target instrument24 Star28)
	(calibration_target instrument24 Star34)
	(calibration_target instrument24 Star29)
	(calibration_target instrument24 GroundStation1)
	(calibration_target instrument24 Star11)
	(calibration_target instrument24 Star23)
	(calibration_target instrument24 GroundStation16)
	(calibration_target instrument24 Star9)
	(calibration_target instrument24 Star15)
	(supports instrument25 infrared1)
	(supports instrument25 spectrograph3)
	(supports instrument25 spectrograph0)
	(calibration_target instrument25 Star13)
	(calibration_target instrument25 Star27)
	(calibration_target instrument25 GroundStation0)
	(calibration_target instrument25 Star30)
	(calibration_target instrument25 GroundStation33)
	(calibration_target instrument25 Star14)
	(calibration_target instrument25 GroundStation24)
	(calibration_target instrument25 GroundStation41)
	(calibration_target instrument25 Star28)
	(supports instrument26 image2)
	(supports instrument26 infrared1)
	(supports instrument26 spectrograph3)
	(calibration_target instrument26 GroundStation3)
	(calibration_target instrument26 Star25)
	(calibration_target instrument26 Star30)
	(calibration_target instrument26 GroundStation6)
	(calibration_target instrument26 Star26)
	(calibration_target instrument26 Star31)
	(calibration_target instrument26 GroundStation22)
	(calibration_target instrument26 Star13)
	(calibration_target instrument26 Star23)
	(calibration_target instrument26 Star32)
	(calibration_target instrument26 Star39)
	(calibration_target instrument26 Star19)
	(on_board instrument23 satellite7)
	(on_board instrument24 satellite7)
	(on_board instrument25 satellite7)
	(on_board instrument26 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star17)
	(supports instrument27 infrared1)
	(supports instrument27 spectrograph0)
	(supports instrument27 image2)
	(calibration_target instrument27 GroundStation7)
	(supports instrument28 infrared4)
	(calibration_target instrument28 Star36)
	(calibration_target instrument28 Star5)
	(calibration_target instrument28 GroundStation22)
	(calibration_target instrument28 Star13)
	(calibration_target instrument28 Star29)
	(calibration_target instrument28 GroundStation18)
	(supports instrument29 spectrograph3)
	(supports instrument29 infrared4)
	(calibration_target instrument29 Star42)
	(calibration_target instrument29 GroundStation1)
	(calibration_target instrument29 GroundStation22)
	(supports instrument30 image2)
	(supports instrument30 infrared4)
	(calibration_target instrument30 GroundStation24)
	(calibration_target instrument30 Star30)
	(calibration_target instrument30 Star32)
	(calibration_target instrument30 GroundStation41)
	(calibration_target instrument30 GroundStation43)
	(calibration_target instrument30 Star26)
	(calibration_target instrument30 Star31)
	(calibration_target instrument30 GroundStation1)
	(on_board instrument27 satellite8)
	(on_board instrument28 satellite8)
	(on_board instrument29 satellite8)
	(on_board instrument30 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star32)
	(supports instrument31 infrared1)
	(calibration_target instrument31 GroundStation22)
	(calibration_target instrument31 Star31)
	(calibration_target instrument31 GroundStation24)
	(calibration_target instrument31 Star11)
	(calibration_target instrument31 Star14)
	(calibration_target instrument31 GroundStation33)
	(calibration_target instrument31 Star12)
	(calibration_target instrument31 Star38)
	(calibration_target instrument31 GroundStation41)
	(calibration_target instrument31 Star21)
	(calibration_target instrument31 Star29)
	(calibration_target instrument31 Star25)
	(calibration_target instrument31 Star17)
	(on_board instrument31 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation41)
)
(:goal (and
	(pointing satellite1 Star19)
	(pointing satellite4 Star12)
	(pointing satellite9 GroundStation18)
	(have_image Phenomenon45 infrared4)
))

)
