(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite2 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite3 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite4 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite5 - satellite
	instrument32 - instrument
	instrument33 - instrument
	satellite6 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	satellite7 - satellite
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	satellite8 - satellite
	instrument50 - instrument
	satellite9 - satellite
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	thermograph3 - mode
	thermograph0 - mode
	image1 - mode
	thermograph2 - mode
	thermograph4 - mode
	Star3 - direction
	GroundStation5 - direction
	GroundStation7 - direction
	GroundStation2 - direction
	Star1 - direction
	Star4 - direction
	Star0 - direction
	GroundStation6 - direction
	Star8 - direction
	Phenomenon9 - direction
)
(:init
	(supports instrument0 thermograph3)
	(supports instrument0 thermograph4)
	(supports instrument0 thermograph0)
	(calibration_target instrument0 Star1)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 image1)
	(supports instrument1 thermograph4)
	(supports instrument1 thermograph2)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 GroundStation6)
	(supports instrument2 thermograph4)
	(supports instrument2 thermograph2)
	(supports instrument2 image1)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 Star3)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star3)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 GroundStation6)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 GroundStation7)
	(supports instrument6 image1)
	(supports instrument6 thermograph4)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 GroundStation6)
	(supports instrument7 thermograph4)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 GroundStation6)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 GroundStation2)
	(calibration_target instrument8 GroundStation6)
	(supports instrument9 thermograph0)
	(supports instrument9 thermograph4)
	(supports instrument9 image1)
	(calibration_target instrument9 Star1)
	(supports instrument10 thermograph3)
	(supports instrument10 thermograph4)
	(supports instrument10 thermograph2)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 GroundStation6)
	(supports instrument11 image1)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 Star1)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 Star4)
	(calibration_target instrument12 GroundStation6)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation6)
	(supports instrument13 thermograph2)
	(supports instrument13 image1)
	(supports instrument13 thermograph3)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 image1)
	(calibration_target instrument14 Star1)
	(supports instrument15 thermograph2)
	(supports instrument15 thermograph4)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 Star4)
	(calibration_target instrument15 GroundStation2)
	(supports instrument16 thermograph2)
	(calibration_target instrument16 Star1)
	(calibration_target instrument16 GroundStation5)
	(supports instrument17 thermograph2)
	(calibration_target instrument17 GroundStation7)
	(calibration_target instrument17 Star0)
	(supports instrument18 thermograph4)
	(supports instrument18 image1)
	(calibration_target instrument18 GroundStation2)
	(calibration_target instrument18 Star4)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation2)
	(supports instrument19 image1)
	(supports instrument19 thermograph3)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 Star4)
	(supports instrument20 image1)
	(supports instrument20 thermograph0)
	(supports instrument20 thermograph3)
	(calibration_target instrument20 GroundStation5)
	(calibration_target instrument20 Star4)
	(supports instrument21 thermograph3)
	(supports instrument21 thermograph2)
	(calibration_target instrument21 Star4)
	(supports instrument22 thermograph3)
	(supports instrument22 thermograph0)
	(calibration_target instrument22 GroundStation6)
	(supports instrument23 thermograph4)
	(supports instrument23 thermograph0)
	(supports instrument23 thermograph2)
	(calibration_target instrument23 GroundStation5)
	(calibration_target instrument23 Star1)
	(supports instrument24 image1)
	(calibration_target instrument24 GroundStation7)
	(supports instrument25 thermograph4)
	(supports instrument25 image1)
	(supports instrument25 thermograph0)
	(calibration_target instrument25 GroundStation2)
	(supports instrument26 image1)
	(supports instrument26 thermograph2)
	(calibration_target instrument26 Star3)
	(supports instrument27 thermograph0)
	(supports instrument27 thermograph4)
	(calibration_target instrument27 Star0)
	(supports instrument28 image1)
	(supports instrument28 thermograph2)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 GroundStation5)
	(calibration_target instrument28 GroundStation6)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star4)
	(supports instrument29 thermograph2)
	(calibration_target instrument29 GroundStation5)
	(calibration_target instrument29 GroundStation7)
	(supports instrument30 thermograph3)
	(supports instrument30 thermograph2)
	(calibration_target instrument30 GroundStation2)
	(calibration_target instrument30 Star4)
	(supports instrument31 image1)
	(calibration_target instrument31 GroundStation5)
	(calibration_target instrument31 Star3)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star1)
	(supports instrument32 thermograph0)
	(calibration_target instrument32 Star3)
	(supports instrument33 thermograph4)
	(supports instrument33 image1)
	(calibration_target instrument33 Star4)
	(calibration_target instrument33 GroundStation2)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star1)
	(supports instrument34 thermograph4)
	(calibration_target instrument34 Star1)
	(supports instrument35 thermograph0)
	(calibration_target instrument35 Star4)
	(supports instrument36 thermograph0)
	(supports instrument36 thermograph3)
	(calibration_target instrument36 GroundStation2)
	(calibration_target instrument36 Star0)
	(supports instrument37 thermograph0)
	(supports instrument37 image1)
	(calibration_target instrument37 GroundStation7)
	(supports instrument38 image1)
	(calibration_target instrument38 Star0)
	(calibration_target instrument38 GroundStation5)
	(supports instrument39 thermograph4)
	(supports instrument39 thermograph3)
	(calibration_target instrument39 Star3)
	(calibration_target instrument39 GroundStation2)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star8)
	(supports instrument40 thermograph4)
	(supports instrument40 image1)
	(supports instrument40 thermograph2)
	(calibration_target instrument40 GroundStation6)
	(calibration_target instrument40 GroundStation5)
	(supports instrument41 thermograph2)
	(supports instrument41 thermograph3)
	(calibration_target instrument41 Star3)
	(supports instrument42 thermograph0)
	(supports instrument42 image1)
	(supports instrument42 thermograph4)
	(calibration_target instrument42 Star4)
	(calibration_target instrument42 GroundStation5)
	(supports instrument43 thermograph3)
	(calibration_target instrument43 Star0)
	(supports instrument44 thermograph2)
	(supports instrument44 image1)
	(supports instrument44 thermograph3)
	(calibration_target instrument44 GroundStation5)
	(calibration_target instrument44 GroundStation2)
	(supports instrument45 thermograph3)
	(calibration_target instrument45 Star0)
	(calibration_target instrument45 GroundStation5)
	(supports instrument46 thermograph3)
	(supports instrument46 image1)
	(supports instrument46 thermograph2)
	(calibration_target instrument46 GroundStation7)
	(calibration_target instrument46 Star0)
	(supports instrument47 thermograph2)
	(supports instrument47 thermograph3)
	(calibration_target instrument47 Star0)
	(calibration_target instrument47 GroundStation2)
	(supports instrument48 thermograph0)
	(supports instrument48 thermograph2)
	(supports instrument48 image1)
	(calibration_target instrument48 GroundStation2)
	(calibration_target instrument48 GroundStation7)
	(supports instrument49 image1)
	(supports instrument49 thermograph4)
	(calibration_target instrument49 GroundStation7)
	(calibration_target instrument49 GroundStation2)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star4)
	(supports instrument50 thermograph0)
	(supports instrument50 image1)
	(supports instrument50 thermograph2)
	(calibration_target instrument50 Star4)
	(on_board instrument50 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation5)
	(supports instrument51 thermograph2)
	(calibration_target instrument51 GroundStation2)
	(supports instrument52 image1)
	(supports instrument52 thermograph4)
	(supports instrument52 thermograph0)
	(calibration_target instrument52 Star1)
	(calibration_target instrument52 GroundStation6)
	(supports instrument53 thermograph2)
	(calibration_target instrument53 Star1)
	(calibration_target instrument53 GroundStation2)
	(supports instrument54 thermograph2)
	(supports instrument54 image1)
	(supports instrument54 thermograph4)
	(calibration_target instrument54 Star0)
	(calibration_target instrument54 Star4)
	(supports instrument55 thermograph4)
	(supports instrument55 thermograph2)
	(supports instrument55 image1)
	(calibration_target instrument55 GroundStation6)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation7)
)
(:goal (and
	(pointing satellite2 Star8)
	(pointing satellite8 GroundStation5)
	(have_image Star8 image1)
	(have_image Phenomenon9 thermograph2)
))

)
