(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite4 - satellite
	instrument20 - instrument
	satellite5 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite6 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite7 - satellite
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite8 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite9 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	image2 - mode
	spectrograph1 - mode
	thermograph0 - mode
	thermograph4 - mode
	spectrograph3 - mode
	Star0 - direction
	GroundStation4 - direction
	GroundStation1 - direction
	Star6 - direction
	Star3 - direction
	GroundStation5 - direction
	Star7 - direction
	Star2 - direction
	Planet8 - direction
	Phenomenon9 - direction
)
(:init
	(supports instrument0 image2)
	(calibration_target instrument0 GroundStation5)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 thermograph4)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 Star6)
	(calibration_target instrument2 Star7)
	(supports instrument3 thermograph0)
	(supports instrument3 spectrograph3)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 Star7)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 Star7)
	(supports instrument6 image2)
	(supports instrument6 thermograph4)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 Star0)
	(supports instrument7 thermograph4)
	(supports instrument7 image2)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 GroundStation5)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet8)
	(supports instrument8 thermograph0)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 Star6)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 Star6)
	(supports instrument10 thermograph0)
	(supports instrument10 image2)
	(supports instrument10 spectrograph3)
	(calibration_target instrument10 Star6)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star7)
	(supports instrument11 spectrograph1)
	(supports instrument11 thermograph0)
	(supports instrument11 spectrograph3)
	(calibration_target instrument11 Star7)
	(calibration_target instrument11 Star2)
	(supports instrument12 image2)
	(supports instrument12 spectrograph1)
	(calibration_target instrument12 Star3)
	(calibration_target instrument12 GroundStation1)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 GroundStation4)
	(supports instrument14 image2)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 Star0)
	(supports instrument15 image2)
	(calibration_target instrument15 Star3)
	(supports instrument16 spectrograph1)
	(supports instrument16 spectrograph3)
	(supports instrument16 image2)
	(calibration_target instrument16 Star6)
	(supports instrument17 thermograph0)
	(supports instrument17 thermograph4)
	(supports instrument17 spectrograph1)
	(calibration_target instrument17 Star6)
	(supports instrument18 spectrograph1)
	(supports instrument18 thermograph0)
	(calibration_target instrument18 GroundStation5)
	(calibration_target instrument18 Star6)
	(supports instrument19 spectrograph3)
	(supports instrument19 spectrograph1)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 Star6)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star6)
	(supports instrument20 thermograph0)
	(calibration_target instrument20 Star3)
	(on_board instrument20 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star6)
	(supports instrument21 image2)
	(calibration_target instrument21 Star7)
	(supports instrument22 spectrograph3)
	(calibration_target instrument22 Star7)
	(supports instrument23 thermograph0)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 Star0)
	(supports instrument24 image2)
	(supports instrument24 thermograph4)
	(calibration_target instrument24 Star3)
	(calibration_target instrument24 Star2)
	(supports instrument25 spectrograph3)
	(calibration_target instrument25 Star2)
	(calibration_target instrument25 Star7)
	(supports instrument26 image2)
	(supports instrument26 spectrograph1)
	(supports instrument26 thermograph0)
	(calibration_target instrument26 GroundStation5)
	(supports instrument27 spectrograph3)
	(supports instrument27 thermograph4)
	(calibration_target instrument27 Star7)
	(calibration_target instrument27 Star6)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation4)
	(supports instrument28 image2)
	(calibration_target instrument28 Star2)
	(supports instrument29 thermograph0)
	(supports instrument29 image2)
	(supports instrument29 thermograph4)
	(calibration_target instrument29 Star3)
	(supports instrument30 image2)
	(calibration_target instrument30 GroundStation1)
	(calibration_target instrument30 GroundStation4)
	(supports instrument31 image2)
	(supports instrument31 thermograph4)
	(supports instrument31 spectrograph1)
	(calibration_target instrument31 Star3)
	(calibration_target instrument31 GroundStation5)
	(supports instrument32 thermograph0)
	(supports instrument32 spectrograph3)
	(supports instrument32 spectrograph1)
	(calibration_target instrument32 Star6)
	(calibration_target instrument32 GroundStation5)
	(supports instrument33 thermograph0)
	(supports instrument33 spectrograph1)
	(supports instrument33 thermograph4)
	(calibration_target instrument33 Star0)
	(supports instrument34 thermograph0)
	(calibration_target instrument34 Star7)
	(supports instrument35 image2)
	(supports instrument35 thermograph0)
	(supports instrument35 thermograph4)
	(calibration_target instrument35 Star0)
	(on_board instrument28 satellite6)
	(on_board instrument29 satellite6)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star7)
	(supports instrument36 image2)
	(supports instrument36 spectrograph1)
	(calibration_target instrument36 Star2)
	(calibration_target instrument36 Star3)
	(supports instrument37 spectrograph3)
	(supports instrument37 spectrograph1)
	(calibration_target instrument37 GroundStation1)
	(calibration_target instrument37 Star0)
	(supports instrument38 spectrograph3)
	(supports instrument38 thermograph4)
	(calibration_target instrument38 Star7)
	(calibration_target instrument38 Star3)
	(supports instrument39 spectrograph1)
	(calibration_target instrument39 GroundStation1)
	(calibration_target instrument39 GroundStation4)
	(supports instrument40 spectrograph3)
	(supports instrument40 spectrograph1)
	(calibration_target instrument40 Star7)
	(supports instrument41 thermograph4)
	(calibration_target instrument41 Star6)
	(calibration_target instrument41 GroundStation5)
	(supports instrument42 spectrograph1)
	(supports instrument42 spectrograph3)
	(supports instrument42 thermograph0)
	(calibration_target instrument42 GroundStation5)
	(calibration_target instrument42 Star6)
	(supports instrument43 thermograph0)
	(calibration_target instrument43 Star6)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation4)
	(supports instrument44 spectrograph3)
	(calibration_target instrument44 Star2)
	(calibration_target instrument44 Star6)
	(supports instrument45 spectrograph1)
	(supports instrument45 spectrograph3)
	(supports instrument45 thermograph4)
	(calibration_target instrument45 GroundStation4)
	(supports instrument46 image2)
	(supports instrument46 spectrograph1)
	(supports instrument46 spectrograph3)
	(calibration_target instrument46 Star3)
	(supports instrument47 thermograph0)
	(supports instrument47 spectrograph3)
	(supports instrument47 image2)
	(calibration_target instrument47 Star6)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(on_board instrument47 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star6)
	(supports instrument48 image2)
	(supports instrument48 thermograph4)
	(calibration_target instrument48 Star0)
	(calibration_target instrument48 Star6)
	(supports instrument49 spectrograph3)
	(calibration_target instrument49 Star2)
	(calibration_target instrument49 GroundStation1)
	(supports instrument50 image2)
	(calibration_target instrument50 GroundStation5)
	(calibration_target instrument50 GroundStation4)
	(supports instrument51 image2)
	(supports instrument51 spectrograph3)
	(supports instrument51 spectrograph1)
	(calibration_target instrument51 GroundStation1)
	(calibration_target instrument51 GroundStation4)
	(supports instrument52 spectrograph1)
	(supports instrument52 thermograph4)
	(calibration_target instrument52 Star2)
	(calibration_target instrument52 Star6)
	(supports instrument53 spectrograph3)
	(supports instrument53 thermograph4)
	(calibration_target instrument53 GroundStation5)
	(calibration_target instrument53 Star3)
	(supports instrument54 spectrograph1)
	(supports instrument54 spectrograph3)
	(supports instrument54 thermograph0)
	(calibration_target instrument54 GroundStation5)
	(calibration_target instrument54 Star3)
	(supports instrument55 spectrograph3)
	(supports instrument55 thermograph4)
	(supports instrument55 thermograph0)
	(calibration_target instrument55 Star2)
	(calibration_target instrument55 Star7)
	(on_board instrument48 satellite9)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star7)
)
(:goal (and
	(pointing satellite0 Star3)
	(pointing satellite1 Phenomenon9)
	(pointing satellite4 Phenomenon9)
	(have_image Planet8 image2)
))

)
