(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite6 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite7 - satellite
	instrument24 - instrument
	instrument25 - instrument
	satellite8 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite9 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	spectrograph3 - mode
	infrared4 - mode
	image2 - mode
	spectrograph0 - mode
	infrared1 - mode
	GroundStation0 - direction
	GroundStation3 - direction
	GroundStation1 - direction
	GroundStation4 - direction
	GroundStation6 - direction
	GroundStation7 - direction
	Star5 - direction
	Star2 - direction
	Star8 - direction
	Phenomenon9 - direction
)
(:init
	(supports instrument0 spectrograph3)
	(supports instrument0 infrared4)
	(calibration_target instrument0 GroundStation3)
	(calibration_target instrument0 Star5)
	(supports instrument1 infrared1)
	(supports instrument1 spectrograph3)
	(supports instrument1 image2)
	(calibration_target instrument1 GroundStation3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation4)
	(supports instrument2 image2)
	(calibration_target instrument2 GroundStation7)
	(supports instrument3 infrared4)
	(supports instrument3 infrared1)
	(supports instrument3 image2)
	(calibration_target instrument3 GroundStation7)
	(calibration_target instrument3 Star2)
	(supports instrument4 image2)
	(calibration_target instrument4 Star2)
	(supports instrument5 infrared1)
	(calibration_target instrument5 GroundStation0)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 GroundStation4)
	(supports instrument7 infrared1)
	(supports instrument7 image2)
	(calibration_target instrument7 GroundStation1)
	(calibration_target instrument7 GroundStation3)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star8)
	(supports instrument8 spectrograph3)
	(supports instrument8 infrared1)
	(supports instrument8 image2)
	(calibration_target instrument8 GroundStation4)
	(supports instrument9 spectrograph3)
	(supports instrument9 infrared4)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 Star2)
	(supports instrument10 infrared1)
	(supports instrument10 spectrograph0)
	(supports instrument10 infrared4)
	(calibration_target instrument10 Star5)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star2)
	(supports instrument11 infrared4)
	(supports instrument11 infrared1)
	(supports instrument11 image2)
	(calibration_target instrument11 Star2)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star5)
	(supports instrument12 spectrograph0)
	(supports instrument12 image2)
	(calibration_target instrument12 Star2)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star2)
	(supports instrument13 spectrograph0)
	(supports instrument13 infrared4)
	(calibration_target instrument13 Star5)
	(supports instrument14 spectrograph0)
	(calibration_target instrument14 Star5)
	(calibration_target instrument14 GroundStation7)
	(supports instrument15 infrared4)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 Star2)
	(calibration_target instrument15 GroundStation3)
	(supports instrument16 infrared1)
	(supports instrument16 image2)
	(calibration_target instrument16 Star5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation1)
	(supports instrument17 spectrograph3)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 Star5)
	(supports instrument18 spectrograph3)
	(supports instrument18 infrared1)
	(supports instrument18 infrared4)
	(calibration_target instrument18 Star5)
	(calibration_target instrument18 GroundStation6)
	(supports instrument19 image2)
	(supports instrument19 infrared4)
	(supports instrument19 spectrograph3)
	(calibration_target instrument19 GroundStation4)
	(calibration_target instrument19 GroundStation3)
	(supports instrument20 image2)
	(supports instrument20 spectrograph3)
	(supports instrument20 infrared1)
	(calibration_target instrument20 GroundStation1)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 GroundStation7)
	(calibration_target instrument21 GroundStation6)
	(supports instrument22 infrared4)
	(supports instrument22 image2)
	(calibration_target instrument22 GroundStation6)
	(calibration_target instrument22 GroundStation0)
	(supports instrument23 spectrograph0)
	(supports instrument23 spectrograph3)
	(supports instrument23 image2)
	(calibration_target instrument23 GroundStation6)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(on_board instrument20 satellite6)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(on_board instrument23 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation4)
	(supports instrument24 image2)
	(calibration_target instrument24 Star5)
	(supports instrument25 spectrograph0)
	(supports instrument25 spectrograph3)
	(calibration_target instrument25 Star5)
	(calibration_target instrument25 GroundStation7)
	(on_board instrument24 satellite7)
	(on_board instrument25 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation4)
	(supports instrument26 infrared1)
	(supports instrument26 spectrograph3)
	(calibration_target instrument26 Star2)
	(calibration_target instrument26 Star5)
	(supports instrument27 spectrograph3)
	(supports instrument27 image2)
	(supports instrument27 infrared4)
	(calibration_target instrument27 GroundStation6)
	(supports instrument28 spectrograph0)
	(supports instrument28 spectrograph3)
	(calibration_target instrument28 Star5)
	(supports instrument29 spectrograph0)
	(supports instrument29 spectrograph3)
	(calibration_target instrument29 GroundStation3)
	(supports instrument30 infrared1)
	(supports instrument30 spectrograph3)
	(calibration_target instrument30 GroundStation6)
	(calibration_target instrument30 GroundStation7)
	(supports instrument31 spectrograph0)
	(supports instrument31 spectrograph3)
	(calibration_target instrument31 Star2)
	(calibration_target instrument31 GroundStation1)
	(supports instrument32 spectrograph3)
	(supports instrument32 spectrograph0)
	(calibration_target instrument32 GroundStation6)
	(calibration_target instrument32 GroundStation7)
	(on_board instrument26 satellite8)
	(on_board instrument27 satellite8)
	(on_board instrument28 satellite8)
	(on_board instrument29 satellite8)
	(on_board instrument30 satellite8)
	(on_board instrument31 satellite8)
	(on_board instrument32 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation3)
	(supports instrument33 image2)
	(calibration_target instrument33 GroundStation4)
	(calibration_target instrument33 GroundStation6)
	(supports instrument34 infrared4)
	(supports instrument34 infrared1)
	(calibration_target instrument34 GroundStation6)
	(supports instrument35 infrared4)
	(calibration_target instrument35 GroundStation7)
	(supports instrument36 infrared1)
	(supports instrument36 spectrograph0)
	(supports instrument36 image2)
	(calibration_target instrument36 Star2)
	(calibration_target instrument36 Star5)
	(on_board instrument33 satellite9)
	(on_board instrument34 satellite9)
	(on_board instrument35 satellite9)
	(on_board instrument36 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star2)
)
(:goal (and
	(pointing satellite1 GroundStation1)
	(pointing satellite2 Phenomenon9)
	(pointing satellite4 GroundStation7)
	(have_image Star8 image2)
	(have_image Phenomenon9 infrared1)
))

)
