(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite2 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	satellite4 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite5 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite6 - satellite
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	satellite7 - satellite
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	satellite8 - satellite
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	satellite9 - satellite
	instrument61 - instrument
	instrument62 - instrument
	instrument63 - instrument
	instrument64 - instrument
	infrared1 - mode
	image3 - mode
	spectrograph0 - mode
	image2 - mode
	image4 - mode
	Star6 - direction
	Star8 - direction
	Star0 - direction
	Star3 - direction
	GroundStation2 - direction
	GroundStation1 - direction
	Star5 - direction
	GroundStation4 - direction
	Star7 - direction
	Phenomenon9 - direction
	Planet10 - direction
)
(:init
	(supports instrument0 image3)
	(supports instrument0 image2)
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 GroundStation4)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 Star6)
	(supports instrument2 image2)
	(calibration_target instrument2 Star7)
	(supports instrument3 image2)
	(supports instrument3 image4)
	(supports instrument3 infrared1)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 GroundStation1)
	(calibration_target instrument3 Star6)
	(supports instrument4 image3)
	(calibration_target instrument4 Star7)
	(supports instrument5 infrared1)
	(supports instrument5 image2)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 GroundStation1)
	(calibration_target instrument5 Star6)
	(calibration_target instrument5 Star3)
	(supports instrument6 image3)
	(supports instrument6 spectrograph0)
	(supports instrument6 image4)
	(calibration_target instrument6 Star8)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star8)
	(supports instrument7 image2)
	(supports instrument7 image4)
	(calibration_target instrument7 Star6)
	(calibration_target instrument7 Star7)
	(calibration_target instrument7 GroundStation1)
	(supports instrument8 image2)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 Star6)
	(supports instrument9 image3)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 image2)
	(supports instrument10 image4)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 Star6)
	(calibration_target instrument10 Star3)
	(supports instrument11 image3)
	(calibration_target instrument11 Star0)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star5)
	(supports instrument12 image2)
	(supports instrument12 image3)
	(calibration_target instrument12 Star6)
	(calibration_target instrument12 Star7)
	(calibration_target instrument12 Star5)
	(supports instrument13 infrared1)
	(calibration_target instrument13 Star7)
	(calibration_target instrument13 Star5)
	(supports instrument14 image2)
	(supports instrument14 image4)
	(calibration_target instrument14 Star7)
	(calibration_target instrument14 GroundStation1)
	(calibration_target instrument14 Star3)
	(supports instrument15 spectrograph0)
	(supports instrument15 image2)
	(supports instrument15 infrared1)
	(calibration_target instrument15 Star6)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 Star3)
	(supports instrument16 image4)
	(supports instrument16 image2)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 Star8)
	(calibration_target instrument16 Star3)
	(supports instrument17 image2)
	(supports instrument17 spectrograph0)
	(supports instrument17 infrared1)
	(calibration_target instrument17 Star0)
	(calibration_target instrument17 Star3)
	(calibration_target instrument17 GroundStation4)
	(supports instrument18 image4)
	(supports instrument18 image3)
	(supports instrument18 infrared1)
	(calibration_target instrument18 Star6)
	(supports instrument19 image4)
	(supports instrument19 infrared1)
	(supports instrument19 image2)
	(calibration_target instrument19 Star6)
	(calibration_target instrument19 Star5)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument20 image4)
	(supports instrument20 image2)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 Star0)
	(on_board instrument20 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation1)
	(supports instrument21 image2)
	(supports instrument21 spectrograph0)
	(supports instrument21 infrared1)
	(calibration_target instrument21 GroundStation2)
	(supports instrument22 image4)
	(supports instrument22 image3)
	(supports instrument22 image2)
	(calibration_target instrument22 GroundStation4)
	(calibration_target instrument22 GroundStation1)
	(calibration_target instrument22 Star7)
	(supports instrument23 infrared1)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 image2)
	(supports instrument24 image3)
	(calibration_target instrument24 Star8)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 Star7)
	(supports instrument25 image2)
	(supports instrument25 infrared1)
	(calibration_target instrument25 Star7)
	(calibration_target instrument25 Star6)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation2)
	(supports instrument26 image2)
	(supports instrument26 infrared1)
	(supports instrument26 image3)
	(calibration_target instrument26 GroundStation1)
	(calibration_target instrument26 Star0)
	(calibration_target instrument26 Star7)
	(supports instrument27 infrared1)
	(supports instrument27 image3)
	(calibration_target instrument27 GroundStation1)
	(calibration_target instrument27 Star3)
	(calibration_target instrument27 Star0)
	(supports instrument28 image3)
	(supports instrument28 image4)
	(supports instrument28 spectrograph0)
	(calibration_target instrument28 Star0)
	(calibration_target instrument28 Star8)
	(supports instrument29 image3)
	(supports instrument29 infrared1)
	(calibration_target instrument29 Star8)
	(calibration_target instrument29 Star5)
	(supports instrument30 image3)
	(calibration_target instrument30 GroundStation4)
	(supports instrument31 image4)
	(supports instrument31 image2)
	(supports instrument31 image3)
	(calibration_target instrument31 Star6)
	(calibration_target instrument31 Star7)
	(calibration_target instrument31 GroundStation1)
	(supports instrument32 spectrograph0)
	(calibration_target instrument32 Star6)
	(calibration_target instrument32 Star5)
	(supports instrument33 image2)
	(supports instrument33 image4)
	(supports instrument33 infrared1)
	(calibration_target instrument33 Star7)
	(supports instrument34 image2)
	(supports instrument34 image4)
	(calibration_target instrument34 Star7)
	(calibration_target instrument34 Star3)
	(supports instrument35 image2)
	(supports instrument35 image3)
	(calibration_target instrument35 Star0)
	(calibration_target instrument35 Star5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star8)
	(supports instrument36 image3)
	(supports instrument36 image2)
	(supports instrument36 infrared1)
	(calibration_target instrument36 GroundStation4)
	(calibration_target instrument36 Star8)
	(calibration_target instrument36 Star5)
	(supports instrument37 image3)
	(calibration_target instrument37 Star0)
	(calibration_target instrument37 Star3)
	(calibration_target instrument37 Star6)
	(supports instrument38 image4)
	(supports instrument38 spectrograph0)
	(supports instrument38 image3)
	(calibration_target instrument38 GroundStation4)
	(calibration_target instrument38 Star7)
	(calibration_target instrument38 Star0)
	(supports instrument39 spectrograph0)
	(supports instrument39 image2)
	(supports instrument39 infrared1)
	(calibration_target instrument39 Star0)
	(calibration_target instrument39 Star8)
	(supports instrument40 image3)
	(supports instrument40 spectrograph0)
	(calibration_target instrument40 Star0)
	(calibration_target instrument40 Star6)
	(supports instrument41 spectrograph0)
	(calibration_target instrument41 Star6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star6)
	(supports instrument42 infrared1)
	(calibration_target instrument42 Star8)
	(calibration_target instrument42 GroundStation4)
	(calibration_target instrument42 Star6)
	(supports instrument43 infrared1)
	(supports instrument43 spectrograph0)
	(calibration_target instrument43 Star0)
	(calibration_target instrument43 Star3)
	(supports instrument44 spectrograph0)
	(supports instrument44 image4)
	(calibration_target instrument44 Star3)
	(supports instrument45 spectrograph0)
	(calibration_target instrument45 Star5)
	(calibration_target instrument45 Star0)
	(calibration_target instrument45 Star8)
	(supports instrument46 infrared1)
	(supports instrument46 image4)
	(calibration_target instrument46 Star6)
	(supports instrument47 infrared1)
	(supports instrument47 image3)
	(calibration_target instrument47 Star5)
	(supports instrument48 spectrograph0)
	(supports instrument48 image4)
	(supports instrument48 image2)
	(calibration_target instrument48 GroundStation2)
	(calibration_target instrument48 Star7)
	(calibration_target instrument48 GroundStation1)
	(supports instrument49 image4)
	(supports instrument49 image2)
	(supports instrument49 spectrograph0)
	(calibration_target instrument49 GroundStation1)
	(calibration_target instrument49 Star0)
	(supports instrument50 image3)
	(supports instrument50 infrared1)
	(supports instrument50 spectrograph0)
	(calibration_target instrument50 Star7)
	(calibration_target instrument50 Star3)
	(calibration_target instrument50 Star8)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
	(supports instrument51 image4)
	(calibration_target instrument51 Star0)
	(supports instrument52 image2)
	(supports instrument52 image4)
	(supports instrument52 infrared1)
	(calibration_target instrument52 Star5)
	(calibration_target instrument52 Star7)
	(calibration_target instrument52 Star0)
	(supports instrument53 image2)
	(supports instrument53 infrared1)
	(calibration_target instrument53 GroundStation4)
	(calibration_target instrument53 Star8)
	(calibration_target instrument53 Star0)
	(supports instrument54 spectrograph0)
	(supports instrument54 image3)
	(calibration_target instrument54 GroundStation2)
	(calibration_target instrument54 Star7)
	(calibration_target instrument54 Star3)
	(supports instrument55 image4)
	(supports instrument55 image2)
	(supports instrument55 image3)
	(calibration_target instrument55 Star3)
	(calibration_target instrument55 GroundStation1)
	(calibration_target instrument55 Star7)
	(supports instrument56 image4)
	(supports instrument56 spectrograph0)
	(calibration_target instrument56 Star3)
	(supports instrument57 infrared1)
	(supports instrument57 image3)
	(supports instrument57 image4)
	(calibration_target instrument57 Star8)
	(calibration_target instrument57 Star6)
	(supports instrument58 infrared1)
	(supports instrument58 image4)
	(calibration_target instrument58 Star7)
	(supports instrument59 infrared1)
	(supports instrument59 image4)
	(calibration_target instrument59 Star3)
	(supports instrument60 image3)
	(calibration_target instrument60 Star7)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(on_board instrument60 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon9)
	(supports instrument61 image3)
	(supports instrument61 infrared1)
	(calibration_target instrument61 Star3)
	(calibration_target instrument61 GroundStation1)
	(calibration_target instrument61 Star0)
	(supports instrument62 image3)
	(supports instrument62 spectrograph0)
	(calibration_target instrument62 GroundStation1)
	(calibration_target instrument62 GroundStation2)
	(calibration_target instrument62 GroundStation4)
	(supports instrument63 spectrograph0)
	(calibration_target instrument63 Star5)
	(supports instrument64 image4)
	(supports instrument64 image2)
	(calibration_target instrument64 Star7)
	(calibration_target instrument64 GroundStation4)
	(on_board instrument61 satellite9)
	(on_board instrument62 satellite9)
	(on_board instrument63 satellite9)
	(on_board instrument64 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation4)
)
(:goal (and
	(pointing satellite0 Phenomenon9)
	(pointing satellite3 Star8)
	(pointing satellite4 Star6)
	(pointing satellite7 Planet10)
	(pointing satellite8 Star3)
	(pointing satellite9 GroundStation4)
	(have_image Phenomenon9 infrared1)
	(have_image Planet10 image4)
))

)
