(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite2 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite3 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite4 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite5 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite6 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	satellite7 - satellite
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	satellite8 - satellite
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	instrument61 - instrument
	instrument62 - instrument
	instrument63 - instrument
	instrument64 - instrument
	instrument65 - instrument
	instrument66 - instrument
	instrument67 - instrument
	satellite9 - satellite
	instrument68 - instrument
	image1 - mode
	infrared3 - mode
	thermograph2 - mode
	spectrograph0 - mode
	spectrograph4 - mode
	Star6 - direction
	Star2 - direction
	Star4 - direction
	Star0 - direction
	GroundStation1 - direction
	GroundStation8 - direction
	GroundStation7 - direction
	Star3 - direction
	Star5 - direction
	Star9 - direction
	Star10 - direction
)
(:init
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 Star3)
	(calibration_target instrument0 Star2)
	(supports instrument1 infrared3)
	(calibration_target instrument1 Star6)
	(supports instrument2 infrared3)
	(calibration_target instrument2 GroundStation7)
	(calibration_target instrument2 GroundStation8)
	(supports instrument3 thermograph2)
	(supports instrument3 infrared3)
	(calibration_target instrument3 Star6)
	(supports instrument4 spectrograph0)
	(supports instrument4 image1)
	(calibration_target instrument4 Star4)
	(calibration_target instrument4 GroundStation8)
	(supports instrument5 spectrograph4)
	(calibration_target instrument5 Star0)
	(calibration_target instrument5 Star2)
	(supports instrument6 infrared3)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 GroundStation1)
	(calibration_target instrument6 GroundStation8)
	(calibration_target instrument6 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star2)
	(supports instrument7 image1)
	(calibration_target instrument7 Star4)
	(supports instrument8 infrared3)
	(supports instrument8 image1)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 Star4)
	(supports instrument9 spectrograph4)
	(supports instrument9 infrared3)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 GroundStation7)
	(supports instrument10 image1)
	(supports instrument10 spectrograph4)
	(supports instrument10 infrared3)
	(calibration_target instrument10 GroundStation7)
	(calibration_target instrument10 Star3)
	(supports instrument11 spectrograph0)
	(supports instrument11 image1)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 GroundStation8)
	(calibration_target instrument11 Star0)
	(supports instrument12 spectrograph4)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star3)
	(supports instrument13 spectrograph0)
	(calibration_target instrument13 Star0)
	(supports instrument14 spectrograph0)
	(supports instrument14 thermograph2)
	(calibration_target instrument14 GroundStation8)
	(calibration_target instrument14 Star6)
	(calibration_target instrument14 Star0)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star10)
	(supports instrument15 thermograph2)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 Star5)
	(calibration_target instrument15 Star0)
	(supports instrument16 thermograph2)
	(supports instrument16 image1)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 Star5)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 Star6)
	(supports instrument17 infrared3)
	(calibration_target instrument17 Star4)
	(calibration_target instrument17 GroundStation7)
	(calibration_target instrument17 Star3)
	(supports instrument18 infrared3)
	(supports instrument18 thermograph2)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 Star5)
	(supports instrument19 image1)
	(supports instrument19 spectrograph4)
	(calibration_target instrument19 Star5)
	(calibration_target instrument19 GroundStation8)
	(supports instrument20 spectrograph0)
	(supports instrument20 image1)
	(calibration_target instrument20 GroundStation7)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 Star5)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation1)
	(supports instrument21 image1)
	(calibration_target instrument21 Star5)
	(calibration_target instrument21 Star4)
	(supports instrument22 thermograph2)
	(supports instrument22 image1)
	(supports instrument22 spectrograph4)
	(calibration_target instrument22 Star3)
	(supports instrument23 spectrograph4)
	(supports instrument23 infrared3)
	(supports instrument23 image1)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 infrared3)
	(supports instrument24 image1)
	(calibration_target instrument24 GroundStation7)
	(supports instrument25 thermograph2)
	(calibration_target instrument25 Star3)
	(calibration_target instrument25 Star6)
	(calibration_target instrument25 Star5)
	(supports instrument26 spectrograph4)
	(supports instrument26 thermograph2)
	(supports instrument26 infrared3)
	(calibration_target instrument26 Star4)
	(supports instrument27 thermograph2)
	(supports instrument27 spectrograph4)
	(calibration_target instrument27 Star3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation7)
	(supports instrument28 image1)
	(calibration_target instrument28 GroundStation7)
	(calibration_target instrument28 Star0)
	(calibration_target instrument28 Star6)
	(supports instrument29 image1)
	(supports instrument29 spectrograph4)
	(supports instrument29 spectrograph0)
	(calibration_target instrument29 Star4)
	(calibration_target instrument29 GroundStation8)
	(calibration_target instrument29 GroundStation1)
	(supports instrument30 image1)
	(supports instrument30 spectrograph0)
	(calibration_target instrument30 Star3)
	(calibration_target instrument30 GroundStation8)
	(calibration_target instrument30 Star0)
	(supports instrument31 image1)
	(supports instrument31 thermograph2)
	(supports instrument31 spectrograph0)
	(calibration_target instrument31 Star4)
	(calibration_target instrument31 GroundStation1)
	(supports instrument32 image1)
	(calibration_target instrument32 Star4)
	(calibration_target instrument32 GroundStation1)
	(supports instrument33 spectrograph0)
	(calibration_target instrument33 Star4)
	(calibration_target instrument33 Star6)
	(calibration_target instrument33 GroundStation7)
	(supports instrument34 spectrograph0)
	(calibration_target instrument34 Star5)
	(calibration_target instrument34 GroundStation1)
	(supports instrument35 spectrograph0)
	(supports instrument35 image1)
	(calibration_target instrument35 GroundStation7)
	(calibration_target instrument35 Star3)
	(calibration_target instrument35 Star2)
	(supports instrument36 image1)
	(supports instrument36 spectrograph0)
	(calibration_target instrument36 Star0)
	(calibration_target instrument36 GroundStation8)
	(calibration_target instrument36 Star4)
	(supports instrument37 spectrograph0)
	(supports instrument37 thermograph2)
	(calibration_target instrument37 Star0)
	(calibration_target instrument37 GroundStation7)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(on_board instrument37 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation8)
	(supports instrument38 image1)
	(supports instrument38 thermograph2)
	(supports instrument38 spectrograph0)
	(calibration_target instrument38 Star4)
	(calibration_target instrument38 Star2)
	(supports instrument39 infrared3)
	(calibration_target instrument39 GroundStation8)
	(calibration_target instrument39 GroundStation1)
	(supports instrument40 spectrograph0)
	(supports instrument40 infrared3)
	(calibration_target instrument40 Star5)
	(calibration_target instrument40 Star2)
	(calibration_target instrument40 GroundStation1)
	(supports instrument41 thermograph2)
	(supports instrument41 infrared3)
	(calibration_target instrument41 Star5)
	(calibration_target instrument41 GroundStation7)
	(supports instrument42 spectrograph0)
	(calibration_target instrument42 GroundStation1)
	(supports instrument43 spectrograph0)
	(supports instrument43 infrared3)
	(supports instrument43 spectrograph4)
	(calibration_target instrument43 GroundStation7)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(on_board instrument41 satellite5)
	(on_board instrument42 satellite5)
	(on_board instrument43 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star2)
	(supports instrument44 image1)
	(supports instrument44 infrared3)
	(supports instrument44 thermograph2)
	(calibration_target instrument44 GroundStation7)
	(calibration_target instrument44 GroundStation8)
	(supports instrument45 spectrograph4)
	(supports instrument45 infrared3)
	(supports instrument45 spectrograph0)
	(calibration_target instrument45 GroundStation1)
	(calibration_target instrument45 GroundStation8)
	(supports instrument46 infrared3)
	(supports instrument46 spectrograph0)
	(calibration_target instrument46 Star2)
	(calibration_target instrument46 Star6)
	(calibration_target instrument46 Star4)
	(supports instrument47 infrared3)
	(supports instrument47 spectrograph4)
	(supports instrument47 image1)
	(calibration_target instrument47 Star0)
	(calibration_target instrument47 Star4)
	(calibration_target instrument47 GroundStation8)
	(supports instrument48 thermograph2)
	(calibration_target instrument48 Star2)
	(calibration_target instrument48 Star5)
	(calibration_target instrument48 GroundStation1)
	(supports instrument49 infrared3)
	(supports instrument49 spectrograph0)
	(calibration_target instrument49 Star4)
	(supports instrument50 infrared3)
	(calibration_target instrument50 Star3)
	(supports instrument51 infrared3)
	(calibration_target instrument51 Star2)
	(supports instrument52 spectrograph4)
	(supports instrument52 thermograph2)
	(calibration_target instrument52 GroundStation1)
	(calibration_target instrument52 Star2)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(on_board instrument46 satellite6)
	(on_board instrument47 satellite6)
	(on_board instrument48 satellite6)
	(on_board instrument49 satellite6)
	(on_board instrument50 satellite6)
	(on_board instrument51 satellite6)
	(on_board instrument52 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star0)
	(supports instrument53 spectrograph0)
	(calibration_target instrument53 Star6)
	(calibration_target instrument53 GroundStation1)
	(calibration_target instrument53 Star0)
	(supports instrument54 thermograph2)
	(supports instrument54 spectrograph4)
	(calibration_target instrument54 Star0)
	(supports instrument55 image1)
	(calibration_target instrument55 Star3)
	(calibration_target instrument55 Star2)
	(calibration_target instrument55 Star5)
	(supports instrument56 spectrograph4)
	(supports instrument56 thermograph2)
	(supports instrument56 image1)
	(calibration_target instrument56 GroundStation1)
	(calibration_target instrument56 Star6)
	(calibration_target instrument56 GroundStation7)
	(supports instrument57 image1)
	(supports instrument57 thermograph2)
	(calibration_target instrument57 GroundStation8)
	(calibration_target instrument57 Star4)
	(on_board instrument53 satellite7)
	(on_board instrument54 satellite7)
	(on_board instrument55 satellite7)
	(on_board instrument56 satellite7)
	(on_board instrument57 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star6)
	(supports instrument58 spectrograph0)
	(supports instrument58 spectrograph4)
	(calibration_target instrument58 Star5)
	(calibration_target instrument58 Star3)
	(supports instrument59 infrared3)
	(calibration_target instrument59 GroundStation8)
	(supports instrument60 infrared3)
	(calibration_target instrument60 Star4)
	(supports instrument61 thermograph2)
	(supports instrument61 spectrograph4)
	(supports instrument61 infrared3)
	(calibration_target instrument61 Star2)
	(supports instrument62 infrared3)
	(supports instrument62 thermograph2)
	(supports instrument62 spectrograph0)
	(calibration_target instrument62 GroundStation8)
	(calibration_target instrument62 Star4)
	(supports instrument63 image1)
	(supports instrument63 spectrograph0)
	(calibration_target instrument63 GroundStation8)
	(calibration_target instrument63 GroundStation1)
	(supports instrument64 infrared3)
	(calibration_target instrument64 Star0)
	(supports instrument65 thermograph2)
	(supports instrument65 infrared3)
	(supports instrument65 image1)
	(calibration_target instrument65 GroundStation1)
	(calibration_target instrument65 GroundStation7)
	(calibration_target instrument65 Star0)
	(supports instrument66 spectrograph4)
	(supports instrument66 thermograph2)
	(supports instrument66 image1)
	(calibration_target instrument66 GroundStation7)
	(calibration_target instrument66 GroundStation8)
	(calibration_target instrument66 Star3)
	(supports instrument67 infrared3)
	(supports instrument67 spectrograph0)
	(supports instrument67 image1)
	(calibration_target instrument67 Star3)
	(calibration_target instrument67 Star5)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(on_board instrument60 satellite8)
	(on_board instrument61 satellite8)
	(on_board instrument62 satellite8)
	(on_board instrument63 satellite8)
	(on_board instrument64 satellite8)
	(on_board instrument65 satellite8)
	(on_board instrument66 satellite8)
	(on_board instrument67 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star6)
	(supports instrument68 spectrograph4)
	(supports instrument68 spectrograph0)
	(supports instrument68 thermograph2)
	(calibration_target instrument68 Star5)
	(on_board instrument68 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star6)
)
(:goal (and
	(pointing satellite2 Star5)
	(pointing satellite5 Star4)
	(pointing satellite6 Star0)
	(have_image Star9 spectrograph4)
	(have_image Star10 thermograph2)
))

)
