(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite3 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite4 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	satellite5 - satellite
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	satellite6 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	satellite7 - satellite
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	satellite8 - satellite
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	satellite9 - satellite
	instrument61 - instrument
	infrared3 - mode
	infrared2 - mode
	spectrograph0 - mode
	image4 - mode
	thermograph1 - mode
	Star0 - direction
	Phenomenon1 - direction
	Phenomenon2 - direction
)
(:init
	(supports instrument0 infrared3)
	(supports instrument0 thermograph1)
	(calibration_target instrument0 Star0)
	(supports instrument1 image4)
	(supports instrument1 infrared3)
	(calibration_target instrument1 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon2)
	(supports instrument2 infrared3)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 Star0)
	(supports instrument3 image4)
	(supports instrument3 thermograph1)
	(calibration_target instrument3 Star0)
	(supports instrument4 image4)
	(calibration_target instrument4 Star0)
	(supports instrument5 image4)
	(supports instrument5 infrared3)
	(calibration_target instrument5 Star0)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star0)
	(supports instrument7 image4)
	(supports instrument7 thermograph1)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 Star0)
	(supports instrument8 infrared3)
	(supports instrument8 image4)
	(supports instrument8 spectrograph0)
	(calibration_target instrument8 Star0)
	(supports instrument9 spectrograph0)
	(supports instrument9 infrared2)
	(calibration_target instrument9 Star0)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon2)
	(supports instrument10 image4)
	(supports instrument10 infrared2)
	(calibration_target instrument10 Star0)
	(supports instrument11 image4)
	(supports instrument11 infrared3)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 Star0)
	(supports instrument12 image4)
	(calibration_target instrument12 Star0)
	(supports instrument13 thermograph1)
	(calibration_target instrument13 Star0)
	(supports instrument14 thermograph1)
	(supports instrument14 image4)
	(calibration_target instrument14 Star0)
	(supports instrument15 thermograph1)
	(supports instrument15 image4)
	(calibration_target instrument15 Star0)
	(supports instrument16 image4)
	(supports instrument16 infrared2)
	(supports instrument16 thermograph1)
	(calibration_target instrument16 Star0)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument17 infrared2)
	(supports instrument17 infrared3)
	(supports instrument17 thermograph1)
	(calibration_target instrument17 Star0)
	(supports instrument18 spectrograph0)
	(supports instrument18 infrared3)
	(calibration_target instrument18 Star0)
	(supports instrument19 thermograph1)
	(calibration_target instrument19 Star0)
	(supports instrument20 infrared3)
	(supports instrument20 image4)
	(calibration_target instrument20 Star0)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon2)
	(supports instrument21 spectrograph0)
	(supports instrument21 thermograph1)
	(calibration_target instrument21 Star0)
	(supports instrument22 thermograph1)
	(calibration_target instrument22 Star0)
	(supports instrument23 image4)
	(supports instrument23 thermograph1)
	(supports instrument23 infrared2)
	(calibration_target instrument23 Star0)
	(supports instrument24 image4)
	(supports instrument24 infrared2)
	(supports instrument24 spectrograph0)
	(calibration_target instrument24 Star0)
	(supports instrument25 image4)
	(calibration_target instrument25 Star0)
	(supports instrument26 spectrograph0)
	(calibration_target instrument26 Star0)
	(supports instrument27 image4)
	(calibration_target instrument27 Star0)
	(supports instrument28 spectrograph0)
	(supports instrument28 image4)
	(calibration_target instrument28 Star0)
	(supports instrument29 spectrograph0)
	(supports instrument29 infrared2)
	(supports instrument29 thermograph1)
	(calibration_target instrument29 Star0)
	(supports instrument30 infrared3)
	(supports instrument30 infrared2)
	(supports instrument30 image4)
	(calibration_target instrument30 Star0)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument31 infrared2)
	(supports instrument31 image4)
	(supports instrument31 infrared3)
	(calibration_target instrument31 Star0)
	(supports instrument32 image4)
	(supports instrument32 infrared3)
	(supports instrument32 spectrograph0)
	(calibration_target instrument32 Star0)
	(supports instrument33 spectrograph0)
	(supports instrument33 thermograph1)
	(calibration_target instrument33 Star0)
	(supports instrument34 image4)
	(supports instrument34 spectrograph0)
	(calibration_target instrument34 Star0)
	(supports instrument35 spectrograph0)
	(supports instrument35 infrared2)
	(calibration_target instrument35 Star0)
	(supports instrument36 infrared3)
	(calibration_target instrument36 Star0)
	(supports instrument37 thermograph1)
	(supports instrument37 infrared3)
	(calibration_target instrument37 Star0)
	(supports instrument38 infrared3)
	(supports instrument38 image4)
	(calibration_target instrument38 Star0)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon1)
	(supports instrument39 thermograph1)
	(supports instrument39 infrared3)
	(supports instrument39 image4)
	(calibration_target instrument39 Star0)
	(supports instrument40 image4)
	(supports instrument40 thermograph1)
	(calibration_target instrument40 Star0)
	(supports instrument41 image4)
	(supports instrument41 infrared3)
	(supports instrument41 spectrograph0)
	(calibration_target instrument41 Star0)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon2)
	(supports instrument42 thermograph1)
	(supports instrument42 infrared3)
	(calibration_target instrument42 Star0)
	(supports instrument43 thermograph1)
	(supports instrument43 spectrograph0)
	(supports instrument43 infrared2)
	(calibration_target instrument43 Star0)
	(supports instrument44 spectrograph0)
	(supports instrument44 infrared2)
	(calibration_target instrument44 Star0)
	(supports instrument45 image4)
	(supports instrument45 spectrograph0)
	(supports instrument45 infrared3)
	(calibration_target instrument45 Star0)
	(supports instrument46 thermograph1)
	(supports instrument46 image4)
	(calibration_target instrument46 Star0)
	(supports instrument47 image4)
	(supports instrument47 infrared2)
	(supports instrument47 spectrograph0)
	(calibration_target instrument47 Star0)
	(supports instrument48 image4)
	(supports instrument48 thermograph1)
	(calibration_target instrument48 Star0)
	(supports instrument49 spectrograph0)
	(calibration_target instrument49 Star0)
	(supports instrument50 spectrograph0)
	(supports instrument50 thermograph1)
	(supports instrument50 infrared3)
	(calibration_target instrument50 Star0)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon2)
	(supports instrument51 image4)
	(supports instrument51 thermograph1)
	(supports instrument51 spectrograph0)
	(calibration_target instrument51 Star0)
	(supports instrument52 infrared3)
	(supports instrument52 thermograph1)
	(supports instrument52 spectrograph0)
	(calibration_target instrument52 Star0)
	(supports instrument53 thermograph1)
	(supports instrument53 spectrograph0)
	(calibration_target instrument53 Star0)
	(supports instrument54 thermograph1)
	(calibration_target instrument54 Star0)
	(supports instrument55 spectrograph0)
	(supports instrument55 infrared2)
	(supports instrument55 thermograph1)
	(calibration_target instrument55 Star0)
	(supports instrument56 infrared2)
	(calibration_target instrument56 Star0)
	(supports instrument57 infrared2)
	(supports instrument57 image4)
	(supports instrument57 thermograph1)
	(calibration_target instrument57 Star0)
	(supports instrument58 infrared2)
	(supports instrument58 image4)
	(calibration_target instrument58 Star0)
	(supports instrument59 spectrograph0)
	(supports instrument59 thermograph1)
	(supports instrument59 infrared2)
	(calibration_target instrument59 Star0)
	(supports instrument60 image4)
	(supports instrument60 spectrograph0)
	(supports instrument60 thermograph1)
	(calibration_target instrument60 Star0)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(on_board instrument60 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon1)
	(supports instrument61 thermograph1)
	(calibration_target instrument61 Star0)
	(on_board instrument61 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star0)
)
(:goal (and
	(pointing satellite5 Phenomenon2)
	(pointing satellite7 Star0)
	(pointing satellite8 Phenomenon1)
	(have_image Phenomenon1 thermograph1)
	(have_image Phenomenon2 infrared2)
))

)
