(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	satellite2 - satellite
	instrument2 - instrument
	satellite3 - satellite
	instrument3 - instrument
	instrument4 - instrument
	satellite4 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite5 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite6 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite7 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite8 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite9 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	thermograph0 - mode
	infrared2 - mode
	spectrograph4 - mode
	image1 - mode
	thermograph3 - mode
	Star0 - direction
	Phenomenon1 - direction
	Phenomenon2 - direction
)
(:init
	(supports instrument0 thermograph3)
	(supports instrument0 infrared2)
	(supports instrument0 spectrograph4)
	(calibration_target instrument0 Star0)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon2)
	(supports instrument1 spectrograph4)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 Star0)
	(on_board instrument1 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon1)
	(supports instrument2 image1)
	(calibration_target instrument2 Star0)
	(on_board instrument2 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument3 thermograph0)
	(supports instrument3 thermograph3)
	(calibration_target instrument3 Star0)
	(supports instrument4 thermograph0)
	(supports instrument4 image1)
	(calibration_target instrument4 Star0)
	(on_board instrument3 satellite3)
	(on_board instrument4 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star0)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 Star0)
	(supports instrument6 image1)
	(supports instrument6 thermograph3)
	(calibration_target instrument6 Star0)
	(supports instrument7 spectrograph4)
	(calibration_target instrument7 Star0)
	(on_board instrument5 satellite4)
	(on_board instrument6 satellite4)
	(on_board instrument7 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument8 thermograph0)
	(supports instrument8 infrared2)
	(calibration_target instrument8 Star0)
	(supports instrument9 thermograph0)
	(supports instrument9 infrared2)
	(supports instrument9 image1)
	(calibration_target instrument9 Star0)
	(supports instrument10 infrared2)
	(calibration_target instrument10 Star0)
	(supports instrument11 spectrograph4)
	(calibration_target instrument11 Star0)
	(supports instrument12 infrared2)
	(supports instrument12 image1)
	(supports instrument12 thermograph3)
	(calibration_target instrument12 Star0)
	(supports instrument13 spectrograph4)
	(supports instrument13 thermograph3)
	(calibration_target instrument13 Star0)
	(supports instrument14 spectrograph4)
	(supports instrument14 thermograph3)
	(supports instrument14 image1)
	(calibration_target instrument14 Star0)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 Star0)
	(supports instrument16 image1)
	(supports instrument16 spectrograph4)
	(supports instrument16 infrared2)
	(calibration_target instrument16 Star0)
	(on_board instrument8 satellite5)
	(on_board instrument9 satellite5)
	(on_board instrument10 satellite5)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star0)
	(supports instrument17 spectrograph4)
	(supports instrument17 thermograph3)
	(supports instrument17 image1)
	(calibration_target instrument17 Star0)
	(supports instrument18 image1)
	(supports instrument18 thermograph0)
	(calibration_target instrument18 Star0)
	(supports instrument19 image1)
	(calibration_target instrument19 Star0)
	(supports instrument20 thermograph3)
	(supports instrument20 image1)
	(supports instrument20 infrared2)
	(calibration_target instrument20 Star0)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(on_board instrument20 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon2)
	(supports instrument21 thermograph0)
	(calibration_target instrument21 Star0)
	(supports instrument22 spectrograph4)
	(calibration_target instrument22 Star0)
	(supports instrument23 thermograph0)
	(supports instrument23 thermograph3)
	(supports instrument23 spectrograph4)
	(calibration_target instrument23 Star0)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(on_board instrument23 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon1)
	(supports instrument24 thermograph3)
	(calibration_target instrument24 Star0)
	(supports instrument25 thermograph3)
	(calibration_target instrument25 Star0)
	(supports instrument26 spectrograph4)
	(supports instrument26 infrared2)
	(supports instrument26 image1)
	(calibration_target instrument26 Star0)
	(supports instrument27 thermograph0)
	(supports instrument27 thermograph3)
	(supports instrument27 spectrograph4)
	(calibration_target instrument27 Star0)
	(on_board instrument24 satellite8)
	(on_board instrument25 satellite8)
	(on_board instrument26 satellite8)
	(on_board instrument27 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star0)
	(supports instrument28 thermograph0)
	(supports instrument28 spectrograph4)
	(supports instrument28 infrared2)
	(calibration_target instrument28 Star0)
	(supports instrument29 image1)
	(calibration_target instrument29 Star0)
	(supports instrument30 thermograph3)
	(supports instrument30 spectrograph4)
	(supports instrument30 infrared2)
	(calibration_target instrument30 Star0)
	(supports instrument31 image1)
	(supports instrument31 thermograph3)
	(calibration_target instrument31 Star0)
	(supports instrument32 spectrograph4)
	(calibration_target instrument32 Star0)
	(supports instrument33 thermograph3)
	(supports instrument33 image1)
	(calibration_target instrument33 Star0)
	(on_board instrument28 satellite9)
	(on_board instrument29 satellite9)
	(on_board instrument30 satellite9)
	(on_board instrument31 satellite9)
	(on_board instrument32 satellite9)
	(on_board instrument33 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon1)
)
(:goal (and
	(pointing satellite2 Phenomenon2)
	(pointing satellite3 Phenomenon2)
	(pointing satellite5 Star0)
	(have_image Phenomenon1 infrared2)
	(have_image Phenomenon2 thermograph0)
))

)
