(define (problem pb7)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (on block1 block3) (on block2 block1) (clear block2) (on block3 block6) (ontable block4) (clear block4) (ontable block5) (clear block5) (ontable block6) (handempty))
	(:goal (and (on block1 block2) (on block2 block4) (on block3 block5) (ontable block4) (on block5 block1) (on block6 block3) (clear block6))))