(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (ontable block1) (on block2 block4) (clear block2) (on block3 block5) (on block4 block3) (on block5 block6) (on block6 block1) (handempty))
	(:goal (and (ontable block1) (on block2 block1) (clear block2) (on block3 block5) (on block4 block3) (clear block4) (on block5 block6) (ontable block6))))