(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (on block1 block5) (ontable block2) (on block3 block2) (clear block3) (on block4 block6) (clear block4) (ontable block5) (on block6 block1) (handempty))
	(:goal (and (on block1 block3) (clear block1) (on block2 block6) (clear block2) (on block3 block4) (ontable block4) (ontable block5) (on block6 block5))))