(define (problem pb2)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (on block1 block3) (ontable block2) (clear block2) (ontable block3) (on block4 block6) (clear block4) (on block5 block1) (on block6 block5) (handempty))
	(:goal (and (on block1 block6) (clear block1) (on block2 block5) (ontable block3) (clear block3) (ontable block4) (clear block4) (ontable block5) (on block6 block2))))