(define (problem pb0)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (on block1 block3) (on block2 block5) (on block3 block6) (ontable block4) (clear block4) (on block5 block7) (on block6 block2) (on block7 block9) (on block8 block1) (clear block8) (on block9 block10) (ontable block10) (handempty))
	(:goal (and (on block1 block5) (on block2 block3) (ontable block3) (ontable block4) (clear block4) (on block5 block6) (on block6 block2) (on block7 block1) (clear block7) (on block8 block9) (ontable block9) (on block10 block8) (clear block10))))