(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (on block1 block7) (clear block1) (on block2 block4) (ontable block3) (on block4 block6) (on block5 block8) (clear block5) (on block6 block3) (on block7 block9) (ontable block8) (on block9 block2) (ontable block10) (clear block10) (handempty))
	(:goal (and (on block1 block5) (on block2 block3) (clear block2) (ontable block3) (ontable block4) (ontable block5) (on block6 block1) (clear block6) (on block7 block9) (on block8 block7) (clear block8) (on block9 block4) (ontable block10) (clear block10))))