(define (problem pb7)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (on block1 block6) (on block2 block8) (clear block2) (on block3 block10) (ontable block4) (ontable block5) (clear block5) (ontable block6) (on block7 block3) (clear block7) (on block8 block4) (ontable block9) (clear block9) (on block10 block1) (handempty))
	(:goal (and (on block1 block2) (on block2 block3) (ontable block3) (on block4 block8) (on block5 block1) (on block6 block9) (clear block6) (ontable block7) (clear block7) (ontable block8) (on block9 block5) (on block10 block4) (clear block10))))