(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (on block1 block6) (on block2 block9) (on block3 block1) (ontable block4) (clear block4) (on block5 block2) (clear block5) (ontable block6) (ontable block7) (clear block7) (ontable block8) (on block9 block3) (on block10 block8) (clear block10) (handempty))
	(:goal (and (on block1 block10) (on block2 block8) (clear block2) (ontable block3) (clear block3) (on block4 block1) (on block5 block6) (ontable block6) (ontable block7) (on block8 block4) (on block9 block5) (clear block9) (on block10 block7))))