(define (problem pb9)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (on block1 block8) (ontable block2) (clear block2) (on block3 block1) (ontable block4) (on block5 block10) (clear block5) (ontable block6) (on block7 block6) (on block8 block4) (on block9 block7) (clear block9) (on block10 block3) (handempty))
	(:goal (and (on block1 block5) (on block2 block4) (clear block2) (on block3 block1) (on block4 block7) (on block5 block10) (on block6 block8) (on block7 block6) (on block8 block3) (ontable block9) (on block10 block9))))