(define (problem pb8)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (ontable block1) (on block2 block7) (on block3 block6) (on block4 block2) (on block5 block8) (clear block5) (on block6 block4) (on block7 block10) (on block8 block1) (on block9 block3) (clear block9) (ontable block10) (handempty))
	(:goal (and (on block1 block8) (on block2 block5) (clear block2) (on block3 block1) (clear block3) (on block4 block10) (on block5 block9) (on block6 block4) (ontable block7) (on block8 block7) (on block9 block6) (ontable block10))))