(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite2 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite3 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite4 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite5 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	satellite6 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	satellite7 - satellite
	instrument49 - instrument
	instrument50 - instrument
	satellite8 - satellite
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	satellite9 - satellite
	instrument59 - instrument
	instrument60 - instrument
	instrument61 - instrument
	instrument62 - instrument
	instrument63 - instrument
	instrument64 - instrument
	instrument65 - instrument
	instrument66 - instrument
	instrument67 - instrument
	thermograph1 - mode
	image0 - mode
	infrared3 - mode
	thermograph2 - mode
	thermograph4 - mode
	GroundStation1 - direction
	Star2 - direction
	Star0 - direction
	GroundStation3 - direction
	Planet4 - direction
	Planet5 - direction
)
(:init
	(supports instrument0 thermograph2)
	(calibration_target instrument0 Star0)
	(supports instrument1 image0)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 Star2)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 GroundStation3)
	(supports instrument3 thermograph1)
	(calibration_target instrument3 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet5)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 Star0)
	(supports instrument5 thermograph2)
	(calibration_target instrument5 Star0)
	(supports instrument6 thermograph1)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star2)
	(supports instrument7 image0)
	(calibration_target instrument7 GroundStation3)
	(supports instrument8 image0)
	(supports instrument8 thermograph4)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 Star0)
	(supports instrument9 thermograph4)
	(supports instrument9 infrared3)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 Star2)
	(supports instrument10 infrared3)
	(supports instrument10 thermograph2)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 Star2)
	(supports instrument11 infrared3)
	(calibration_target instrument11 Star2)
	(supports instrument12 infrared3)
	(supports instrument12 thermograph2)
	(calibration_target instrument12 Star0)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation1)
	(supports instrument13 thermograph1)
	(supports instrument13 image0)
	(calibration_target instrument13 Star0)
	(supports instrument14 infrared3)
	(calibration_target instrument14 Star0)
	(supports instrument15 image0)
	(supports instrument15 thermograph4)
	(supports instrument15 infrared3)
	(calibration_target instrument15 Star0)
	(supports instrument16 image0)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 Star2)
	(supports instrument17 thermograph1)
	(calibration_target instrument17 GroundStation1)
	(supports instrument18 thermograph2)
	(supports instrument18 thermograph1)
	(calibration_target instrument18 GroundStation3)
	(supports instrument19 thermograph2)
	(supports instrument19 thermograph4)
	(supports instrument19 infrared3)
	(calibration_target instrument19 Star2)
	(supports instrument20 thermograph4)
	(supports instrument20 thermograph1)
	(calibration_target instrument20 GroundStation3)
	(supports instrument21 image0)
	(calibration_target instrument21 GroundStation3)
	(supports instrument22 thermograph1)
	(supports instrument22 thermograph2)
	(supports instrument22 image0)
	(calibration_target instrument22 Star2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(on_board instrument22 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet5)
	(supports instrument23 image0)
	(supports instrument23 infrared3)
	(calibration_target instrument23 Star2)
	(supports instrument24 thermograph1)
	(supports instrument24 infrared3)
	(calibration_target instrument24 Star0)
	(supports instrument25 thermograph4)
	(supports instrument25 thermograph2)
	(supports instrument25 thermograph1)
	(calibration_target instrument25 Star0)
	(supports instrument26 thermograph4)
	(supports instrument26 image0)
	(supports instrument26 thermograph1)
	(calibration_target instrument26 GroundStation3)
	(supports instrument27 image0)
	(calibration_target instrument27 GroundStation1)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 Star2)
	(supports instrument29 thermograph4)
	(calibration_target instrument29 GroundStation1)
	(supports instrument30 image0)
	(calibration_target instrument30 Star0)
	(supports instrument31 thermograph4)
	(calibration_target instrument31 Star2)
	(supports instrument32 thermograph1)
	(supports instrument32 infrared3)
	(calibration_target instrument32 Star2)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(on_board instrument30 satellite3)
	(on_board instrument31 satellite3)
	(on_board instrument32 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation3)
	(supports instrument33 thermograph2)
	(calibration_target instrument33 GroundStation1)
	(supports instrument34 image0)
	(supports instrument34 infrared3)
	(supports instrument34 thermograph2)
	(calibration_target instrument34 GroundStation1)
	(supports instrument35 image0)
	(supports instrument35 thermograph2)
	(calibration_target instrument35 Star0)
	(supports instrument36 thermograph2)
	(supports instrument36 thermograph1)
	(calibration_target instrument36 Star0)
	(supports instrument37 image0)
	(supports instrument37 infrared3)
	(calibration_target instrument37 Star0)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(on_board instrument37 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star2)
	(supports instrument38 image0)
	(supports instrument38 thermograph1)
	(supports instrument38 thermograph2)
	(calibration_target instrument38 Star2)
	(supports instrument39 image0)
	(supports instrument39 thermograph2)
	(calibration_target instrument39 GroundStation1)
	(supports instrument40 thermograph2)
	(supports instrument40 image0)
	(calibration_target instrument40 GroundStation3)
	(supports instrument41 thermograph1)
	(supports instrument41 image0)
	(supports instrument41 thermograph2)
	(calibration_target instrument41 Star0)
	(supports instrument42 thermograph1)
	(calibration_target instrument42 GroundStation3)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(on_board instrument41 satellite5)
	(on_board instrument42 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet4)
	(supports instrument43 thermograph1)
	(supports instrument43 thermograph4)
	(supports instrument43 image0)
	(calibration_target instrument43 Star2)
	(supports instrument44 infrared3)
	(supports instrument44 thermograph4)
	(supports instrument44 thermograph2)
	(calibration_target instrument44 GroundStation3)
	(supports instrument45 thermograph2)
	(supports instrument45 thermograph4)
	(supports instrument45 image0)
	(calibration_target instrument45 GroundStation3)
	(supports instrument46 thermograph4)
	(supports instrument46 infrared3)
	(calibration_target instrument46 GroundStation1)
	(supports instrument47 thermograph2)
	(supports instrument47 thermograph4)
	(calibration_target instrument47 Star2)
	(supports instrument48 thermograph1)
	(supports instrument48 thermograph2)
	(calibration_target instrument48 GroundStation3)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(on_board instrument46 satellite6)
	(on_board instrument47 satellite6)
	(on_board instrument48 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star0)
	(supports instrument49 image0)
	(calibration_target instrument49 Star2)
	(supports instrument50 infrared3)
	(calibration_target instrument50 GroundStation3)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet4)
	(supports instrument51 thermograph4)
	(calibration_target instrument51 Star0)
	(supports instrument52 thermograph4)
	(supports instrument52 image0)
	(calibration_target instrument52 GroundStation3)
	(supports instrument53 thermograph2)
	(calibration_target instrument53 GroundStation1)
	(supports instrument54 thermograph2)
	(calibration_target instrument54 Star0)
	(supports instrument55 thermograph1)
	(supports instrument55 thermograph2)
	(supports instrument55 image0)
	(calibration_target instrument55 GroundStation3)
	(supports instrument56 infrared3)
	(calibration_target instrument56 GroundStation1)
	(supports instrument57 image0)
	(supports instrument57 infrared3)
	(calibration_target instrument57 Star2)
	(supports instrument58 image0)
	(calibration_target instrument58 GroundStation3)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet5)
	(supports instrument59 thermograph4)
	(supports instrument59 image0)
	(calibration_target instrument59 Star2)
	(supports instrument60 thermograph1)
	(supports instrument60 image0)
	(supports instrument60 thermograph4)
	(calibration_target instrument60 Star2)
	(supports instrument61 infrared3)
	(supports instrument61 thermograph1)
	(calibration_target instrument61 GroundStation1)
	(supports instrument62 thermograph4)
	(supports instrument62 infrared3)
	(calibration_target instrument62 Star0)
	(supports instrument63 thermograph1)
	(supports instrument63 image0)
	(supports instrument63 infrared3)
	(calibration_target instrument63 Star2)
	(supports instrument64 thermograph4)
	(supports instrument64 image0)
	(supports instrument64 infrared3)
	(calibration_target instrument64 GroundStation3)
	(supports instrument65 thermograph2)
	(supports instrument65 image0)
	(calibration_target instrument65 GroundStation3)
	(supports instrument66 thermograph2)
	(supports instrument66 infrared3)
	(calibration_target instrument66 Star0)
	(supports instrument67 thermograph4)
	(calibration_target instrument67 GroundStation3)
	(on_board instrument59 satellite9)
	(on_board instrument60 satellite9)
	(on_board instrument61 satellite9)
	(on_board instrument62 satellite9)
	(on_board instrument63 satellite9)
	(on_board instrument64 satellite9)
	(on_board instrument65 satellite9)
	(on_board instrument66 satellite9)
	(on_board instrument67 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star2)
)
(:goal (and
	(pointing satellite6 GroundStation3)
	(have_image Planet4 infrared3)
	(have_image Planet5 thermograph1)
))

)
