(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite4 - satellite
	instrument15 - instrument
	satellite5 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite6 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite7 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite8 - satellite
	instrument36 - instrument
	instrument37 - instrument
	satellite9 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	infrared2 - mode
	thermograph4 - mode
	image3 - mode
	infrared0 - mode
	spectrograph1 - mode
	Star0 - direction
	GroundStation1 - direction
	GroundStation2 - direction
	Star3 - direction
	Star4 - direction
	Phenomenon5 - direction
)
(:init
	(supports instrument0 infrared2)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 infrared2)
	(supports instrument1 image3)
	(calibration_target instrument1 Star0)
	(supports instrument2 spectrograph1)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star3)
	(supports instrument3 infrared2)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 Star3)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star3)
	(supports instrument4 infrared2)
	(calibration_target instrument4 GroundStation2)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 GroundStation1)
	(supports instrument6 infrared2)
	(supports instrument6 thermograph4)
	(supports instrument6 infrared0)
	(calibration_target instrument6 Star0)
	(supports instrument7 spectrograph1)
	(supports instrument7 thermograph4)
	(supports instrument7 infrared0)
	(calibration_target instrument7 Star0)
	(supports instrument8 infrared0)
	(calibration_target instrument8 Star3)
	(supports instrument9 infrared0)
	(supports instrument9 thermograph4)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 thermograph4)
	(supports instrument10 image3)
	(supports instrument10 infrared0)
	(calibration_target instrument10 GroundStation2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument11 spectrograph1)
	(supports instrument11 infrared0)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 Star0)
	(supports instrument12 thermograph4)
	(supports instrument12 spectrograph1)
	(supports instrument12 infrared0)
	(calibration_target instrument12 GroundStation2)
	(supports instrument13 spectrograph1)
	(supports instrument13 thermograph4)
	(supports instrument13 infrared0)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 thermograph4)
	(supports instrument14 image3)
	(calibration_target instrument14 GroundStation1)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star4)
	(supports instrument15 image3)
	(supports instrument15 spectrograph1)
	(calibration_target instrument15 GroundStation2)
	(on_board instrument15 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star3)
	(supports instrument16 infrared0)
	(supports instrument16 image3)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 Star0)
	(supports instrument17 infrared0)
	(calibration_target instrument17 Star0)
	(supports instrument18 thermograph4)
	(supports instrument18 infrared0)
	(supports instrument18 spectrograph1)
	(calibration_target instrument18 Star3)
	(supports instrument19 spectrograph1)
	(supports instrument19 thermograph4)
	(supports instrument19 image3)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 image3)
	(calibration_target instrument20 GroundStation2)
	(supports instrument21 infrared2)
	(supports instrument21 infrared0)
	(supports instrument21 spectrograph1)
	(calibration_target instrument21 Star3)
	(supports instrument22 image3)
	(supports instrument22 infrared0)
	(calibration_target instrument22 GroundStation2)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star0)
	(supports instrument23 image3)
	(calibration_target instrument23 GroundStation2)
	(supports instrument24 thermograph4)
	(supports instrument24 infrared0)
	(supports instrument24 image3)
	(calibration_target instrument24 GroundStation2)
	(supports instrument25 thermograph4)
	(calibration_target instrument25 GroundStation1)
	(supports instrument26 infrared0)
	(calibration_target instrument26 GroundStation2)
	(supports instrument27 infrared0)
	(supports instrument27 infrared2)
	(calibration_target instrument27 GroundStation2)
	(on_board instrument23 satellite6)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(on_board instrument26 satellite6)
	(on_board instrument27 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star3)
	(supports instrument28 image3)
	(supports instrument28 infrared0)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 GroundStation2)
	(supports instrument29 image3)
	(supports instrument29 spectrograph1)
	(supports instrument29 infrared0)
	(calibration_target instrument29 GroundStation1)
	(supports instrument30 infrared0)
	(supports instrument30 image3)
	(supports instrument30 thermograph4)
	(calibration_target instrument30 GroundStation2)
	(supports instrument31 thermograph4)
	(calibration_target instrument31 GroundStation1)
	(supports instrument32 image3)
	(calibration_target instrument32 GroundStation2)
	(supports instrument33 image3)
	(supports instrument33 infrared2)
	(supports instrument33 spectrograph1)
	(calibration_target instrument33 GroundStation2)
	(supports instrument34 infrared2)
	(supports instrument34 spectrograph1)
	(supports instrument34 image3)
	(calibration_target instrument34 Star3)
	(supports instrument35 infrared2)
	(supports instrument35 image3)
	(calibration_target instrument35 Star3)
	(on_board instrument28 satellite7)
	(on_board instrument29 satellite7)
	(on_board instrument30 satellite7)
	(on_board instrument31 satellite7)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation2)
	(supports instrument36 infrared0)
	(supports instrument36 infrared2)
	(calibration_target instrument36 Star3)
	(supports instrument37 thermograph4)
	(supports instrument37 infrared0)
	(supports instrument37 image3)
	(calibration_target instrument37 Star3)
	(on_board instrument36 satellite8)
	(on_board instrument37 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star4)
	(supports instrument38 infrared0)
	(calibration_target instrument38 GroundStation2)
	(supports instrument39 thermograph4)
	(supports instrument39 infrared2)
	(calibration_target instrument39 GroundStation2)
	(supports instrument40 spectrograph1)
	(supports instrument40 infrared0)
	(supports instrument40 infrared2)
	(calibration_target instrument40 GroundStation1)
	(supports instrument41 thermograph4)
	(calibration_target instrument41 GroundStation2)
	(supports instrument42 image3)
	(calibration_target instrument42 Star3)
	(supports instrument43 image3)
	(supports instrument43 infrared0)
	(calibration_target instrument43 GroundStation2)
	(supports instrument44 spectrograph1)
	(supports instrument44 infrared0)
	(calibration_target instrument44 Star3)
	(on_board instrument38 satellite9)
	(on_board instrument39 satellite9)
	(on_board instrument40 satellite9)
	(on_board instrument41 satellite9)
	(on_board instrument42 satellite9)
	(on_board instrument43 satellite9)
	(on_board instrument44 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation2)
)
(:goal (and
	(pointing satellite1 GroundStation1)
	(pointing satellite2 GroundStation1)
	(pointing satellite3 GroundStation2)
	(pointing satellite5 Star3)
	(have_image Phenomenon5 infrared2)
))

)
