(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite4 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite5 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite6 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite7 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite8 - satellite
	instrument32 - instrument
	instrument33 - instrument
	satellite9 - satellite
	instrument34 - instrument
	instrument35 - instrument
	image1 - mode
	thermograph0 - mode
	infrared2 - mode
	spectrograph4 - mode
	thermograph3 - mode
	GroundStation1 - direction
	Star2 - direction
	Star0 - direction
	GroundStation3 - direction
	Planet4 - direction
	Phenomenon5 - direction
)
(:init
	(supports instrument0 image1)
	(calibration_target instrument0 GroundStation1)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star2)
	(supports instrument1 thermograph0)
	(supports instrument1 spectrograph4)
	(calibration_target instrument1 Star2)
	(supports instrument2 thermograph0)
	(supports instrument2 image1)
	(calibration_target instrument2 Star2)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument3 spectrograph4)
	(calibration_target instrument3 GroundStation3)
	(supports instrument4 image1)
	(supports instrument4 spectrograph4)
	(calibration_target instrument4 Star2)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 GroundStation1)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation3)
	(supports instrument6 thermograph0)
	(supports instrument6 infrared2)
	(calibration_target instrument6 Star2)
	(supports instrument7 thermograph0)
	(supports instrument7 infrared2)
	(supports instrument7 image1)
	(calibration_target instrument7 GroundStation3)
	(supports instrument8 infrared2)
	(calibration_target instrument8 GroundStation1)
	(supports instrument9 thermograph3)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 infrared2)
	(supports instrument10 image1)
	(supports instrument10 spectrograph4)
	(calibration_target instrument10 GroundStation3)
	(supports instrument11 thermograph3)
	(supports instrument11 spectrograph4)
	(calibration_target instrument11 GroundStation3)
	(supports instrument12 thermograph3)
	(supports instrument12 spectrograph4)
	(supports instrument12 image1)
	(calibration_target instrument12 GroundStation3)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 Star0)
	(supports instrument14 image1)
	(supports instrument14 thermograph3)
	(supports instrument14 infrared2)
	(calibration_target instrument14 GroundStation1)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star2)
	(supports instrument15 thermograph3)
	(supports instrument15 spectrograph4)
	(supports instrument15 image1)
	(calibration_target instrument15 GroundStation1)
	(supports instrument16 image1)
	(supports instrument16 thermograph0)
	(calibration_target instrument16 GroundStation3)
	(supports instrument17 image1)
	(calibration_target instrument17 GroundStation1)
	(supports instrument18 spectrograph4)
	(supports instrument18 image1)
	(supports instrument18 infrared2)
	(calibration_target instrument18 Star2)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon5)
	(supports instrument19 thermograph0)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 thermograph3)
	(calibration_target instrument20 Star0)
	(supports instrument21 thermograph0)
	(supports instrument21 spectrograph4)
	(supports instrument21 thermograph3)
	(calibration_target instrument21 Star2)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet4)
	(supports instrument22 spectrograph4)
	(calibration_target instrument22 Star0)
	(supports instrument23 spectrograph4)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 thermograph3)
	(supports instrument24 infrared2)
	(supports instrument24 image1)
	(calibration_target instrument24 Star2)
	(supports instrument25 thermograph0)
	(supports instrument25 spectrograph4)
	(supports instrument25 thermograph3)
	(calibration_target instrument25 Star0)
	(on_board instrument22 satellite6)
	(on_board instrument23 satellite6)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star0)
	(supports instrument26 thermograph0)
	(supports instrument26 thermograph3)
	(supports instrument26 infrared2)
	(calibration_target instrument26 Star2)
	(supports instrument27 image1)
	(calibration_target instrument27 GroundStation3)
	(supports instrument28 spectrograph4)
	(supports instrument28 thermograph3)
	(supports instrument28 infrared2)
	(calibration_target instrument28 Star0)
	(supports instrument29 image1)
	(supports instrument29 spectrograph4)
	(calibration_target instrument29 GroundStation3)
	(supports instrument30 thermograph3)
	(calibration_target instrument30 Star0)
	(supports instrument31 spectrograph4)
	(supports instrument31 image1)
	(calibration_target instrument31 GroundStation1)
	(on_board instrument26 satellite7)
	(on_board instrument27 satellite7)
	(on_board instrument28 satellite7)
	(on_board instrument29 satellite7)
	(on_board instrument30 satellite7)
	(on_board instrument31 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet4)
	(supports instrument32 thermograph0)
	(supports instrument32 image1)
	(supports instrument32 infrared2)
	(calibration_target instrument32 Star2)
	(supports instrument33 infrared2)
	(calibration_target instrument33 Star0)
	(on_board instrument32 satellite8)
	(on_board instrument33 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet4)
	(supports instrument34 thermograph3)
	(supports instrument34 spectrograph4)
	(calibration_target instrument34 Star0)
	(supports instrument35 thermograph3)
	(calibration_target instrument35 GroundStation3)
	(on_board instrument34 satellite9)
	(on_board instrument35 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet4)
)
(:goal (and
	(pointing satellite0 GroundStation3)
	(pointing satellite1 GroundStation3)
	(pointing satellite3 Star0)
	(pointing satellite8 Phenomenon5)
	(have_image Planet4 thermograph0)
))

)
