(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite3 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite4 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite5 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite6 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	satellite7 - satellite
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	satellite8 - satellite
	instrument59 - instrument
	instrument60 - instrument
	instrument61 - instrument
	satellite9 - satellite
	instrument62 - instrument
	instrument63 - instrument
	instrument64 - instrument
	instrument65 - instrument
	spectrograph2 - mode
	thermograph4 - mode
	image0 - mode
	spectrograph1 - mode
	image3 - mode
	GroundStation3 - direction
	GroundStation0 - direction
	GroundStation2 - direction
	Star1 - direction
	Phenomenon4 - direction
	Star5 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 spectrograph1)
	(calibration_target instrument0 GroundStation0)
	(supports instrument1 spectrograph2)
	(supports instrument1 image0)
	(calibration_target instrument1 Star1)
	(supports instrument2 thermograph4)
	(supports instrument2 image0)
	(calibration_target instrument2 Star1)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 Star1)
	(supports instrument4 spectrograph2)
	(supports instrument4 spectrograph1)
	(supports instrument4 image0)
	(calibration_target instrument4 Star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation3)
	(supports instrument5 image0)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 GroundStation0)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 Star1)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 Star1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation0)
	(supports instrument8 spectrograph1)
	(supports instrument8 spectrograph2)
	(supports instrument8 image0)
	(calibration_target instrument8 GroundStation3)
	(supports instrument9 image3)
	(supports instrument9 spectrograph2)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 GroundStation0)
	(supports instrument10 thermograph4)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 GroundStation3)
	(supports instrument11 spectrograph2)
	(calibration_target instrument11 GroundStation3)
	(supports instrument12 spectrograph2)
	(supports instrument12 image0)
	(supports instrument12 spectrograph1)
	(calibration_target instrument12 GroundStation2)
	(supports instrument13 spectrograph1)
	(supports instrument13 image3)
	(supports instrument13 image0)
	(calibration_target instrument13 GroundStation0)
	(supports instrument14 spectrograph1)
	(calibration_target instrument14 GroundStation2)
	(supports instrument15 spectrograph2)
	(supports instrument15 image3)
	(supports instrument15 image0)
	(calibration_target instrument15 GroundStation3)
	(supports instrument16 spectrograph2)
	(supports instrument16 image0)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 GroundStation2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star1)
	(supports instrument17 spectrograph1)
	(supports instrument17 spectrograph2)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 GroundStation2)
	(supports instrument18 thermograph4)
	(supports instrument18 image0)
	(calibration_target instrument18 GroundStation2)
	(supports instrument19 spectrograph2)
	(calibration_target instrument19 GroundStation3)
	(supports instrument20 image0)
	(calibration_target instrument20 GroundStation0)
	(supports instrument21 spectrograph2)
	(calibration_target instrument21 GroundStation2)
	(supports instrument22 thermograph4)
	(supports instrument22 spectrograph2)
	(calibration_target instrument22 GroundStation2)
	(supports instrument23 spectrograph2)
	(supports instrument23 image0)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 Star1)
	(supports instrument24 spectrograph2)
	(supports instrument24 image3)
	(supports instrument24 image0)
	(calibration_target instrument24 GroundStation0)
	(supports instrument25 image3)
	(supports instrument25 spectrograph1)
	(calibration_target instrument25 GroundStation3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation3)
	(supports instrument26 spectrograph1)
	(supports instrument26 spectrograph2)
	(supports instrument26 image0)
	(calibration_target instrument26 Star1)
	(supports instrument27 spectrograph1)
	(supports instrument27 image3)
	(calibration_target instrument27 GroundStation3)
	(supports instrument28 spectrograph2)
	(supports instrument28 spectrograph1)
	(supports instrument28 image0)
	(calibration_target instrument28 GroundStation2)
	(supports instrument29 thermograph4)
	(calibration_target instrument29 GroundStation0)
	(supports instrument30 spectrograph2)
	(calibration_target instrument30 GroundStation0)
	(supports instrument31 spectrograph2)
	(supports instrument31 spectrograph1)
	(calibration_target instrument31 GroundStation3)
	(supports instrument32 spectrograph1)
	(supports instrument32 thermograph4)
	(calibration_target instrument32 Star1)
	(supports instrument33 thermograph4)
	(calibration_target instrument33 GroundStation3)
	(supports instrument34 spectrograph1)
	(supports instrument34 spectrograph2)
	(calibration_target instrument34 Star1)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation3)
	(supports instrument35 spectrograph1)
	(supports instrument35 thermograph4)
	(calibration_target instrument35 Star1)
	(supports instrument36 spectrograph2)
	(supports instrument36 spectrograph1)
	(calibration_target instrument36 Star1)
	(supports instrument37 image3)
	(supports instrument37 spectrograph1)
	(calibration_target instrument37 GroundStation3)
	(supports instrument38 image0)
	(calibration_target instrument38 GroundStation3)
	(supports instrument39 image3)
	(supports instrument39 spectrograph1)
	(supports instrument39 spectrograph2)
	(calibration_target instrument39 GroundStation2)
	(supports instrument40 spectrograph1)
	(calibration_target instrument40 GroundStation2)
	(supports instrument41 spectrograph1)
	(supports instrument41 image0)
	(calibration_target instrument41 GroundStation2)
	(supports instrument42 spectrograph1)
	(calibration_target instrument42 GroundStation0)
	(supports instrument43 image0)
	(supports instrument43 spectrograph1)
	(calibration_target instrument43 GroundStation0)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(on_board instrument41 satellite5)
	(on_board instrument42 satellite5)
	(on_board instrument43 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star5)
	(supports instrument44 image0)
	(supports instrument44 spectrograph1)
	(calibration_target instrument44 GroundStation2)
	(supports instrument45 spectrograph2)
	(calibration_target instrument45 GroundStation3)
	(supports instrument46 spectrograph2)
	(supports instrument46 spectrograph1)
	(calibration_target instrument46 GroundStation2)
	(supports instrument47 thermograph4)
	(supports instrument47 spectrograph1)
	(supports instrument47 image0)
	(calibration_target instrument47 GroundStation3)
	(supports instrument48 spectrograph2)
	(calibration_target instrument48 Star1)
	(supports instrument49 spectrograph1)
	(supports instrument49 image0)
	(calibration_target instrument49 GroundStation2)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(on_board instrument46 satellite6)
	(on_board instrument47 satellite6)
	(on_board instrument48 satellite6)
	(on_board instrument49 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation0)
	(supports instrument50 image3)
	(supports instrument50 spectrograph2)
	(calibration_target instrument50 Star1)
	(supports instrument51 image3)
	(supports instrument51 spectrograph2)
	(calibration_target instrument51 GroundStation2)
	(supports instrument52 spectrograph2)
	(supports instrument52 spectrograph1)
	(calibration_target instrument52 Star1)
	(supports instrument53 image0)
	(supports instrument53 spectrograph1)
	(supports instrument53 image3)
	(calibration_target instrument53 GroundStation0)
	(supports instrument54 image0)
	(supports instrument54 spectrograph1)
	(supports instrument54 spectrograph2)
	(calibration_target instrument54 Star1)
	(supports instrument55 thermograph4)
	(calibration_target instrument55 GroundStation0)
	(supports instrument56 spectrograph1)
	(calibration_target instrument56 GroundStation3)
	(supports instrument57 thermograph4)
	(supports instrument57 spectrograph1)
	(calibration_target instrument57 GroundStation3)
	(supports instrument58 spectrograph1)
	(supports instrument58 image0)
	(calibration_target instrument58 GroundStation2)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(on_board instrument53 satellite7)
	(on_board instrument54 satellite7)
	(on_board instrument55 satellite7)
	(on_board instrument56 satellite7)
	(on_board instrument57 satellite7)
	(on_board instrument58 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation0)
	(supports instrument59 thermograph4)
	(calibration_target instrument59 Star1)
	(supports instrument60 image0)
	(supports instrument60 image3)
	(supports instrument60 spectrograph1)
	(calibration_target instrument60 GroundStation0)
	(supports instrument61 image0)
	(supports instrument61 thermograph4)
	(supports instrument61 spectrograph2)
	(calibration_target instrument61 GroundStation0)
	(on_board instrument59 satellite8)
	(on_board instrument60 satellite8)
	(on_board instrument61 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation3)
	(supports instrument62 image3)
	(supports instrument62 image0)
	(supports instrument62 spectrograph2)
	(calibration_target instrument62 GroundStation0)
	(supports instrument63 spectrograph1)
	(supports instrument63 image3)
	(supports instrument63 image0)
	(calibration_target instrument63 GroundStation0)
	(supports instrument64 thermograph4)
	(supports instrument64 spectrograph1)
	(supports instrument64 image3)
	(calibration_target instrument64 GroundStation2)
	(supports instrument65 image3)
	(supports instrument65 spectrograph1)
	(supports instrument65 image0)
	(calibration_target instrument65 Star1)
	(on_board instrument62 satellite9)
	(on_board instrument63 satellite9)
	(on_board instrument64 satellite9)
	(on_board instrument65 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star1)
)
(:goal (and
	(pointing satellite1 Star5)
	(pointing satellite2 Star1)
	(have_image Phenomenon4 spectrograph1)
	(have_image Star5 image3)
))

)
