(define (problem pb9)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (ontable block1) (on block2 block7) (clear block2) (on block3 block1) (on block4 block9) (on block5 block6) (on block6 block8) (on block7 block4) (on block8 block3) (on block9 block5) (handempty))
	(:goal (and (ontable block1) (clear block1) (on block2 block9) (clear block2) (ontable block3) (on block4 block7) (on block5 block4) (clear block5) (ontable block6) (on block7 block8) (on block8 block6) (on block9 block3))))