(define (problem pb7)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (ontable block1) (clear block1) (on block2 block6) (on block3 block9) (clear block3) (on block4 block5) (ontable block5) (on block6 block7) (ontable block7) (on block8 block2) (clear block8) (on block9 block4) (handempty))
	(:goal (and (on block1 block3) (on block2 block6) (on block3 block4) (on block4 block7) (ontable block5) (clear block5) (ontable block6) (ontable block7) (on block8 block2) (clear block8) (on block9 block1) (clear block9))))