(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (on block1 block4) (ontable block2) (ontable block3) (on block4 block8) (on block5 block2) (on block6 block1) (on block7 block5) (clear block7) (on block8 block3) (on block9 block6) (clear block9) (handempty))
	(:goal (and (on block1 block4) (clear block1) (ontable block2) (on block3 block6) (clear block3) (on block4 block5) (ontable block5) (on block6 block7) (on block7 block2) (ontable block8) (on block9 block8) (clear block9))))