(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (ontable block1) (on block2 block3) (clear block2) (on block3 block9) (ontable block4) (clear block4) (ontable block5) (clear block5) (on block6 block8) (clear block6) (ontable block7) (clear block7) (ontable block8) (on block9 block1) (handempty))
	(:goal (and (on block1 block6) (on block2 block1) (clear block2) (on block3 block5) (clear block3) (ontable block4) (on block5 block8) (ontable block6) (on block7 block4) (on block8 block7) (ontable block9) (clear block9))))