(define (problem pb2)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (ontable block1) (clear block1) (ontable block2) (clear block2) (on block3 block7) (ontable block4) (on block5 block8) (clear block5) (on block6 block3) (clear block6) (ontable block7) (ontable block8) (on block9 block4) (clear block9) (handempty))
	(:goal (and (ontable block1) (on block2 block6) (on block3 block8) (clear block3) (on block4 block2) (ontable block5) (on block6 block1) (on block7 block5) (on block8 block7) (on block9 block4) (clear block9))))