(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (on block1 block8) (on block2 block3) (clear block2) (on block3 block9) (on block4 block1) (clear block4) (ontable block5) (ontable block6) (clear block6) (ontable block7) (on block8 block7) (on block9 block5) (handempty))
	(:goal (and (ontable block1) (clear block1) (ontable block2) (ontable block3) (ontable block4) (clear block4) (on block5 block2) (clear block5) (on block6 block9) (clear block6) (ontable block7) (clear block7) (on block8 block3) (clear block8) (ontable block9))))