(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (on block1 block4) (clear block1) (on block2 block6) (clear block2) (on block3 block7) (on block4 block3) (ontable block5) (on block6 block9) (ontable block7) (on block8 block5) (clear block8) (ontable block9) (handempty))
	(:goal (and (on block1 block8) (on block2 block3) (clear block2) (on block3 block9) (on block4 block6) (on block5 block4) (ontable block6) (on block7 block5) (clear block7) (ontable block8) (on block9 block1))))