(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite2 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite3 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	satellite4 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite5 - satellite
	instrument38 - instrument
	instrument39 - instrument
	satellite6 - satellite
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite7 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	satellite8 - satellite
	instrument58 - instrument
	instrument59 - instrument
	satellite9 - satellite
	instrument60 - instrument
	instrument61 - instrument
	instrument62 - instrument
	instrument63 - instrument
	instrument64 - instrument
	instrument65 - instrument
	infrared3 - mode
	thermograph2 - mode
	thermograph1 - mode
	image0 - mode
	thermograph4 - mode
	Star0 - direction
	GroundStation4 - direction
	GroundStation1 - direction
	GroundStation3 - direction
	Star2 - direction
	Star5 - direction
	Planet6 - direction
	Phenomenon7 - direction
)
(:init
	(supports instrument0 thermograph1)
	(calibration_target instrument0 Star2)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 Star2)
	(calibration_target instrument1 GroundStation4)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 GroundStation3)
	(calibration_target instrument2 Star0)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 image0)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 Star5)
	(supports instrument5 thermograph2)
	(supports instrument5 image0)
	(calibration_target instrument5 Star2)
	(calibration_target instrument5 Star5)
	(supports instrument6 infrared3)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 Star5)
	(calibration_target instrument6 GroundStation1)
	(supports instrument7 infrared3)
	(supports instrument7 image0)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 GroundStation1)
	(calibration_target instrument7 Star5)
	(supports instrument8 infrared3)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 GroundStation4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation1)
	(supports instrument9 thermograph1)
	(supports instrument9 image0)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 GroundStation3)
	(supports instrument10 thermograph4)
	(supports instrument10 image0)
	(supports instrument10 infrared3)
	(calibration_target instrument10 Star5)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 Star2)
	(calibration_target instrument11 Star5)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 GroundStation4)
	(calibration_target instrument12 GroundStation1)
	(supports instrument13 image0)
	(calibration_target instrument13 Star5)
	(calibration_target instrument13 GroundStation3)
	(supports instrument14 thermograph2)
	(calibration_target instrument14 Star5)
	(supports instrument15 thermograph4)
	(supports instrument15 thermograph1)
	(supports instrument15 thermograph2)
	(calibration_target instrument15 GroundStation4)
	(calibration_target instrument15 Star2)
	(supports instrument16 image0)
	(calibration_target instrument16 Star0)
	(calibration_target instrument16 GroundStation4)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star2)
	(supports instrument17 infrared3)
	(supports instrument17 image0)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 GroundStation1)
	(supports instrument18 infrared3)
	(supports instrument18 thermograph1)
	(calibration_target instrument18 GroundStation1)
	(calibration_target instrument18 GroundStation3)
	(supports instrument19 thermograph2)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 Star2)
	(supports instrument20 thermograph2)
	(supports instrument20 image0)
	(supports instrument20 infrared3)
	(calibration_target instrument20 Star2)
	(supports instrument21 infrared3)
	(supports instrument21 thermograph1)
	(supports instrument21 image0)
	(calibration_target instrument21 Star5)
	(supports instrument22 thermograph1)
	(calibration_target instrument22 GroundStation1)
	(calibration_target instrument22 Star2)
	(supports instrument23 image0)
	(calibration_target instrument23 GroundStation4)
	(calibration_target instrument23 Star5)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(on_board instrument22 satellite2)
	(on_board instrument23 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation1)
	(supports instrument24 image0)
	(supports instrument24 thermograph1)
	(calibration_target instrument24 Star2)
	(supports instrument25 thermograph1)
	(supports instrument25 thermograph4)
	(calibration_target instrument25 Star2)
	(supports instrument26 infrared3)
	(supports instrument26 image0)
	(supports instrument26 thermograph4)
	(calibration_target instrument26 GroundStation1)
	(calibration_target instrument26 Star2)
	(supports instrument27 thermograph4)
	(supports instrument27 thermograph1)
	(calibration_target instrument27 GroundStation1)
	(supports instrument28 image0)
	(supports instrument28 infrared3)
	(supports instrument28 thermograph1)
	(calibration_target instrument28 Star5)
	(calibration_target instrument28 GroundStation4)
	(supports instrument29 thermograph4)
	(calibration_target instrument29 Star0)
	(calibration_target instrument29 GroundStation4)
	(supports instrument30 thermograph4)
	(supports instrument30 thermograph1)
	(calibration_target instrument30 Star5)
	(supports instrument31 infrared3)
	(supports instrument31 thermograph2)
	(supports instrument31 image0)
	(calibration_target instrument31 GroundStation4)
	(calibration_target instrument31 GroundStation1)
	(supports instrument32 thermograph1)
	(calibration_target instrument32 GroundStation4)
	(supports instrument33 image0)
	(supports instrument33 thermograph2)
	(supports instrument33 infrared3)
	(calibration_target instrument33 GroundStation1)
	(calibration_target instrument33 Star2)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(on_board instrument30 satellite3)
	(on_board instrument31 satellite3)
	(on_board instrument32 satellite3)
	(on_board instrument33 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet6)
	(supports instrument34 thermograph4)
	(supports instrument34 thermograph2)
	(supports instrument34 thermograph1)
	(calibration_target instrument34 GroundStation4)
	(supports instrument35 thermograph1)
	(supports instrument35 thermograph2)
	(supports instrument35 infrared3)
	(calibration_target instrument35 GroundStation4)
	(calibration_target instrument35 GroundStation3)
	(supports instrument36 thermograph1)
	(calibration_target instrument36 GroundStation4)
	(supports instrument37 thermograph1)
	(supports instrument37 image0)
	(calibration_target instrument37 GroundStation3)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(on_board instrument37 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon7)
	(supports instrument38 thermograph4)
	(supports instrument38 image0)
	(supports instrument38 thermograph2)
	(calibration_target instrument38 Star0)
	(supports instrument39 image0)
	(calibration_target instrument39 Star2)
	(calibration_target instrument39 Star5)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation3)
	(supports instrument40 infrared3)
	(supports instrument40 thermograph1)
	(supports instrument40 image0)
	(calibration_target instrument40 Star5)
	(supports instrument41 image0)
	(supports instrument41 thermograph4)
	(supports instrument41 thermograph1)
	(calibration_target instrument41 GroundStation1)
	(calibration_target instrument41 GroundStation4)
	(supports instrument42 thermograph2)
	(calibration_target instrument42 GroundStation3)
	(calibration_target instrument42 Star5)
	(supports instrument43 thermograph2)
	(calibration_target instrument43 GroundStation1)
	(supports instrument44 infrared3)
	(supports instrument44 thermograph1)
	(supports instrument44 image0)
	(calibration_target instrument44 Star2)
	(supports instrument45 infrared3)
	(supports instrument45 thermograph1)
	(calibration_target instrument45 GroundStation3)
	(supports instrument46 thermograph2)
	(supports instrument46 image0)
	(supports instrument46 infrared3)
	(calibration_target instrument46 Star2)
	(supports instrument47 image0)
	(supports instrument47 thermograph1)
	(calibration_target instrument47 GroundStation1)
	(calibration_target instrument47 Star0)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(on_board instrument46 satellite6)
	(on_board instrument47 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon7)
	(supports instrument48 image0)
	(supports instrument48 infrared3)
	(supports instrument48 thermograph4)
	(calibration_target instrument48 Star5)
	(calibration_target instrument48 Star2)
	(supports instrument49 image0)
	(calibration_target instrument49 GroundStation3)
	(supports instrument50 thermograph4)
	(supports instrument50 thermograph1)
	(supports instrument50 infrared3)
	(calibration_target instrument50 Star0)
	(calibration_target instrument50 GroundStation4)
	(supports instrument51 image0)
	(supports instrument51 thermograph4)
	(calibration_target instrument51 GroundStation4)
	(supports instrument52 thermograph4)
	(calibration_target instrument52 GroundStation4)
	(supports instrument53 thermograph4)
	(supports instrument53 infrared3)
	(calibration_target instrument53 Star5)
	(supports instrument54 thermograph1)
	(calibration_target instrument54 Star0)
	(supports instrument55 thermograph1)
	(calibration_target instrument55 GroundStation4)
	(calibration_target instrument55 Star5)
	(supports instrument56 image0)
	(supports instrument56 thermograph2)
	(calibration_target instrument56 GroundStation1)
	(calibration_target instrument56 Star0)
	(supports instrument57 thermograph4)
	(supports instrument57 image0)
	(calibration_target instrument57 GroundStation4)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(on_board instrument53 satellite7)
	(on_board instrument54 satellite7)
	(on_board instrument55 satellite7)
	(on_board instrument56 satellite7)
	(on_board instrument57 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star2)
	(supports instrument58 thermograph2)
	(supports instrument58 image0)
	(calibration_target instrument58 Star0)
	(supports instrument59 thermograph1)
	(calibration_target instrument59 GroundStation4)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation4)
	(supports instrument60 thermograph1)
	(supports instrument60 image0)
	(supports instrument60 infrared3)
	(calibration_target instrument60 Star2)
	(supports instrument61 thermograph1)
	(calibration_target instrument61 GroundStation1)
	(supports instrument62 image0)
	(supports instrument62 thermograph2)
	(calibration_target instrument62 GroundStation3)
	(calibration_target instrument62 GroundStation1)
	(supports instrument63 thermograph2)
	(calibration_target instrument63 Star5)
	(calibration_target instrument63 Star2)
	(supports instrument64 thermograph4)
	(supports instrument64 thermograph1)
	(calibration_target instrument64 Star2)
	(supports instrument65 thermograph4)
	(supports instrument65 image0)
	(supports instrument65 thermograph1)
	(calibration_target instrument65 Star5)
	(on_board instrument60 satellite9)
	(on_board instrument61 satellite9)
	(on_board instrument62 satellite9)
	(on_board instrument63 satellite9)
	(on_board instrument64 satellite9)
	(on_board instrument65 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon7)
)
(:goal (and
	(pointing satellite3 Planet6)
	(pointing satellite4 Star2)
	(pointing satellite6 Star0)
	(pointing satellite8 GroundStation1)
	(pointing satellite9 Phenomenon7)
	(have_image Planet6 thermograph4)
))

)
