(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite3 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite4 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite5 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite6 - satellite
	instrument30 - instrument
	satellite7 - satellite
	instrument31 - instrument
	instrument32 - instrument
	satellite8 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	satellite9 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	thermograph3 - mode
	thermograph4 - mode
	spectrograph0 - mode
	infrared2 - mode
	infrared1 - mode
	GroundStation1 - direction
	Star4 - direction
	Star3 - direction
	Star2 - direction
	Star5 - direction
	Star0 - direction
	Star6 - direction
	Planet7 - direction
)
(:init
	(supports instrument0 spectrograph0)
	(supports instrument0 infrared1)
	(calibration_target instrument0 GroundStation1)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation1)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 Star3)
	(supports instrument2 thermograph4)
	(supports instrument2 infrared2)
	(calibration_target instrument2 Star2)
	(calibration_target instrument2 Star4)
	(supports instrument3 infrared1)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 Star5)
	(supports instrument4 infrared2)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 Star5)
	(supports instrument5 spectrograph0)
	(supports instrument5 infrared1)
	(calibration_target instrument5 Star0)
	(supports instrument6 infrared2)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star5)
	(supports instrument7 infrared2)
	(supports instrument7 thermograph3)
	(calibration_target instrument7 Star4)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 Star4)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument9 infrared2)
	(supports instrument9 infrared1)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 Star2)
	(supports instrument10 spectrograph0)
	(supports instrument10 infrared2)
	(supports instrument10 infrared1)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 thermograph3)
	(supports instrument11 spectrograph0)
	(supports instrument11 infrared2)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 Star4)
	(supports instrument12 thermograph4)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 GroundStation1)
	(supports instrument13 thermograph3)
	(supports instrument13 spectrograph0)
	(supports instrument13 infrared2)
	(calibration_target instrument13 GroundStation1)
	(supports instrument14 infrared2)
	(calibration_target instrument14 Star2)
	(calibration_target instrument14 Star3)
	(supports instrument15 thermograph4)
	(supports instrument15 thermograph3)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 Star4)
	(supports instrument16 thermograph4)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 Star0)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 Star2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument18 thermograph3)
	(supports instrument18 infrared2)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 GroundStation1)
	(calibration_target instrument18 Star4)
	(supports instrument19 thermograph4)
	(supports instrument19 infrared1)
	(supports instrument19 thermograph3)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 Star4)
	(supports instrument20 infrared2)
	(supports instrument20 infrared1)
	(calibration_target instrument20 Star5)
	(supports instrument21 thermograph3)
	(supports instrument21 infrared1)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 Star5)
	(calibration_target instrument21 Star4)
	(supports instrument22 infrared2)
	(calibration_target instrument22 Star2)
	(supports instrument23 thermograph3)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 Star5)
	(calibration_target instrument23 Star2)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet7)
	(supports instrument24 infrared2)
	(supports instrument24 spectrograph0)
	(supports instrument24 infrared1)
	(calibration_target instrument24 GroundStation1)
	(supports instrument25 infrared2)
	(calibration_target instrument25 Star2)
	(calibration_target instrument25 Star3)
	(supports instrument26 thermograph3)
	(calibration_target instrument26 Star2)
	(calibration_target instrument26 Star5)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation1)
	(supports instrument27 infrared1)
	(supports instrument27 spectrograph0)
	(calibration_target instrument27 Star5)
	(supports instrument28 infrared1)
	(supports instrument28 spectrograph0)
	(calibration_target instrument28 Star0)
	(supports instrument29 spectrograph0)
	(supports instrument29 infrared1)
	(supports instrument29 thermograph3)
	(calibration_target instrument29 Star4)
	(calibration_target instrument29 GroundStation1)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star5)
	(supports instrument30 thermograph4)
	(calibration_target instrument30 GroundStation1)
	(on_board instrument30 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star0)
	(supports instrument31 thermograph3)
	(supports instrument31 infrared2)
	(supports instrument31 thermograph4)
	(calibration_target instrument31 GroundStation1)
	(calibration_target instrument31 Star5)
	(supports instrument32 thermograph3)
	(supports instrument32 infrared1)
	(calibration_target instrument32 Star4)
	(on_board instrument31 satellite7)
	(on_board instrument32 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation1)
	(supports instrument33 thermograph4)
	(supports instrument33 infrared2)
	(supports instrument33 thermograph3)
	(calibration_target instrument33 Star5)
	(supports instrument34 infrared2)
	(supports instrument34 thermograph4)
	(calibration_target instrument34 Star5)
	(calibration_target instrument34 GroundStation1)
	(supports instrument35 thermograph3)
	(calibration_target instrument35 GroundStation1)
	(calibration_target instrument35 Star0)
	(supports instrument36 infrared2)
	(supports instrument36 infrared1)
	(supports instrument36 thermograph3)
	(calibration_target instrument36 Star5)
	(supports instrument37 spectrograph0)
	(supports instrument37 infrared2)
	(calibration_target instrument37 Star4)
	(calibration_target instrument37 Star0)
	(supports instrument38 infrared2)
	(supports instrument38 spectrograph0)
	(supports instrument38 infrared1)
	(calibration_target instrument38 Star0)
	(calibration_target instrument38 Star2)
	(on_board instrument33 satellite8)
	(on_board instrument34 satellite8)
	(on_board instrument35 satellite8)
	(on_board instrument36 satellite8)
	(on_board instrument37 satellite8)
	(on_board instrument38 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star4)
	(supports instrument39 thermograph4)
	(calibration_target instrument39 Star3)
	(calibration_target instrument39 Star2)
	(supports instrument40 spectrograph0)
	(calibration_target instrument40 Star2)
	(calibration_target instrument40 Star3)
	(supports instrument41 infrared1)
	(supports instrument41 thermograph4)
	(supports instrument41 spectrograph0)
	(calibration_target instrument41 Star5)
	(calibration_target instrument41 Star0)
	(supports instrument42 infrared1)
	(supports instrument42 infrared2)
	(supports instrument42 spectrograph0)
	(calibration_target instrument42 Star0)
	(on_board instrument39 satellite9)
	(on_board instrument40 satellite9)
	(on_board instrument41 satellite9)
	(on_board instrument42 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star2)
)
(:goal (and
	(pointing satellite0 Star3)
	(pointing satellite1 Star6)
	(pointing satellite6 Star3)
	(pointing satellite8 Star6)
	(pointing satellite9 Star5)
	(have_image Star6 infrared1)
	(have_image Planet7 thermograph4)
))

)
