(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite3 - satellite
	instrument19 - instrument
	satellite4 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite5 - satellite
	instrument26 - instrument
	instrument27 - instrument
	satellite6 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite7 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	satellite8 - satellite
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	satellite9 - satellite
	instrument47 - instrument
	instrument48 - instrument
	infrared3 - mode
	infrared1 - mode
	infrared4 - mode
	thermograph2 - mode
	image0 - mode
	Star2 - direction
	GroundStation4 - direction
	GroundStation5 - direction
	Star3 - direction
	Star1 - direction
	Star0 - direction
	Planet6 - direction
	Star7 - direction
)
(:init
	(supports instrument0 infrared1)
	(supports instrument0 infrared3)
	(calibration_target instrument0 Star3)
	(calibration_target instrument0 Star1)
	(supports instrument1 infrared1)
	(supports instrument1 infrared4)
	(supports instrument1 image0)
	(calibration_target instrument1 Star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(supports instrument2 infrared3)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 GroundStation5)
	(supports instrument3 infrared4)
	(supports instrument3 thermograph2)
	(supports instrument3 infrared3)
	(calibration_target instrument3 Star0)
	(supports instrument4 infrared4)
	(supports instrument4 infrared1)
	(calibration_target instrument4 GroundStation5)
	(supports instrument5 infrared4)
	(supports instrument5 infrared3)
	(supports instrument5 thermograph2)
	(calibration_target instrument5 Star1)
	(supports instrument6 infrared3)
	(supports instrument6 infrared4)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star2)
	(calibration_target instrument6 Star3)
	(supports instrument7 thermograph2)
	(supports instrument7 infrared1)
	(supports instrument7 image0)
	(calibration_target instrument7 Star0)
	(supports instrument8 image0)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 Star0)
	(supports instrument9 thermograph2)
	(calibration_target instrument9 Star0)
	(supports instrument10 infrared3)
	(supports instrument10 image0)
	(calibration_target instrument10 GroundStation4)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument11 infrared4)
	(supports instrument11 infrared1)
	(supports instrument11 infrared3)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 Star2)
	(supports instrument12 thermograph2)
	(supports instrument12 infrared4)
	(calibration_target instrument12 Star1)
	(calibration_target instrument12 GroundStation4)
	(supports instrument13 image0)
	(supports instrument13 infrared1)
	(calibration_target instrument13 Star2)
	(supports instrument14 infrared4)
	(supports instrument14 infrared3)
	(calibration_target instrument14 Star3)
	(supports instrument15 infrared1)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 Star1)
	(supports instrument16 thermograph2)
	(supports instrument16 infrared1)
	(supports instrument16 infrared4)
	(calibration_target instrument16 Star0)
	(supports instrument17 image0)
	(calibration_target instrument17 Star1)
	(calibration_target instrument17 GroundStation4)
	(supports instrument18 infrared1)
	(supports instrument18 infrared3)
	(supports instrument18 thermograph2)
	(calibration_target instrument18 Star0)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star7)
	(supports instrument19 infrared3)
	(supports instrument19 infrared1)
	(calibration_target instrument19 Star1)
	(on_board instrument19 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star0)
	(supports instrument20 image0)
	(supports instrument20 infrared3)
	(supports instrument20 infrared1)
	(calibration_target instrument20 Star3)
	(supports instrument21 infrared1)
	(supports instrument21 thermograph2)
	(calibration_target instrument21 GroundStation5)
	(calibration_target instrument21 Star0)
	(supports instrument22 infrared3)
	(supports instrument22 infrared1)
	(calibration_target instrument22 GroundStation5)
	(supports instrument23 infrared1)
	(supports instrument23 thermograph2)
	(supports instrument23 infrared3)
	(calibration_target instrument23 GroundStation4)
	(calibration_target instrument23 Star3)
	(supports instrument24 infrared4)
	(supports instrument24 infrared3)
	(supports instrument24 infrared1)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 Star1)
	(supports instrument25 image0)
	(supports instrument25 infrared4)
	(supports instrument25 thermograph2)
	(calibration_target instrument25 GroundStation5)
	(calibration_target instrument25 Star0)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation5)
	(supports instrument26 infrared1)
	(calibration_target instrument26 Star1)
	(supports instrument27 infrared4)
	(supports instrument27 infrared3)
	(calibration_target instrument27 GroundStation4)
	(calibration_target instrument27 Star1)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star7)
	(supports instrument28 infrared1)
	(supports instrument28 infrared3)
	(calibration_target instrument28 Star0)
	(calibration_target instrument28 Star2)
	(supports instrument29 infrared4)
	(supports instrument29 thermograph2)
	(calibration_target instrument29 Star2)
	(supports instrument30 infrared4)
	(supports instrument30 thermograph2)
	(supports instrument30 infrared3)
	(calibration_target instrument30 Star0)
	(supports instrument31 image0)
	(calibration_target instrument31 Star2)
	(calibration_target instrument31 GroundStation5)
	(supports instrument32 infrared1)
	(supports instrument32 infrared3)
	(calibration_target instrument32 GroundStation5)
	(calibration_target instrument32 Star0)
	(on_board instrument28 satellite6)
	(on_board instrument29 satellite6)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star3)
	(supports instrument33 infrared3)
	(supports instrument33 infrared1)
	(calibration_target instrument33 Star2)
	(supports instrument34 infrared4)
	(supports instrument34 thermograph2)
	(calibration_target instrument34 Star1)
	(calibration_target instrument34 GroundStation5)
	(supports instrument35 image0)
	(calibration_target instrument35 GroundStation4)
	(supports instrument36 image0)
	(supports instrument36 infrared4)
	(supports instrument36 thermograph2)
	(calibration_target instrument36 Star1)
	(supports instrument37 infrared1)
	(calibration_target instrument37 Star0)
	(supports instrument38 image0)
	(supports instrument38 infrared1)
	(supports instrument38 infrared3)
	(calibration_target instrument38 Star3)
	(supports instrument39 thermograph2)
	(supports instrument39 infrared4)
	(calibration_target instrument39 Star3)
	(calibration_target instrument39 GroundStation4)
	(supports instrument40 image0)
	(supports instrument40 infrared1)
	(calibration_target instrument40 Star0)
	(calibration_target instrument40 GroundStation5)
	(supports instrument41 infrared4)
	(calibration_target instrument41 GroundStation4)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet6)
	(supports instrument42 thermograph2)
	(supports instrument42 infrared3)
	(calibration_target instrument42 Star3)
	(supports instrument43 image0)
	(calibration_target instrument43 GroundStation5)
	(calibration_target instrument43 Star0)
	(supports instrument44 infrared3)
	(supports instrument44 thermograph2)
	(supports instrument44 infrared1)
	(calibration_target instrument44 Star0)
	(calibration_target instrument44 GroundStation4)
	(supports instrument45 infrared1)
	(supports instrument45 image0)
	(supports instrument45 thermograph2)
	(calibration_target instrument45 GroundStation4)
	(calibration_target instrument45 GroundStation5)
	(supports instrument46 infrared3)
	(supports instrument46 infrared4)
	(calibration_target instrument46 GroundStation5)
	(calibration_target instrument46 Star1)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation5)
	(supports instrument47 infrared1)
	(supports instrument47 thermograph2)
	(supports instrument47 infrared4)
	(calibration_target instrument47 Star3)
	(calibration_target instrument47 Star0)
	(supports instrument48 image0)
	(supports instrument48 thermograph2)
	(supports instrument48 infrared4)
	(calibration_target instrument48 Star0)
	(calibration_target instrument48 Star1)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star2)
)
(:goal (and
	(pointing satellite1 GroundStation4)
	(pointing satellite3 Star1)
	(pointing satellite4 GroundStation4)
	(pointing satellite5 Star1)
	(pointing satellite6 GroundStation4)
	(pointing satellite8 Star3)
	(pointing satellite9 Star1)
	(have_image Planet6 infrared3)
	(have_image Star7 image0)
))

)
