(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite2 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite4 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite5 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite6 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite7 - satellite
	instrument44 - instrument
	satellite8 - satellite
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	satellite9 - satellite
	instrument52 - instrument
	instrument53 - instrument
	spectrograph3 - mode
	infrared0 - mode
	thermograph4 - mode
	infrared1 - mode
	image2 - mode
	Star1 - direction
	Star3 - direction
	Star2 - direction
	Star0 - direction
	GroundStation5 - direction
	GroundStation4 - direction
	Star6 - direction
	Star7 - direction
)
(:init
	(supports instrument0 infrared1)
	(supports instrument0 spectrograph3)
	(calibration_target instrument0 GroundStation4)
	(supports instrument1 infrared0)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 Star0)
	(supports instrument2 spectrograph3)
	(supports instrument2 infrared0)
	(calibration_target instrument2 Star3)
	(supports instrument3 image2)
	(supports instrument3 infrared0)
	(calibration_target instrument3 GroundStation4)
	(supports instrument4 infrared0)
	(supports instrument4 infrared1)
	(calibration_target instrument4 Star2)
	(supports instrument5 infrared1)
	(supports instrument5 image2)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation5)
	(supports instrument6 image2)
	(supports instrument6 spectrograph3)
	(calibration_target instrument6 Star3)
	(supports instrument7 infrared0)
	(supports instrument7 image2)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation5)
	(supports instrument8 infrared0)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 Star0)
	(supports instrument9 infrared0)
	(supports instrument9 infrared1)
	(calibration_target instrument9 Star2)
	(supports instrument10 infrared0)
	(calibration_target instrument10 Star2)
	(calibration_target instrument10 Star0)
	(supports instrument11 infrared1)
	(calibration_target instrument11 Star3)
	(supports instrument12 image2)
	(calibration_target instrument12 GroundStation4)
	(supports instrument13 infrared0)
	(supports instrument13 spectrograph3)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 Star0)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation5)
	(calibration_target instrument14 GroundStation4)
	(supports instrument15 infrared0)
	(supports instrument15 image2)
	(calibration_target instrument15 Star1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument16 image2)
	(supports instrument16 infrared0)
	(supports instrument16 spectrograph3)
	(calibration_target instrument16 Star2)
	(supports instrument17 spectrograph3)
	(supports instrument17 infrared1)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 Star2)
	(supports instrument18 image2)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 Star2)
	(supports instrument19 image2)
	(calibration_target instrument19 Star2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation5)
	(supports instrument20 spectrograph3)
	(supports instrument20 infrared1)
	(supports instrument20 infrared0)
	(calibration_target instrument20 Star0)
	(supports instrument21 infrared1)
	(supports instrument21 infrared0)
	(supports instrument21 spectrograph3)
	(calibration_target instrument21 Star1)
	(calibration_target instrument21 GroundStation5)
	(supports instrument22 infrared0)
	(supports instrument22 spectrograph3)
	(calibration_target instrument22 Star0)
	(calibration_target instrument22 GroundStation5)
	(supports instrument23 infrared1)
	(supports instrument23 image2)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 GroundStation5)
	(calibration_target instrument23 Star1)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation4)
	(supports instrument24 infrared0)
	(supports instrument24 thermograph4)
	(supports instrument24 spectrograph3)
	(calibration_target instrument24 Star2)
	(calibration_target instrument24 Star3)
	(supports instrument25 infrared0)
	(supports instrument25 spectrograph3)
	(calibration_target instrument25 GroundStation5)
	(supports instrument26 image2)
	(calibration_target instrument26 Star1)
	(calibration_target instrument26 GroundStation4)
	(supports instrument27 infrared0)
	(supports instrument27 infrared1)
	(supports instrument27 image2)
	(calibration_target instrument27 Star0)
	(calibration_target instrument27 Star1)
	(supports instrument28 image2)
	(supports instrument28 thermograph4)
	(supports instrument28 infrared0)
	(calibration_target instrument28 GroundStation4)
	(supports instrument29 infrared0)
	(calibration_target instrument29 GroundStation4)
	(calibration_target instrument29 Star3)
	(supports instrument30 infrared0)
	(supports instrument30 thermograph4)
	(calibration_target instrument30 Star1)
	(supports instrument31 infrared1)
	(supports instrument31 thermograph4)
	(calibration_target instrument31 Star0)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation5)
	(supports instrument32 spectrograph3)
	(supports instrument32 image2)
	(calibration_target instrument32 Star2)
	(calibration_target instrument32 Star3)
	(supports instrument33 infrared1)
	(supports instrument33 thermograph4)
	(calibration_target instrument33 Star2)
	(calibration_target instrument33 GroundStation4)
	(supports instrument34 image2)
	(supports instrument34 spectrograph3)
	(supports instrument34 infrared0)
	(calibration_target instrument34 Star3)
	(calibration_target instrument34 GroundStation4)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(supports instrument35 infrared0)
	(calibration_target instrument35 GroundStation5)
	(calibration_target instrument35 Star3)
	(supports instrument36 infrared0)
	(calibration_target instrument36 Star1)
	(calibration_target instrument36 GroundStation5)
	(supports instrument37 thermograph4)
	(supports instrument37 infrared1)
	(supports instrument37 spectrograph3)
	(calibration_target instrument37 Star1)
	(supports instrument38 infrared0)
	(supports instrument38 image2)
	(supports instrument38 spectrograph3)
	(calibration_target instrument38 Star0)
	(supports instrument39 thermograph4)
	(calibration_target instrument39 Star2)
	(supports instrument40 spectrograph3)
	(calibration_target instrument40 GroundStation5)
	(calibration_target instrument40 Star0)
	(supports instrument41 infrared1)
	(supports instrument41 image2)
	(supports instrument41 infrared0)
	(calibration_target instrument41 GroundStation4)
	(calibration_target instrument41 Star1)
	(supports instrument42 infrared1)
	(supports instrument42 thermograph4)
	(calibration_target instrument42 Star2)
	(supports instrument43 infrared0)
	(supports instrument43 image2)
	(calibration_target instrument43 GroundStation5)
	(calibration_target instrument43 Star1)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation4)
	(supports instrument44 thermograph4)
	(supports instrument44 spectrograph3)
	(supports instrument44 infrared1)
	(calibration_target instrument44 GroundStation5)
	(on_board instrument44 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
	(supports instrument45 thermograph4)
	(supports instrument45 image2)
	(supports instrument45 infrared0)
	(calibration_target instrument45 GroundStation5)
	(supports instrument46 infrared1)
	(supports instrument46 infrared0)
	(supports instrument46 spectrograph3)
	(calibration_target instrument46 Star3)
	(supports instrument47 infrared0)
	(supports instrument47 thermograph4)
	(supports instrument47 infrared1)
	(calibration_target instrument47 Star2)
	(supports instrument48 spectrograph3)
	(supports instrument48 image2)
	(calibration_target instrument48 Star0)
	(supports instrument49 spectrograph3)
	(supports instrument49 thermograph4)
	(calibration_target instrument49 Star2)
	(supports instrument50 spectrograph3)
	(calibration_target instrument50 GroundStation4)
	(calibration_target instrument50 Star0)
	(supports instrument51 thermograph4)
	(supports instrument51 infrared0)
	(supports instrument51 infrared1)
	(calibration_target instrument51 GroundStation5)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star1)
	(supports instrument52 infrared1)
	(calibration_target instrument52 GroundStation4)
	(supports instrument53 image2)
	(calibration_target instrument53 GroundStation4)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation5)
)
(:goal (and
	(pointing satellite4 Star6)
	(pointing satellite5 Star1)
	(have_image Star7 thermograph4)
))

)
