(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite3 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite4 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite5 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite6 - satellite
	instrument27 - instrument
	instrument28 - instrument
	satellite7 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite8 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite9 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	image2 - mode
	thermograph4 - mode
	infrared1 - mode
	spectrograph3 - mode
	infrared0 - mode
	Star13 - direction
	Star11 - direction
	Star23 - direction
	GroundStation31 - direction
	Star2 - direction
	Star3 - direction
	GroundStation12 - direction
	Star32 - direction
	Star8 - direction
	GroundStation21 - direction
	GroundStation16 - direction
	GroundStation25 - direction
	GroundStation15 - direction
	Star27 - direction
	GroundStation14 - direction
	Star26 - direction
	GroundStation24 - direction
	Star1 - direction
	GroundStation22 - direction
	GroundStation30 - direction
	GroundStation28 - direction
	Star0 - direction
	Star18 - direction
	GroundStation20 - direction
	Star7 - direction
	GroundStation9 - direction
	GroundStation17 - direction
	GroundStation10 - direction
	Star6 - direction
	GroundStation29 - direction
	GroundStation5 - direction
	Star19 - direction
	GroundStation4 - direction
	Phenomenon33 - direction
	Planet34 - direction
)
(:init
	(supports instrument0 spectrograph3)
	(supports instrument0 thermograph4)
	(calibration_target instrument0 GroundStation16)
	(calibration_target instrument0 GroundStation17)
	(calibration_target instrument0 Star3)
	(calibration_target instrument0 GroundStation21)
	(calibration_target instrument0 Star2)
	(calibration_target instrument0 Star27)
	(calibration_target instrument0 GroundStation25)
	(calibration_target instrument0 GroundStation12)
	(supports instrument1 image2)
	(supports instrument1 thermograph4)
	(supports instrument1 spectrograph3)
	(calibration_target instrument1 Star13)
	(calibration_target instrument1 GroundStation30)
	(calibration_target instrument1 GroundStation24)
	(calibration_target instrument1 Star27)
	(calibration_target instrument1 Star11)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 GroundStation14)
	(calibration_target instrument1 Star8)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 GroundStation5)
	(calibration_target instrument2 GroundStation22)
	(calibration_target instrument2 Star23)
	(calibration_target instrument2 GroundStation21)
	(calibration_target instrument2 GroundStation25)
	(calibration_target instrument2 Star32)
	(calibration_target instrument2 GroundStation28)
	(calibration_target instrument2 GroundStation4)
	(supports instrument3 spectrograph3)
	(supports instrument3 thermograph4)
	(supports instrument3 image2)
	(calibration_target instrument3 Star18)
	(calibration_target instrument3 GroundStation25)
	(calibration_target instrument3 GroundStation14)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation22)
	(supports instrument4 image2)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 Star13)
	(calibration_target instrument4 Star23)
	(calibration_target instrument4 GroundStation29)
	(calibration_target instrument4 GroundStation9)
	(calibration_target instrument4 GroundStation4)
	(calibration_target instrument4 GroundStation24)
	(calibration_target instrument4 GroundStation16)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star8)
	(supports instrument5 infrared1)
	(supports instrument5 spectrograph3)
	(supports instrument5 image2)
	(calibration_target instrument5 Star8)
	(calibration_target instrument5 Star2)
	(supports instrument6 thermograph4)
	(supports instrument6 infrared1)
	(supports instrument6 infrared0)
	(calibration_target instrument6 GroundStation30)
	(calibration_target instrument6 Star23)
	(calibration_target instrument6 GroundStation29)
	(calibration_target instrument6 GroundStation12)
	(calibration_target instrument6 GroundStation25)
	(supports instrument7 infrared1)
	(supports instrument7 spectrograph3)
	(calibration_target instrument7 GroundStation15)
	(calibration_target instrument7 Star0)
	(supports instrument8 infrared0)
	(calibration_target instrument8 Star32)
	(calibration_target instrument8 Star13)
	(calibration_target instrument8 GroundStation28)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 GroundStation17)
	(calibration_target instrument8 Star19)
	(calibration_target instrument8 GroundStation5)
	(calibration_target instrument8 GroundStation24)
	(calibration_target instrument8 GroundStation14)
	(calibration_target instrument8 Star23)
	(supports instrument9 thermograph4)
	(supports instrument9 spectrograph3)
	(calibration_target instrument9 GroundStation22)
	(calibration_target instrument9 GroundStation9)
	(calibration_target instrument9 GroundStation24)
	(calibration_target instrument9 GroundStation30)
	(calibration_target instrument9 GroundStation16)
	(supports instrument10 image2)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 GroundStation17)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 GroundStation31)
	(calibration_target instrument10 Star7)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 Star26)
	(calibration_target instrument11 GroundStation10)
	(calibration_target instrument11 GroundStation30)
	(calibration_target instrument11 GroundStation15)
	(calibration_target instrument11 GroundStation5)
	(supports instrument12 infrared1)
	(calibration_target instrument12 GroundStation29)
	(supports instrument13 image2)
	(calibration_target instrument13 GroundStation30)
	(calibration_target instrument13 Star18)
	(calibration_target instrument13 GroundStation17)
	(calibration_target instrument13 Star11)
	(calibration_target instrument13 GroundStation12)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation14)
	(supports instrument14 image2)
	(calibration_target instrument14 Star19)
	(calibration_target instrument14 GroundStation22)
	(calibration_target instrument14 GroundStation31)
	(calibration_target instrument14 Star3)
	(supports instrument15 thermograph4)
	(supports instrument15 infrared0)
	(supports instrument15 image2)
	(calibration_target instrument15 GroundStation17)
	(calibration_target instrument15 GroundStation30)
	(calibration_target instrument15 Star19)
	(calibration_target instrument15 Star2)
	(calibration_target instrument15 Star13)
	(calibration_target instrument15 Star18)
	(calibration_target instrument15 Star1)
	(calibration_target instrument15 Star27)
	(supports instrument16 image2)
	(supports instrument16 infrared1)
	(supports instrument16 infrared0)
	(calibration_target instrument16 Star8)
	(supports instrument17 spectrograph3)
	(supports instrument17 infrared1)
	(supports instrument17 infrared0)
	(calibration_target instrument17 GroundStation29)
	(calibration_target instrument17 GroundStation24)
	(calibration_target instrument17 Star0)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 GroundStation14)
	(calibration_target instrument17 Star32)
	(supports instrument18 spectrograph3)
	(calibration_target instrument18 GroundStation9)
	(calibration_target instrument18 Star8)
	(calibration_target instrument18 GroundStation17)
	(calibration_target instrument18 GroundStation12)
	(calibration_target instrument18 Star18)
	(calibration_target instrument18 GroundStation5)
	(calibration_target instrument18 GroundStation4)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation24)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 GroundStation25)
	(calibration_target instrument19 GroundStation14)
	(calibration_target instrument19 GroundStation22)
	(calibration_target instrument19 Star8)
	(calibration_target instrument19 GroundStation29)
	(calibration_target instrument19 GroundStation15)
	(calibration_target instrument19 Star2)
	(calibration_target instrument19 Star6)
	(calibration_target instrument19 GroundStation21)
	(supports instrument20 infrared0)
	(calibration_target instrument20 Star2)
	(calibration_target instrument20 GroundStation22)
	(calibration_target instrument20 Star13)
	(calibration_target instrument20 GroundStation15)
	(supports instrument21 infrared0)
	(supports instrument21 thermograph4)
	(supports instrument21 infrared1)
	(calibration_target instrument21 GroundStation14)
	(calibration_target instrument21 GroundStation30)
	(calibration_target instrument21 GroundStation24)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star19)
	(supports instrument22 infrared0)
	(supports instrument22 infrared1)
	(calibration_target instrument22 GroundStation16)
	(calibration_target instrument22 Star19)
	(calibration_target instrument22 Star6)
	(calibration_target instrument22 Star18)
	(calibration_target instrument22 Star26)
	(calibration_target instrument22 Star1)
	(calibration_target instrument22 Star0)
	(calibration_target instrument22 Star3)
	(calibration_target instrument22 GroundStation28)
	(supports instrument23 spectrograph3)
	(supports instrument23 infrared0)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 GroundStation12)
	(calibration_target instrument23 Star3)
	(calibration_target instrument23 GroundStation28)
	(calibration_target instrument23 GroundStation14)
	(calibration_target instrument23 GroundStation31)
	(calibration_target instrument23 Star13)
	(calibration_target instrument23 GroundStation5)
	(calibration_target instrument23 Star6)
	(supports instrument24 spectrograph3)
	(calibration_target instrument24 Star3)
	(calibration_target instrument24 GroundStation28)
	(supports instrument25 infrared1)
	(supports instrument25 spectrograph3)
	(calibration_target instrument25 Star18)
	(calibration_target instrument25 Star13)
	(supports instrument26 infrared0)
	(calibration_target instrument26 GroundStation28)
	(calibration_target instrument26 GroundStation16)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star13)
	(supports instrument27 infrared0)
	(calibration_target instrument27 Star11)
	(calibration_target instrument27 Star23)
	(supports instrument28 infrared0)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 GroundStation31)
	(calibration_target instrument28 Star26)
	(calibration_target instrument28 GroundStation30)
	(calibration_target instrument28 GroundStation24)
	(calibration_target instrument28 GroundStation25)
	(calibration_target instrument28 GroundStation28)
	(calibration_target instrument28 GroundStation5)
	(calibration_target instrument28 Star23)
	(calibration_target instrument28 Star7)
	(calibration_target instrument28 Star0)
	(on_board instrument27 satellite6)
	(on_board instrument28 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation25)
	(supports instrument29 thermograph4)
	(supports instrument29 infrared1)
	(supports instrument29 spectrograph3)
	(calibration_target instrument29 Star8)
	(calibration_target instrument29 GroundStation17)
	(calibration_target instrument29 Star26)
	(calibration_target instrument29 Star11)
	(calibration_target instrument29 Star27)
	(supports instrument30 thermograph4)
	(supports instrument30 spectrograph3)
	(supports instrument30 image2)
	(calibration_target instrument30 GroundStation29)
	(calibration_target instrument30 GroundStation20)
	(calibration_target instrument30 GroundStation17)
	(calibration_target instrument30 GroundStation31)
	(calibration_target instrument30 GroundStation10)
	(calibration_target instrument30 GroundStation22)
	(calibration_target instrument30 Star23)
	(supports instrument31 spectrograph3)
	(supports instrument31 infrared1)
	(supports instrument31 infrared0)
	(calibration_target instrument31 GroundStation9)
	(calibration_target instrument31 GroundStation14)
	(calibration_target instrument31 GroundStation12)
	(calibration_target instrument31 Star26)
	(calibration_target instrument31 Star0)
	(calibration_target instrument31 GroundStation5)
	(calibration_target instrument31 Star32)
	(calibration_target instrument31 GroundStation16)
	(on_board instrument29 satellite7)
	(on_board instrument30 satellite7)
	(on_board instrument31 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation29)
	(supports instrument32 image2)
	(calibration_target instrument32 GroundStation4)
	(calibration_target instrument32 Star0)
	(calibration_target instrument32 GroundStation29)
	(calibration_target instrument32 Star6)
	(supports instrument33 image2)
	(supports instrument33 infrared0)
	(calibration_target instrument33 GroundStation25)
	(calibration_target instrument33 Star32)
	(calibration_target instrument33 Star18)
	(calibration_target instrument33 GroundStation29)
	(calibration_target instrument33 GroundStation16)
	(calibration_target instrument33 Star2)
	(calibration_target instrument33 GroundStation22)
	(supports instrument34 thermograph4)
	(calibration_target instrument34 GroundStation30)
	(calibration_target instrument34 GroundStation5)
	(calibration_target instrument34 GroundStation12)
	(calibration_target instrument34 Star3)
	(calibration_target instrument34 Star27)
	(calibration_target instrument34 GroundStation22)
	(calibration_target instrument34 GroundStation9)
	(on_board instrument32 satellite8)
	(on_board instrument33 satellite8)
	(on_board instrument34 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star19)
	(supports instrument35 infrared0)
	(supports instrument35 infrared1)
	(supports instrument35 thermograph4)
	(calibration_target instrument35 GroundStation21)
	(calibration_target instrument35 Star8)
	(calibration_target instrument35 Star32)
	(calibration_target instrument35 GroundStation24)
	(calibration_target instrument35 GroundStation22)
	(calibration_target instrument35 GroundStation15)
	(calibration_target instrument35 GroundStation25)
	(calibration_target instrument35 GroundStation20)
	(supports instrument36 spectrograph3)
	(supports instrument36 image2)
	(calibration_target instrument36 GroundStation16)
	(supports instrument37 image2)
	(supports instrument37 infrared1)
	(calibration_target instrument37 Star18)
	(calibration_target instrument37 GroundStation25)
	(calibration_target instrument37 Star0)
	(calibration_target instrument37 GroundStation10)
	(calibration_target instrument37 Star6)
	(supports instrument38 spectrograph3)
	(calibration_target instrument38 GroundStation14)
	(calibration_target instrument38 Star27)
	(calibration_target instrument38 GroundStation10)
	(calibration_target instrument38 Star7)
	(calibration_target instrument38 GroundStation15)
	(calibration_target instrument38 Star26)
	(calibration_target instrument38 GroundStation9)
	(calibration_target instrument38 GroundStation5)
	(supports instrument39 spectrograph3)
	(supports instrument39 thermograph4)
	(calibration_target instrument39 GroundStation17)
	(calibration_target instrument39 GroundStation30)
	(calibration_target instrument39 Star26)
	(calibration_target instrument39 Star0)
	(calibration_target instrument39 Star7)
	(supports instrument40 infrared1)
	(supports instrument40 infrared0)
	(supports instrument40 spectrograph3)
	(calibration_target instrument40 Star0)
	(calibration_target instrument40 GroundStation28)
	(calibration_target instrument40 GroundStation30)
	(calibration_target instrument40 GroundStation22)
	(calibration_target instrument40 Star1)
	(calibration_target instrument40 GroundStation24)
	(supports instrument41 thermograph4)
	(calibration_target instrument41 Star18)
	(calibration_target instrument41 Star6)
	(supports instrument42 infrared0)
	(calibration_target instrument42 GroundStation9)
	(calibration_target instrument42 Star7)
	(calibration_target instrument42 GroundStation20)
	(supports instrument43 spectrograph3)
	(supports instrument43 infrared1)
	(calibration_target instrument43 GroundStation5)
	(calibration_target instrument43 GroundStation29)
	(calibration_target instrument43 Star6)
	(calibration_target instrument43 GroundStation10)
	(calibration_target instrument43 GroundStation17)
	(supports instrument44 infrared0)
	(calibration_target instrument44 GroundStation4)
	(calibration_target instrument44 Star19)
	(on_board instrument35 satellite9)
	(on_board instrument36 satellite9)
	(on_board instrument37 satellite9)
	(on_board instrument38 satellite9)
	(on_board instrument39 satellite9)
	(on_board instrument40 satellite9)
	(on_board instrument41 satellite9)
	(on_board instrument42 satellite9)
	(on_board instrument43 satellite9)
	(on_board instrument44 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star26)
)
(:goal (and
	(pointing satellite5 Star32)
	(pointing satellite7 GroundStation17)
	(pointing satellite9 GroundStation31)
	(have_image Planet34 spectrograph3)
))

)
