(define (problem pb9)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (on block1 block6) (clear block1) (on block2 block7) (on block3 block2) (ontable block4) (on block5 block4) (on block6 block3) (on block7 block9) (on block8 block5) (clear block8) (ontable block9) (handempty))
	(:goal (and (on block1 block5) (on block2 block6) (on block3 block8) (on block4 block3) (clear block4) (on block5 block7) (on block6 block9) (on block7 block2) (on block8 block1) (ontable block9))))