(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (on block1 block4) (on block2 block9) (on block3 block8) (clear block3) (ontable block4) (on block5 block2) (clear block5) (on block6 block1) (on block7 block6) (on block8 block7) (ontable block9) (handempty))
	(:goal (and (on block1 block8) (ontable block2) (ontable block3) (clear block3) (on block4 block7) (clear block4) (ontable block5) (on block6 block1) (clear block6) (ontable block7) (on block8 block5) (on block9 block2) (clear block9))))