(define (problem pb8)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (on block1 block2) (clear block1) (ontable block2) (ontable block3) (ontable block4) (clear block4) (on block5 block8) (clear block5) (ontable block6) (on block7 block3) (clear block7) (ontable block8) (on block9 block6) (clear block9) (handempty))
	(:goal (and (ontable block1) (on block2 block6) (on block3 block9) (on block4 block2) (clear block4) (ontable block5) (clear block5) (on block6 block8) (on block7 block3) (clear block7) (on block8 block1) (ontable block9))))