(define (problem pb0)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9)
	(:init (on block1 block5) (on block2 block7) (clear block2) (on block3 block4) (ontable block4) (on block5 block8) (on block6 block1) (on block7 block9) (on block8 block3) (on block9 block6) (handempty))
	(:goal (and (on block1 block2) (on block2 block4) (on block3 block9) (clear block3) (on block4 block7) (on block5 block1) (on block6 block5) (clear block6) (ontable block7) (ontable block8) (on block9 block8))))