(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (on block1 block6) (clear block1) (on block2 block5) (clear block2) (ontable block3) (clear block3) (ontable block4) (ontable block5) (on block6 block4) (handempty))
	(:goal (and (ontable block1) (ontable block2) (clear block2) (on block3 block5) (clear block3) (ontable block4) (on block5 block4) (on block6 block1) (clear block6))))