(define (problem pb9)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (ontable block1) (clear block1) (ontable block2) (clear block2) (on block3 block6) (on block4 block3) (on block5 block4) (clear block5) (ontable block6) (handempty))
	(:goal (and (on block1 block5) (ontable block2) (on block3 block1) (on block4 block2) (clear block4) (ontable block5) (on block6 block3) (clear block6))))