(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (ontable block1) (on block2 block1) (ontable block3) (clear block3) (on block4 block5) (on block5 block2) (on block6 block4) (clear block6) (handempty))
	(:goal (and (ontable block1) (ontable block2) (on block3 block1) (clear block3) (on block4 block5) (clear block4) (on block5 block2) (ontable block6) (clear block6))))