(define (problem pb8)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (on block1 block6) (clear block1) (ontable block2) (on block3 block2) (clear block3) (on block4 block5) (ontable block5) (on block6 block4) (handempty))
	(:goal (and (ontable block1) (ontable block2) (on block3 block1) (clear block3) (on block4 block2) (clear block4) (ontable block5) (on block6 block5) (clear block6))))