(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6)
	(:init (on block1 block6) (ontable block2) (on block3 block2) (clear block3) (on block4 block1) (clear block4) (ontable block5) (on block6 block5) (handempty))
	(:goal (and (on block1 block6) (on block2 block1) (clear block2) (ontable block3) (on block4 block3) (clear block4) (ontable block5) (clear block5) (ontable block6))))