(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (ontable block1) (on block2 block3) (ontable block3) (on block4 block7) (clear block4) (on block5 block6) (clear block5) (on block6 block1) (on block7 block10) (on block8 block2) (clear block8) (ontable block9) (on block10 block9) (handempty))
	(:goal (and (ontable block1) (clear block1) (on block2 block7) (on block3 block2) (on block4 block3) (on block5 block6) (clear block5) (on block6 block4) (on block7 block9) (ontable block8) (clear block8) (ontable block9) (ontable block10) (clear block10))))