(define (problem pb5)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (ontable block1) (clear block1) (on block2 block7) (on block3 block8) (ontable block4) (ontable block5) (on block6 block5) (on block7 block6) (on block8 block2) (on block9 block3) (clear block9) (on block10 block4) (clear block10) (handempty))
	(:goal (and (on block1 block5) (clear block1) (on block2 block3) (on block3 block6) (on block4 block7) (on block5 block8) (on block6 block10) (on block7 block9) (on block8 block4) (on block9 block2) (ontable block10))))