(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (ontable block1) (clear block1) (on block2 block5) (clear block2) (ontable block3) (on block4 block8) (on block5 block9) (on block6 block3) (clear block6) (ontable block7) (on block8 block7) (on block9 block10) (on block10 block4) (handempty))
	(:goal (and (on block1 block8) (on block2 block3) (clear block2) (on block3 block4) (ontable block4) (on block5 block7) (ontable block6) (ontable block7) (on block8 block6) (on block9 block1) (clear block9) (on block10 block5) (clear block10))))