(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (ontable block1) (clear block1) (on block2 block10) (clear block2) (on block3 block8) (clear block3) (ontable block4) (ontable block5) (clear block5) (on block6 block4) (ontable block7) (on block8 block9) (on block9 block7) (on block10 block6) (handempty))
	(:goal (and (on block1 block7) (on block2 block3) (ontable block3) (on block4 block2) (clear block4) (on block5 block9) (on block6 block5) (clear block6) (ontable block7) (on block8 block10) (clear block8) (ontable block9) (on block10 block1))))