(define (problem pb9)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10)
	(:init (on block1 block6) (on block2 block5) (on block3 block10) (clear block3) (on block4 block8) (clear block4) (ontable block5) (on block6 block7) (on block7 block9) (ontable block8) (on block9 block2) (on block10 block1) (handempty))
	(:goal (and (on block1 block6) (on block2 block3) (clear block2) (on block3 block7) (on block4 block8) (on block5 block9) (ontable block6) (on block7 block4) (on block8 block5) (on block9 block10) (on block10 block1))))