(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite3 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite4 - satellite
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	satellite6 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite7 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite8 - satellite
	instrument26 - instrument
	instrument27 - instrument
	satellite9 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	thermograph1 - mode
	thermograph4 - mode
	thermograph2 - mode
	thermograph0 - mode
	infrared3 - mode
	GroundStation0 - direction
	GroundStation11 - direction
	GroundStation12 - direction
	GroundStation5 - direction
	Star21 - direction
	Star18 - direction
	Star6 - direction
	GroundStation2 - direction
	Star9 - direction
	Star1 - direction
	GroundStation19 - direction
	GroundStation15 - direction
	Star22 - direction
	Star17 - direction
	Star16 - direction
	GroundStation27 - direction
	GroundStation23 - direction
	Star4 - direction
	GroundStation3 - direction
	GroundStation13 - direction
	GroundStation7 - direction
	GroundStation10 - direction
	GroundStation8 - direction
	GroundStation20 - direction
	Star24 - direction
	Star28 - direction
	GroundStation26 - direction
	Star25 - direction
	Star14 - direction
	Star29 - direction
	Star30 - direction
)
(:init
	(supports instrument0 thermograph4)
	(calibration_target instrument0 Star4)
	(calibration_target instrument0 GroundStation20)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star25)
	(supports instrument1 thermograph0)
	(supports instrument1 infrared3)
	(calibration_target instrument1 Star24)
	(supports instrument2 infrared3)
	(supports instrument2 thermograph4)
	(supports instrument2 thermograph1)
	(calibration_target instrument2 GroundStation19)
	(calibration_target instrument2 Star16)
	(calibration_target instrument2 Star28)
	(supports instrument3 thermograph1)
	(supports instrument3 thermograph2)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 GroundStation7)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 Star28)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 Star25)
	(calibration_target instrument4 GroundStation0)
	(calibration_target instrument4 Star28)
	(calibration_target instrument4 GroundStation26)
	(supports instrument5 thermograph1)
	(calibration_target instrument5 Star24)
	(calibration_target instrument5 GroundStation12)
	(calibration_target instrument5 Star4)
	(calibration_target instrument5 GroundStation20)
	(calibration_target instrument5 GroundStation15)
	(calibration_target instrument5 Star22)
	(calibration_target instrument5 Star16)
	(calibration_target instrument5 Star25)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star21)
	(calibration_target instrument6 GroundStation20)
	(calibration_target instrument6 GroundStation23)
	(calibration_target instrument6 GroundStation13)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation0)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 Star4)
	(calibration_target instrument7 GroundStation26)
	(calibration_target instrument7 GroundStation7)
	(calibration_target instrument7 GroundStation0)
	(calibration_target instrument7 Star24)
	(calibration_target instrument7 Star18)
	(calibration_target instrument7 Star25)
	(calibration_target instrument7 Star21)
	(supports instrument8 thermograph2)
	(supports instrument8 thermograph0)
	(supports instrument8 thermograph1)
	(calibration_target instrument8 GroundStation12)
	(calibration_target instrument8 GroundStation5)
	(calibration_target instrument8 GroundStation10)
	(calibration_target instrument8 GroundStation11)
	(supports instrument9 infrared3)
	(supports instrument9 thermograph1)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 GroundStation8)
	(calibration_target instrument9 Star16)
	(calibration_target instrument9 Star24)
	(calibration_target instrument9 GroundStation27)
	(calibration_target instrument9 GroundStation10)
	(calibration_target instrument9 Star28)
	(calibration_target instrument9 Star17)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star22)
	(supports instrument10 thermograph4)
	(supports instrument10 thermograph2)
	(calibration_target instrument10 Star25)
	(calibration_target instrument10 Star4)
	(calibration_target instrument10 Star16)
	(calibration_target instrument10 GroundStation13)
	(calibration_target instrument10 GroundStation11)
	(supports instrument11 thermograph2)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 Star18)
	(supports instrument12 thermograph1)
	(calibration_target instrument12 GroundStation13)
	(calibration_target instrument12 Star17)
	(calibration_target instrument12 GroundStation20)
	(calibration_target instrument12 Star22)
	(supports instrument13 thermograph1)
	(calibration_target instrument13 GroundStation10)
	(supports instrument14 thermograph4)
	(supports instrument14 thermograph2)
	(supports instrument14 thermograph0)
	(calibration_target instrument14 GroundStation7)
	(calibration_target instrument14 GroundStation8)
	(calibration_target instrument14 Star6)
	(calibration_target instrument14 GroundStation13)
	(calibration_target instrument14 GroundStation15)
	(calibration_target instrument14 Star18)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star1)
	(supports instrument15 infrared3)
	(calibration_target instrument15 Star21)
	(calibration_target instrument15 GroundStation23)
	(calibration_target instrument15 GroundStation10)
	(supports instrument16 thermograph1)
	(supports instrument16 infrared3)
	(calibration_target instrument16 GroundStation13)
	(calibration_target instrument16 GroundStation23)
	(calibration_target instrument16 Star22)
	(calibration_target instrument16 Star21)
	(calibration_target instrument16 Star18)
	(calibration_target instrument16 GroundStation8)
	(calibration_target instrument16 GroundStation26)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation23)
	(supports instrument17 thermograph1)
	(supports instrument17 infrared3)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 Star1)
	(calibration_target instrument17 Star6)
	(calibration_target instrument17 GroundStation3)
	(calibration_target instrument17 Star21)
	(calibration_target instrument17 GroundStation2)
	(calibration_target instrument17 GroundStation26)
	(calibration_target instrument17 Star18)
	(calibration_target instrument17 Star14)
	(on_board instrument17 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation0)
	(supports instrument18 thermograph0)
	(calibration_target instrument18 GroundStation26)
	(calibration_target instrument18 Star17)
	(calibration_target instrument18 GroundStation12)
	(calibration_target instrument18 GroundStation5)
	(supports instrument19 thermograph2)
	(calibration_target instrument19 GroundStation5)
	(supports instrument20 thermograph1)
	(supports instrument20 thermograph4)
	(supports instrument20 thermograph2)
	(calibration_target instrument20 Star17)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(on_board instrument20 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation20)
	(supports instrument21 thermograph4)
	(supports instrument21 thermograph1)
	(calibration_target instrument21 GroundStation10)
	(calibration_target instrument21 GroundStation15)
	(calibration_target instrument21 Star9)
	(calibration_target instrument21 Star14)
	(calibration_target instrument21 Star21)
	(calibration_target instrument21 Star24)
	(calibration_target instrument21 GroundStation20)
	(calibration_target instrument21 GroundStation19)
	(supports instrument22 thermograph1)
	(supports instrument22 thermograph4)
	(supports instrument22 thermograph0)
	(calibration_target instrument22 GroundStation26)
	(calibration_target instrument22 GroundStation13)
	(calibration_target instrument22 Star9)
	(supports instrument23 thermograph4)
	(supports instrument23 thermograph2)
	(calibration_target instrument23 GroundStation27)
	(calibration_target instrument23 GroundStation19)
	(calibration_target instrument23 GroundStation8)
	(supports instrument24 thermograph0)
	(calibration_target instrument24 GroundStation20)
	(calibration_target instrument24 Star1)
	(calibration_target instrument24 Star9)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 Star6)
	(calibration_target instrument24 Star18)
	(calibration_target instrument24 GroundStation23)
	(supports instrument25 thermograph0)
	(calibration_target instrument25 Star14)
	(calibration_target instrument25 Star25)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(on_board instrument23 satellite7)
	(on_board instrument24 satellite7)
	(on_board instrument25 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star21)
	(supports instrument26 infrared3)
	(supports instrument26 thermograph0)
	(calibration_target instrument26 GroundStation19)
	(calibration_target instrument26 GroundStation27)
	(calibration_target instrument26 GroundStation8)
	(supports instrument27 thermograph1)
	(supports instrument27 thermograph4)
	(calibration_target instrument27 Star17)
	(calibration_target instrument27 Star22)
	(calibration_target instrument27 GroundStation15)
	(on_board instrument26 satellite8)
	(on_board instrument27 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star1)
	(supports instrument28 thermograph1)
	(supports instrument28 thermograph2)
	(calibration_target instrument28 GroundStation13)
	(calibration_target instrument28 Star4)
	(calibration_target instrument28 GroundStation23)
	(calibration_target instrument28 GroundStation20)
	(calibration_target instrument28 GroundStation27)
	(calibration_target instrument28 Star16)
	(supports instrument29 thermograph2)
	(supports instrument29 thermograph4)
	(calibration_target instrument29 Star28)
	(calibration_target instrument29 Star24)
	(calibration_target instrument29 GroundStation20)
	(calibration_target instrument29 GroundStation8)
	(calibration_target instrument29 GroundStation10)
	(calibration_target instrument29 GroundStation7)
	(calibration_target instrument29 GroundStation13)
	(calibration_target instrument29 GroundStation3)
	(supports instrument30 infrared3)
	(supports instrument30 thermograph0)
	(calibration_target instrument30 Star14)
	(calibration_target instrument30 Star25)
	(calibration_target instrument30 GroundStation26)
	(on_board instrument28 satellite9)
	(on_board instrument29 satellite9)
	(on_board instrument30 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation3)
)
(:goal (and
	(pointing satellite0 GroundStation15)
	(pointing satellite3 Star16)
	(pointing satellite7 Star30)
	(have_image Star29 thermograph0)
	(have_image Star30 thermograph2)
))

)
