(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite2 - satellite
	instrument14 - instrument
	satellite3 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite4 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite5 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	satellite6 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	satellite7 - satellite
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	satellite8 - satellite
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	instrument61 - instrument
	satellite9 - satellite
	instrument62 - instrument
	instrument63 - instrument
	spectrograph3 - mode
	image2 - mode
	infrared4 - mode
	spectrograph0 - mode
	infrared1 - mode
	Star9 - direction
	Star5 - direction
	GroundStation6 - direction
	Star8 - direction
	Star2 - direction
	GroundStation1 - direction
	GroundStation3 - direction
	GroundStation10 - direction
	GroundStation0 - direction
	GroundStation4 - direction
	GroundStation7 - direction
	Star11 - direction
	Planet12 - direction
)
(:init
	(supports instrument0 spectrograph0)
	(supports instrument0 image2)
	(supports instrument0 spectrograph3)
	(calibration_target instrument0 GroundStation10)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 infrared4)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 image2)
	(calibration_target instrument2 GroundStation0)
	(calibration_target instrument2 GroundStation1)
	(supports instrument3 infrared4)
	(supports instrument3 spectrograph0)
	(supports instrument3 infrared1)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 spectrograph3)
	(supports instrument4 infrared1)
	(supports instrument4 infrared4)
	(calibration_target instrument4 Star2)
	(supports instrument5 image2)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 GroundStation3)
	(supports instrument6 infrared1)
	(supports instrument6 infrared4)
	(calibration_target instrument6 Star8)
	(calibration_target instrument6 GroundStation1)
	(calibration_target instrument6 GroundStation7)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 Star8)
	(calibration_target instrument7 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation3)
	(supports instrument8 infrared4)
	(supports instrument8 infrared1)
	(supports instrument8 spectrograph0)
	(calibration_target instrument8 GroundStation7)
	(calibration_target instrument8 GroundStation6)
	(calibration_target instrument8 Star9)
	(supports instrument9 spectrograph3)
	(supports instrument9 infrared1)
	(calibration_target instrument9 Star9)
	(calibration_target instrument9 Star2)
	(calibration_target instrument9 Star5)
	(supports instrument10 image2)
	(supports instrument10 spectrograph0)
	(supports instrument10 spectrograph3)
	(calibration_target instrument10 Star9)
	(supports instrument11 image2)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 Star8)
	(calibration_target instrument11 GroundStation6)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 GroundStation7)
	(calibration_target instrument12 Star9)
	(supports instrument13 image2)
	(supports instrument13 infrared1)
	(calibration_target instrument13 GroundStation7)
	(calibration_target instrument13 Star5)
	(calibration_target instrument13 Star2)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star5)
	(supports instrument14 infrared4)
	(supports instrument14 infrared1)
	(calibration_target instrument14 Star5)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 GroundStation3)
	(on_board instrument14 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation4)
	(supports instrument15 spectrograph3)
	(calibration_target instrument15 GroundStation7)
	(calibration_target instrument15 GroundStation1)
	(calibration_target instrument15 GroundStation0)
	(supports instrument16 infrared1)
	(supports instrument16 infrared4)
	(calibration_target instrument16 GroundStation4)
	(calibration_target instrument16 GroundStation7)
	(supports instrument17 spectrograph3)
	(supports instrument17 spectrograph0)
	(supports instrument17 image2)
	(calibration_target instrument17 GroundStation4)
	(supports instrument18 spectrograph0)
	(supports instrument18 infrared4)
	(calibration_target instrument18 GroundStation7)
	(calibration_target instrument18 GroundStation10)
	(supports instrument19 spectrograph0)
	(calibration_target instrument19 Star9)
	(calibration_target instrument19 GroundStation6)
	(calibration_target instrument19 Star2)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation7)
	(supports instrument20 infrared1)
	(supports instrument20 image2)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 Star8)
	(calibration_target instrument20 GroundStation10)
	(supports instrument21 spectrograph0)
	(supports instrument21 image2)
	(calibration_target instrument21 GroundStation7)
	(calibration_target instrument21 Star2)
	(supports instrument22 spectrograph3)
	(calibration_target instrument22 GroundStation4)
	(calibration_target instrument22 GroundStation10)
	(supports instrument23 spectrograph0)
	(supports instrument23 infrared4)
	(supports instrument23 infrared1)
	(calibration_target instrument23 Star2)
	(calibration_target instrument23 Star5)
	(supports instrument24 spectrograph3)
	(calibration_target instrument24 GroundStation1)
	(supports instrument25 spectrograph3)
	(calibration_target instrument25 GroundStation10)
	(calibration_target instrument25 GroundStation7)
	(supports instrument26 spectrograph3)
	(calibration_target instrument26 Star9)
	(calibration_target instrument26 GroundStation7)
	(supports instrument27 spectrograph3)
	(supports instrument27 infrared4)
	(calibration_target instrument27 Star5)
	(supports instrument28 image2)
	(supports instrument28 spectrograph0)
	(calibration_target instrument28 GroundStation1)
	(calibration_target instrument28 GroundStation0)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star9)
	(supports instrument29 spectrograph3)
	(supports instrument29 infrared1)
	(calibration_target instrument29 GroundStation4)
	(calibration_target instrument29 Star9)
	(supports instrument30 infrared1)
	(supports instrument30 image2)
	(calibration_target instrument30 Star2)
	(calibration_target instrument30 Star9)
	(supports instrument31 infrared4)
	(supports instrument31 spectrograph3)
	(calibration_target instrument31 GroundStation4)
	(supports instrument32 spectrograph3)
	(supports instrument32 infrared1)
	(supports instrument32 spectrograph0)
	(calibration_target instrument32 GroundStation3)
	(calibration_target instrument32 Star8)
	(supports instrument33 infrared4)
	(supports instrument33 image2)
	(supports instrument33 infrared1)
	(calibration_target instrument33 Star2)
	(calibration_target instrument33 Star5)
	(calibration_target instrument33 Star8)
	(supports instrument34 spectrograph3)
	(supports instrument34 infrared1)
	(supports instrument34 infrared4)
	(calibration_target instrument34 Star8)
	(supports instrument35 infrared1)
	(supports instrument35 spectrograph3)
	(calibration_target instrument35 GroundStation3)
	(calibration_target instrument35 Star9)
	(calibration_target instrument35 GroundStation4)
	(supports instrument36 spectrograph0)
	(supports instrument36 spectrograph3)
	(supports instrument36 infrared4)
	(calibration_target instrument36 Star2)
	(calibration_target instrument36 GroundStation3)
	(supports instrument37 image2)
	(calibration_target instrument37 GroundStation10)
	(calibration_target instrument37 Star8)
	(supports instrument38 infrared1)
	(supports instrument38 spectrograph0)
	(supports instrument38 image2)
	(calibration_target instrument38 GroundStation7)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation6)
	(supports instrument39 spectrograph0)
	(calibration_target instrument39 GroundStation10)
	(calibration_target instrument39 Star5)
	(calibration_target instrument39 GroundStation4)
	(supports instrument40 image2)
	(supports instrument40 infrared1)
	(supports instrument40 spectrograph3)
	(calibration_target instrument40 GroundStation1)
	(calibration_target instrument40 GroundStation4)
	(calibration_target instrument40 GroundStation6)
	(supports instrument41 infrared4)
	(supports instrument41 image2)
	(supports instrument41 spectrograph3)
	(calibration_target instrument41 GroundStation6)
	(supports instrument42 spectrograph3)
	(supports instrument42 infrared1)
	(calibration_target instrument42 GroundStation4)
	(supports instrument43 infrared1)
	(calibration_target instrument43 GroundStation7)
	(calibration_target instrument43 GroundStation3)
	(supports instrument44 image2)
	(supports instrument44 infrared1)
	(supports instrument44 infrared4)
	(calibration_target instrument44 GroundStation7)
	(supports instrument45 spectrograph0)
	(calibration_target instrument45 GroundStation4)
	(supports instrument46 infrared1)
	(calibration_target instrument46 Star9)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(on_board instrument46 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star11)
	(supports instrument47 infrared4)
	(calibration_target instrument47 GroundStation3)
	(supports instrument48 infrared4)
	(calibration_target instrument48 Star5)
	(calibration_target instrument48 GroundStation6)
	(supports instrument49 infrared4)
	(supports instrument49 image2)
	(calibration_target instrument49 Star5)
	(calibration_target instrument49 Star8)
	(calibration_target instrument49 GroundStation4)
	(supports instrument50 spectrograph3)
	(calibration_target instrument50 Star5)
	(calibration_target instrument50 GroundStation0)
	(calibration_target instrument50 GroundStation10)
	(supports instrument51 spectrograph3)
	(calibration_target instrument51 GroundStation0)
	(calibration_target instrument51 Star9)
	(calibration_target instrument51 GroundStation10)
	(supports instrument52 infrared4)
	(calibration_target instrument52 GroundStation10)
	(calibration_target instrument52 Star8)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet12)
	(supports instrument53 infrared4)
	(supports instrument53 spectrograph3)
	(calibration_target instrument53 Star2)
	(calibration_target instrument53 Star8)
	(supports instrument54 infrared4)
	(supports instrument54 image2)
	(supports instrument54 spectrograph3)
	(calibration_target instrument54 Star5)
	(supports instrument55 image2)
	(calibration_target instrument55 Star2)
	(calibration_target instrument55 GroundStation6)
	(supports instrument56 image2)
	(supports instrument56 spectrograph0)
	(calibration_target instrument56 Star2)
	(calibration_target instrument56 Star8)
	(calibration_target instrument56 GroundStation1)
	(supports instrument57 infrared4)
	(supports instrument57 image2)
	(supports instrument57 spectrograph0)
	(calibration_target instrument57 GroundStation1)
	(supports instrument58 image2)
	(calibration_target instrument58 GroundStation1)
	(calibration_target instrument58 Star2)
	(supports instrument59 infrared4)
	(calibration_target instrument59 GroundStation1)
	(supports instrument60 spectrograph0)
	(supports instrument60 spectrograph3)
	(calibration_target instrument60 GroundStation10)
	(supports instrument61 image2)
	(calibration_target instrument61 GroundStation4)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(on_board instrument60 satellite8)
	(on_board instrument61 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation6)
	(supports instrument62 image2)
	(supports instrument62 spectrograph0)
	(supports instrument62 infrared1)
	(calibration_target instrument62 GroundStation10)
	(calibration_target instrument62 GroundStation4)
	(calibration_target instrument62 GroundStation3)
	(supports instrument63 infrared1)
	(supports instrument63 spectrograph0)
	(supports instrument63 infrared4)
	(calibration_target instrument63 GroundStation7)
	(calibration_target instrument63 GroundStation4)
	(calibration_target instrument63 GroundStation0)
	(on_board instrument62 satellite9)
	(on_board instrument63 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation3)
)
(:goal (and
	(pointing satellite3 Star5)
	(pointing satellite5 Star11)
	(pointing satellite7 Star5)
	(pointing satellite8 Star9)
	(pointing satellite9 Star5)
	(have_image Star11 image2)
	(have_image Planet12 infrared1)
))

)
