(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite3 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite4 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite5 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	satellite6 - satellite
	instrument31 - instrument
	satellite7 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite8 - satellite
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	satellite9 - satellite
	instrument41 - instrument
	thermograph0 - mode
	infrared2 - mode
	image3 - mode
	infrared4 - mode
	image1 - mode
	GroundStation21 - direction
	GroundStation1 - direction
	Star15 - direction
	GroundStation13 - direction
	Star2 - direction
	Star9 - direction
	GroundStation5 - direction
	GroundStation19 - direction
	Star12 - direction
	GroundStation22 - direction
	GroundStation6 - direction
	GroundStation14 - direction
	Star18 - direction
	Star24 - direction
	Star11 - direction
	Star7 - direction
	GroundStation25 - direction
	Star10 - direction
	GroundStation0 - direction
	GroundStation17 - direction
	GroundStation4 - direction
	GroundStation23 - direction
	Star20 - direction
	Star16 - direction
	GroundStation3 - direction
	GroundStation8 - direction
	Star26 - direction
	Phenomenon27 - direction
)
(:init
	(supports instrument0 infrared2)
	(supports instrument0 image1)
	(supports instrument0 infrared4)
	(calibration_target instrument0 GroundStation6)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 Star24)
	(calibration_target instrument0 Star15)
	(supports instrument1 image1)
	(supports instrument1 image3)
	(supports instrument1 infrared2)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 Star24)
	(calibration_target instrument1 GroundStation13)
	(calibration_target instrument1 GroundStation25)
	(calibration_target instrument1 GroundStation23)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 GroundStation13)
	(calibration_target instrument2 GroundStation21)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 GroundStation13)
	(calibration_target instrument3 GroundStation14)
	(calibration_target instrument3 Star18)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 GroundStation17)
	(supports instrument4 image3)
	(supports instrument4 thermograph0)
	(supports instrument4 infrared2)
	(calibration_target instrument4 Star18)
	(calibration_target instrument4 GroundStation19)
	(calibration_target instrument4 Star7)
	(calibration_target instrument4 Star10)
	(calibration_target instrument4 Star15)
	(supports instrument5 thermograph0)
	(supports instrument5 image3)
	(supports instrument5 infrared2)
	(calibration_target instrument5 GroundStation22)
	(calibration_target instrument5 GroundStation8)
	(calibration_target instrument5 GroundStation14)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 GroundStation6)
	(supports instrument6 infrared2)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 GroundStation1)
	(calibration_target instrument6 GroundStation17)
	(calibration_target instrument6 GroundStation5)
	(calibration_target instrument6 GroundStation21)
	(supports instrument7 image3)
	(calibration_target instrument7 Star20)
	(calibration_target instrument7 GroundStation3)
	(calibration_target instrument7 GroundStation25)
	(calibration_target instrument7 Star16)
	(calibration_target instrument7 Star2)
	(calibration_target instrument7 GroundStation5)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star24)
	(supports instrument9 image1)
	(supports instrument9 infrared4)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 Star10)
	(calibration_target instrument9 GroundStation21)
	(calibration_target instrument9 GroundStation25)
	(calibration_target instrument9 GroundStation17)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation1)
	(supports instrument10 image1)
	(supports instrument10 infrared2)
	(calibration_target instrument10 GroundStation22)
	(calibration_target instrument10 GroundStation14)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 Star7)
	(calibration_target instrument10 Star20)
	(calibration_target instrument10 GroundStation8)
	(supports instrument11 infrared2)
	(supports instrument11 image3)
	(calibration_target instrument11 Star7)
	(supports instrument12 infrared2)
	(calibration_target instrument12 GroundStation5)
	(calibration_target instrument12 GroundStation1)
	(calibration_target instrument12 GroundStation3)
	(calibration_target instrument12 GroundStation13)
	(calibration_target instrument12 GroundStation14)
	(calibration_target instrument12 Star2)
	(calibration_target instrument12 Star16)
	(calibration_target instrument12 GroundStation6)
	(supports instrument13 thermograph0)
	(supports instrument13 image3)
	(supports instrument13 image1)
	(calibration_target instrument13 GroundStation19)
	(calibration_target instrument13 GroundStation23)
	(calibration_target instrument13 Star20)
	(calibration_target instrument13 GroundStation4)
	(calibration_target instrument13 Star24)
	(calibration_target instrument13 GroundStation25)
	(calibration_target instrument13 GroundStation5)
	(supports instrument14 thermograph0)
	(supports instrument14 infrared4)
	(calibration_target instrument14 Star24)
	(calibration_target instrument14 GroundStation23)
	(calibration_target instrument14 GroundStation6)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star11)
	(supports instrument15 infrared2)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 GroundStation21)
	(calibration_target instrument15 Star15)
	(calibration_target instrument15 GroundStation19)
	(calibration_target instrument15 GroundStation25)
	(calibration_target instrument15 Star16)
	(calibration_target instrument15 GroundStation5)
	(calibration_target instrument15 Star9)
	(calibration_target instrument15 Star18)
	(supports instrument16 image1)
	(supports instrument16 infrared4)
	(calibration_target instrument16 GroundStation6)
	(supports instrument17 image3)
	(calibration_target instrument17 GroundStation22)
	(calibration_target instrument17 GroundStation14)
	(calibration_target instrument17 Star7)
	(calibration_target instrument17 GroundStation3)
	(calibration_target instrument17 GroundStation17)
	(calibration_target instrument17 Star10)
	(calibration_target instrument17 Star9)
	(calibration_target instrument17 GroundStation1)
	(supports instrument18 image1)
	(supports instrument18 image3)
	(supports instrument18 infrared4)
	(calibration_target instrument18 Star24)
	(calibration_target instrument18 GroundStation21)
	(calibration_target instrument18 GroundStation6)
	(calibration_target instrument18 GroundStation3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star7)
	(supports instrument19 thermograph0)
	(calibration_target instrument19 Star11)
	(calibration_target instrument19 Star9)
	(supports instrument20 thermograph0)
	(calibration_target instrument20 GroundStation13)
	(calibration_target instrument20 GroundStation3)
	(calibration_target instrument20 GroundStation23)
	(calibration_target instrument20 Star11)
	(calibration_target instrument20 GroundStation14)
	(supports instrument21 image1)
	(supports instrument21 thermograph0)
	(supports instrument21 image3)
	(calibration_target instrument21 GroundStation17)
	(calibration_target instrument21 Star2)
	(calibration_target instrument21 Star10)
	(calibration_target instrument21 GroundStation1)
	(calibration_target instrument21 Star24)
	(calibration_target instrument21 Star18)
	(calibration_target instrument21 GroundStation22)
	(calibration_target instrument21 GroundStation3)
	(supports instrument22 infrared2)
	(supports instrument22 infrared4)
	(supports instrument22 image1)
	(calibration_target instrument22 Star2)
	(calibration_target instrument22 Star12)
	(calibration_target instrument22 Star16)
	(calibration_target instrument22 Star7)
	(calibration_target instrument22 GroundStation25)
	(calibration_target instrument22 GroundStation5)
	(calibration_target instrument22 GroundStation17)
	(supports instrument23 infrared4)
	(supports instrument23 infrared2)
	(supports instrument23 image1)
	(calibration_target instrument23 Star11)
	(supports instrument24 infrared2)
	(supports instrument24 infrared4)
	(calibration_target instrument24 Star10)
	(calibration_target instrument24 GroundStation17)
	(calibration_target instrument24 Star12)
	(calibration_target instrument24 Star7)
	(calibration_target instrument24 GroundStation14)
	(calibration_target instrument24 GroundStation1)
	(calibration_target instrument24 GroundStation5)
	(supports instrument25 infrared2)
	(calibration_target instrument25 GroundStation25)
	(calibration_target instrument25 Star9)
	(calibration_target instrument25 GroundStation14)
	(calibration_target instrument25 Star24)
	(calibration_target instrument25 GroundStation0)
	(supports instrument26 infrared4)
	(supports instrument26 infrared2)
	(calibration_target instrument26 Star18)
	(calibration_target instrument26 Star11)
	(calibration_target instrument26 Star15)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star10)
	(supports instrument27 image1)
	(calibration_target instrument27 Star10)
	(calibration_target instrument27 GroundStation4)
	(calibration_target instrument27 GroundStation0)
	(supports instrument28 image3)
	(calibration_target instrument28 GroundStation19)
	(calibration_target instrument28 Star10)
	(calibration_target instrument28 GroundStation22)
	(calibration_target instrument28 Star11)
	(calibration_target instrument28 GroundStation25)
	(calibration_target instrument28 Star12)
	(calibration_target instrument28 GroundStation13)
	(supports instrument29 image3)
	(supports instrument29 image1)
	(supports instrument29 infrared4)
	(calibration_target instrument29 GroundStation19)
	(calibration_target instrument29 Star2)
	(supports instrument30 thermograph0)
	(supports instrument30 infrared2)
	(calibration_target instrument30 Star10)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star2)
	(supports instrument31 image1)
	(supports instrument31 image3)
	(calibration_target instrument31 GroundStation19)
	(calibration_target instrument31 Star18)
	(calibration_target instrument31 GroundStation23)
	(calibration_target instrument31 Star9)
	(on_board instrument31 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation4)
	(supports instrument32 image1)
	(calibration_target instrument32 GroundStation3)
	(calibration_target instrument32 GroundStation5)
	(calibration_target instrument32 GroundStation22)
	(calibration_target instrument32 Star10)
	(calibration_target instrument32 GroundStation0)
	(supports instrument33 infrared2)
	(calibration_target instrument33 GroundStation5)
	(calibration_target instrument33 GroundStation0)
	(calibration_target instrument33 GroundStation3)
	(calibration_target instrument33 GroundStation4)
	(calibration_target instrument33 Star16)
	(calibration_target instrument33 GroundStation19)
	(calibration_target instrument33 Star18)
	(supports instrument34 infrared2)
	(calibration_target instrument34 Star18)
	(calibration_target instrument34 GroundStation0)
	(calibration_target instrument34 GroundStation22)
	(calibration_target instrument34 Star12)
	(calibration_target instrument34 GroundStation19)
	(supports instrument35 infrared2)
	(supports instrument35 image3)
	(supports instrument35 image1)
	(calibration_target instrument35 GroundStation25)
	(calibration_target instrument35 GroundStation3)
	(calibration_target instrument35 GroundStation14)
	(calibration_target instrument35 Star16)
	(calibration_target instrument35 GroundStation23)
	(calibration_target instrument35 Star7)
	(calibration_target instrument35 GroundStation6)
	(supports instrument36 infrared2)
	(calibration_target instrument36 GroundStation8)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation4)
	(supports instrument37 infrared2)
	(supports instrument37 image3)
	(calibration_target instrument37 Star18)
	(supports instrument38 infrared4)
	(supports instrument38 thermograph0)
	(supports instrument38 image3)
	(calibration_target instrument38 Star24)
	(calibration_target instrument38 GroundStation23)
	(calibration_target instrument38 Star20)
	(supports instrument39 image1)
	(supports instrument39 image3)
	(calibration_target instrument39 Star11)
	(calibration_target instrument39 GroundStation4)
	(calibration_target instrument39 GroundStation17)
	(supports instrument40 infrared4)
	(supports instrument40 infrared2)
	(supports instrument40 thermograph0)
	(calibration_target instrument40 GroundStation23)
	(calibration_target instrument40 GroundStation4)
	(calibration_target instrument40 GroundStation17)
	(calibration_target instrument40 GroundStation0)
	(calibration_target instrument40 Star10)
	(calibration_target instrument40 GroundStation25)
	(calibration_target instrument40 Star7)
	(on_board instrument37 satellite8)
	(on_board instrument38 satellite8)
	(on_board instrument39 satellite8)
	(on_board instrument40 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation23)
	(supports instrument41 image1)
	(supports instrument41 infrared4)
	(supports instrument41 image3)
	(calibration_target instrument41 GroundStation8)
	(calibration_target instrument41 GroundStation3)
	(calibration_target instrument41 Star16)
	(calibration_target instrument41 Star20)
	(on_board instrument41 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star9)
)
(:goal (and
	(pointing satellite0 Star26)
	(pointing satellite1 GroundStation4)
	(pointing satellite3 Star16)
	(pointing satellite5 Star26)
	(pointing satellite7 GroundStation6)
	(pointing satellite8 GroundStation8)
	(have_image Star26 image3)
	(have_image Phenomenon27 image3)
))

)
