(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite2 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite4 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite5 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite6 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	satellite7 - satellite
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	satellite8 - satellite
	instrument61 - instrument
	satellite9 - satellite
	instrument62 - instrument
	instrument63 - instrument
	instrument64 - instrument
	instrument65 - instrument
	instrument66 - instrument
	instrument67 - instrument
	instrument68 - instrument
	instrument69 - instrument
	instrument70 - instrument
	instrument71 - instrument
	thermograph2 - mode
	image0 - mode
	infrared3 - mode
	infrared1 - mode
	infrared4 - mode
	Star0 - direction
	Phenomenon1 - direction
	Phenomenon2 - direction
)
(:init
	(supports instrument0 infrared1)
	(calibration_target instrument0 Star0)
	(supports instrument1 infrared1)
	(calibration_target instrument1 Star0)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 Star0)
	(supports instrument3 thermograph2)
	(calibration_target instrument3 Star0)
	(supports instrument4 image0)
	(supports instrument4 infrared3)
	(calibration_target instrument4 Star0)
	(supports instrument5 thermograph2)
	(supports instrument5 infrared1)
	(calibration_target instrument5 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon2)
	(supports instrument6 image0)
	(calibration_target instrument6 Star0)
	(supports instrument7 infrared1)
	(supports instrument7 image0)
	(calibration_target instrument7 Star0)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 Star0)
	(supports instrument9 infrared4)
	(supports instrument9 infrared1)
	(calibration_target instrument9 Star0)
	(supports instrument10 infrared3)
	(supports instrument10 infrared1)
	(supports instrument10 infrared4)
	(calibration_target instrument10 Star0)
	(supports instrument11 infrared4)
	(supports instrument11 thermograph2)
	(supports instrument11 image0)
	(calibration_target instrument11 Star0)
	(supports instrument12 infrared4)
	(supports instrument12 infrared1)
	(supports instrument12 image0)
	(calibration_target instrument12 Star0)
	(supports instrument13 infrared1)
	(supports instrument13 infrared4)
	(calibration_target instrument13 Star0)
	(supports instrument14 infrared1)
	(calibration_target instrument14 Star0)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument15 thermograph2)
	(supports instrument15 infrared4)
	(calibration_target instrument15 Star0)
	(supports instrument16 infrared1)
	(supports instrument16 infrared4)
	(supports instrument16 infrared3)
	(calibration_target instrument16 Star0)
	(supports instrument17 thermograph2)
	(supports instrument17 infrared3)
	(supports instrument17 image0)
	(calibration_target instrument17 Star0)
	(supports instrument18 image0)
	(supports instrument18 thermograph2)
	(calibration_target instrument18 Star0)
	(supports instrument19 thermograph2)
	(calibration_target instrument19 Star0)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon1)
	(supports instrument20 thermograph2)
	(supports instrument20 infrared4)
	(calibration_target instrument20 Star0)
	(supports instrument21 infrared1)
	(supports instrument21 infrared3)
	(supports instrument21 thermograph2)
	(calibration_target instrument21 Star0)
	(supports instrument22 infrared1)
	(supports instrument22 infrared4)
	(supports instrument22 image0)
	(calibration_target instrument22 Star0)
	(supports instrument23 infrared4)
	(supports instrument23 thermograph2)
	(calibration_target instrument23 Star0)
	(supports instrument24 image0)
	(calibration_target instrument24 Star0)
	(supports instrument25 thermograph2)
	(calibration_target instrument25 Star0)
	(supports instrument26 image0)
	(calibration_target instrument26 Star0)
	(supports instrument27 thermograph2)
	(supports instrument27 infrared3)
	(supports instrument27 image0)
	(calibration_target instrument27 Star0)
	(supports instrument28 infrared1)
	(supports instrument28 infrared4)
	(calibration_target instrument28 Star0)
	(supports instrument29 infrared1)
	(supports instrument29 infrared4)
	(calibration_target instrument29 Star0)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon1)
	(supports instrument30 image0)
	(calibration_target instrument30 Star0)
	(supports instrument31 infrared4)
	(supports instrument31 infrared1)
	(supports instrument31 image0)
	(calibration_target instrument31 Star0)
	(supports instrument32 thermograph2)
	(supports instrument32 infrared4)
	(calibration_target instrument32 Star0)
	(supports instrument33 infrared4)
	(supports instrument33 infrared3)
	(supports instrument33 infrared1)
	(calibration_target instrument33 Star0)
	(supports instrument34 infrared4)
	(supports instrument34 image0)
	(calibration_target instrument34 Star0)
	(supports instrument35 infrared1)
	(supports instrument35 infrared4)
	(calibration_target instrument35 Star0)
	(supports instrument36 infrared4)
	(supports instrument36 image0)
	(supports instrument36 infrared1)
	(calibration_target instrument36 Star0)
	(supports instrument37 thermograph2)
	(calibration_target instrument37 Star0)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(on_board instrument37 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument38 thermograph2)
	(calibration_target instrument38 Star0)
	(supports instrument39 infrared1)
	(supports instrument39 infrared4)
	(supports instrument39 thermograph2)
	(calibration_target instrument39 Star0)
	(supports instrument40 image0)
	(calibration_target instrument40 Star0)
	(supports instrument41 infrared4)
	(supports instrument41 infrared3)
	(calibration_target instrument41 Star0)
	(supports instrument42 infrared1)
	(supports instrument42 infrared4)
	(supports instrument42 thermograph2)
	(calibration_target instrument42 Star0)
	(supports instrument43 infrared1)
	(supports instrument43 image0)
	(supports instrument43 infrared4)
	(calibration_target instrument43 Star0)
	(supports instrument44 infrared1)
	(supports instrument44 thermograph2)
	(supports instrument44 infrared3)
	(calibration_target instrument44 Star0)
	(supports instrument45 infrared4)
	(supports instrument45 infrared3)
	(calibration_target instrument45 Star0)
	(supports instrument46 infrared4)
	(supports instrument46 thermograph2)
	(supports instrument46 image0)
	(calibration_target instrument46 Star0)
	(supports instrument47 thermograph2)
	(calibration_target instrument47 Star0)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(on_board instrument41 satellite5)
	(on_board instrument42 satellite5)
	(on_board instrument43 satellite5)
	(on_board instrument44 satellite5)
	(on_board instrument45 satellite5)
	(on_board instrument46 satellite5)
	(on_board instrument47 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon2)
	(supports instrument48 infrared1)
	(supports instrument48 thermograph2)
	(supports instrument48 infrared3)
	(calibration_target instrument48 Star0)
	(supports instrument49 infrared1)
	(calibration_target instrument49 Star0)
	(supports instrument50 infrared3)
	(calibration_target instrument50 Star0)
	(supports instrument51 thermograph2)
	(calibration_target instrument51 Star0)
	(supports instrument52 image0)
	(supports instrument52 infrared4)
	(calibration_target instrument52 Star0)
	(supports instrument53 image0)
	(supports instrument53 infrared4)
	(supports instrument53 thermograph2)
	(calibration_target instrument53 Star0)
	(supports instrument54 infrared1)
	(calibration_target instrument54 Star0)
	(supports instrument55 image0)
	(supports instrument55 infrared1)
	(supports instrument55 infrared3)
	(calibration_target instrument55 Star0)
	(on_board instrument48 satellite6)
	(on_board instrument49 satellite6)
	(on_board instrument50 satellite6)
	(on_board instrument51 satellite6)
	(on_board instrument52 satellite6)
	(on_board instrument53 satellite6)
	(on_board instrument54 satellite6)
	(on_board instrument55 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon2)
	(supports instrument56 infrared3)
	(calibration_target instrument56 Star0)
	(supports instrument57 infrared4)
	(supports instrument57 infrared1)
	(calibration_target instrument57 Star0)
	(supports instrument58 image0)
	(calibration_target instrument58 Star0)
	(supports instrument59 infrared3)
	(supports instrument59 infrared1)
	(calibration_target instrument59 Star0)
	(supports instrument60 thermograph2)
	(calibration_target instrument60 Star0)
	(on_board instrument56 satellite7)
	(on_board instrument57 satellite7)
	(on_board instrument58 satellite7)
	(on_board instrument59 satellite7)
	(on_board instrument60 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon1)
	(supports instrument61 infrared1)
	(supports instrument61 infrared3)
	(supports instrument61 infrared4)
	(calibration_target instrument61 Star0)
	(on_board instrument61 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star0)
	(supports instrument62 infrared3)
	(supports instrument62 image0)
	(supports instrument62 thermograph2)
	(calibration_target instrument62 Star0)
	(supports instrument63 image0)
	(supports instrument63 infrared4)
	(calibration_target instrument63 Star0)
	(supports instrument64 infrared3)
	(calibration_target instrument64 Star0)
	(supports instrument65 image0)
	(calibration_target instrument65 Star0)
	(supports instrument66 infrared1)
	(supports instrument66 infrared4)
	(supports instrument66 image0)
	(calibration_target instrument66 Star0)
	(supports instrument67 infrared3)
	(supports instrument67 infrared1)
	(supports instrument67 infrared4)
	(calibration_target instrument67 Star0)
	(supports instrument68 infrared3)
	(supports instrument68 infrared1)
	(supports instrument68 infrared4)
	(calibration_target instrument68 Star0)
	(supports instrument69 infrared1)
	(supports instrument69 image0)
	(calibration_target instrument69 Star0)
	(supports instrument70 infrared3)
	(supports instrument70 image0)
	(calibration_target instrument70 Star0)
	(supports instrument71 infrared4)
	(supports instrument71 infrared1)
	(calibration_target instrument71 Star0)
	(on_board instrument62 satellite9)
	(on_board instrument63 satellite9)
	(on_board instrument64 satellite9)
	(on_board instrument65 satellite9)
	(on_board instrument66 satellite9)
	(on_board instrument67 satellite9)
	(on_board instrument68 satellite9)
	(on_board instrument69 satellite9)
	(on_board instrument70 satellite9)
	(on_board instrument71 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star0)
)
(:goal (and
	(pointing satellite1 Phenomenon2)
	(pointing satellite3 Phenomenon1)
	(pointing satellite9 Phenomenon2)
	(have_image Phenomenon1 infrared1)
	(have_image Phenomenon2 image0)
))

)
