(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite1 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite2 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite3 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite4 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite5 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite6 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite7 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	satellite8 - satellite
	instrument41 - instrument
	instrument42 - instrument
	satellite9 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	infrared2 - mode
	infrared3 - mode
	infrared4 - mode
	image0 - mode
	image1 - mode
	GroundStation0 - direction
	Star1 - direction
	Star2 - direction
)
(:init
	(supports instrument0 infrared2)
	(supports instrument0 infrared3)
	(supports instrument0 image0)
	(calibration_target instrument0 GroundStation0)
	(supports instrument1 image1)
	(supports instrument1 infrared4)
	(calibration_target instrument1 GroundStation0)
	(supports instrument2 infrared3)
	(supports instrument2 image0)
	(supports instrument2 image1)
	(calibration_target instrument2 GroundStation0)
	(supports instrument3 infrared3)
	(supports instrument3 infrared4)
	(supports instrument3 image1)
	(calibration_target instrument3 GroundStation0)
	(supports instrument4 image1)
	(supports instrument4 infrared2)
	(calibration_target instrument4 GroundStation0)
	(supports instrument5 image0)
	(supports instrument5 image1)
	(calibration_target instrument5 GroundStation0)
	(supports instrument6 image0)
	(calibration_target instrument6 GroundStation0)
	(supports instrument7 infrared2)
	(supports instrument7 image1)
	(supports instrument7 infrared3)
	(calibration_target instrument7 GroundStation0)
	(supports instrument8 infrared2)
	(calibration_target instrument8 GroundStation0)
	(supports instrument9 infrared3)
	(calibration_target instrument9 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(on_board instrument9 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation0)
	(supports instrument10 infrared4)
	(supports instrument10 image1)
	(supports instrument10 infrared3)
	(calibration_target instrument10 GroundStation0)
	(supports instrument11 infrared4)
	(supports instrument11 image0)
	(supports instrument11 infrared3)
	(calibration_target instrument11 GroundStation0)
	(supports instrument12 infrared2)
	(supports instrument12 image0)
	(calibration_target instrument12 GroundStation0)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star2)
	(supports instrument13 infrared2)
	(supports instrument13 image1)
	(calibration_target instrument13 GroundStation0)
	(supports instrument14 image0)
	(calibration_target instrument14 GroundStation0)
	(supports instrument15 infrared2)
	(calibration_target instrument15 GroundStation0)
	(supports instrument16 infrared2)
	(calibration_target instrument16 GroundStation0)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star2)
	(supports instrument17 infrared3)
	(supports instrument17 infrared4)
	(calibration_target instrument17 GroundStation0)
	(supports instrument18 infrared4)
	(calibration_target instrument18 GroundStation0)
	(supports instrument19 image1)
	(supports instrument19 image0)
	(calibration_target instrument19 GroundStation0)
	(supports instrument20 image1)
	(calibration_target instrument20 GroundStation0)
	(supports instrument21 infrared4)
	(supports instrument21 image1)
	(supports instrument21 infrared3)
	(calibration_target instrument21 GroundStation0)
	(supports instrument22 image1)
	(supports instrument22 infrared4)
	(calibration_target instrument22 GroundStation0)
	(supports instrument23 image1)
	(supports instrument23 infrared2)
	(supports instrument23 infrared3)
	(calibration_target instrument23 GroundStation0)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star2)
	(supports instrument24 image0)
	(calibration_target instrument24 GroundStation0)
	(supports instrument25 infrared3)
	(supports instrument25 infrared4)
	(supports instrument25 infrared2)
	(calibration_target instrument25 GroundStation0)
	(supports instrument26 infrared4)
	(calibration_target instrument26 GroundStation0)
	(supports instrument27 infrared3)
	(calibration_target instrument27 GroundStation0)
	(supports instrument28 image1)
	(supports instrument28 infrared4)
	(calibration_target instrument28 GroundStation0)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star2)
	(supports instrument29 infrared4)
	(supports instrument29 infrared3)
	(calibration_target instrument29 GroundStation0)
	(supports instrument30 image1)
	(calibration_target instrument30 GroundStation0)
	(supports instrument31 infrared3)
	(supports instrument31 image0)
	(supports instrument31 infrared4)
	(calibration_target instrument31 GroundStation0)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star1)
	(supports instrument32 image0)
	(supports instrument32 infrared2)
	(supports instrument32 infrared4)
	(calibration_target instrument32 GroundStation0)
	(supports instrument33 image0)
	(calibration_target instrument33 GroundStation0)
	(supports instrument34 infrared4)
	(supports instrument34 image0)
	(supports instrument34 infrared3)
	(calibration_target instrument34 GroundStation0)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star2)
	(supports instrument35 infrared2)
	(calibration_target instrument35 GroundStation0)
	(supports instrument36 infrared2)
	(supports instrument36 image0)
	(supports instrument36 image1)
	(calibration_target instrument36 GroundStation0)
	(supports instrument37 image0)
	(supports instrument37 infrared4)
	(supports instrument37 infrared2)
	(calibration_target instrument37 GroundStation0)
	(supports instrument38 infrared4)
	(supports instrument38 image0)
	(calibration_target instrument38 GroundStation0)
	(supports instrument39 image0)
	(supports instrument39 image1)
	(supports instrument39 infrared2)
	(calibration_target instrument39 GroundStation0)
	(supports instrument40 image1)
	(calibration_target instrument40 GroundStation0)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star1)
	(supports instrument41 image0)
	(supports instrument41 image1)
	(supports instrument41 infrared4)
	(calibration_target instrument41 GroundStation0)
	(supports instrument42 image0)
	(supports instrument42 infrared2)
	(calibration_target instrument42 GroundStation0)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation0)
	(supports instrument43 infrared2)
	(calibration_target instrument43 GroundStation0)
	(supports instrument44 infrared4)
	(supports instrument44 infrared3)
	(calibration_target instrument44 GroundStation0)
	(supports instrument45 image0)
	(supports instrument45 image1)
	(calibration_target instrument45 GroundStation0)
	(supports instrument46 image1)
	(calibration_target instrument46 GroundStation0)
	(on_board instrument43 satellite9)
	(on_board instrument44 satellite9)
	(on_board instrument45 satellite9)
	(on_board instrument46 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation0)
)
(:goal (and
	(pointing satellite1 Star1)
	(pointing satellite2 Star1)
	(pointing satellite3 Star1)
	(pointing satellite6 GroundStation0)
	(pointing satellite8 Star1)
	(have_image Star1 image0)
	(have_image Star2 infrared2)
))

)
