(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite2 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite4 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite5 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite6 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	satellite7 - satellite
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	satellite8 - satellite
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	satellite9 - satellite
	instrument60 - instrument
	infrared3 - mode
	spectrograph0 - mode
	spectrograph2 - mode
	thermograph4 - mode
	spectrograph1 - mode
	Star0 - direction
	Star1 - direction
	GroundStation2 - direction
	GroundStation4 - direction
	GroundStation3 - direction
	Planet5 - direction
	Phenomenon6 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 GroundStation4)
	(supports instrument1 infrared3)
	(calibration_target instrument1 Star0)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 Star0)
	(supports instrument3 infrared3)
	(calibration_target instrument3 Star0)
	(supports instrument4 spectrograph0)
	(calibration_target instrument4 Star1)
	(supports instrument5 infrared3)
	(calibration_target instrument5 GroundStation3)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star1)
	(supports instrument7 spectrograph1)
	(supports instrument7 infrared3)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 GroundStation4)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 GroundStation3)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 GroundStation4)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 Star1)
	(supports instrument11 infrared3)
	(supports instrument11 thermograph4)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 GroundStation2)
	(supports instrument12 infrared3)
	(supports instrument12 spectrograph1)
	(calibration_target instrument12 GroundStation4)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 Star1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation3)
	(supports instrument14 spectrograph2)
	(supports instrument14 infrared3)
	(supports instrument14 spectrograph0)
	(calibration_target instrument14 Star0)
	(supports instrument15 spectrograph2)
	(supports instrument15 thermograph4)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 GroundStation2)
	(supports instrument16 spectrograph0)
	(supports instrument16 spectrograph2)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 GroundStation4)
	(supports instrument17 spectrograph2)
	(supports instrument17 spectrograph1)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 GroundStation2)
	(supports instrument18 spectrograph1)
	(supports instrument18 thermograph4)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 Star1)
	(supports instrument19 spectrograph0)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 Star0)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star1)
	(supports instrument20 spectrograph0)
	(supports instrument20 spectrograph1)
	(calibration_target instrument20 Star1)
	(supports instrument21 infrared3)
	(calibration_target instrument21 GroundStation3)
	(supports instrument22 spectrograph0)
	(supports instrument22 infrared3)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 GroundStation2)
	(supports instrument23 infrared3)
	(calibration_target instrument23 Star0)
	(supports instrument24 infrared3)
	(supports instrument24 spectrograph1)
	(supports instrument24 spectrograph2)
	(calibration_target instrument24 GroundStation2)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation4)
	(supports instrument25 spectrograph1)
	(calibration_target instrument25 GroundStation4)
	(supports instrument26 spectrograph1)
	(supports instrument26 spectrograph2)
	(supports instrument26 spectrograph0)
	(calibration_target instrument26 GroundStation4)
	(supports instrument27 spectrograph2)
	(supports instrument27 spectrograph1)
	(calibration_target instrument27 GroundStation4)
	(supports instrument28 infrared3)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 Star1)
	(supports instrument29 spectrograph1)
	(supports instrument29 spectrograph0)
	(supports instrument29 thermograph4)
	(calibration_target instrument29 GroundStation4)
	(supports instrument30 infrared3)
	(supports instrument30 spectrograph0)
	(calibration_target instrument30 GroundStation3)
	(supports instrument31 infrared3)
	(supports instrument31 spectrograph2)
	(calibration_target instrument31 GroundStation3)
	(supports instrument32 spectrograph2)
	(supports instrument32 infrared3)
	(calibration_target instrument32 Star1)
	(supports instrument33 infrared3)
	(supports instrument33 spectrograph2)
	(supports instrument33 spectrograph0)
	(calibration_target instrument33 Star1)
	(supports instrument34 thermograph4)
	(calibration_target instrument34 GroundStation4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet5)
	(supports instrument35 spectrograph1)
	(supports instrument35 thermograph4)
	(calibration_target instrument35 Star0)
	(supports instrument36 thermograph4)
	(supports instrument36 infrared3)
	(supports instrument36 spectrograph0)
	(calibration_target instrument36 GroundStation2)
	(supports instrument37 thermograph4)
	(calibration_target instrument37 GroundStation2)
	(supports instrument38 spectrograph2)
	(calibration_target instrument38 Star1)
	(supports instrument39 spectrograph1)
	(supports instrument39 spectrograph0)
	(calibration_target instrument39 Star0)
	(supports instrument40 thermograph4)
	(supports instrument40 spectrograph1)
	(supports instrument40 spectrograph0)
	(calibration_target instrument40 GroundStation4)
	(supports instrument41 spectrograph2)
	(calibration_target instrument41 Star0)
	(supports instrument42 spectrograph2)
	(supports instrument42 thermograph4)
	(supports instrument42 spectrograph1)
	(calibration_target instrument42 GroundStation3)
	(supports instrument43 spectrograph0)
	(supports instrument43 spectrograph2)
	(calibration_target instrument43 Star0)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(on_board instrument41 satellite5)
	(on_board instrument42 satellite5)
	(on_board instrument43 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon6)
	(supports instrument44 spectrograph0)
	(supports instrument44 spectrograph1)
	(calibration_target instrument44 Star1)
	(supports instrument45 spectrograph2)
	(supports instrument45 infrared3)
	(supports instrument45 spectrograph1)
	(calibration_target instrument45 GroundStation4)
	(supports instrument46 thermograph4)
	(calibration_target instrument46 GroundStation3)
	(supports instrument47 infrared3)
	(supports instrument47 thermograph4)
	(calibration_target instrument47 GroundStation2)
	(supports instrument48 infrared3)
	(calibration_target instrument48 GroundStation3)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(on_board instrument46 satellite6)
	(on_board instrument47 satellite6)
	(on_board instrument48 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation3)
	(supports instrument49 spectrograph0)
	(supports instrument49 spectrograph2)
	(supports instrument49 spectrograph1)
	(calibration_target instrument49 GroundStation4)
	(supports instrument50 spectrograph2)
	(supports instrument50 spectrograph1)
	(calibration_target instrument50 GroundStation4)
	(supports instrument51 infrared3)
	(calibration_target instrument51 Star0)
	(supports instrument52 thermograph4)
	(supports instrument52 spectrograph1)
	(supports instrument52 spectrograph2)
	(calibration_target instrument52 GroundStation3)
	(supports instrument53 spectrograph0)
	(supports instrument53 spectrograph1)
	(supports instrument53 infrared3)
	(calibration_target instrument53 GroundStation2)
	(supports instrument54 infrared3)
	(supports instrument54 thermograph4)
	(calibration_target instrument54 Star1)
	(supports instrument55 thermograph4)
	(supports instrument55 spectrograph2)
	(calibration_target instrument55 GroundStation3)
	(supports instrument56 thermograph4)
	(supports instrument56 spectrograph0)
	(supports instrument56 spectrograph2)
	(calibration_target instrument56 GroundStation4)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(on_board instrument53 satellite7)
	(on_board instrument54 satellite7)
	(on_board instrument55 satellite7)
	(on_board instrument56 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
	(supports instrument57 spectrograph2)
	(calibration_target instrument57 GroundStation2)
	(supports instrument58 spectrograph2)
	(supports instrument58 thermograph4)
	(supports instrument58 spectrograph0)
	(calibration_target instrument58 GroundStation3)
	(supports instrument59 thermograph4)
	(supports instrument59 spectrograph1)
	(calibration_target instrument59 GroundStation4)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet5)
	(supports instrument60 spectrograph1)
	(calibration_target instrument60 GroundStation3)
	(on_board instrument60 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon6)
)
(:goal (and
	(pointing satellite0 GroundStation2)
	(pointing satellite3 GroundStation2)
	(pointing satellite5 GroundStation2)
	(pointing satellite6 GroundStation3)
	(have_image Planet5 thermograph4)
	(have_image Phenomenon6 spectrograph2)
))

)
