(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite3 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	satellite4 - satellite
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	satellite5 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite6 - satellite
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	satellite7 - satellite
	instrument46 - instrument
	satellite8 - satellite
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	satellite9 - satellite
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	thermograph2 - mode
	thermograph1 - mode
	infrared0 - mode
	infrared4 - mode
	image3 - mode
	GroundStation4 - direction
	Star3 - direction
	Star1 - direction
	GroundStation0 - direction
	GroundStation2 - direction
	Star5 - direction
	Planet6 - direction
)
(:init
	(supports instrument0 infrared0)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 GroundStation0)
	(supports instrument1 image3)
	(calibration_target instrument1 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star5)
	(supports instrument2 thermograph1)
	(supports instrument2 thermograph2)
	(supports instrument2 infrared4)
	(calibration_target instrument2 Star1)
	(supports instrument3 infrared4)
	(supports instrument3 image3)
	(calibration_target instrument3 Star3)
	(supports instrument4 infrared4)
	(supports instrument4 thermograph1)
	(calibration_target instrument4 Star3)
	(supports instrument5 infrared0)
	(supports instrument5 thermograph2)
	(supports instrument5 infrared4)
	(calibration_target instrument5 GroundStation2)
	(supports instrument6 thermograph1)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 GroundStation4)
	(supports instrument7 infrared0)
	(supports instrument7 thermograph2)
	(supports instrument7 image3)
	(calibration_target instrument7 Star3)
	(supports instrument8 infrared0)
	(calibration_target instrument8 GroundStation2)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 infrared0)
	(calibration_target instrument10 GroundStation0)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star1)
	(supports instrument11 thermograph1)
	(supports instrument11 thermograph2)
	(calibration_target instrument11 GroundStation4)
	(supports instrument12 thermograph1)
	(supports instrument12 infrared0)
	(supports instrument12 infrared4)
	(calibration_target instrument12 Star3)
	(supports instrument13 thermograph2)
	(calibration_target instrument13 Star1)
	(supports instrument14 image3)
	(calibration_target instrument14 Star3)
	(supports instrument15 thermograph2)
	(supports instrument15 infrared0)
	(supports instrument15 infrared4)
	(calibration_target instrument15 Star1)
	(supports instrument16 image3)
	(supports instrument16 infrared4)
	(supports instrument16 thermograph2)
	(calibration_target instrument16 Star3)
	(supports instrument17 infrared4)
	(calibration_target instrument17 GroundStation0)
	(supports instrument18 image3)
	(supports instrument18 infrared4)
	(calibration_target instrument18 Star3)
	(supports instrument19 image3)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 image3)
	(calibration_target instrument20 GroundStation0)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star5)
	(supports instrument21 infrared4)
	(supports instrument21 thermograph2)
	(supports instrument21 image3)
	(calibration_target instrument21 GroundStation2)
	(supports instrument22 infrared0)
	(supports instrument22 infrared4)
	(supports instrument22 image3)
	(calibration_target instrument22 Star3)
	(supports instrument23 image3)
	(calibration_target instrument23 Star1)
	(supports instrument24 thermograph1)
	(supports instrument24 infrared4)
	(supports instrument24 thermograph2)
	(calibration_target instrument24 Star3)
	(supports instrument25 thermograph1)
	(supports instrument25 infrared4)
	(supports instrument25 thermograph2)
	(calibration_target instrument25 Star1)
	(supports instrument26 thermograph2)
	(supports instrument26 infrared4)
	(calibration_target instrument26 Star3)
	(supports instrument27 thermograph1)
	(supports instrument27 infrared0)
	(calibration_target instrument27 GroundStation4)
	(supports instrument28 thermograph2)
	(supports instrument28 infrared4)
	(calibration_target instrument28 Star3)
	(supports instrument29 image3)
	(supports instrument29 thermograph1)
	(supports instrument29 thermograph2)
	(calibration_target instrument29 GroundStation0)
	(supports instrument30 image3)
	(supports instrument30 infrared4)
	(supports instrument30 thermograph1)
	(calibration_target instrument30 Star3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(on_board instrument30 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star1)
	(supports instrument31 infrared0)
	(calibration_target instrument31 Star3)
	(supports instrument32 thermograph1)
	(supports instrument32 infrared4)
	(supports instrument32 image3)
	(calibration_target instrument32 GroundStation2)
	(supports instrument33 thermograph2)
	(supports instrument33 image3)
	(supports instrument33 thermograph1)
	(calibration_target instrument33 Star1)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation4)
	(supports instrument34 thermograph1)
	(supports instrument34 infrared4)
	(calibration_target instrument34 GroundStation2)
	(supports instrument35 infrared0)
	(calibration_target instrument35 GroundStation2)
	(supports instrument36 thermograph2)
	(supports instrument36 image3)
	(calibration_target instrument36 Star3)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star1)
	(supports instrument37 thermograph2)
	(supports instrument37 thermograph1)
	(calibration_target instrument37 Star3)
	(supports instrument38 infrared0)
	(supports instrument38 thermograph1)
	(supports instrument38 thermograph2)
	(calibration_target instrument38 Star1)
	(supports instrument39 thermograph2)
	(supports instrument39 infrared0)
	(supports instrument39 thermograph1)
	(calibration_target instrument39 GroundStation2)
	(supports instrument40 thermograph1)
	(supports instrument40 infrared0)
	(calibration_target instrument40 Star3)
	(supports instrument41 thermograph2)
	(calibration_target instrument41 GroundStation0)
	(supports instrument42 infrared4)
	(supports instrument42 thermograph2)
	(calibration_target instrument42 GroundStation4)
	(supports instrument43 thermograph1)
	(supports instrument43 thermograph2)
	(calibration_target instrument43 Star1)
	(supports instrument44 thermograph1)
	(supports instrument44 infrared4)
	(supports instrument44 thermograph2)
	(calibration_target instrument44 Star1)
	(supports instrument45 infrared0)
	(supports instrument45 thermograph1)
	(supports instrument45 thermograph2)
	(calibration_target instrument45 GroundStation0)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation2)
	(supports instrument46 infrared0)
	(calibration_target instrument46 GroundStation2)
	(on_board instrument46 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation0)
	(supports instrument47 infrared0)
	(supports instrument47 image3)
	(calibration_target instrument47 Star3)
	(supports instrument48 infrared0)
	(supports instrument48 thermograph1)
	(calibration_target instrument48 Star1)
	(supports instrument49 thermograph2)
	(supports instrument49 infrared4)
	(supports instrument49 infrared0)
	(calibration_target instrument49 GroundStation4)
	(supports instrument50 image3)
	(supports instrument50 thermograph1)
	(calibration_target instrument50 Star3)
	(supports instrument51 thermograph2)
	(calibration_target instrument51 GroundStation0)
	(supports instrument52 thermograph1)
	(calibration_target instrument52 Star1)
	(supports instrument53 infrared4)
	(supports instrument53 image3)
	(calibration_target instrument53 Star1)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation0)
	(supports instrument54 infrared4)
	(supports instrument54 infrared0)
	(calibration_target instrument54 GroundStation2)
	(supports instrument55 infrared0)
	(calibration_target instrument55 GroundStation0)
	(supports instrument56 thermograph2)
	(supports instrument56 image3)
	(supports instrument56 thermograph1)
	(calibration_target instrument56 GroundStation2)
	(supports instrument57 infrared4)
	(supports instrument57 infrared0)
	(supports instrument57 thermograph1)
	(calibration_target instrument57 GroundStation0)
	(supports instrument58 image3)
	(calibration_target instrument58 GroundStation2)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation4)
)
(:goal (and
	(pointing satellite0 Star1)
	(pointing satellite2 GroundStation4)
	(pointing satellite5 Star1)
	(pointing satellite7 GroundStation0)
	(pointing satellite9 Star1)
	(have_image Star5 infrared0)
	(have_image Planet6 thermograph1)
))

)
