(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (on block1 block5) (clear block1) (ontable block2) (on block3 block11) (on block4 block10) (clear block4) (ontable block5) (ontable block6) (on block7 block2) (clear block7) (on block8 block3) (on block9 block8) (on block10 block9) (on block11 block6) (handempty))
	(:goal (and (on block1 block3) (ontable block2) (on block3 block2) (ontable block4) (ontable block5) (on block6 block10) (clear block6) (on block7 block1) (on block8 block4) (on block9 block8) (clear block9) (on block10 block5) (on block11 block7) (clear block11))))