(define (problem pb8)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (on block1 block8) (on block2 block7) (on block3 block10) (clear block3) (on block4 block2) (on block5 block4) (clear block5) (ontable block6) (clear block6) (on block7 block9) (ontable block8) (ontable block9) (on block10 block1) (ontable block11) (clear block11) (handempty))
	(:goal (and (on block1 block9) (on block2 block3) (clear block2) (on block3 block1) (ontable block4) (on block5 block8) (clear block5) (ontable block6) (on block7 block4) (clear block7) (ontable block8) (ontable block9) (on block10 block11) (clear block10) (on block11 block6))))