(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (ontable block1) (ontable block2) (on block3 block10) (on block4 block5) (clear block4) (ontable block5) (on block6 block3) (clear block6) (on block7 block11) (on block8 block2) (on block9 block8) (clear block9) (on block10 block7) (on block11 block1) (handempty))
	(:goal (and (ontable block1) (on block2 block3) (on block3 block1) (ontable block4) (on block5 block11) (clear block5) (on block6 block10) (ontable block7) (clear block7) (on block8 block2) (clear block8) (on block9 block6) (on block10 block4) (on block11 block9))))