(define (problem pb5)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (on block1 block7) (clear block1) (on block2 block9) (on block3 block8) (on block4 block3) (on block5 block6) (ontable block6) (on block7 block10) (on block8 block2) (on block9 block11) (on block10 block4) (on block11 block5) (handempty))
	(:goal (and (ontable block1) (on block2 block4) (ontable block3) (clear block3) (on block4 block11) (ontable block5) (clear block5) (on block6 block10) (clear block6) (ontable block7) (clear block7) (on block8 block2) (on block9 block8) (clear block9) (ontable block10) (on block11 block1))))