(define (problem pb2)
	(:domain blocks)
	(:objects block1 block2 block3 block4)
	(:init (ontable block1) (clear block1) (ontable block2) (on block3 block2) (clear block3) (ontable block4) (clear block4) (handempty))
	(:goal (and (on block1 block2) (clear block1) (ontable block2) (ontable block3) (clear block3) (ontable block4) (clear block4))))