(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4)
	(:init (on block1 block4) (clear block1) (ontable block2) (on block3 block2) (clear block3) (ontable block4) (handempty))
	(:goal (and (ontable block1) (on block2 block1) (clear block2) (on block3 block4) (clear block3) (ontable block4))))