(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3 block4)
	(:init (ontable block1) (clear block1) (ontable block2) (clear block2) (ontable block3) (on block4 block3) (clear block4) (handempty))
	(:goal (and (on block1 block3) (ontable block2) (clear block2) (ontable block3) (on block4 block1) (clear block4))))