(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite3 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite4 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite5 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite6 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite7 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite8 - satellite
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite9 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	infrared0 - mode
	spectrograph4 - mode
	spectrograph2 - mode
	spectrograph1 - mode
	image3 - mode
	Star3 - direction
	GroundStation1 - direction
	Star0 - direction
	GroundStation2 - direction
	Planet4 - direction
	Planet5 - direction
)
(:init
	(supports instrument0 spectrograph2)
	(supports instrument0 image3)
	(calibration_target instrument0 Star0)
	(supports instrument1 spectrograph4)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 spectrograph4)
	(calibration_target instrument2 Star0)
	(supports instrument3 image3)
	(supports instrument3 infrared0)
	(supports instrument3 spectrograph4)
	(calibration_target instrument3 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation1)
	(supports instrument4 infrared0)
	(supports instrument4 image3)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 GroundStation2)
	(supports instrument5 image3)
	(supports instrument5 spectrograph1)
	(calibration_target instrument5 Star3)
	(supports instrument6 spectrograph4)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 GroundStation1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument7 spectrograph4)
	(supports instrument7 image3)
	(supports instrument7 infrared0)
	(calibration_target instrument7 Star3)
	(supports instrument8 spectrograph4)
	(calibration_target instrument8 GroundStation2)
	(supports instrument9 spectrograph4)
	(calibration_target instrument9 GroundStation2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument10 spectrograph2)
	(supports instrument10 spectrograph4)
	(supports instrument10 infrared0)
	(calibration_target instrument10 Star3)
	(supports instrument11 infrared0)
	(supports instrument11 spectrograph4)
	(calibration_target instrument11 GroundStation2)
	(supports instrument12 spectrograph4)
	(calibration_target instrument12 Star0)
	(supports instrument13 image3)
	(supports instrument13 spectrograph1)
	(supports instrument13 infrared0)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 infrared0)
	(calibration_target instrument14 GroundStation2)
	(supports instrument15 image3)
	(calibration_target instrument15 GroundStation1)
	(supports instrument16 spectrograph1)
	(supports instrument16 spectrograph2)
	(supports instrument16 infrared0)
	(calibration_target instrument16 GroundStation1)
	(supports instrument17 spectrograph1)
	(supports instrument17 spectrograph4)
	(calibration_target instrument17 Star3)
	(supports instrument18 spectrograph1)
	(supports instrument18 infrared0)
	(calibration_target instrument18 GroundStation2)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet4)
	(supports instrument19 image3)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 image3)
	(calibration_target instrument20 GroundStation2)
	(supports instrument21 infrared0)
	(supports instrument21 spectrograph1)
	(calibration_target instrument21 GroundStation1)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet5)
	(supports instrument22 image3)
	(supports instrument22 spectrograph4)
	(calibration_target instrument22 Star0)
	(supports instrument23 spectrograph1)
	(supports instrument23 spectrograph4)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 spectrograph1)
	(supports instrument24 spectrograph2)
	(supports instrument24 image3)
	(calibration_target instrument24 Star3)
	(supports instrument25 image3)
	(supports instrument25 spectrograph4)
	(supports instrument25 infrared0)
	(calibration_target instrument25 GroundStation1)
	(supports instrument26 spectrograph2)
	(supports instrument26 image3)
	(calibration_target instrument26 Star3)
	(supports instrument27 spectrograph2)
	(supports instrument27 infrared0)
	(supports instrument27 image3)
	(calibration_target instrument27 Star3)
	(supports instrument28 spectrograph4)
	(supports instrument28 infrared0)
	(supports instrument28 spectrograph2)
	(calibration_target instrument28 Star0)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation2)
	(supports instrument29 spectrograph4)
	(supports instrument29 infrared0)
	(supports instrument29 spectrograph2)
	(calibration_target instrument29 Star0)
	(supports instrument30 spectrograph2)
	(supports instrument30 spectrograph4)
	(supports instrument30 image3)
	(calibration_target instrument30 GroundStation1)
	(supports instrument31 spectrograph1)
	(supports instrument31 image3)
	(calibration_target instrument31 Star3)
	(on_board instrument29 satellite6)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet5)
	(supports instrument32 image3)
	(supports instrument32 spectrograph1)
	(calibration_target instrument32 Star0)
	(supports instrument33 infrared0)
	(supports instrument33 spectrograph2)
	(supports instrument33 spectrograph1)
	(calibration_target instrument33 GroundStation2)
	(supports instrument34 spectrograph1)
	(supports instrument34 spectrograph2)
	(supports instrument34 infrared0)
	(calibration_target instrument34 Star3)
	(supports instrument35 spectrograph1)
	(supports instrument35 image3)
	(supports instrument35 spectrograph2)
	(calibration_target instrument35 GroundStation1)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation1)
	(supports instrument36 image3)
	(calibration_target instrument36 GroundStation1)
	(supports instrument37 spectrograph2)
	(supports instrument37 spectrograph1)
	(supports instrument37 image3)
	(calibration_target instrument37 GroundStation2)
	(supports instrument38 infrared0)
	(supports instrument38 spectrograph4)
	(calibration_target instrument38 Star3)
	(supports instrument39 spectrograph4)
	(supports instrument39 infrared0)
	(calibration_target instrument39 Star3)
	(supports instrument40 infrared0)
	(supports instrument40 spectrograph4)
	(calibration_target instrument40 Star0)
	(supports instrument41 spectrograph2)
	(calibration_target instrument41 Star0)
	(supports instrument42 infrared0)
	(supports instrument42 spectrograph2)
	(supports instrument42 spectrograph1)
	(calibration_target instrument42 Star0)
	(supports instrument43 spectrograph4)
	(supports instrument43 image3)
	(supports instrument43 infrared0)
	(calibration_target instrument43 GroundStation2)
	(on_board instrument36 satellite8)
	(on_board instrument37 satellite8)
	(on_board instrument38 satellite8)
	(on_board instrument39 satellite8)
	(on_board instrument40 satellite8)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation1)
	(supports instrument44 spectrograph1)
	(supports instrument44 infrared0)
	(supports instrument44 spectrograph2)
	(calibration_target instrument44 Star0)
	(supports instrument45 spectrograph4)
	(supports instrument45 spectrograph1)
	(calibration_target instrument45 Star0)
	(supports instrument46 infrared0)
	(supports instrument46 spectrograph1)
	(supports instrument46 spectrograph2)
	(calibration_target instrument46 Star0)
	(supports instrument47 infrared0)
	(calibration_target instrument47 GroundStation1)
	(supports instrument48 image3)
	(calibration_target instrument48 GroundStation2)
	(supports instrument49 spectrograph4)
	(supports instrument49 infrared0)
	(calibration_target instrument49 Star0)
	(supports instrument50 spectrograph4)
	(supports instrument50 spectrograph1)
	(calibration_target instrument50 Star0)
	(supports instrument51 spectrograph1)
	(supports instrument51 spectrograph2)
	(supports instrument51 image3)
	(calibration_target instrument51 Star0)
	(supports instrument52 image3)
	(supports instrument52 spectrograph1)
	(calibration_target instrument52 GroundStation2)
	(on_board instrument44 satellite9)
	(on_board instrument45 satellite9)
	(on_board instrument46 satellite9)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation1)
)
(:goal (and
	(pointing satellite2 Star3)
	(pointing satellite4 Star3)
	(pointing satellite5 Star3)
	(pointing satellite9 Planet4)
	(have_image Planet4 spectrograph2)
	(have_image Planet5 spectrograph1)
))

)
