(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite4 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite5 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite6 - satellite
	instrument37 - instrument
	instrument38 - instrument
	satellite7 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	satellite8 - satellite
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	satellite9 - satellite
	instrument59 - instrument
	instrument60 - instrument
	image3 - mode
	image2 - mode
	image4 - mode
	spectrograph0 - mode
	infrared1 - mode
	Star3 - direction
	GroundStation1 - direction
	GroundStation2 - direction
	Star0 - direction
	Planet4 - direction
	Planet5 - direction
)
(:init
	(supports instrument0 image4)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 spectrograph0)
	(supports instrument1 image2)
	(supports instrument1 image3)
	(calibration_target instrument1 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(supports instrument2 image3)
	(supports instrument2 image4)
	(supports instrument2 image2)
	(calibration_target instrument2 Star3)
	(supports instrument3 image2)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 image2)
	(supports instrument4 infrared1)
	(calibration_target instrument4 Star0)
	(supports instrument5 image4)
	(supports instrument5 image2)
	(calibration_target instrument5 Star0)
	(supports instrument6 image3)
	(supports instrument6 image2)
	(calibration_target instrument6 GroundStation1)
	(supports instrument7 image2)
	(supports instrument7 spectrograph0)
	(supports instrument7 infrared1)
	(calibration_target instrument7 GroundStation1)
	(supports instrument8 image4)
	(supports instrument8 image3)
	(supports instrument8 infrared1)
	(calibration_target instrument8 GroundStation1)
	(supports instrument9 image4)
	(supports instrument9 infrared1)
	(calibration_target instrument9 GroundStation1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet4)
	(supports instrument10 spectrograph0)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 image2)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 GroundStation1)
	(supports instrument12 image3)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 Star0)
	(supports instrument13 infrared1)
	(supports instrument13 image2)
	(calibration_target instrument13 GroundStation1)
	(supports instrument14 image3)
	(calibration_target instrument14 GroundStation1)
	(supports instrument15 image3)
	(supports instrument15 spectrograph0)
	(supports instrument15 image4)
	(calibration_target instrument15 GroundStation2)
	(supports instrument16 image4)
	(supports instrument16 image2)
	(supports instrument16 image3)
	(calibration_target instrument16 Star3)
	(supports instrument17 infrared1)
	(supports instrument17 image4)
	(calibration_target instrument17 GroundStation2)
	(supports instrument18 image4)
	(supports instrument18 image2)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 Star0)
	(supports instrument19 infrared1)
	(supports instrument19 spectrograph0)
	(supports instrument19 image3)
	(calibration_target instrument19 Star3)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet5)
	(supports instrument20 image2)
	(supports instrument20 image3)
	(calibration_target instrument20 Star0)
	(supports instrument21 image4)
	(supports instrument21 spectrograph0)
	(supports instrument21 infrared1)
	(calibration_target instrument21 Star0)
	(supports instrument22 image2)
	(calibration_target instrument22 Star0)
	(supports instrument23 infrared1)
	(calibration_target instrument23 GroundStation2)
	(supports instrument24 image4)
	(calibration_target instrument24 Star0)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation1)
	(supports instrument25 spectrograph0)
	(supports instrument25 image4)
	(calibration_target instrument25 Star3)
	(supports instrument26 infrared1)
	(supports instrument26 spectrograph0)
	(calibration_target instrument26 Star0)
	(supports instrument27 infrared1)
	(supports instrument27 spectrograph0)
	(calibration_target instrument27 GroundStation2)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet5)
	(supports instrument28 infrared1)
	(supports instrument28 image3)
	(supports instrument28 image4)
	(calibration_target instrument28 Star3)
	(supports instrument29 spectrograph0)
	(supports instrument29 image4)
	(supports instrument29 image3)
	(calibration_target instrument29 GroundStation1)
	(supports instrument30 spectrograph0)
	(calibration_target instrument30 GroundStation1)
	(supports instrument31 image4)
	(supports instrument31 infrared1)
	(calibration_target instrument31 GroundStation1)
	(supports instrument32 spectrograph0)
	(calibration_target instrument32 GroundStation2)
	(supports instrument33 image2)
	(supports instrument33 image3)
	(supports instrument33 spectrograph0)
	(calibration_target instrument33 GroundStation1)
	(supports instrument34 spectrograph0)
	(supports instrument34 image2)
	(supports instrument34 infrared1)
	(calibration_target instrument34 Star0)
	(supports instrument35 image3)
	(supports instrument35 image4)
	(supports instrument35 infrared1)
	(calibration_target instrument35 GroundStation1)
	(supports instrument36 image3)
	(supports instrument36 infrared1)
	(supports instrument36 spectrograph0)
	(calibration_target instrument36 GroundStation1)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(supports instrument37 image2)
	(calibration_target instrument37 GroundStation1)
	(supports instrument38 image4)
	(supports instrument38 image3)
	(calibration_target instrument38 GroundStation2)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation2)
	(supports instrument39 spectrograph0)
	(supports instrument39 image3)
	(supports instrument39 infrared1)
	(calibration_target instrument39 GroundStation1)
	(supports instrument40 image2)
	(calibration_target instrument40 GroundStation1)
	(supports instrument41 image4)
	(calibration_target instrument41 GroundStation2)
	(supports instrument42 infrared1)
	(calibration_target instrument42 GroundStation2)
	(supports instrument43 spectrograph0)
	(supports instrument43 image2)
	(calibration_target instrument43 Star3)
	(supports instrument44 infrared1)
	(supports instrument44 image4)
	(calibration_target instrument44 GroundStation2)
	(supports instrument45 spectrograph0)
	(supports instrument45 image4)
	(calibration_target instrument45 GroundStation2)
	(supports instrument46 image4)
	(calibration_target instrument46 GroundStation1)
	(supports instrument47 image4)
	(supports instrument47 spectrograph0)
	(supports instrument47 infrared1)
	(calibration_target instrument47 GroundStation1)
	(supports instrument48 image2)
	(supports instrument48 image4)
	(calibration_target instrument48 Star0)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet4)
	(supports instrument49 image4)
	(supports instrument49 spectrograph0)
	(calibration_target instrument49 GroundStation1)
	(supports instrument50 infrared1)
	(calibration_target instrument50 GroundStation2)
	(supports instrument51 image2)
	(supports instrument51 infrared1)
	(calibration_target instrument51 Star0)
	(supports instrument52 image2)
	(calibration_target instrument52 Star3)
	(supports instrument53 image3)
	(calibration_target instrument53 Star0)
	(supports instrument54 image2)
	(calibration_target instrument54 GroundStation1)
	(supports instrument55 image3)
	(supports instrument55 spectrograph0)
	(calibration_target instrument55 GroundStation2)
	(supports instrument56 image3)
	(supports instrument56 infrared1)
	(calibration_target instrument56 Star0)
	(supports instrument57 infrared1)
	(supports instrument57 image4)
	(calibration_target instrument57 Star0)
	(supports instrument58 infrared1)
	(supports instrument58 image4)
	(calibration_target instrument58 Star0)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(on_board instrument54 satellite8)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation1)
	(supports instrument59 spectrograph0)
	(supports instrument59 image2)
	(calibration_target instrument59 GroundStation2)
	(supports instrument60 infrared1)
	(supports instrument60 spectrograph0)
	(supports instrument60 image4)
	(calibration_target instrument60 Star0)
	(on_board instrument59 satellite9)
	(on_board instrument60 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation2)
)
(:goal (and
	(pointing satellite5 Planet4)
	(pointing satellite9 Star0)
	(have_image Planet4 spectrograph0)
	(have_image Planet5 infrared1)
))

)
