(define (problem pb2)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (ontable block1) (on block2 block6) (clear block2) (on block3 block1) (on block4 block7) (ontable block5) (clear block5) (ontable block6) (on block7 block3) (on block8 block4) (clear block8) (handempty))
	(:goal (and (ontable block1) (on block2 block4) (on block3 block7) (clear block3) (on block4 block6) (on block5 block8) (on block6 block1) (on block7 block5) (on block8 block2))))