(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (on block1 block2) (clear block1) (ontable block2) (on block3 block5) (ontable block4) (ontable block5) (on block6 block4) (clear block6) (ontable block7) (clear block7) (on block8 block3) (clear block8) (handempty))
	(:goal (and (ontable block1) (on block2 block1) (clear block2) (on block3 block6) (on block4 block3) (clear block4) (ontable block5) (on block6 block8) (ontable block7) (clear block7) (on block8 block5))))