(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (on block1 block6) (on block2 block1) (on block3 block8) (clear block3) (ontable block4) (on block5 block2) (clear block5) (on block6 block4) (ontable block7) (clear block7) (ontable block8) (handempty))
	(:goal (and (on block1 block5) (on block2 block7) (on block3 block8) (ontable block4) (on block5 block3) (on block6 block1) (clear block6) (on block7 block4) (on block8 block2))))