(define (problem pb8)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (on block1 block7) (clear block1) (ontable block2) (on block3 block4) (clear block3) (on block4 block2) (on block5 block8) (on block6 block5) (clear block6) (ontable block7) (ontable block8) (handempty))
	(:goal (and (on block1 block4) (on block2 block7) (clear block2) (ontable block3) (on block4 block3) (on block5 block8) (on block6 block5) (on block7 block6) (on block8 block1))))