(define (problem pb0)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (ontable block1) (ontable block2) (clear block2) (on block3 block8) (clear block3) (on block4 block1) (on block5 block4) (clear block5) (ontable block6) (ontable block7) (clear block7) (on block8 block6) (handempty))
	(:goal (and (on block1 block2) (on block2 block8) (on block3 block6) (clear block3) (ontable block4) (on block5 block1) (clear block5) (on block6 block7) (on block7 block4) (ontable block8))))