(define (problem pb7)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (on block1 block4) (clear block1) (on block2 block3) (on block3 block5) (on block4 block2) (ontable block5) (ontable block6) (ontable block7) (clear block7) (on block8 block6) (clear block8) (handempty))
	(:goal (and (on block1 block6) (clear block1) (on block2 block5) (on block3 block7) (clear block3) (ontable block4) (ontable block5) (on block6 block4) (on block7 block8) (on block8 block2))))