(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (on block1 block6) (on block2 block3) (on block3 block5) (ontable block4) (clear block4) (on block5 block1) (ontable block6) (on block7 block8) (clear block7) (on block8 block2) (handempty))
	(:goal (and (ontable block1) (clear block1) (on block2 block5) (clear block2) (on block3 block4) (ontable block4) (on block5 block7) (on block6 block3) (clear block6) (on block7 block8) (ontable block8))))