(define (problem pb5)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (ontable block1) (clear block1) (ontable block2) (on block3 block4) (ontable block4) (on block5 block3) (on block6 block7) (clear block6) (on block7 block2) (on block8 block5) (clear block8) (handempty))
	(:goal (and (on block1 block3) (on block2 block7) (ontable block3) (ontable block4) (clear block4) (ontable block5) (clear block5) (on block6 block2) (clear block6) (ontable block7) (on block8 block1) (clear block8))))