(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (on block1 block5) (on block2 block1) (clear block2) (on block3 block11) (on block4 block6) (on block5 block10) (ontable block6) (on block7 block9) (on block8 block3) (on block9 block4) (on block10 block8) (on block11 block7) (handempty))
	(:goal (and (ontable block1) (clear block1) (ontable block2) (clear block2) (on block3 block9) (clear block3) (ontable block4) (on block5 block11) (clear block5) (ontable block6) (on block7 block4) (on block8 block6) (clear block8) (ontable block9) (on block10 block7) (clear block10) (ontable block11))))