(define (problem pb2)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (ontable block1) (ontable block2) (ontable block3) (clear block3) (on block4 block5) (clear block4) (ontable block5) (on block6 block2) (on block7 block10) (on block8 block7) (clear block8) (on block9 block6) (clear block9) (on block10 block1) (ontable block11) (clear block11) (handempty))
	(:goal (and (on block1 block2) (on block2 block5) (on block3 block7) (on block4 block3) (on block5 block4) (on block6 block9) (clear block6) (on block7 block11) (on block8 block10) (clear block8) (on block9 block1) (ontable block10) (ontable block11))))