(define (problem pb0)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (on block1 block4) (on block2 block9) (on block3 block10) (clear block3) (on block4 block11) (ontable block5) (on block6 block5) (on block7 block1) (clear block7) (on block8 block2) (ontable block9) (on block10 block8) (on block11 block6) (handempty))
	(:goal (and (on block1 block7) (ontable block2) (clear block2) (on block3 block6) (clear block3) (on block4 block5) (on block5 block1) (ontable block6) (on block7 block10) (on block8 block4) (clear block8) (ontable block9) (clear block9) (ontable block10) (ontable block11) (clear block11))))