(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (on block1 block5) (clear block1) (on block2 block9) (clear block2) (on block3 block6) (clear block3) (on block4 block7) (clear block4) (on block5 block10) (ontable block6) (ontable block7) (on block8 block11) (on block9 block8) (ontable block10) (ontable block11) (handempty))
	(:goal (and (on block1 block3) (on block2 block11) (ontable block3) (on block4 block10) (ontable block5) (on block6 block2) (clear block6) (on block7 block4) (clear block7) (on block8 block5) (on block9 block1) (on block10 block8) (on block11 block9))))