(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (ontable block1) (ontable block2) (on block3 block1) (clear block3) (on block4 block7) (on block5 block8) (clear block5) (ontable block6) (clear block6) (on block7 block10) (on block8 block2) (on block9 block4) (clear block9) (ontable block10) (ontable block11) (clear block11) (handempty))
	(:goal (and (on block1 block5) (on block2 block1) (on block3 block11) (ontable block4) (on block5 block3) (on block6 block4) (on block7 block8) (clear block7) (on block8 block2) (on block9 block6) (on block10 block9) (on block11 block10))))