(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8 block9 block10 block11)
	(:init (ontable block1) (on block2 block8) (clear block2) (on block3 block10) (clear block3) (on block4 block9) (on block5 block1) (on block6 block5) (clear block6) (on block7 block4) (clear block7) (on block8 block11) (ontable block9) (ontable block10) (ontable block11) (handempty))
	(:goal (and (on block1 block7) (on block2 block10) (on block3 block1) (on block4 block2) (clear block4) (ontable block5) (on block6 block3) (on block7 block5) (on block8 block9) (clear block8) (on block9 block11) (on block10 block6) (ontable block11))))