(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite4 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite6 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite7 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite8 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite9 - satellite
	instrument33 - instrument
	thermograph4 - mode
	image3 - mode
	infrared0 - mode
	infrared2 - mode
	spectrograph1 - mode
	GroundStation13 - direction
	Star3 - direction
	Star40 - direction
	GroundStation28 - direction
	GroundStation36 - direction
	Star35 - direction
	GroundStation18 - direction
	Star45 - direction
	Star41 - direction
	Star10 - direction
	GroundStation17 - direction
	Star43 - direction
	GroundStation37 - direction
	Star8 - direction
	GroundStation14 - direction
	Star11 - direction
	Star4 - direction
	GroundStation22 - direction
	GroundStation25 - direction
	GroundStation23 - direction
	GroundStation33 - direction
	GroundStation2 - direction
	GroundStation7 - direction
	GroundStation12 - direction
	GroundStation6 - direction
	GroundStation15 - direction
	GroundStation1 - direction
	GroundStation26 - direction
	GroundStation31 - direction
	Star32 - direction
	GroundStation27 - direction
	Star42 - direction
	Star0 - direction
	Star24 - direction
	Star9 - direction
	GroundStation19 - direction
	Star16 - direction
	Star38 - direction
	GroundStation30 - direction
	GroundStation20 - direction
	GroundStation39 - direction
	Star34 - direction
	GroundStation5 - direction
	GroundStation44 - direction
	GroundStation29 - direction
	Star21 - direction
	Planet46 - direction
	Phenomenon47 - direction
)
(:init
	(supports instrument0 infrared0)
	(supports instrument0 infrared2)
	(calibration_target instrument0 GroundStation25)
	(calibration_target instrument0 GroundStation31)
	(calibration_target instrument0 Star34)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 Star3)
	(supports instrument1 infrared0)
	(calibration_target instrument1 Star41)
	(calibration_target instrument1 GroundStation29)
	(calibration_target instrument1 GroundStation39)
	(supports instrument2 spectrograph1)
	(supports instrument2 infrared2)
	(supports instrument2 infrared0)
	(calibration_target instrument2 GroundStation14)
	(calibration_target instrument2 GroundStation30)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation14)
	(supports instrument3 infrared0)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 Star43)
	(calibration_target instrument3 GroundStation28)
	(calibration_target instrument3 Star9)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 GroundStation37)
	(calibration_target instrument4 GroundStation31)
	(calibration_target instrument4 Star21)
	(calibration_target instrument4 Star45)
	(calibration_target instrument4 GroundStation26)
	(calibration_target instrument4 GroundStation13)
	(calibration_target instrument4 GroundStation29)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 GroundStation39)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 GroundStation23)
	(calibration_target instrument5 Star11)
	(calibration_target instrument5 GroundStation12)
	(calibration_target instrument5 GroundStation44)
	(calibration_target instrument5 GroundStation7)
	(calibration_target instrument5 GroundStation13)
	(calibration_target instrument5 GroundStation36)
	(calibration_target instrument5 GroundStation1)
	(calibration_target instrument5 GroundStation19)
	(calibration_target instrument5 Star4)
	(calibration_target instrument5 Star41)
	(supports instrument6 image3)
	(supports instrument6 thermograph4)
	(calibration_target instrument6 GroundStation23)
	(calibration_target instrument6 Star16)
	(supports instrument7 thermograph4)
	(supports instrument7 spectrograph1)
	(supports instrument7 infrared2)
	(calibration_target instrument7 Star34)
	(calibration_target instrument7 GroundStation44)
	(calibration_target instrument7 GroundStation1)
	(calibration_target instrument7 GroundStation25)
	(calibration_target instrument7 GroundStation18)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation25)
	(supports instrument8 infrared2)
	(supports instrument8 image3)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 GroundStation33)
	(calibration_target instrument8 GroundStation12)
	(calibration_target instrument8 GroundStation5)
	(calibration_target instrument8 Star4)
	(calibration_target instrument8 Star21)
	(calibration_target instrument8 Star11)
	(calibration_target instrument8 Star38)
	(calibration_target instrument8 GroundStation37)
	(calibration_target instrument8 Star10)
	(calibration_target instrument8 GroundStation13)
	(calibration_target instrument8 GroundStation39)
	(supports instrument9 infrared0)
	(calibration_target instrument9 GroundStation31)
	(calibration_target instrument9 GroundStation13)
	(calibration_target instrument9 Star24)
	(calibration_target instrument9 GroundStation37)
	(calibration_target instrument9 Star43)
	(calibration_target instrument9 Star21)
	(calibration_target instrument9 GroundStation15)
	(calibration_target instrument9 Star35)
	(calibration_target instrument9 GroundStation5)
	(calibration_target instrument9 GroundStation39)
	(supports instrument10 image3)
	(supports instrument10 infrared0)
	(supports instrument10 infrared2)
	(calibration_target instrument10 GroundStation13)
	(calibration_target instrument10 GroundStation28)
	(calibration_target instrument10 GroundStation37)
	(calibration_target instrument10 Star32)
	(calibration_target instrument10 GroundStation26)
	(calibration_target instrument10 GroundStation18)
	(calibration_target instrument10 Star11)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star10)
	(supports instrument11 spectrograph1)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 GroundStation14)
	(calibration_target instrument11 Star21)
	(calibration_target instrument11 GroundStation29)
	(calibration_target instrument11 GroundStation30)
	(calibration_target instrument11 Star35)
	(calibration_target instrument11 GroundStation5)
	(calibration_target instrument11 Star42)
	(calibration_target instrument11 Star8)
	(calibration_target instrument11 GroundStation12)
	(calibration_target instrument11 Star16)
	(calibration_target instrument11 GroundStation25)
	(calibration_target instrument11 Star40)
	(supports instrument12 spectrograph1)
	(supports instrument12 image3)
	(calibration_target instrument12 GroundStation44)
	(supports instrument13 image3)
	(supports instrument13 infrared0)
	(supports instrument13 infrared2)
	(calibration_target instrument13 Star41)
	(calibration_target instrument13 Star16)
	(calibration_target instrument13 GroundStation22)
	(calibration_target instrument13 GroundStation1)
	(calibration_target instrument13 GroundStation33)
	(calibration_target instrument13 Star11)
	(calibration_target instrument13 GroundStation12)
	(calibration_target instrument13 Star32)
	(calibration_target instrument13 GroundStation13)
	(calibration_target instrument13 Star10)
	(calibration_target instrument13 GroundStation18)
	(calibration_target instrument13 GroundStation23)
	(calibration_target instrument13 GroundStation31)
	(calibration_target instrument13 GroundStation27)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation23)
	(supports instrument14 image3)
	(supports instrument14 thermograph4)
	(supports instrument14 infrared2)
	(calibration_target instrument14 GroundStation37)
	(calibration_target instrument14 GroundStation19)
	(calibration_target instrument14 Star16)
	(calibration_target instrument14 Star41)
	(calibration_target instrument14 Star43)
	(calibration_target instrument14 GroundStation14)
	(calibration_target instrument14 Star35)
	(calibration_target instrument14 GroundStation27)
	(calibration_target instrument14 Star9)
	(supports instrument15 image3)
	(calibration_target instrument15 GroundStation30)
	(calibration_target instrument15 Star41)
	(calibration_target instrument15 Star3)
	(calibration_target instrument15 GroundStation27)
	(calibration_target instrument15 GroundStation7)
	(calibration_target instrument15 GroundStation17)
	(calibration_target instrument15 GroundStation33)
	(calibration_target instrument15 Star4)
	(calibration_target instrument15 Star32)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 GroundStation28)
	(calibration_target instrument16 GroundStation44)
	(calibration_target instrument16 Star10)
	(calibration_target instrument16 Star42)
	(calibration_target instrument16 GroundStation5)
	(calibration_target instrument16 GroundStation19)
	(calibration_target instrument16 Star34)
	(calibration_target instrument16 Star9)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation18)
	(supports instrument17 spectrograph1)
	(supports instrument17 infrared2)
	(calibration_target instrument17 Star41)
	(calibration_target instrument17 GroundStation1)
	(calibration_target instrument17 GroundStation27)
	(calibration_target instrument17 Star40)
	(calibration_target instrument17 Star3)
	(calibration_target instrument17 GroundStation39)
	(calibration_target instrument17 GroundStation30)
	(calibration_target instrument17 Star45)
	(calibration_target instrument17 Star35)
	(supports instrument18 spectrograph1)
	(supports instrument18 infrared0)
	(supports instrument18 infrared2)
	(calibration_target instrument18 GroundStation20)
	(calibration_target instrument18 Star16)
	(calibration_target instrument18 GroundStation6)
	(calibration_target instrument18 Star43)
	(calibration_target instrument18 Star45)
	(calibration_target instrument18 GroundStation39)
	(calibration_target instrument18 GroundStation44)
	(calibration_target instrument18 GroundStation12)
	(supports instrument19 image3)
	(supports instrument19 infrared2)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 GroundStation7)
	(calibration_target instrument19 Star11)
	(calibration_target instrument19 GroundStation37)
	(calibration_target instrument19 Star32)
	(calibration_target instrument19 GroundStation28)
	(calibration_target instrument19 Star24)
	(calibration_target instrument19 GroundStation31)
	(calibration_target instrument19 Star35)
	(supports instrument20 infrared2)
	(supports instrument20 spectrograph1)
	(supports instrument20 infrared0)
	(calibration_target instrument20 GroundStation18)
	(calibration_target instrument20 GroundStation14)
	(calibration_target instrument20 GroundStation26)
	(calibration_target instrument20 Star11)
	(calibration_target instrument20 Star10)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 GroundStation23)
	(calibration_target instrument20 GroundStation37)
	(calibration_target instrument20 GroundStation36)
	(calibration_target instrument20 Star45)
	(calibration_target instrument20 Star42)
	(calibration_target instrument20 Star34)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation6)
	(supports instrument21 infrared2)
	(supports instrument21 image3)
	(supports instrument21 spectrograph1)
	(calibration_target instrument21 GroundStation27)
	(calibration_target instrument21 Star8)
	(calibration_target instrument21 GroundStation12)
	(calibration_target instrument21 GroundStation44)
	(calibration_target instrument21 GroundStation36)
	(calibration_target instrument21 Star11)
	(calibration_target instrument21 GroundStation23)
	(calibration_target instrument21 GroundStation26)
	(supports instrument22 spectrograph1)
	(supports instrument22 infrared0)
	(supports instrument22 infrared2)
	(calibration_target instrument22 GroundStation18)
	(calibration_target instrument22 GroundStation19)
	(calibration_target instrument22 GroundStation20)
	(calibration_target instrument22 Star35)
	(calibration_target instrument22 GroundStation31)
	(calibration_target instrument22 GroundStation39)
	(calibration_target instrument22 Star16)
	(calibration_target instrument22 GroundStation12)
	(calibration_target instrument22 GroundStation5)
	(calibration_target instrument22 GroundStation27)
	(calibration_target instrument22 GroundStation30)
	(calibration_target instrument22 GroundStation1)
	(calibration_target instrument22 Star41)
	(supports instrument23 image3)
	(supports instrument23 infrared2)
	(supports instrument23 infrared0)
	(calibration_target instrument23 GroundStation25)
	(calibration_target instrument23 GroundStation1)
	(calibration_target instrument23 Star11)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(on_board instrument23 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star3)
	(supports instrument24 thermograph4)
	(supports instrument24 image3)
	(calibration_target instrument24 Star9)
	(supports instrument25 infrared2)
	(supports instrument25 thermograph4)
	(calibration_target instrument25 Star43)
	(calibration_target instrument25 GroundStation39)
	(calibration_target instrument25 Star45)
	(calibration_target instrument25 GroundStation1)
	(calibration_target instrument25 GroundStation29)
	(calibration_target instrument25 GroundStation27)
	(calibration_target instrument25 Star42)
	(calibration_target instrument25 GroundStation17)
	(calibration_target instrument25 GroundStation31)
	(supports instrument26 infrared0)
	(calibration_target instrument26 Star16)
	(calibration_target instrument26 GroundStation7)
	(supports instrument27 infrared0)
	(supports instrument27 spectrograph1)
	(calibration_target instrument27 GroundStation29)
	(calibration_target instrument27 Star11)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 Star43)
	(calibration_target instrument28 GroundStation17)
	(calibration_target instrument28 GroundStation7)
	(calibration_target instrument28 GroundStation20)
	(calibration_target instrument28 Star11)
	(calibration_target instrument28 Star9)
	(calibration_target instrument28 Star21)
	(calibration_target instrument28 Star10)
	(calibration_target instrument28 GroundStation19)
	(calibration_target instrument28 Star41)
	(calibration_target instrument28 GroundStation22)
	(supports instrument29 infrared2)
	(supports instrument29 image3)
	(supports instrument29 infrared0)
	(calibration_target instrument29 GroundStation1)
	(calibration_target instrument29 GroundStation22)
	(calibration_target instrument29 Star4)
	(calibration_target instrument29 GroundStation26)
	(calibration_target instrument29 GroundStation27)
	(calibration_target instrument29 Star11)
	(calibration_target instrument29 Star34)
	(calibration_target instrument29 GroundStation14)
	(calibration_target instrument29 Star21)
	(calibration_target instrument29 GroundStation15)
	(calibration_target instrument29 Star8)
	(calibration_target instrument29 GroundStation37)
	(on_board instrument24 satellite7)
	(on_board instrument25 satellite7)
	(on_board instrument26 satellite7)
	(on_board instrument27 satellite7)
	(on_board instrument28 satellite7)
	(on_board instrument29 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star9)
	(supports instrument30 image3)
	(supports instrument30 thermograph4)
	(supports instrument30 spectrograph1)
	(calibration_target instrument30 Star0)
	(calibration_target instrument30 GroundStation12)
	(calibration_target instrument30 GroundStation15)
	(calibration_target instrument30 GroundStation33)
	(calibration_target instrument30 GroundStation31)
	(calibration_target instrument30 GroundStation23)
	(calibration_target instrument30 GroundStation25)
	(supports instrument31 spectrograph1)
	(calibration_target instrument31 GroundStation15)
	(calibration_target instrument31 GroundStation6)
	(calibration_target instrument31 GroundStation20)
	(calibration_target instrument31 GroundStation12)
	(calibration_target instrument31 GroundStation7)
	(calibration_target instrument31 GroundStation2)
	(supports instrument32 spectrograph1)
	(supports instrument32 image3)
	(supports instrument32 infrared0)
	(calibration_target instrument32 GroundStation20)
	(calibration_target instrument32 GroundStation19)
	(calibration_target instrument32 Star0)
	(calibration_target instrument32 Star42)
	(calibration_target instrument32 GroundStation27)
	(calibration_target instrument32 Star32)
	(calibration_target instrument32 Star24)
	(calibration_target instrument32 GroundStation31)
	(calibration_target instrument32 GroundStation26)
	(calibration_target instrument32 GroundStation1)
	(on_board instrument30 satellite8)
	(on_board instrument31 satellite8)
	(on_board instrument32 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation1)
	(supports instrument33 spectrograph1)
	(supports instrument33 infrared2)
	(supports instrument33 infrared0)
	(calibration_target instrument33 Star21)
	(calibration_target instrument33 GroundStation29)
	(calibration_target instrument33 GroundStation44)
	(calibration_target instrument33 GroundStation5)
	(calibration_target instrument33 Star34)
	(calibration_target instrument33 GroundStation39)
	(calibration_target instrument33 GroundStation20)
	(calibration_target instrument33 GroundStation30)
	(calibration_target instrument33 Star38)
	(calibration_target instrument33 Star16)
	(calibration_target instrument33 GroundStation19)
	(calibration_target instrument33 Star9)
	(calibration_target instrument33 Star24)
	(on_board instrument33 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star4)
)
(:goal (and
	(pointing satellite8 Star45)
	(have_image Planet46 infrared2)
	(have_image Phenomenon47 thermograph4)
))

)
