(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	satellite5 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite6 - satellite
	instrument17 - instrument
	satellite7 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite8 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite9 - satellite
	instrument29 - instrument
	thermograph1 - mode
	image3 - mode
	infrared0 - mode
	infrared4 - mode
	thermograph2 - mode
	Star16 - direction
	Star10 - direction
	GroundStation28 - direction
	GroundStation29 - direction
	GroundStation17 - direction
	GroundStation8 - direction
	GroundStation37 - direction
	Star32 - direction
	GroundStation22 - direction
	GroundStation20 - direction
	GroundStation4 - direction
	GroundStation39 - direction
	Star23 - direction
	Star1 - direction
	Star25 - direction
	Star40 - direction
	Star41 - direction
	GroundStation2 - direction
	Star12 - direction
	GroundStation0 - direction
	Star42 - direction
	Star5 - direction
	GroundStation30 - direction
	GroundStation31 - direction
	Star14 - direction
	Star3 - direction
	GroundStation43 - direction
	GroundStation11 - direction
	Star21 - direction
	Star19 - direction
	Star36 - direction
	GroundStation34 - direction
	GroundStation27 - direction
	GroundStation38 - direction
	Star35 - direction
	GroundStation26 - direction
	Star7 - direction
	GroundStation18 - direction
	Star9 - direction
	Star33 - direction
	Star24 - direction
	Star6 - direction
	GroundStation44 - direction
	GroundStation13 - direction
	Star15 - direction
	Planet45 - direction
	Phenomenon46 - direction
)
(:init
	(supports instrument0 thermograph2)
	(supports instrument0 image3)
	(calibration_target instrument0 Star33)
	(calibration_target instrument0 GroundStation28)
	(calibration_target instrument0 Star24)
	(calibration_target instrument0 GroundStation27)
	(calibration_target instrument0 Star42)
	(calibration_target instrument0 Star9)
	(calibration_target instrument0 GroundStation26)
	(calibration_target instrument0 Star6)
	(calibration_target instrument0 GroundStation39)
	(calibration_target instrument0 Star19)
	(calibration_target instrument0 Star41)
	(calibration_target instrument0 GroundStation8)
	(calibration_target instrument0 Star12)
	(calibration_target instrument0 Star32)
	(calibration_target instrument0 Star21)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star6)
	(supports instrument1 infrared4)
	(calibration_target instrument1 Star41)
	(calibration_target instrument1 Star10)
	(calibration_target instrument1 Star40)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 Star42)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 GroundStation30)
	(supports instrument2 image3)
	(supports instrument2 infrared0)
	(calibration_target instrument2 GroundStation29)
	(calibration_target instrument2 GroundStation38)
	(calibration_target instrument2 Star1)
	(calibration_target instrument2 Star5)
	(calibration_target instrument2 GroundStation44)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 GroundStation34)
	(supports instrument3 image3)
	(supports instrument3 thermograph2)
	(calibration_target instrument3 GroundStation13)
	(calibration_target instrument3 GroundStation30)
	(calibration_target instrument3 GroundStation22)
	(calibration_target instrument3 Star6)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 GroundStation37)
	(calibration_target instrument3 Star1)
	(supports instrument4 thermograph2)
	(supports instrument4 infrared4)
	(supports instrument4 infrared0)
	(calibration_target instrument4 Star5)
	(calibration_target instrument4 GroundStation28)
	(calibration_target instrument4 Star1)
	(calibration_target instrument4 Star41)
	(calibration_target instrument4 GroundStation4)
	(calibration_target instrument4 GroundStation20)
	(calibration_target instrument4 Star14)
	(calibration_target instrument4 Star35)
	(calibration_target instrument4 Star10)
	(calibration_target instrument4 GroundStation11)
	(calibration_target instrument4 Star9)
	(calibration_target instrument4 GroundStation17)
	(supports instrument5 thermograph2)
	(supports instrument5 thermograph1)
	(supports instrument5 infrared0)
	(calibration_target instrument5 Star6)
	(calibration_target instrument5 GroundStation43)
	(calibration_target instrument5 GroundStation0)
	(calibration_target instrument5 GroundStation8)
	(supports instrument6 infrared0)
	(supports instrument6 thermograph2)
	(supports instrument6 thermograph1)
	(calibration_target instrument6 Star16)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star1)
	(supports instrument7 infrared4)
	(calibration_target instrument7 Star42)
	(calibration_target instrument7 GroundStation18)
	(calibration_target instrument7 GroundStation44)
	(calibration_target instrument7 GroundStation17)
	(calibration_target instrument7 GroundStation29)
	(calibration_target instrument7 GroundStation11)
	(calibration_target instrument7 GroundStation26)
	(calibration_target instrument7 Star35)
	(calibration_target instrument7 Star9)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star42)
	(supports instrument8 image3)
	(supports instrument8 thermograph1)
	(calibration_target instrument8 GroundStation34)
	(calibration_target instrument8 Star6)
	(calibration_target instrument8 GroundStation0)
	(calibration_target instrument8 GroundStation38)
	(calibration_target instrument8 Star12)
	(calibration_target instrument8 Star40)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation11)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 Star36)
	(calibration_target instrument9 GroundStation37)
	(calibration_target instrument9 GroundStation39)
	(calibration_target instrument9 GroundStation18)
	(calibration_target instrument9 Star10)
	(calibration_target instrument9 Star1)
	(calibration_target instrument9 Star12)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 Star40)
	(calibration_target instrument9 Star24)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 GroundStation43)
	(calibration_target instrument9 Star16)
	(calibration_target instrument9 GroundStation4)
	(on_board instrument9 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation18)
	(supports instrument10 thermograph2)
	(supports instrument10 image3)
	(calibration_target instrument10 Star15)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 Star14)
	(calibration_target instrument10 GroundStation38)
	(calibration_target instrument10 GroundStation28)
	(calibration_target instrument10 Star12)
	(calibration_target instrument10 GroundStation44)
	(calibration_target instrument10 Star1)
	(calibration_target instrument10 Star19)
	(calibration_target instrument10 GroundStation27)
	(calibration_target instrument10 GroundStation18)
	(calibration_target instrument10 GroundStation37)
	(calibration_target instrument10 Star40)
	(calibration_target instrument10 Star7)
	(calibration_target instrument10 GroundStation17)
	(supports instrument11 infrared4)
	(supports instrument11 image3)
	(calibration_target instrument11 GroundStation38)
	(calibration_target instrument11 Star25)
	(calibration_target instrument11 Star7)
	(calibration_target instrument11 GroundStation4)
	(calibration_target instrument11 Star12)
	(calibration_target instrument11 Star1)
	(calibration_target instrument11 Star10)
	(calibration_target instrument11 GroundStation18)
	(calibration_target instrument11 GroundStation27)
	(calibration_target instrument11 GroundStation0)
	(calibration_target instrument11 Star15)
	(calibration_target instrument11 Star35)
	(calibration_target instrument11 GroundStation31)
	(calibration_target instrument11 Star24)
	(supports instrument12 thermograph1)
	(calibration_target instrument12 GroundStation13)
	(supports instrument13 infrared4)
	(supports instrument13 infrared0)
	(supports instrument13 image3)
	(calibration_target instrument13 Star21)
	(calibration_target instrument13 GroundStation39)
	(calibration_target instrument13 Star10)
	(calibration_target instrument13 Star32)
	(calibration_target instrument13 Star1)
	(supports instrument14 thermograph1)
	(calibration_target instrument14 Star36)
	(calibration_target instrument14 GroundStation29)
	(calibration_target instrument14 GroundStation28)
	(calibration_target instrument14 GroundStation20)
	(calibration_target instrument14 GroundStation13)
	(calibration_target instrument14 Star40)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 Star33)
	(calibration_target instrument14 GroundStation0)
	(calibration_target instrument14 GroundStation22)
	(calibration_target instrument14 Star41)
	(calibration_target instrument14 Star1)
	(calibration_target instrument14 Star5)
	(calibration_target instrument14 GroundStation38)
	(supports instrument15 image3)
	(supports instrument15 thermograph1)
	(calibration_target instrument15 Star25)
	(calibration_target instrument15 GroundStation17)
	(calibration_target instrument15 Star40)
	(calibration_target instrument15 GroundStation31)
	(calibration_target instrument15 Star1)
	(calibration_target instrument15 GroundStation39)
	(calibration_target instrument15 Star15)
	(calibration_target instrument15 Star14)
	(calibration_target instrument15 Star5)
	(calibration_target instrument15 Star12)
	(calibration_target instrument15 GroundStation34)
	(calibration_target instrument15 GroundStation8)
	(supports instrument16 image3)
	(supports instrument16 infrared0)
	(supports instrument16 thermograph2)
	(calibration_target instrument16 GroundStation2)
	(calibration_target instrument16 GroundStation17)
	(calibration_target instrument16 Star14)
	(calibration_target instrument16 Star24)
	(calibration_target instrument16 Star15)
	(on_board instrument10 satellite5)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation34)
	(supports instrument17 thermograph1)
	(supports instrument17 thermograph2)
	(supports instrument17 infrared0)
	(calibration_target instrument17 GroundStation22)
	(calibration_target instrument17 GroundStation43)
	(calibration_target instrument17 GroundStation38)
	(calibration_target instrument17 Star24)
	(calibration_target instrument17 GroundStation26)
	(calibration_target instrument17 Star32)
	(calibration_target instrument17 GroundStation37)
	(calibration_target instrument17 GroundStation27)
	(calibration_target instrument17 GroundStation8)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star7)
	(supports instrument18 infrared0)
	(calibration_target instrument18 Star14)
	(calibration_target instrument18 Star42)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 Star7)
	(calibration_target instrument18 Star41)
	(calibration_target instrument18 Star40)
	(calibration_target instrument18 Star19)
	(calibration_target instrument18 GroundStation13)
	(calibration_target instrument18 GroundStation30)
	(calibration_target instrument18 GroundStation20)
	(supports instrument19 infrared0)
	(supports instrument19 thermograph2)
	(calibration_target instrument19 Star19)
	(calibration_target instrument19 Star40)
	(calibration_target instrument19 GroundStation39)
	(calibration_target instrument19 GroundStation4)
	(calibration_target instrument19 Star35)
	(calibration_target instrument19 Star42)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 GroundStation13)
	(calibration_target instrument19 GroundStation11)
	(calibration_target instrument19 GroundStation18)
	(supports instrument20 thermograph2)
	(supports instrument20 thermograph1)
	(calibration_target instrument20 GroundStation13)
	(calibration_target instrument20 Star1)
	(calibration_target instrument20 GroundStation31)
	(calibration_target instrument20 GroundStation27)
	(calibration_target instrument20 GroundStation34)
	(calibration_target instrument20 Star23)
	(calibration_target instrument20 Star21)
	(calibration_target instrument20 Star33)
	(calibration_target instrument20 Star35)
	(supports instrument21 infrared0)
	(calibration_target instrument21 Star40)
	(calibration_target instrument21 Star25)
	(calibration_target instrument21 GroundStation44)
	(calibration_target instrument21 Star5)
	(calibration_target instrument21 Star21)
	(calibration_target instrument21 GroundStation26)
	(supports instrument22 infrared0)
	(supports instrument22 thermograph1)
	(calibration_target instrument22 GroundStation0)
	(calibration_target instrument22 Star33)
	(calibration_target instrument22 Star7)
	(calibration_target instrument22 Star19)
	(calibration_target instrument22 Star12)
	(calibration_target instrument22 GroundStation18)
	(calibration_target instrument22 GroundStation2)
	(calibration_target instrument22 Star42)
	(calibration_target instrument22 Star41)
	(calibration_target instrument22 Star5)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star32)
	(supports instrument23 thermograph1)
	(supports instrument23 infrared4)
	(calibration_target instrument23 Star42)
	(supports instrument24 infrared0)
	(supports instrument24 image3)
	(calibration_target instrument24 Star5)
	(supports instrument25 image3)
	(supports instrument25 infrared0)
	(calibration_target instrument25 GroundStation34)
	(calibration_target instrument25 GroundStation30)
	(supports instrument26 thermograph2)
	(calibration_target instrument26 GroundStation30)
	(calibration_target instrument26 GroundStation31)
	(supports instrument27 infrared0)
	(supports instrument27 infrared4)
	(supports instrument27 image3)
	(calibration_target instrument27 Star19)
	(calibration_target instrument27 GroundStation26)
	(calibration_target instrument27 Star33)
	(calibration_target instrument27 Star21)
	(calibration_target instrument27 GroundStation11)
	(calibration_target instrument27 GroundStation43)
	(calibration_target instrument27 Star36)
	(calibration_target instrument27 Star3)
	(calibration_target instrument27 Star14)
	(calibration_target instrument27 GroundStation31)
	(calibration_target instrument27 Star6)
	(calibration_target instrument27 GroundStation34)
	(calibration_target instrument27 GroundStation13)
	(supports instrument28 infrared4)
	(supports instrument28 infrared0)
	(supports instrument28 thermograph2)
	(calibration_target instrument28 Star7)
	(calibration_target instrument28 GroundStation26)
	(calibration_target instrument28 Star35)
	(calibration_target instrument28 GroundStation38)
	(calibration_target instrument28 GroundStation27)
	(calibration_target instrument28 GroundStation34)
	(calibration_target instrument28 GroundStation44)
	(calibration_target instrument28 Star36)
	(on_board instrument23 satellite8)
	(on_board instrument24 satellite8)
	(on_board instrument25 satellite8)
	(on_board instrument26 satellite8)
	(on_board instrument27 satellite8)
	(on_board instrument28 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star23)
	(supports instrument29 thermograph2)
	(supports instrument29 infrared4)
	(calibration_target instrument29 Star15)
	(calibration_target instrument29 GroundStation13)
	(calibration_target instrument29 GroundStation44)
	(calibration_target instrument29 Star6)
	(calibration_target instrument29 Star24)
	(calibration_target instrument29 Star33)
	(calibration_target instrument29 Star9)
	(calibration_target instrument29 GroundStation18)
	(on_board instrument29 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star40)
)
(:goal (and
	(pointing satellite0 GroundStation2)
	(pointing satellite2 GroundStation38)
	(pointing satellite3 Star41)
	(pointing satellite4 Planet45)
	(pointing satellite7 Phenomenon46)
	(have_image Planet45 thermograph1)
	(have_image Phenomenon46 thermograph2)
))

)
