(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2)
	(:init (on block1 block2) (clear block1) (ontable block2) (handempty))
	(:goal (and (on block1 block2) (clear block1) (ontable block2))))