(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (on block1 block5) (clear block1) (on block2 block6) (on block3 block2) (ontable block4) (clear block4) (ontable block5) (ontable block6) (on block7 block3) (clear block7) (handempty))
	(:goal (and (ontable block1) (ontable block2) (ontable block3) (on block4 block1) (clear block4) (on block5 block2) (on block6 block5) (clear block6) (on block7 block3) (clear block7))))