(define (problem pb8)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (on block1 block3) (on block2 block5) (clear block2) (ontable block3) (on block4 block6) (clear block4) (on block5 block7) (on block6 block1) (ontable block7) (handempty))
	(:goal (and (ontable block1) (on block2 block1) (on block3 block6) (clear block3) (on block4 block7) (clear block4) (on block5 block2) (clear block5) (ontable block6) (ontable block7))))