(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (on block1 block4) (on block2 block7) (on block3 block2) (clear block3) (ontable block4) (on block5 block6) (clear block5) (ontable block6) (on block7 block1) (handempty))
	(:goal (and (ontable block1) (ontable block2) (on block3 block1) (clear block3) (on block4 block6) (on block5 block7) (clear block5) (on block6 block2) (on block7 block4))))