(define (problem pb9)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (on block1 block3) (on block2 block1) (ontable block3) (on block4 block2) (clear block4) (on block5 block6) (ontable block6) (on block7 block5) (clear block7) (handempty))
	(:goal (and (on block1 block6) (clear block1) (on block2 block4) (clear block2) (ontable block3) (clear block3) (ontable block4) (on block5 block7) (on block6 block5) (ontable block7))))