(define (problem pb7)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (on block1 block7) (clear block1) (ontable block2) (on block3 block2) (on block4 block6) (clear block4) (ontable block5) (clear block5) (on block6 block3) (ontable block7) (handempty))
	(:goal (and (on block1 block6) (on block2 block5) (clear block2) (on block3 block4) (on block4 block1) (on block5 block7) (ontable block6) (on block7 block3))))