(define (problem pb5)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (on block1 block5) (on block2 block4) (clear block2) (ontable block3) (on block4 block7) (on block5 block6) (on block6 block3) (on block7 block1) (handempty))
	(:goal (and (on block1 block5) (on block2 block1) (clear block2) (on block3 block7) (ontable block4) (on block5 block6) (on block6 block3) (on block7 block4))))