(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (on block1 block2) (on block2 block4) (on block3 block5) (ontable block4) (ontable block5) (on block6 block1) (clear block6) (on block7 block3) (clear block7) (handempty))
	(:goal (and (on block1 block4) (on block2 block5) (ontable block3) (on block4 block3) (on block5 block1) (on block6 block2) (clear block6) (ontable block7) (clear block7))))