(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite3 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite4 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite5 - satellite
	instrument22 - instrument
	instrument23 - instrument
	satellite6 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite7 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite8 - satellite
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	satellite9 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	thermograph2 - mode
	infrared3 - mode
	thermograph4 - mode
	thermograph0 - mode
	thermograph1 - mode
	GroundStation0 - direction
	Star1 - direction
	Planet2 - direction
	Star3 - direction
)
(:init
	(supports instrument0 thermograph1)
	(calibration_target instrument0 GroundStation0)
	(supports instrument1 infrared3)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 Star1)
	(supports instrument2 thermograph2)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 GroundStation0)
	(supports instrument3 thermograph1)
	(supports instrument3 thermograph4)
	(supports instrument3 infrared3)
	(calibration_target instrument3 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation0)
	(supports instrument4 infrared3)
	(calibration_target instrument4 Star1)
	(supports instrument5 infrared3)
	(supports instrument5 thermograph4)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 Star1)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star1)
	(supports instrument7 infrared3)
	(supports instrument7 thermograph2)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 GroundStation0)
	(supports instrument8 thermograph0)
	(supports instrument8 infrared3)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 Star1)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 Star1)
	(supports instrument10 thermograph4)
	(supports instrument10 thermograph2)
	(supports instrument10 thermograph1)
	(calibration_target instrument10 Star1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star3)
	(supports instrument11 thermograph1)
	(supports instrument11 thermograph2)
	(supports instrument11 infrared3)
	(calibration_target instrument11 GroundStation0)
	(supports instrument12 thermograph2)
	(supports instrument12 thermograph4)
	(supports instrument12 infrared3)
	(calibration_target instrument12 Star1)
	(supports instrument13 thermograph0)
	(supports instrument13 thermograph1)
	(supports instrument13 thermograph2)
	(calibration_target instrument13 GroundStation0)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument14 thermograph1)
	(supports instrument14 thermograph2)
	(supports instrument14 thermograph0)
	(calibration_target instrument14 Star1)
	(supports instrument15 thermograph2)
	(calibration_target instrument15 GroundStation0)
	(supports instrument16 thermograph0)
	(calibration_target instrument16 GroundStation0)
	(supports instrument17 thermograph2)
	(supports instrument17 thermograph0)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 Star1)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 GroundStation0)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star1)
	(supports instrument19 thermograph2)
	(supports instrument19 thermograph1)
	(calibration_target instrument19 GroundStation0)
	(supports instrument20 thermograph2)
	(supports instrument20 infrared3)
	(calibration_target instrument20 Star1)
	(supports instrument21 thermograph4)
	(supports instrument21 thermograph2)
	(calibration_target instrument21 GroundStation0)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation0)
	(supports instrument22 thermograph1)
	(supports instrument22 infrared3)
	(supports instrument22 thermograph0)
	(calibration_target instrument22 GroundStation0)
	(supports instrument23 thermograph1)
	(supports instrument23 thermograph2)
	(supports instrument23 thermograph0)
	(calibration_target instrument23 GroundStation0)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(supports instrument24 infrared3)
	(supports instrument24 thermograph2)
	(supports instrument24 thermograph0)
	(calibration_target instrument24 Star1)
	(supports instrument25 thermograph0)
	(calibration_target instrument25 Star1)
	(supports instrument26 thermograph4)
	(supports instrument26 thermograph1)
	(supports instrument26 infrared3)
	(calibration_target instrument26 Star1)
	(supports instrument27 thermograph0)
	(supports instrument27 thermograph1)
	(supports instrument27 infrared3)
	(calibration_target instrument27 GroundStation0)
	(on_board instrument24 satellite6)
	(on_board instrument25 satellite6)
	(on_board instrument26 satellite6)
	(on_board instrument27 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet2)
	(supports instrument28 thermograph4)
	(supports instrument28 thermograph0)
	(calibration_target instrument28 GroundStation0)
	(supports instrument29 infrared3)
	(supports instrument29 thermograph4)
	(calibration_target instrument29 Star1)
	(supports instrument30 thermograph0)
	(calibration_target instrument30 GroundStation0)
	(supports instrument31 thermograph4)
	(supports instrument31 thermograph1)
	(calibration_target instrument31 Star1)
	(supports instrument32 thermograph0)
	(supports instrument32 infrared3)
	(supports instrument32 thermograph1)
	(calibration_target instrument32 GroundStation0)
	(supports instrument33 thermograph2)
	(supports instrument33 infrared3)
	(calibration_target instrument33 Star1)
	(supports instrument34 thermograph0)
	(supports instrument34 thermograph1)
	(calibration_target instrument34 Star1)
	(supports instrument35 thermograph0)
	(calibration_target instrument35 Star1)
	(on_board instrument28 satellite7)
	(on_board instrument29 satellite7)
	(on_board instrument30 satellite7)
	(on_board instrument31 satellite7)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation0)
	(supports instrument36 infrared3)
	(supports instrument36 thermograph0)
	(calibration_target instrument36 GroundStation0)
	(supports instrument37 thermograph0)
	(supports instrument37 thermograph1)
	(calibration_target instrument37 Star1)
	(supports instrument38 infrared3)
	(calibration_target instrument38 GroundStation0)
	(supports instrument39 infrared3)
	(supports instrument39 thermograph0)
	(supports instrument39 thermograph1)
	(calibration_target instrument39 GroundStation0)
	(supports instrument40 infrared3)
	(calibration_target instrument40 Star1)
	(supports instrument41 infrared3)
	(supports instrument41 thermograph0)
	(calibration_target instrument41 Star1)
	(supports instrument42 thermograph2)
	(supports instrument42 thermograph1)
	(supports instrument42 thermograph0)
	(calibration_target instrument42 GroundStation0)
	(on_board instrument36 satellite8)
	(on_board instrument37 satellite8)
	(on_board instrument38 satellite8)
	(on_board instrument39 satellite8)
	(on_board instrument40 satellite8)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet2)
	(supports instrument43 thermograph1)
	(supports instrument43 infrared3)
	(calibration_target instrument43 Star1)
	(supports instrument44 thermograph0)
	(supports instrument44 thermograph1)
	(calibration_target instrument44 Star1)
	(supports instrument45 infrared3)
	(supports instrument45 thermograph0)
	(calibration_target instrument45 Star1)
	(supports instrument46 infrared3)
	(supports instrument46 thermograph4)
	(calibration_target instrument46 GroundStation0)
	(supports instrument47 thermograph0)
	(calibration_target instrument47 GroundStation0)
	(supports instrument48 thermograph1)
	(supports instrument48 thermograph0)
	(supports instrument48 thermograph4)
	(calibration_target instrument48 Star1)
	(on_board instrument43 satellite9)
	(on_board instrument44 satellite9)
	(on_board instrument45 satellite9)
	(on_board instrument46 satellite9)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet2)
)
(:goal (and
	(pointing satellite0 Star3)
	(pointing satellite1 Star1)
	(pointing satellite5 Star3)
	(pointing satellite7 Planet2)
	(have_image Planet2 thermograph1)
	(have_image Star3 thermograph1)
))

)
