(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite2 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite3 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite4 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite5 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite6 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	satellite7 - satellite
	instrument41 - instrument
	instrument42 - instrument
	satellite8 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	satellite9 - satellite
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	image1 - mode
	infrared3 - mode
	image0 - mode
	infrared4 - mode
	infrared2 - mode
	Star1 - direction
	GroundStation0 - direction
	Planet2 - direction
	Star3 - direction
)
(:init
	(supports instrument0 image0)
	(supports instrument0 image1)
	(calibration_target instrument0 GroundStation0)
	(supports instrument1 infrared4)
	(supports instrument1 infrared3)
	(supports instrument1 image0)
	(calibration_target instrument1 Star1)
	(supports instrument2 infrared4)
	(supports instrument2 image1)
	(supports instrument2 image0)
	(calibration_target instrument2 Star1)
	(supports instrument3 image0)
	(supports instrument3 infrared2)
	(calibration_target instrument3 GroundStation0)
	(supports instrument4 infrared3)
	(supports instrument4 image0)
	(calibration_target instrument4 GroundStation0)
	(supports instrument5 infrared3)
	(calibration_target instrument5 Star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star3)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star1)
	(supports instrument7 infrared2)
	(calibration_target instrument7 Star1)
	(supports instrument8 infrared2)
	(supports instrument8 infrared3)
	(supports instrument8 infrared4)
	(calibration_target instrument8 Star1)
	(supports instrument9 image1)
	(supports instrument9 infrared4)
	(supports instrument9 infrared2)
	(calibration_target instrument9 GroundStation0)
	(supports instrument10 image1)
	(supports instrument10 image0)
	(supports instrument10 infrared2)
	(calibration_target instrument10 Star1)
	(supports instrument11 infrared3)
	(supports instrument11 image0)
	(calibration_target instrument11 GroundStation0)
	(supports instrument12 image1)
	(supports instrument12 image0)
	(supports instrument12 infrared2)
	(calibration_target instrument12 GroundStation0)
	(supports instrument13 image1)
	(supports instrument13 infrared4)
	(calibration_target instrument13 GroundStation0)
	(supports instrument14 image0)
	(calibration_target instrument14 GroundStation0)
	(supports instrument15 image1)
	(calibration_target instrument15 Star1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet2)
	(supports instrument16 infrared2)
	(supports instrument16 infrared3)
	(calibration_target instrument16 Star1)
	(supports instrument17 infrared4)
	(calibration_target instrument17 Star1)
	(supports instrument18 infrared2)
	(calibration_target instrument18 GroundStation0)
	(supports instrument19 image0)
	(supports instrument19 image1)
	(calibration_target instrument19 GroundStation0)
	(supports instrument20 image0)
	(calibration_target instrument20 GroundStation0)
	(supports instrument21 infrared2)
	(supports instrument21 image0)
	(supports instrument21 infrared4)
	(calibration_target instrument21 Star1)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star1)
	(supports instrument22 infrared3)
	(supports instrument22 infrared4)
	(supports instrument22 image1)
	(calibration_target instrument22 Star1)
	(supports instrument23 infrared4)
	(supports instrument23 infrared2)
	(calibration_target instrument23 Star1)
	(supports instrument24 image0)
	(calibration_target instrument24 Star1)
	(supports instrument25 infrared3)
	(supports instrument25 image1)
	(supports instrument25 infrared2)
	(calibration_target instrument25 Star1)
	(supports instrument26 image1)
	(calibration_target instrument26 Star1)
	(supports instrument27 infrared3)
	(calibration_target instrument27 GroundStation0)
	(supports instrument28 infrared4)
	(supports instrument28 image1)
	(calibration_target instrument28 GroundStation0)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star3)
	(supports instrument29 image1)
	(supports instrument29 infrared3)
	(calibration_target instrument29 GroundStation0)
	(supports instrument30 infrared4)
	(calibration_target instrument30 GroundStation0)
	(supports instrument31 infrared3)
	(supports instrument31 image0)
	(supports instrument31 image1)
	(calibration_target instrument31 Star1)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star1)
	(supports instrument32 image0)
	(supports instrument32 infrared2)
	(supports instrument32 image1)
	(calibration_target instrument32 GroundStation0)
	(supports instrument33 image0)
	(calibration_target instrument33 Star1)
	(supports instrument34 image1)
	(supports instrument34 image0)
	(supports instrument34 infrared3)
	(calibration_target instrument34 Star1)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(supports instrument35 infrared2)
	(calibration_target instrument35 GroundStation0)
	(supports instrument36 infrared2)
	(supports instrument36 image0)
	(supports instrument36 infrared4)
	(calibration_target instrument36 GroundStation0)
	(supports instrument37 image0)
	(supports instrument37 image1)
	(supports instrument37 infrared2)
	(calibration_target instrument37 Star1)
	(supports instrument38 image1)
	(supports instrument38 image0)
	(calibration_target instrument38 Star1)
	(supports instrument39 image0)
	(supports instrument39 infrared4)
	(supports instrument39 infrared2)
	(calibration_target instrument39 Star1)
	(supports instrument40 infrared4)
	(calibration_target instrument40 Star1)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet2)
	(supports instrument41 image0)
	(supports instrument41 infrared4)
	(supports instrument41 image1)
	(calibration_target instrument41 GroundStation0)
	(supports instrument42 image0)
	(supports instrument42 infrared2)
	(calibration_target instrument42 Star1)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation0)
	(supports instrument43 infrared2)
	(calibration_target instrument43 Star1)
	(supports instrument44 image1)
	(supports instrument44 infrared3)
	(calibration_target instrument44 Star1)
	(supports instrument45 image0)
	(supports instrument45 infrared4)
	(calibration_target instrument45 GroundStation0)
	(supports instrument46 infrared4)
	(calibration_target instrument46 Star1)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star1)
	(supports instrument47 image1)
	(calibration_target instrument47 Star1)
	(supports instrument48 infrared3)
	(supports instrument48 infrared2)
	(supports instrument48 image0)
	(calibration_target instrument48 Star1)
	(supports instrument49 infrared3)
	(supports instrument49 image1)
	(supports instrument49 infrared4)
	(calibration_target instrument49 GroundStation0)
	(supports instrument50 image0)
	(supports instrument50 infrared3)
	(supports instrument50 infrared4)
	(calibration_target instrument50 Star1)
	(supports instrument51 infrared3)
	(calibration_target instrument51 GroundStation0)
	(supports instrument52 infrared3)
	(supports instrument52 infrared4)
	(calibration_target instrument52 GroundStation0)
	(supports instrument53 infrared4)
	(supports instrument53 image0)
	(calibration_target instrument53 Star1)
	(supports instrument54 infrared2)
	(supports instrument54 infrared4)
	(supports instrument54 image0)
	(calibration_target instrument54 GroundStation0)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star3)
)
(:goal (and
	(pointing satellite1 Star3)
	(pointing satellite5 Star1)
	(pointing satellite7 Planet2)
	(have_image Planet2 infrared4)
	(have_image Star3 infrared2)
))

)
