(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite2 - satellite
	instrument13 - instrument
	satellite3 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite4 - satellite
	instrument17 - instrument
	instrument18 - instrument
	satellite5 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite6 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite7 - satellite
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	satellite8 - satellite
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	satellite9 - satellite
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	thermograph1 - mode
	infrared2 - mode
	infrared3 - mode
	spectrograph0 - mode
	image4 - mode
	GroundStation1 - direction
	Star0 - direction
	Star2 - direction
	Star3 - direction
)
(:init
	(supports instrument0 thermograph1)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 thermograph1)
	(supports instrument1 infrared3)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 infrared3)
	(supports instrument2 infrared2)
	(calibration_target instrument2 GroundStation1)
	(supports instrument3 thermograph1)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 thermograph1)
	(calibration_target instrument4 Star0)
	(supports instrument5 thermograph1)
	(supports instrument5 infrared3)
	(calibration_target instrument5 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star2)
	(supports instrument6 spectrograph0)
	(supports instrument6 infrared2)
	(calibration_target instrument6 GroundStation1)
	(supports instrument7 spectrograph0)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star0)
	(supports instrument8 infrared2)
	(supports instrument8 image4)
	(calibration_target instrument8 Star0)
	(supports instrument9 infrared2)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 image4)
	(calibration_target instrument10 Star0)
	(supports instrument11 infrared3)
	(calibration_target instrument11 Star0)
	(supports instrument12 image4)
	(supports instrument12 thermograph1)
	(calibration_target instrument12 Star0)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument13 spectrograph0)
	(supports instrument13 infrared3)
	(supports instrument13 image4)
	(calibration_target instrument13 GroundStation1)
	(on_board instrument13 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument14 infrared3)
	(supports instrument14 infrared2)
	(supports instrument14 spectrograph0)
	(calibration_target instrument14 GroundStation1)
	(supports instrument15 infrared2)
	(supports instrument15 thermograph1)
	(calibration_target instrument15 GroundStation1)
	(supports instrument16 thermograph1)
	(calibration_target instrument16 Star0)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star2)
	(supports instrument17 infrared3)
	(supports instrument17 image4)
	(calibration_target instrument17 Star0)
	(supports instrument18 thermograph1)
	(supports instrument18 image4)
	(calibration_target instrument18 Star0)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star3)
	(supports instrument19 infrared2)
	(supports instrument19 infrared3)
	(supports instrument19 image4)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 infrared3)
	(calibration_target instrument20 GroundStation1)
	(supports instrument21 thermograph1)
	(supports instrument21 infrared3)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 Star0)
	(supports instrument22 thermograph1)
	(supports instrument22 spectrograph0)
	(supports instrument22 infrared2)
	(calibration_target instrument22 Star0)
	(supports instrument23 thermograph1)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 infrared2)
	(calibration_target instrument24 GroundStation1)
	(supports instrument25 thermograph1)
	(calibration_target instrument25 GroundStation1)
	(supports instrument26 infrared2)
	(supports instrument26 thermograph1)
	(calibration_target instrument26 GroundStation1)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation1)
	(supports instrument27 image4)
	(supports instrument27 thermograph1)
	(supports instrument27 infrared3)
	(calibration_target instrument27 Star0)
	(supports instrument28 infrared2)
	(supports instrument28 thermograph1)
	(calibration_target instrument28 GroundStation1)
	(supports instrument29 infrared2)
	(supports instrument29 image4)
	(supports instrument29 infrared3)
	(calibration_target instrument29 Star0)
	(supports instrument30 image4)
	(supports instrument30 infrared3)
	(supports instrument30 infrared2)
	(calibration_target instrument30 Star0)
	(supports instrument31 thermograph1)
	(calibration_target instrument31 GroundStation1)
	(supports instrument32 image4)
	(supports instrument32 infrared3)
	(calibration_target instrument32 GroundStation1)
	(supports instrument33 spectrograph0)
	(calibration_target instrument33 GroundStation1)
	(supports instrument34 infrared3)
	(supports instrument34 infrared2)
	(calibration_target instrument34 Star0)
	(supports instrument35 image4)
	(calibration_target instrument35 GroundStation1)
	(supports instrument36 infrared3)
	(calibration_target instrument36 GroundStation1)
	(on_board instrument27 satellite6)
	(on_board instrument28 satellite6)
	(on_board instrument29 satellite6)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star3)
	(supports instrument37 infrared2)
	(calibration_target instrument37 Star0)
	(supports instrument38 infrared2)
	(supports instrument38 infrared3)
	(calibration_target instrument38 GroundStation1)
	(supports instrument39 image4)
	(supports instrument39 infrared2)
	(calibration_target instrument39 GroundStation1)
	(supports instrument40 image4)
	(supports instrument40 infrared3)
	(supports instrument40 spectrograph0)
	(calibration_target instrument40 Star0)
	(supports instrument41 spectrograph0)
	(supports instrument41 thermograph1)
	(calibration_target instrument41 GroundStation1)
	(supports instrument42 image4)
	(supports instrument42 infrared3)
	(supports instrument42 spectrograph0)
	(calibration_target instrument42 GroundStation1)
	(supports instrument43 image4)
	(supports instrument43 thermograph1)
	(supports instrument43 infrared2)
	(calibration_target instrument43 GroundStation1)
	(supports instrument44 thermograph1)
	(supports instrument44 infrared2)
	(calibration_target instrument44 GroundStation1)
	(supports instrument45 spectrograph0)
	(supports instrument45 thermograph1)
	(supports instrument45 infrared3)
	(calibration_target instrument45 Star0)
	(supports instrument46 image4)
	(supports instrument46 spectrograph0)
	(calibration_target instrument46 Star0)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
	(supports instrument47 image4)
	(supports instrument47 infrared3)
	(calibration_target instrument47 Star0)
	(supports instrument48 thermograph1)
	(calibration_target instrument48 Star0)
	(supports instrument49 thermograph1)
	(supports instrument49 infrared3)
	(supports instrument49 infrared2)
	(calibration_target instrument49 Star0)
	(supports instrument50 spectrograph0)
	(supports instrument50 infrared3)
	(supports instrument50 image4)
	(calibration_target instrument50 GroundStation1)
	(supports instrument51 thermograph1)
	(supports instrument51 infrared3)
	(supports instrument51 spectrograph0)
	(calibration_target instrument51 Star0)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star3)
	(supports instrument52 infrared3)
	(supports instrument52 spectrograph0)
	(calibration_target instrument52 Star0)
	(supports instrument53 infrared3)
	(calibration_target instrument53 Star0)
	(supports instrument54 spectrograph0)
	(supports instrument54 infrared2)
	(supports instrument54 infrared3)
	(calibration_target instrument54 GroundStation1)
	(supports instrument55 infrared2)
	(calibration_target instrument55 Star0)
	(supports instrument56 infrared2)
	(supports instrument56 image4)
	(supports instrument56 infrared3)
	(calibration_target instrument56 Star0)
	(supports instrument57 infrared2)
	(supports instrument57 image4)
	(calibration_target instrument57 GroundStation1)
	(supports instrument58 spectrograph0)
	(supports instrument58 infrared3)
	(supports instrument58 infrared2)
	(calibration_target instrument58 Star0)
	(supports instrument59 image4)
	(supports instrument59 spectrograph0)
	(supports instrument59 infrared3)
	(calibration_target instrument59 Star0)
	(supports instrument60 image4)
	(calibration_target instrument60 Star0)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(on_board instrument59 satellite9)
	(on_board instrument60 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star2)
)
(:goal (and
	(pointing satellite0 Star2)
	(pointing satellite2 Star3)
	(pointing satellite4 Star0)
	(pointing satellite8 Star0)
	(pointing satellite9 Star3)
	(have_image Star3 thermograph1)
))

)
