(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite2 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite3 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite4 - satellite
	instrument28 - instrument
	satellite5 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	satellite6 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	satellite7 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite8 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	satellite9 - satellite
	instrument51 - instrument
	instrument52 - instrument
	image0 - mode
	infrared1 - mode
	infrared3 - mode
	thermograph2 - mode
	infrared4 - mode
	Star0 - direction
	Star1 - direction
	Star2 - direction
	Phenomenon3 - direction
)
(:init
	(supports instrument0 infrared1)
	(supports instrument0 image0)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 Star1)
	(supports instrument1 infrared3)
	(calibration_target instrument1 Star1)
	(supports instrument2 image0)
	(supports instrument2 thermograph2)
	(supports instrument2 infrared4)
	(calibration_target instrument2 Star1)
	(supports instrument3 infrared4)
	(supports instrument3 infrared3)
	(calibration_target instrument3 Star1)
	(supports instrument4 infrared1)
	(calibration_target instrument4 Star1)
	(supports instrument5 infrared1)
	(calibration_target instrument5 Star0)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star1)
	(supports instrument7 thermograph2)
	(supports instrument7 image0)
	(calibration_target instrument7 Star1)
	(supports instrument8 infrared3)
	(calibration_target instrument8 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star1)
	(supports instrument9 thermograph2)
	(supports instrument9 infrared4)
	(calibration_target instrument9 Star1)
	(supports instrument10 infrared3)
	(calibration_target instrument10 Star0)
	(supports instrument11 infrared1)
	(supports instrument11 infrared4)
	(supports instrument11 infrared3)
	(calibration_target instrument11 Star0)
	(supports instrument12 infrared4)
	(supports instrument12 infrared3)
	(calibration_target instrument12 Star0)
	(supports instrument13 thermograph2)
	(supports instrument13 infrared3)
	(supports instrument13 infrared4)
	(calibration_target instrument13 Star1)
	(supports instrument14 thermograph2)
	(supports instrument14 infrared3)
	(supports instrument14 infrared1)
	(calibration_target instrument14 Star0)
	(supports instrument15 infrared3)
	(supports instrument15 infrared1)
	(supports instrument15 thermograph2)
	(calibration_target instrument15 Star0)
	(supports instrument16 infrared1)
	(supports instrument16 thermograph2)
	(calibration_target instrument16 Star1)
	(supports instrument17 infrared3)
	(calibration_target instrument17 Star0)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(on_board instrument17 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon3)
	(supports instrument18 infrared3)
	(calibration_target instrument18 Star1)
	(supports instrument19 infrared4)
	(supports instrument19 image0)
	(supports instrument19 thermograph2)
	(calibration_target instrument19 Star1)
	(supports instrument20 infrared4)
	(calibration_target instrument20 Star1)
	(supports instrument21 infrared1)
	(calibration_target instrument21 Star1)
	(supports instrument22 infrared1)
	(supports instrument22 infrared4)
	(calibration_target instrument22 Star0)
	(supports instrument23 thermograph2)
	(supports instrument23 image0)
	(calibration_target instrument23 Star1)
	(supports instrument24 infrared1)
	(calibration_target instrument24 Star0)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(on_board instrument22 satellite2)
	(on_board instrument23 satellite2)
	(on_board instrument24 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon3)
	(supports instrument25 thermograph2)
	(calibration_target instrument25 Star1)
	(supports instrument26 infrared1)
	(supports instrument26 infrared3)
	(supports instrument26 thermograph2)
	(calibration_target instrument26 Star0)
	(supports instrument27 infrared4)
	(supports instrument27 image0)
	(calibration_target instrument27 Star0)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star1)
	(supports instrument28 infrared1)
	(supports instrument28 image0)
	(calibration_target instrument28 Star1)
	(on_board instrument28 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument29 image0)
	(supports instrument29 thermograph2)
	(supports instrument29 infrared3)
	(calibration_target instrument29 Star1)
	(supports instrument30 infrared3)
	(supports instrument30 image0)
	(supports instrument30 infrared4)
	(calibration_target instrument30 Star1)
	(supports instrument31 infrared3)
	(supports instrument31 thermograph2)
	(calibration_target instrument31 Star0)
	(supports instrument32 image0)
	(calibration_target instrument32 Star0)
	(supports instrument33 image0)
	(calibration_target instrument33 Star0)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star0)
	(supports instrument34 infrared1)
	(calibration_target instrument34 Star1)
	(supports instrument35 image0)
	(supports instrument35 thermograph2)
	(supports instrument35 infrared3)
	(calibration_target instrument35 Star1)
	(supports instrument36 image0)
	(calibration_target instrument36 Star1)
	(supports instrument37 infrared1)
	(supports instrument37 thermograph2)
	(supports instrument37 image0)
	(calibration_target instrument37 Star1)
	(supports instrument38 infrared3)
	(calibration_target instrument38 Star0)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon3)
	(supports instrument39 infrared3)
	(supports instrument39 image0)
	(calibration_target instrument39 Star0)
	(supports instrument40 infrared3)
	(supports instrument40 infrared4)
	(supports instrument40 image0)
	(calibration_target instrument40 Star1)
	(supports instrument41 infrared3)
	(supports instrument41 infrared1)
	(supports instrument41 thermograph2)
	(calibration_target instrument41 Star1)
	(supports instrument42 image0)
	(supports instrument42 thermograph2)
	(calibration_target instrument42 Star0)
	(supports instrument43 image0)
	(supports instrument43 infrared1)
	(supports instrument43 infrared4)
	(calibration_target instrument43 Star0)
	(supports instrument44 infrared1)
	(calibration_target instrument44 Star1)
	(supports instrument45 infrared4)
	(supports instrument45 infrared3)
	(calibration_target instrument45 Star1)
	(supports instrument46 infrared3)
	(supports instrument46 thermograph2)
	(supports instrument46 infrared4)
	(calibration_target instrument46 Star0)
	(supports instrument47 image0)
	(supports instrument47 infrared3)
	(supports instrument47 infrared4)
	(calibration_target instrument47 Star0)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
	(supports instrument48 thermograph2)
	(supports instrument48 infrared3)
	(supports instrument48 infrared1)
	(calibration_target instrument48 Star1)
	(supports instrument49 thermograph2)
	(calibration_target instrument49 Star1)
	(supports instrument50 thermograph2)
	(calibration_target instrument50 Star0)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star2)
	(supports instrument51 infrared4)
	(calibration_target instrument51 Star0)
	(supports instrument52 infrared4)
	(calibration_target instrument52 Star1)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star1)
)
(:goal (and
	(pointing satellite1 Star0)
	(pointing satellite2 Star0)
	(pointing satellite4 Phenomenon3)
	(pointing satellite8 Star1)
	(have_image Star2 infrared1)
))

)
