(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (on block1 block3) (clear block1) (ontable block2) (on block3 block2) (on block4 block5) (clear block4) (ontable block5) (handempty))
	(:goal (and (on block1 block4) (on block2 block1) (on block3 block2) (ontable block4) (on block5 block3) (clear block5))))