(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (ontable block1) (on block2 block5) (clear block2) (on block3 block1) (on block4 block3) (clear block4) (ontable block5) (handempty))
	(:goal (and (ontable block1) (ontable block2) (on block3 block5) (clear block3) (on block4 block1) (clear block4) (on block5 block2))))