(define (problem pb9)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (ontable block1) (clear block1) (on block2 block3) (clear block2) (ontable block3) (ontable block4) (clear block4) (ontable block5) (clear block5) (handempty))
	(:goal (and (on block1 block2) (clear block1) (on block2 block4) (ontable block3) (ontable block4) (on block5 block3) (clear block5))))