(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5)
	(:init (on block1 block5) (on block2 block1) (clear block2) (ontable block3) (on block4 block3) (clear block4) (ontable block5) (handempty))
	(:goal (and (on block1 block5) (ontable block2) (on block3 block1) (on block4 block3) (clear block4) (on block5 block2))))