(define (problem pb2)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (ontable block1) (on block2 block8) (on block3 block6) (clear block3) (on block4 block5) (clear block4) (on block5 block2) (on block6 block7) (on block7 block1) (ontable block8) (handempty))
	(:goal (and (on block1 block7) (on block2 block5) (on block3 block1) (on block4 block6) (on block5 block4) (on block6 block3) (ontable block7) (on block8 block2) (clear block8))))