(define (problem pb6)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (on block1 block2) (on block2 block6) (on block3 block5) (clear block3) (ontable block4) (on block5 block8) (ontable block6) (on block7 block1) (clear block7) (on block8 block4) (handempty))
	(:goal (and (on block1 block2) (on block2 block4) (on block3 block8) (clear block3) (on block4 block5) (on block5 block6) (on block6 block7) (ontable block7) (on block8 block1))))