(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (on block1 block3) (clear block1) (ontable block2) (on block3 block8) (on block4 block6) (on block5 block7) (clear block5) (ontable block6) (on block7 block2) (on block8 block4) (handempty))
	(:goal (and (on block1 block7) (clear block1) (ontable block2) (ontable block3) (on block4 block5) (on block5 block3) (on block6 block2) (clear block6) (ontable block7) (on block8 block4) (clear block8))))