(define (problem pb3)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (on block1 block4) (clear block1) (ontable block2) (clear block2) (on block3 block6) (on block4 block3) (ontable block5) (clear block5) (ontable block6) (ontable block7) (clear block7) (ontable block8) (clear block8) (handempty))
	(:goal (and (on block1 block6) (on block2 block5) (on block3 block1) (clear block3) (on block4 block2) (on block5 block8) (ontable block6) (on block7 block4) (clear block7) (ontable block8))))