(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (ontable block1) (on block2 block5) (on block3 block4) (clear block3) (on block4 block1) (on block5 block8) (on block6 block2) (clear block6) (ontable block7) (on block8 block7) (handempty))
	(:goal (and (ontable block1) (clear block1) (ontable block2) (on block3 block7) (clear block3) (on block4 block5) (clear block4) (ontable block5) (ontable block6) (clear block6) (on block7 block8) (on block8 block2))))