(define (problem pb9)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (on block1 block4) (clear block1) (on block2 block7) (on block3 block5) (on block4 block8) (on block5 block2) (ontable block6) (clear block6) (ontable block7) (on block8 block3) (handempty))
	(:goal (and (on block1 block8) (on block2 block6) (ontable block3) (ontable block4) (clear block4) (on block5 block2) (clear block5) (on block6 block3) (on block7 block1) (clear block7) (ontable block8))))