(define (problem pb8)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7 block8)
	(:init (on block1 block6) (on block2 block1) (on block3 block2) (on block4 block3) (clear block4) (on block5 block7) (on block6 block8) (ontable block7) (on block8 block5) (handempty))
	(:goal (and (on block1 block2) (on block2 block4) (on block3 block8) (clear block3) (on block4 block7) (on block5 block1) (on block6 block5) (clear block6) (ontable block7) (ontable block8))))