(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite2 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite3 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite4 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite5 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	satellite6 - satellite
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	satellite7 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	satellite8 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	satellite9 - satellite
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	infrared2 - mode
	thermograph0 - mode
	thermograph3 - mode
	image1 - mode
	spectrograph4 - mode
	Star0 - direction
	Star6 - direction
	GroundStation4 - direction
	Star2 - direction
	Star7 - direction
	GroundStation1 - direction
	Star5 - direction
	GroundStation3 - direction
	Planet8 - direction
	Phenomenon9 - direction
)
(:init
	(supports instrument0 thermograph3)
	(supports instrument0 infrared2)
	(supports instrument0 thermograph0)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 Star2)
	(supports instrument1 thermograph0)
	(supports instrument1 thermograph3)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 Star6)
	(supports instrument2 thermograph3)
	(supports instrument2 spectrograph4)
	(supports instrument2 infrared2)
	(calibration_target instrument2 GroundStation4)
	(supports instrument3 thermograph3)
	(supports instrument3 infrared2)
	(supports instrument3 spectrograph4)
	(calibration_target instrument3 Star2)
	(calibration_target instrument3 GroundStation3)
	(supports instrument4 image1)
	(calibration_target instrument4 GroundStation1)
	(calibration_target instrument4 Star6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation4)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 Star5)
	(calibration_target instrument5 GroundStation4)
	(supports instrument6 thermograph3)
	(calibration_target instrument6 Star5)
	(calibration_target instrument6 GroundStation1)
	(supports instrument7 spectrograph4)
	(calibration_target instrument7 Star2)
	(supports instrument8 thermograph3)
	(supports instrument8 image1)
	(supports instrument8 spectrograph4)
	(calibration_target instrument8 Star6)
	(calibration_target instrument8 Star2)
	(supports instrument9 thermograph3)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 Star5)
	(supports instrument10 infrared2)
	(calibration_target instrument10 GroundStation3)
	(supports instrument11 thermograph0)
	(supports instrument11 spectrograph4)
	(supports instrument11 image1)
	(calibration_target instrument11 GroundStation4)
	(calibration_target instrument11 Star2)
	(supports instrument12 thermograph0)
	(supports instrument12 infrared2)
	(calibration_target instrument12 Star7)
	(supports instrument13 spectrograph4)
	(supports instrument13 image1)
	(supports instrument13 infrared2)
	(calibration_target instrument13 Star6)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star5)
	(supports instrument14 thermograph3)
	(calibration_target instrument14 GroundStation3)
	(calibration_target instrument14 GroundStation1)
	(supports instrument15 image1)
	(supports instrument15 thermograph3)
	(calibration_target instrument15 Star0)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument16 infrared2)
	(supports instrument16 thermograph3)
	(calibration_target instrument16 Star0)
	(calibration_target instrument16 Star6)
	(supports instrument17 image1)
	(supports instrument17 thermograph0)
	(supports instrument17 spectrograph4)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 GroundStation1)
	(supports instrument18 infrared2)
	(supports instrument18 thermograph0)
	(calibration_target instrument18 Star7)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation4)
	(supports instrument19 thermograph0)
	(supports instrument19 infrared2)
	(supports instrument19 spectrograph4)
	(calibration_target instrument19 GroundStation1)
	(calibration_target instrument19 Star2)
	(supports instrument20 spectrograph4)
	(supports instrument20 thermograph0)
	(supports instrument20 infrared2)
	(calibration_target instrument20 GroundStation1)
	(supports instrument21 thermograph3)
	(supports instrument21 thermograph0)
	(supports instrument21 image1)
	(calibration_target instrument21 GroundStation3)
	(calibration_target instrument21 Star5)
	(supports instrument22 spectrograph4)
	(calibration_target instrument22 GroundStation3)
	(supports instrument23 thermograph3)
	(supports instrument23 spectrograph4)
	(supports instrument23 image1)
	(calibration_target instrument23 Star7)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star5)
	(supports instrument24 thermograph3)
	(calibration_target instrument24 GroundStation4)
	(calibration_target instrument24 Star7)
	(supports instrument25 spectrograph4)
	(supports instrument25 image1)
	(calibration_target instrument25 Star0)
	(calibration_target instrument25 Star7)
	(supports instrument26 thermograph0)
	(supports instrument26 infrared2)
	(supports instrument26 image1)
	(calibration_target instrument26 GroundStation3)
	(supports instrument27 infrared2)
	(supports instrument27 thermograph0)
	(supports instrument27 spectrograph4)
	(calibration_target instrument27 Star7)
	(calibration_target instrument27 GroundStation1)
	(supports instrument28 image1)
	(supports instrument28 thermograph3)
	(calibration_target instrument28 Star5)
	(calibration_target instrument28 GroundStation1)
	(supports instrument29 spectrograph4)
	(supports instrument29 thermograph3)
	(calibration_target instrument29 Star5)
	(calibration_target instrument29 GroundStation3)
	(supports instrument30 thermograph0)
	(calibration_target instrument30 Star0)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation1)
	(supports instrument31 spectrograph4)
	(supports instrument31 thermograph3)
	(supports instrument31 image1)
	(calibration_target instrument31 Star5)
	(calibration_target instrument31 Star6)
	(supports instrument32 infrared2)
	(supports instrument32 spectrograph4)
	(calibration_target instrument32 Star6)
	(calibration_target instrument32 GroundStation3)
	(supports instrument33 thermograph3)
	(supports instrument33 spectrograph4)
	(supports instrument33 infrared2)
	(calibration_target instrument33 Star6)
	(calibration_target instrument33 Star0)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star2)
	(supports instrument34 thermograph0)
	(supports instrument34 thermograph3)
	(supports instrument34 infrared2)
	(calibration_target instrument34 Star2)
	(supports instrument35 image1)
	(supports instrument35 spectrograph4)
	(supports instrument35 thermograph3)
	(calibration_target instrument35 Star6)
	(calibration_target instrument35 GroundStation1)
	(supports instrument36 image1)
	(supports instrument36 thermograph3)
	(supports instrument36 thermograph0)
	(calibration_target instrument36 GroundStation4)
	(calibration_target instrument36 Star6)
	(supports instrument37 thermograph0)
	(supports instrument37 spectrograph4)
	(supports instrument37 infrared2)
	(calibration_target instrument37 Star5)
	(supports instrument38 thermograph0)
	(calibration_target instrument38 Star0)
	(calibration_target instrument38 Star7)
	(supports instrument39 thermograph3)
	(calibration_target instrument39 Star2)
	(calibration_target instrument39 Star0)
	(supports instrument40 thermograph0)
	(supports instrument40 infrared2)
	(calibration_target instrument40 Star6)
	(supports instrument41 spectrograph4)
	(calibration_target instrument41 GroundStation4)
	(supports instrument42 thermograph0)
	(supports instrument42 thermograph3)
	(supports instrument42 spectrograph4)
	(calibration_target instrument42 Star7)
	(calibration_target instrument42 GroundStation3)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star6)
	(supports instrument43 image1)
	(calibration_target instrument43 Star6)
	(calibration_target instrument43 GroundStation4)
	(supports instrument44 image1)
	(supports instrument44 spectrograph4)
	(calibration_target instrument44 Star5)
	(calibration_target instrument44 GroundStation3)
	(supports instrument45 spectrograph4)
	(calibration_target instrument45 GroundStation1)
	(calibration_target instrument45 GroundStation4)
	(supports instrument46 thermograph3)
	(calibration_target instrument46 Star0)
	(supports instrument47 thermograph3)
	(supports instrument47 thermograph0)
	(calibration_target instrument47 Star0)
	(supports instrument48 spectrograph4)
	(calibration_target instrument48 GroundStation4)
	(supports instrument49 thermograph0)
	(supports instrument49 spectrograph4)
	(supports instrument49 image1)
	(calibration_target instrument49 Star6)
	(calibration_target instrument49 GroundStation1)
	(supports instrument50 thermograph0)
	(supports instrument50 image1)
	(calibration_target instrument50 Star2)
	(calibration_target instrument50 GroundStation4)
	(supports instrument51 thermograph3)
	(supports instrument51 image1)
	(supports instrument51 spectrograph4)
	(calibration_target instrument51 GroundStation3)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation4)
	(supports instrument52 thermograph0)
	(supports instrument52 spectrograph4)
	(calibration_target instrument52 Star7)
	(supports instrument53 infrared2)
	(supports instrument53 image1)
	(supports instrument53 thermograph3)
	(calibration_target instrument53 GroundStation3)
	(calibration_target instrument53 Star5)
	(supports instrument54 thermograph3)
	(supports instrument54 thermograph0)
	(calibration_target instrument54 GroundStation1)
	(calibration_target instrument54 GroundStation3)
	(supports instrument55 spectrograph4)
	(supports instrument55 image1)
	(supports instrument55 thermograph3)
	(calibration_target instrument55 GroundStation3)
	(calibration_target instrument55 Star5)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation4)
)
(:goal (and
	(pointing satellite1 GroundStation4)
	(pointing satellite2 Star0)
	(pointing satellite3 GroundStation3)
	(pointing satellite5 Phenomenon9)
	(pointing satellite7 GroundStation4)
	(have_image Planet8 image1)
	(have_image Phenomenon9 infrared2)
))

)
