(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite4 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite5 - satellite
	instrument29 - instrument
	satellite6 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite7 - satellite
	instrument36 - instrument
	instrument37 - instrument
	satellite8 - satellite
	instrument38 - instrument
	satellite9 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	image3 - mode
	image1 - mode
	thermograph0 - mode
	infrared2 - mode
	infrared4 - mode
	Star7 - direction
	GroundStation4 - direction
	GroundStation3 - direction
	GroundStation5 - direction
	GroundStation1 - direction
	GroundStation0 - direction
	Star2 - direction
	GroundStation6 - direction
	Planet8 - direction
	Star9 - direction
)
(:init
	(supports instrument0 image1)
	(supports instrument0 image3)
	(calibration_target instrument0 GroundStation6)
	(calibration_target instrument0 Star7)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation3)
	(supports instrument1 image3)
	(supports instrument1 infrared2)
	(calibration_target instrument1 Star2)
	(calibration_target instrument1 GroundStation0)
	(supports instrument2 image1)
	(calibration_target instrument2 Star7)
	(supports instrument3 infrared2)
	(supports instrument3 image3)
	(supports instrument3 infrared4)
	(calibration_target instrument3 Star7)
	(calibration_target instrument3 Star2)
	(supports instrument4 image1)
	(calibration_target instrument4 Star2)
	(calibration_target instrument4 GroundStation3)
	(supports instrument5 infrared4)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 GroundStation5)
	(supports instrument6 image1)
	(supports instrument6 infrared4)
	(calibration_target instrument6 Star7)
	(supports instrument7 infrared2)
	(supports instrument7 image1)
	(calibration_target instrument7 GroundStation5)
	(supports instrument8 infrared4)
	(supports instrument8 image3)
	(calibration_target instrument8 GroundStation1)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation4)
	(supports instrument9 image3)
	(calibration_target instrument9 GroundStation0)
	(supports instrument10 infrared4)
	(calibration_target instrument10 GroundStation4)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation3)
	(supports instrument11 infrared4)
	(supports instrument11 infrared2)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 GroundStation1)
	(supports instrument12 image3)
	(calibration_target instrument12 GroundStation1)
	(calibration_target instrument12 GroundStation4)
	(supports instrument13 infrared2)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 GroundStation0)
	(supports instrument14 image3)
	(supports instrument14 infrared2)
	(supports instrument14 infrared4)
	(calibration_target instrument14 Star2)
	(calibration_target instrument14 GroundStation1)
	(supports instrument15 infrared4)
	(supports instrument15 infrared2)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 GroundStation0)
	(supports instrument16 thermograph0)
	(supports instrument16 image1)
	(supports instrument16 infrared2)
	(calibration_target instrument16 Star2)
	(supports instrument17 image1)
	(supports instrument17 infrared2)
	(calibration_target instrument17 GroundStation0)
	(calibration_target instrument17 Star2)
	(supports instrument18 image3)
	(supports instrument18 thermograph0)
	(calibration_target instrument18 GroundStation0)
	(supports instrument19 image3)
	(calibration_target instrument19 GroundStation0)
	(supports instrument20 infrared2)
	(supports instrument20 thermograph0)
	(supports instrument20 image1)
	(calibration_target instrument20 GroundStation4)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet8)
	(supports instrument21 thermograph0)
	(supports instrument21 image1)
	(supports instrument21 infrared2)
	(calibration_target instrument21 Star7)
	(supports instrument22 image1)
	(calibration_target instrument22 GroundStation6)
	(calibration_target instrument22 GroundStation3)
	(supports instrument23 infrared4)
	(supports instrument23 infrared2)
	(calibration_target instrument23 Star2)
	(supports instrument24 infrared2)
	(supports instrument24 image1)
	(supports instrument24 thermograph0)
	(calibration_target instrument24 Star7)
	(calibration_target instrument24 Star2)
	(supports instrument25 image1)
	(supports instrument25 infrared2)
	(supports instrument25 infrared4)
	(calibration_target instrument25 Star2)
	(supports instrument26 thermograph0)
	(supports instrument26 infrared2)
	(calibration_target instrument26 GroundStation0)
	(supports instrument27 infrared4)
	(supports instrument27 infrared2)
	(calibration_target instrument27 GroundStation4)
	(calibration_target instrument27 GroundStation5)
	(supports instrument28 infrared2)
	(calibration_target instrument28 GroundStation0)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation6)
	(supports instrument29 thermograph0)
	(calibration_target instrument29 GroundStation4)
	(on_board instrument29 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation6)
	(supports instrument30 image3)
	(supports instrument30 infrared4)
	(supports instrument30 image1)
	(calibration_target instrument30 Star7)
	(supports instrument31 thermograph0)
	(calibration_target instrument31 Star7)
	(calibration_target instrument31 GroundStation5)
	(supports instrument32 infrared4)
	(supports instrument32 image1)
	(supports instrument32 thermograph0)
	(calibration_target instrument32 Star2)
	(calibration_target instrument32 GroundStation6)
	(supports instrument33 infrared4)
	(supports instrument33 image3)
	(calibration_target instrument33 Star2)
	(supports instrument34 image1)
	(supports instrument34 thermograph0)
	(calibration_target instrument34 Star2)
	(calibration_target instrument34 GroundStation4)
	(supports instrument35 infrared2)
	(calibration_target instrument35 GroundStation3)
	(calibration_target instrument35 GroundStation1)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet8)
	(supports instrument36 infrared4)
	(supports instrument36 thermograph0)
	(calibration_target instrument36 GroundStation5)
	(calibration_target instrument36 GroundStation1)
	(supports instrument37 image1)
	(supports instrument37 thermograph0)
	(calibration_target instrument37 GroundStation1)
	(calibration_target instrument37 Star2)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation5)
	(supports instrument38 image3)
	(calibration_target instrument38 GroundStation0)
	(on_board instrument38 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation3)
	(supports instrument39 infrared2)
	(supports instrument39 image1)
	(supports instrument39 image3)
	(calibration_target instrument39 GroundStation0)
	(calibration_target instrument39 GroundStation5)
	(supports instrument40 infrared4)
	(calibration_target instrument40 GroundStation6)
	(supports instrument41 infrared4)
	(calibration_target instrument41 GroundStation6)
	(supports instrument42 infrared4)
	(supports instrument42 thermograph0)
	(calibration_target instrument42 GroundStation0)
	(calibration_target instrument42 Star2)
	(supports instrument43 thermograph0)
	(calibration_target instrument43 GroundStation0)
	(supports instrument44 infrared2)
	(calibration_target instrument44 GroundStation0)
	(calibration_target instrument44 GroundStation1)
	(supports instrument45 infrared4)
	(calibration_target instrument45 GroundStation6)
	(calibration_target instrument45 Star2)
	(on_board instrument39 satellite9)
	(on_board instrument40 satellite9)
	(on_board instrument41 satellite9)
	(on_board instrument42 satellite9)
	(on_board instrument43 satellite9)
	(on_board instrument44 satellite9)
	(on_board instrument45 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation3)
)
(:goal (and
	(pointing satellite1 Star9)
	(pointing satellite3 GroundStation3)
	(pointing satellite4 GroundStation6)
	(pointing satellite5 GroundStation6)
	(pointing satellite6 GroundStation3)
	(pointing satellite7 Star9)
	(have_image Star9 thermograph0)
))

)
