(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite2 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite3 - satellite
	instrument18 - instrument
	instrument19 - instrument
	satellite4 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite5 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite6 - satellite
	instrument30 - instrument
	instrument31 - instrument
	satellite7 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite8 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	satellite9 - satellite
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	infrared4 - mode
	thermograph0 - mode
	infrared1 - mode
	image3 - mode
	infrared2 - mode
	Star5 - direction
	Star1 - direction
	Star0 - direction
	GroundStation7 - direction
	Star3 - direction
	GroundStation2 - direction
	GroundStation4 - direction
	Star6 - direction
	Planet8 - direction
	Phenomenon9 - direction
)
(:init
	(supports instrument0 infrared2)
	(supports instrument0 image3)
	(supports instrument0 infrared4)
	(calibration_target instrument0 Star0)
	(calibration_target instrument0 Star6)
	(supports instrument1 infrared4)
	(calibration_target instrument1 GroundStation2)
	(calibration_target instrument1 Star1)
	(supports instrument2 image3)
	(supports instrument2 infrared2)
	(calibration_target instrument2 GroundStation2)
	(supports instrument3 infrared1)
	(calibration_target instrument3 Star6)
	(supports instrument4 infrared1)
	(supports instrument4 infrared4)
	(supports instrument4 image3)
	(calibration_target instrument4 Star1)
	(calibration_target instrument4 Star5)
	(supports instrument5 thermograph0)
	(supports instrument5 infrared4)
	(calibration_target instrument5 GroundStation4)
	(supports instrument6 infrared1)
	(calibration_target instrument6 GroundStation2)
	(supports instrument7 infrared1)
	(supports instrument7 infrared4)
	(supports instrument7 infrared2)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 Star6)
	(supports instrument8 infrared2)
	(calibration_target instrument8 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet8)
	(supports instrument9 infrared1)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 Star5)
	(calibration_target instrument10 GroundStation7)
	(supports instrument11 infrared2)
	(calibration_target instrument11 Star5)
	(calibration_target instrument11 GroundStation2)
	(supports instrument12 infrared1)
	(supports instrument12 image3)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 GroundStation7)
	(supports instrument13 image3)
	(calibration_target instrument13 Star1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation4)
	(supports instrument14 infrared2)
	(calibration_target instrument14 GroundStation7)
	(calibration_target instrument14 Star6)
	(supports instrument15 infrared1)
	(calibration_target instrument15 Star1)
	(supports instrument16 infrared4)
	(supports instrument16 thermograph0)
	(supports instrument16 infrared2)
	(calibration_target instrument16 GroundStation7)
	(supports instrument17 infrared2)
	(supports instrument17 image3)
	(calibration_target instrument17 Star1)
	(calibration_target instrument17 Star0)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star5)
	(supports instrument18 thermograph0)
	(calibration_target instrument18 Star5)
	(calibration_target instrument18 GroundStation2)
	(supports instrument19 infrared1)
	(supports instrument19 image3)
	(supports instrument19 infrared4)
	(calibration_target instrument19 GroundStation2)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star3)
	(supports instrument20 infrared2)
	(supports instrument20 infrared4)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 GroundStation2)
	(supports instrument21 infrared1)
	(supports instrument21 infrared4)
	(supports instrument21 thermograph0)
	(calibration_target instrument21 Star3)
	(supports instrument22 thermograph0)
	(supports instrument22 infrared2)
	(calibration_target instrument22 Star5)
	(calibration_target instrument22 Star0)
	(supports instrument23 image3)
	(supports instrument23 infrared1)
	(supports instrument23 infrared2)
	(calibration_target instrument23 Star1)
	(calibration_target instrument23 Star6)
	(supports instrument24 infrared2)
	(supports instrument24 thermograph0)
	(calibration_target instrument24 Star3)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation2)
	(supports instrument25 infrared2)
	(supports instrument25 thermograph0)
	(supports instrument25 infrared4)
	(calibration_target instrument25 Star5)
	(calibration_target instrument25 Star6)
	(supports instrument26 infrared4)
	(supports instrument26 image3)
	(calibration_target instrument26 GroundStation4)
	(supports instrument27 infrared1)
	(supports instrument27 image3)
	(calibration_target instrument27 Star3)
	(calibration_target instrument27 GroundStation2)
	(supports instrument28 thermograph0)
	(supports instrument28 infrared4)
	(supports instrument28 infrared2)
	(calibration_target instrument28 GroundStation4)
	(calibration_target instrument28 Star5)
	(supports instrument29 thermograph0)
	(supports instrument29 infrared2)
	(calibration_target instrument29 GroundStation2)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet8)
	(supports instrument30 image3)
	(supports instrument30 infrared4)
	(supports instrument30 infrared2)
	(calibration_target instrument30 GroundStation2)
	(calibration_target instrument30 Star5)
	(supports instrument31 infrared1)
	(supports instrument31 thermograph0)
	(supports instrument31 image3)
	(calibration_target instrument31 GroundStation2)
	(calibration_target instrument31 Star6)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star3)
	(supports instrument32 thermograph0)
	(supports instrument32 image3)
	(supports instrument32 infrared1)
	(calibration_target instrument32 Star6)
	(supports instrument33 infrared2)
	(calibration_target instrument33 GroundStation7)
	(supports instrument34 infrared4)
	(calibration_target instrument34 Star0)
	(calibration_target instrument34 Star3)
	(supports instrument35 infrared1)
	(calibration_target instrument35 Star0)
	(calibration_target instrument35 GroundStation2)
	(supports instrument36 infrared2)
	(calibration_target instrument36 Star5)
	(supports instrument37 infrared2)
	(calibration_target instrument37 Star1)
	(calibration_target instrument37 GroundStation7)
	(on_board instrument32 satellite7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star6)
	(supports instrument38 infrared4)
	(supports instrument38 image3)
	(supports instrument38 infrared2)
	(calibration_target instrument38 GroundStation4)
	(supports instrument39 infrared4)
	(supports instrument39 infrared2)
	(supports instrument39 infrared1)
	(calibration_target instrument39 Star1)
	(calibration_target instrument39 Star6)
	(supports instrument40 thermograph0)
	(calibration_target instrument40 Star3)
	(supports instrument41 infrared4)
	(supports instrument41 thermograph0)
	(calibration_target instrument41 GroundStation7)
	(supports instrument42 infrared1)
	(supports instrument42 infrared2)
	(supports instrument42 thermograph0)
	(calibration_target instrument42 GroundStation7)
	(calibration_target instrument42 Star6)
	(supports instrument43 image3)
	(supports instrument43 thermograph0)
	(supports instrument43 infrared2)
	(calibration_target instrument43 Star6)
	(calibration_target instrument43 Star5)
	(supports instrument44 infrared2)
	(calibration_target instrument44 GroundStation4)
	(supports instrument45 thermograph0)
	(calibration_target instrument45 GroundStation4)
	(on_board instrument38 satellite8)
	(on_board instrument39 satellite8)
	(on_board instrument40 satellite8)
	(on_board instrument41 satellite8)
	(on_board instrument42 satellite8)
	(on_board instrument43 satellite8)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation7)
	(supports instrument46 infrared2)
	(supports instrument46 infrared1)
	(calibration_target instrument46 Star0)
	(calibration_target instrument46 Star1)
	(supports instrument47 infrared4)
	(supports instrument47 thermograph0)
	(supports instrument47 image3)
	(calibration_target instrument47 GroundStation7)
	(calibration_target instrument47 Star6)
	(supports instrument48 infrared4)
	(supports instrument48 image3)
	(supports instrument48 infrared1)
	(calibration_target instrument48 Star1)
	(supports instrument49 infrared4)
	(supports instrument49 image3)
	(calibration_target instrument49 Star0)
	(calibration_target instrument49 Star6)
	(supports instrument50 thermograph0)
	(supports instrument50 image3)
	(calibration_target instrument50 GroundStation4)
	(calibration_target instrument50 Star3)
	(supports instrument51 infrared4)
	(supports instrument51 infrared1)
	(calibration_target instrument51 Star0)
	(calibration_target instrument51 GroundStation4)
	(supports instrument52 infrared4)
	(supports instrument52 infrared1)
	(supports instrument52 infrared2)
	(calibration_target instrument52 GroundStation7)
	(supports instrument53 thermograph0)
	(supports instrument53 infrared2)
	(supports instrument53 infrared4)
	(calibration_target instrument53 GroundStation2)
	(calibration_target instrument53 Star3)
	(supports instrument54 infrared2)
	(supports instrument54 image3)
	(supports instrument54 infrared1)
	(calibration_target instrument54 Star6)
	(calibration_target instrument54 GroundStation4)
	(on_board instrument46 satellite9)
	(on_board instrument47 satellite9)
	(on_board instrument48 satellite9)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star1)
)
(:goal (and
	(pointing satellite0 GroundStation4)
	(pointing satellite1 Star3)
	(pointing satellite3 GroundStation7)
	(pointing satellite4 Phenomenon9)
	(pointing satellite5 Star0)
	(pointing satellite7 Planet8)
	(have_image Planet8 image3)
	(have_image Phenomenon9 thermograph0)
))

)
