(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite3 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite4 - satellite
	instrument25 - instrument
	instrument26 - instrument
	satellite5 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite6 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	satellite7 - satellite
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite8 - satellite
	instrument48 - instrument
	satellite9 - satellite
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	spectrograph0 - mode
	image3 - mode
	infrared1 - mode
	image4 - mode
	image2 - mode
	Star0 - direction
	GroundStation2 - direction
	GroundStation1 - direction
	Star7 - direction
	Star5 - direction
	GroundStation4 - direction
	Star3 - direction
	Star6 - direction
	Star8 - direction
	Planet9 - direction
)
(:init
	(supports instrument0 image2)
	(supports instrument0 image4)
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 Star7)
	(supports instrument1 image4)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 image4)
	(supports instrument2 image3)
	(supports instrument2 infrared1)
	(calibration_target instrument2 Star6)
	(calibration_target instrument2 Star7)
	(supports instrument3 image3)
	(calibration_target instrument3 Star5)
	(calibration_target instrument3 GroundStation4)
	(supports instrument4 spectrograph0)
	(supports instrument4 image4)
	(calibration_target instrument4 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation1)
	(supports instrument5 image2)
	(supports instrument5 infrared1)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 Star0)
	(supports instrument6 image3)
	(calibration_target instrument6 GroundStation4)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star3)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 Star5)
	(supports instrument8 image2)
	(calibration_target instrument8 GroundStation1)
	(supports instrument9 infrared1)
	(supports instrument9 image4)
	(calibration_target instrument9 Star6)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 image3)
	(supports instrument10 image2)
	(calibration_target instrument10 Star5)
	(calibration_target instrument10 Star0)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 Star5)
	(supports instrument12 infrared1)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star7)
	(supports instrument13 image2)
	(supports instrument13 spectrograph0)
	(calibration_target instrument13 Star6)
	(supports instrument14 image2)
	(supports instrument14 infrared1)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 GroundStation1)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star8)
	(supports instrument15 spectrograph0)
	(supports instrument15 image2)
	(calibration_target instrument15 Star6)
	(calibration_target instrument15 Star0)
	(supports instrument16 spectrograph0)
	(supports instrument16 image3)
	(supports instrument16 image4)
	(calibration_target instrument16 Star7)
	(supports instrument17 infrared1)
	(calibration_target instrument17 Star6)
	(calibration_target instrument17 Star0)
	(supports instrument18 spectrograph0)
	(supports instrument18 image4)
	(calibration_target instrument18 Star6)
	(calibration_target instrument18 Star5)
	(supports instrument19 image2)
	(supports instrument19 spectrograph0)
	(calibration_target instrument19 Star5)
	(supports instrument20 image4)
	(supports instrument20 infrared1)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 Star6)
	(supports instrument21 image2)
	(supports instrument21 infrared1)
	(supports instrument21 image4)
	(calibration_target instrument21 Star3)
	(supports instrument22 image3)
	(calibration_target instrument22 Star5)
	(calibration_target instrument22 Star0)
	(supports instrument23 image2)
	(supports instrument23 spectrograph0)
	(calibration_target instrument23 GroundStation1)
	(calibration_target instrument23 GroundStation4)
	(supports instrument24 infrared1)
	(calibration_target instrument24 Star0)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star7)
	(supports instrument25 image3)
	(supports instrument25 spectrograph0)
	(calibration_target instrument25 Star5)
	(supports instrument26 image2)
	(calibration_target instrument26 GroundStation4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet9)
	(supports instrument27 infrared1)
	(supports instrument27 image2)
	(supports instrument27 image4)
	(calibration_target instrument27 Star3)
	(calibration_target instrument27 GroundStation4)
	(supports instrument28 image3)
	(supports instrument28 infrared1)
	(calibration_target instrument28 Star5)
	(calibration_target instrument28 Star6)
	(supports instrument29 image2)
	(supports instrument29 spectrograph0)
	(supports instrument29 image4)
	(calibration_target instrument29 Star3)
	(calibration_target instrument29 Star5)
	(supports instrument30 image2)
	(calibration_target instrument30 Star0)
	(calibration_target instrument30 Star7)
	(supports instrument31 image4)
	(calibration_target instrument31 Star5)
	(calibration_target instrument31 Star6)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star6)
	(supports instrument32 image2)
	(calibration_target instrument32 GroundStation4)
	(supports instrument33 image2)
	(supports instrument33 image4)
	(supports instrument33 spectrograph0)
	(calibration_target instrument33 GroundStation4)
	(calibration_target instrument33 Star6)
	(supports instrument34 image2)
	(supports instrument34 infrared1)
	(supports instrument34 image3)
	(calibration_target instrument34 Star0)
	(supports instrument35 image2)
	(supports instrument35 spectrograph0)
	(supports instrument35 infrared1)
	(calibration_target instrument35 Star6)
	(calibration_target instrument35 Star5)
	(supports instrument36 image4)
	(supports instrument36 infrared1)
	(calibration_target instrument36 Star7)
	(calibration_target instrument36 GroundStation1)
	(supports instrument37 spectrograph0)
	(supports instrument37 image2)
	(supports instrument37 image4)
	(calibration_target instrument37 GroundStation1)
	(supports instrument38 spectrograph0)
	(calibration_target instrument38 GroundStation2)
	(supports instrument39 image4)
	(supports instrument39 image3)
	(supports instrument39 spectrograph0)
	(calibration_target instrument39 GroundStation4)
	(calibration_target instrument39 Star0)
	(supports instrument40 infrared1)
	(calibration_target instrument40 Star3)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet9)
	(supports instrument41 spectrograph0)
	(calibration_target instrument41 Star5)
	(calibration_target instrument41 GroundStation2)
	(supports instrument42 spectrograph0)
	(supports instrument42 image2)
	(calibration_target instrument42 GroundStation4)
	(supports instrument43 image4)
	(supports instrument43 image2)
	(supports instrument43 image3)
	(calibration_target instrument43 GroundStation1)
	(calibration_target instrument43 Star7)
	(supports instrument44 image4)
	(calibration_target instrument44 Star7)
	(supports instrument45 image2)
	(supports instrument45 image4)
	(supports instrument45 spectrograph0)
	(calibration_target instrument45 Star3)
	(calibration_target instrument45 Star0)
	(supports instrument46 image4)
	(calibration_target instrument46 Star3)
	(supports instrument47 spectrograph0)
	(supports instrument47 image3)
	(calibration_target instrument47 Star7)
	(calibration_target instrument47 Star0)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star8)
	(supports instrument48 image4)
	(calibration_target instrument48 Star3)
	(calibration_target instrument48 Star5)
	(on_board instrument48 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star7)
	(supports instrument49 image4)
	(supports instrument49 image2)
	(calibration_target instrument49 GroundStation2)
	(supports instrument50 infrared1)
	(supports instrument50 image4)
	(supports instrument50 image3)
	(calibration_target instrument50 Star3)
	(supports instrument51 spectrograph0)
	(supports instrument51 infrared1)
	(supports instrument51 image4)
	(calibration_target instrument51 GroundStation1)
	(supports instrument52 infrared1)
	(supports instrument52 spectrograph0)
	(supports instrument52 image2)
	(calibration_target instrument52 Star7)
	(supports instrument53 infrared1)
	(supports instrument53 image2)
	(supports instrument53 image4)
	(calibration_target instrument53 Star5)
	(supports instrument54 image2)
	(supports instrument54 image3)
	(calibration_target instrument54 Star7)
	(supports instrument55 image2)
	(calibration_target instrument55 GroundStation4)
	(calibration_target instrument55 Star5)
	(supports instrument56 image2)
	(supports instrument56 image4)
	(supports instrument56 infrared1)
	(calibration_target instrument56 Star6)
	(calibration_target instrument56 Star3)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation1)
)
(:goal (and
	(pointing satellite6 Star0)
	(pointing satellite8 Planet9)
	(have_image Star8 image2)
	(have_image Planet9 spectrograph0)
))

)
