(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite2 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite3 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite4 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite5 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	satellite6 - satellite
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	satellite7 - satellite
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	satellite8 - satellite
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	satellite9 - satellite
	instrument61 - instrument
	instrument62 - instrument
	instrument63 - instrument
	instrument64 - instrument
	instrument65 - instrument
	instrument66 - instrument
	instrument67 - instrument
	spectrograph0 - mode
	infrared1 - mode
	image2 - mode
	infrared4 - mode
	spectrograph3 - mode
	GroundStation1 - direction
	Star2 - direction
	GroundStation0 - direction
	Planet3 - direction
	Star4 - direction
)
(:init
	(supports instrument0 infrared1)
	(supports instrument0 image2)
	(supports instrument0 infrared4)
	(calibration_target instrument0 Star2)
	(supports instrument1 image2)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 infrared1)
	(supports instrument2 infrared4)
	(calibration_target instrument2 Star2)
	(supports instrument3 infrared4)
	(calibration_target instrument3 Star2)
	(supports instrument4 infrared1)
	(supports instrument4 spectrograph0)
	(calibration_target instrument4 GroundStation1)
	(supports instrument5 spectrograph3)
	(calibration_target instrument5 GroundStation0)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet3)
	(supports instrument7 infrared4)
	(calibration_target instrument7 GroundStation1)
	(supports instrument8 image2)
	(supports instrument8 spectrograph0)
	(calibration_target instrument8 GroundStation1)
	(supports instrument9 spectrograph3)
	(supports instrument9 spectrograph0)
	(supports instrument9 infrared1)
	(calibration_target instrument9 GroundStation0)
	(supports instrument10 image2)
	(supports instrument10 spectrograph3)
	(supports instrument10 infrared1)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 spectrograph3)
	(supports instrument11 infrared1)
	(calibration_target instrument11 GroundStation0)
	(supports instrument12 spectrograph3)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 GroundStation0)
	(supports instrument13 infrared1)
	(supports instrument13 spectrograph3)
	(supports instrument13 image2)
	(calibration_target instrument13 GroundStation0)
	(supports instrument14 infrared4)
	(supports instrument14 spectrograph0)
	(supports instrument14 image2)
	(calibration_target instrument14 Star2)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star2)
	(supports instrument15 infrared4)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 GroundStation0)
	(supports instrument16 spectrograph3)
	(supports instrument16 image2)
	(calibration_target instrument16 GroundStation0)
	(supports instrument17 infrared4)
	(calibration_target instrument17 GroundStation1)
	(supports instrument18 infrared1)
	(calibration_target instrument18 Star2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation0)
	(supports instrument19 infrared4)
	(supports instrument19 image2)
	(supports instrument19 infrared1)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 image2)
	(calibration_target instrument20 GroundStation1)
	(supports instrument21 infrared4)
	(calibration_target instrument21 Star2)
	(supports instrument22 image2)
	(calibration_target instrument22 GroundStation0)
	(supports instrument23 image2)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 spectrograph0)
	(supports instrument24 image2)
	(calibration_target instrument24 GroundStation1)
	(supports instrument25 image2)
	(supports instrument25 infrared1)
	(supports instrument25 spectrograph3)
	(calibration_target instrument25 GroundStation0)
	(supports instrument26 spectrograph0)
	(calibration_target instrument26 Star2)
	(supports instrument27 infrared1)
	(supports instrument27 infrared4)
	(supports instrument27 spectrograph3)
	(calibration_target instrument27 GroundStation1)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star2)
	(supports instrument28 infrared4)
	(supports instrument28 spectrograph3)
	(calibration_target instrument28 GroundStation0)
	(supports instrument29 infrared1)
	(supports instrument29 spectrograph0)
	(supports instrument29 infrared4)
	(calibration_target instrument29 Star2)
	(supports instrument30 infrared1)
	(supports instrument30 image2)
	(calibration_target instrument30 Star2)
	(supports instrument31 infrared1)
	(supports instrument31 image2)
	(calibration_target instrument31 GroundStation1)
	(supports instrument32 spectrograph0)
	(calibration_target instrument32 Star2)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star2)
	(supports instrument33 infrared1)
	(calibration_target instrument33 GroundStation0)
	(supports instrument34 infrared1)
	(calibration_target instrument34 GroundStation1)
	(supports instrument35 infrared1)
	(supports instrument35 image2)
	(supports instrument35 infrared4)
	(calibration_target instrument35 GroundStation0)
	(supports instrument36 image2)
	(calibration_target instrument36 GroundStation1)
	(supports instrument37 infrared1)
	(supports instrument37 infrared4)
	(supports instrument37 image2)
	(calibration_target instrument37 GroundStation1)
	(supports instrument38 infrared4)
	(supports instrument38 spectrograph3)
	(calibration_target instrument38 GroundStation1)
	(supports instrument39 infrared4)
	(calibration_target instrument39 GroundStation0)
	(supports instrument40 image2)
	(calibration_target instrument40 GroundStation1)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star4)
	(supports instrument41 infrared1)
	(supports instrument41 image2)
	(calibration_target instrument41 Star2)
	(supports instrument42 spectrograph0)
	(calibration_target instrument42 Star2)
	(supports instrument43 image2)
	(calibration_target instrument43 GroundStation0)
	(supports instrument44 spectrograph0)
	(supports instrument44 infrared1)
	(calibration_target instrument44 GroundStation0)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet3)
	(supports instrument45 infrared1)
	(supports instrument45 image2)
	(calibration_target instrument45 Star2)
	(supports instrument46 infrared1)
	(calibration_target instrument46 GroundStation1)
	(supports instrument47 infrared4)
	(supports instrument47 spectrograph3)
	(supports instrument47 spectrograph0)
	(calibration_target instrument47 GroundStation0)
	(supports instrument48 infrared4)
	(calibration_target instrument48 GroundStation1)
	(supports instrument49 infrared4)
	(supports instrument49 spectrograph3)
	(calibration_target instrument49 Star2)
	(supports instrument50 image2)
	(supports instrument50 spectrograph3)
	(calibration_target instrument50 Star2)
	(supports instrument51 infrared4)
	(supports instrument51 spectrograph3)
	(calibration_target instrument51 GroundStation1)
	(supports instrument52 spectrograph0)
	(supports instrument52 infrared1)
	(calibration_target instrument52 Star2)
	(supports instrument53 spectrograph0)
	(supports instrument53 infrared4)
	(supports instrument53 infrared1)
	(calibration_target instrument53 GroundStation0)
	(supports instrument54 image2)
	(supports instrument54 infrared1)
	(supports instrument54 spectrograph0)
	(calibration_target instrument54 Star2)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(on_board instrument53 satellite7)
	(on_board instrument54 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation0)
	(supports instrument55 spectrograph3)
	(calibration_target instrument55 Star2)
	(supports instrument56 spectrograph3)
	(calibration_target instrument56 Star2)
	(supports instrument57 image2)
	(supports instrument57 infrared4)
	(supports instrument57 infrared1)
	(calibration_target instrument57 GroundStation0)
	(supports instrument58 infrared4)
	(supports instrument58 infrared1)
	(calibration_target instrument58 GroundStation0)
	(supports instrument59 spectrograph0)
	(calibration_target instrument59 GroundStation1)
	(supports instrument60 spectrograph0)
	(calibration_target instrument60 GroundStation0)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(on_board instrument60 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star2)
	(supports instrument61 infrared1)
	(supports instrument61 image2)
	(supports instrument61 spectrograph0)
	(calibration_target instrument61 GroundStation0)
	(supports instrument62 infrared4)
	(calibration_target instrument62 GroundStation0)
	(supports instrument63 infrared1)
	(supports instrument63 image2)
	(supports instrument63 spectrograph3)
	(calibration_target instrument63 Star2)
	(supports instrument64 infrared1)
	(supports instrument64 spectrograph3)
	(supports instrument64 infrared4)
	(calibration_target instrument64 GroundStation0)
	(supports instrument65 image2)
	(supports instrument65 infrared1)
	(calibration_target instrument65 GroundStation0)
	(supports instrument66 infrared4)
	(supports instrument66 spectrograph3)
	(supports instrument66 image2)
	(calibration_target instrument66 GroundStation0)
	(supports instrument67 spectrograph3)
	(supports instrument67 infrared4)
	(calibration_target instrument67 GroundStation0)
	(on_board instrument61 satellite9)
	(on_board instrument62 satellite9)
	(on_board instrument63 satellite9)
	(on_board instrument64 satellite9)
	(on_board instrument65 satellite9)
	(on_board instrument66 satellite9)
	(on_board instrument67 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet3)
)
(:goal (and
	(pointing satellite3 Star4)
	(pointing satellite4 GroundStation1)
	(pointing satellite5 Planet3)
	(pointing satellite7 GroundStation1)
	(pointing satellite9 Star4)
	(have_image Planet3 spectrograph3)
	(have_image Star4 infrared1)
))

)
