(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite2 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite3 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite4 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	satellite5 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	satellite6 - satellite
	instrument49 - instrument
	instrument50 - instrument
	satellite7 - satellite
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	satellite8 - satellite
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	satellite9 - satellite
	instrument60 - instrument
	instrument61 - instrument
	instrument62 - instrument
	instrument63 - instrument
	instrument64 - instrument
	instrument65 - instrument
	instrument66 - instrument
	instrument67 - instrument
	instrument68 - instrument
	infrared3 - mode
	thermograph4 - mode
	spectrograph0 - mode
	spectrograph1 - mode
	spectrograph2 - mode
	Star1 - direction
	GroundStation2 - direction
	Star0 - direction
	Phenomenon3 - direction
	Phenomenon4 - direction
)
(:init
	(supports instrument0 spectrograph1)
	(calibration_target instrument0 Star1)
	(supports instrument1 spectrograph0)
	(supports instrument1 thermograph4)
	(supports instrument1 infrared3)
	(calibration_target instrument1 Star1)
	(supports instrument2 thermograph4)
	(supports instrument2 spectrograph0)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 Star0)
	(supports instrument3 spectrograph1)
	(supports instrument3 infrared3)
	(calibration_target instrument3 Star0)
	(supports instrument4 spectrograph2)
	(supports instrument4 spectrograph0)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 GroundStation2)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 Star1)
	(supports instrument6 thermograph4)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star1)
	(supports instrument7 spectrograph2)
	(supports instrument7 infrared3)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 Star0)
	(supports instrument8 infrared3)
	(calibration_target instrument8 Star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation2)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 Star1)
	(supports instrument10 thermograph4)
	(supports instrument10 infrared3)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 GroundStation2)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 Star1)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 Star1)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 Star0)
	(supports instrument14 infrared3)
	(supports instrument14 spectrograph0)
	(supports instrument14 spectrograph2)
	(calibration_target instrument14 GroundStation2)
	(supports instrument15 infrared3)
	(supports instrument15 thermograph4)
	(calibration_target instrument15 Star0)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 Star0)
	(supports instrument17 spectrograph1)
	(supports instrument17 infrared3)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 Star1)
	(supports instrument18 spectrograph1)
	(supports instrument18 spectrograph0)
	(supports instrument18 spectrograph2)
	(calibration_target instrument18 Star0)
	(supports instrument19 spectrograph2)
	(supports instrument19 spectrograph1)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 spectrograph1)
	(supports instrument20 thermograph4)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 GroundStation2)
	(supports instrument21 thermograph4)
	(supports instrument21 spectrograph0)
	(supports instrument21 spectrograph2)
	(calibration_target instrument21 Star0)
	(supports instrument22 spectrograph2)
	(supports instrument22 spectrograph0)
	(calibration_target instrument22 GroundStation2)
	(supports instrument23 spectrograph1)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 Star1)
	(supports instrument24 spectrograph2)
	(supports instrument24 spectrograph1)
	(calibration_target instrument24 GroundStation2)
	(supports instrument25 spectrograph0)
	(supports instrument25 infrared3)
	(calibration_target instrument25 Star0)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(on_board instrument22 satellite2)
	(on_board instrument23 satellite2)
	(on_board instrument24 satellite2)
	(on_board instrument25 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument26 infrared3)
	(calibration_target instrument26 Star1)
	(supports instrument27 infrared3)
	(supports instrument27 spectrograph1)
	(supports instrument27 thermograph4)
	(calibration_target instrument27 Star1)
	(supports instrument28 spectrograph0)
	(supports instrument28 infrared3)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 Star0)
	(supports instrument29 infrared3)
	(calibration_target instrument29 GroundStation2)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon4)
	(supports instrument30 spectrograph0)
	(supports instrument30 infrared3)
	(calibration_target instrument30 GroundStation2)
	(supports instrument31 spectrograph1)
	(supports instrument31 spectrograph2)
	(calibration_target instrument31 Star1)
	(supports instrument32 infrared3)
	(supports instrument32 thermograph4)
	(supports instrument32 spectrograph2)
	(calibration_target instrument32 Star1)
	(supports instrument33 spectrograph1)
	(supports instrument33 thermograph4)
	(calibration_target instrument33 Star0)
	(supports instrument34 spectrograph1)
	(supports instrument34 spectrograph0)
	(calibration_target instrument34 Star0)
	(supports instrument35 spectrograph0)
	(supports instrument35 spectrograph1)
	(calibration_target instrument35 Star1)
	(supports instrument36 spectrograph1)
	(supports instrument36 spectrograph0)
	(supports instrument36 thermograph4)
	(calibration_target instrument36 Star1)
	(supports instrument37 spectrograph2)
	(calibration_target instrument37 Star0)
	(supports instrument38 spectrograph1)
	(supports instrument38 infrared3)
	(supports instrument38 thermograph4)
	(calibration_target instrument38 GroundStation2)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(on_board instrument37 satellite4)
	(on_board instrument38 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon4)
	(supports instrument39 thermograph4)
	(supports instrument39 spectrograph2)
	(supports instrument39 spectrograph0)
	(calibration_target instrument39 Star1)
	(supports instrument40 spectrograph1)
	(supports instrument40 thermograph4)
	(supports instrument40 spectrograph2)
	(calibration_target instrument40 Star0)
	(supports instrument41 spectrograph2)
	(supports instrument41 thermograph4)
	(calibration_target instrument41 GroundStation2)
	(supports instrument42 spectrograph0)
	(supports instrument42 spectrograph2)
	(calibration_target instrument42 GroundStation2)
	(supports instrument43 spectrograph1)
	(calibration_target instrument43 Star1)
	(supports instrument44 spectrograph0)
	(supports instrument44 spectrograph2)
	(supports instrument44 spectrograph1)
	(calibration_target instrument44 Star1)
	(supports instrument45 infrared3)
	(supports instrument45 spectrograph0)
	(supports instrument45 spectrograph1)
	(calibration_target instrument45 Star1)
	(supports instrument46 spectrograph2)
	(supports instrument46 thermograph4)
	(calibration_target instrument46 GroundStation2)
	(supports instrument47 spectrograph2)
	(calibration_target instrument47 Star1)
	(supports instrument48 thermograph4)
	(supports instrument48 spectrograph1)
	(calibration_target instrument48 Star1)
	(on_board instrument39 satellite5)
	(on_board instrument40 satellite5)
	(on_board instrument41 satellite5)
	(on_board instrument42 satellite5)
	(on_board instrument43 satellite5)
	(on_board instrument44 satellite5)
	(on_board instrument45 satellite5)
	(on_board instrument46 satellite5)
	(on_board instrument47 satellite5)
	(on_board instrument48 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star1)
	(supports instrument49 infrared3)
	(supports instrument49 spectrograph0)
	(supports instrument49 spectrograph1)
	(calibration_target instrument49 Star1)
	(supports instrument50 thermograph4)
	(calibration_target instrument50 Star1)
	(on_board instrument49 satellite6)
	(on_board instrument50 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation2)
	(supports instrument51 infrared3)
	(calibration_target instrument51 Star0)
	(supports instrument52 spectrograph0)
	(calibration_target instrument52 Star1)
	(supports instrument53 thermograph4)
	(supports instrument53 infrared3)
	(calibration_target instrument53 Star0)
	(supports instrument54 spectrograph0)
	(supports instrument54 spectrograph2)
	(calibration_target instrument54 Star0)
	(supports instrument55 thermograph4)
	(supports instrument55 spectrograph2)
	(calibration_target instrument55 GroundStation2)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(on_board instrument53 satellite7)
	(on_board instrument54 satellite7)
	(on_board instrument55 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon3)
	(supports instrument56 infrared3)
	(supports instrument56 thermograph4)
	(calibration_target instrument56 Star0)
	(supports instrument57 spectrograph1)
	(supports instrument57 infrared3)
	(calibration_target instrument57 Star0)
	(supports instrument58 spectrograph2)
	(supports instrument58 spectrograph1)
	(supports instrument58 thermograph4)
	(calibration_target instrument58 Star1)
	(supports instrument59 spectrograph1)
	(supports instrument59 spectrograph0)
	(calibration_target instrument59 Star0)
	(on_board instrument56 satellite8)
	(on_board instrument57 satellite8)
	(on_board instrument58 satellite8)
	(on_board instrument59 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star0)
	(supports instrument60 spectrograph0)
	(supports instrument60 spectrograph1)
	(supports instrument60 thermograph4)
	(calibration_target instrument60 Star1)
	(supports instrument61 infrared3)
	(calibration_target instrument61 GroundStation2)
	(supports instrument62 spectrograph2)
	(supports instrument62 spectrograph1)
	(supports instrument62 infrared3)
	(calibration_target instrument62 Star0)
	(supports instrument63 spectrograph0)
	(supports instrument63 spectrograph2)
	(supports instrument63 thermograph4)
	(calibration_target instrument63 Star0)
	(supports instrument64 infrared3)
	(calibration_target instrument64 Star1)
	(supports instrument65 infrared3)
	(calibration_target instrument65 Star1)
	(supports instrument66 spectrograph2)
	(supports instrument66 thermograph4)
	(calibration_target instrument66 GroundStation2)
	(supports instrument67 spectrograph2)
	(supports instrument67 spectrograph0)
	(calibration_target instrument67 GroundStation2)
	(supports instrument68 spectrograph2)
	(supports instrument68 spectrograph1)
	(supports instrument68 spectrograph0)
	(calibration_target instrument68 Star0)
	(on_board instrument60 satellite9)
	(on_board instrument61 satellite9)
	(on_board instrument62 satellite9)
	(on_board instrument63 satellite9)
	(on_board instrument64 satellite9)
	(on_board instrument65 satellite9)
	(on_board instrument66 satellite9)
	(on_board instrument67 satellite9)
	(on_board instrument68 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star1)
)
(:goal (and
	(pointing satellite0 GroundStation2)
	(pointing satellite1 Star0)
	(pointing satellite5 Phenomenon3)
	(pointing satellite6 Star0)
	(pointing satellite8 Star0)
	(have_image Phenomenon4 spectrograph0)
))

)
