(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite4 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite5 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite6 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	satellite7 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	satellite8 - satellite
	instrument49 - instrument
	instrument50 - instrument
	satellite9 - satellite
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	image0 - mode
	infrared3 - mode
	thermograph2 - mode
	thermograph1 - mode
	thermograph4 - mode
	GroundStation1 - direction
	Star2 - direction
	Star0 - direction
	Phenomenon3 - direction
	Phenomenon4 - direction
)
(:init
	(supports instrument0 thermograph1)
	(supports instrument0 thermograph4)
	(supports instrument0 image0)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 image0)
	(supports instrument1 thermograph4)
	(supports instrument1 infrared3)
	(calibration_target instrument1 Star0)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 Star2)
	(supports instrument3 thermograph1)
	(supports instrument3 infrared3)
	(calibration_target instrument3 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation1)
	(supports instrument4 image0)
	(supports instrument4 thermograph2)
	(calibration_target instrument4 Star0)
	(supports instrument5 infrared3)
	(supports instrument5 thermograph4)
	(supports instrument5 thermograph1)
	(calibration_target instrument5 GroundStation1)
	(supports instrument6 infrared3)
	(supports instrument6 thermograph4)
	(calibration_target instrument6 Star0)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation1)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 Star0)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 GroundStation1)
	(supports instrument9 image0)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 Star0)
	(supports instrument10 thermograph1)
	(supports instrument10 infrared3)
	(supports instrument10 image0)
	(calibration_target instrument10 Star0)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 Star0)
	(supports instrument12 thermograph1)
	(supports instrument12 infrared3)
	(calibration_target instrument12 Star0)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star2)
	(supports instrument13 thermograph2)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 Star0)
	(supports instrument14 thermograph1)
	(calibration_target instrument14 Star0)
	(supports instrument15 thermograph4)
	(supports instrument15 image0)
	(supports instrument15 thermograph1)
	(calibration_target instrument15 Star0)
	(supports instrument16 thermograph4)
	(supports instrument16 image0)
	(calibration_target instrument16 GroundStation1)
	(supports instrument17 thermograph2)
	(calibration_target instrument17 Star2)
	(supports instrument18 infrared3)
	(supports instrument18 thermograph2)
	(calibration_target instrument18 Star0)
	(supports instrument19 infrared3)
	(supports instrument19 image0)
	(supports instrument19 thermograph1)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 image0)
	(supports instrument20 thermograph2)
	(calibration_target instrument20 Star0)
	(supports instrument21 thermograph4)
	(calibration_target instrument21 Star0)
	(supports instrument22 thermograph2)
	(supports instrument22 infrared3)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 GroundStation1)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon4)
	(supports instrument23 thermograph4)
	(supports instrument23 thermograph1)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 thermograph2)
	(supports instrument24 thermograph1)
	(calibration_target instrument24 Star2)
	(supports instrument25 image0)
	(supports instrument25 infrared3)
	(supports instrument25 thermograph2)
	(calibration_target instrument25 Star2)
	(supports instrument26 image0)
	(supports instrument26 thermograph4)
	(supports instrument26 thermograph2)
	(calibration_target instrument26 GroundStation1)
	(supports instrument27 thermograph4)
	(calibration_target instrument27 Star0)
	(supports instrument28 image0)
	(calibration_target instrument28 Star2)
	(supports instrument29 image0)
	(calibration_target instrument29 Star2)
	(supports instrument30 thermograph4)
	(calibration_target instrument30 GroundStation1)
	(supports instrument31 image0)
	(calibration_target instrument31 Star2)
	(supports instrument32 thermograph2)
	(supports instrument32 thermograph1)
	(calibration_target instrument32 Star2)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument33 infrared3)
	(calibration_target instrument33 GroundStation1)
	(supports instrument34 thermograph4)
	(supports instrument34 thermograph1)
	(supports instrument34 infrared3)
	(calibration_target instrument34 GroundStation1)
	(supports instrument35 thermograph4)
	(supports instrument35 infrared3)
	(calibration_target instrument35 Star0)
	(supports instrument36 infrared3)
	(supports instrument36 thermograph2)
	(calibration_target instrument36 Star0)
	(supports instrument37 thermograph4)
	(supports instrument37 thermograph1)
	(calibration_target instrument37 Star0)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star2)
	(supports instrument38 thermograph4)
	(supports instrument38 thermograph2)
	(supports instrument38 infrared3)
	(calibration_target instrument38 Star2)
	(supports instrument39 thermograph4)
	(supports instrument39 infrared3)
	(calibration_target instrument39 GroundStation1)
	(supports instrument40 infrared3)
	(supports instrument40 thermograph4)
	(calibration_target instrument40 Star0)
	(supports instrument41 thermograph2)
	(supports instrument41 thermograph4)
	(supports instrument41 infrared3)
	(calibration_target instrument41 Star2)
	(supports instrument42 thermograph2)
	(calibration_target instrument42 Star2)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon3)
	(supports instrument43 thermograph2)
	(supports instrument43 image0)
	(supports instrument43 thermograph4)
	(calibration_target instrument43 GroundStation1)
	(supports instrument44 thermograph1)
	(supports instrument44 image0)
	(supports instrument44 infrared3)
	(calibration_target instrument44 Star2)
	(supports instrument45 infrared3)
	(supports instrument45 image0)
	(supports instrument45 thermograph4)
	(calibration_target instrument45 Star2)
	(supports instrument46 image0)
	(supports instrument46 thermograph1)
	(calibration_target instrument46 Star0)
	(supports instrument47 infrared3)
	(supports instrument47 image0)
	(calibration_target instrument47 Star2)
	(supports instrument48 thermograph2)
	(supports instrument48 infrared3)
	(calibration_target instrument48 Star0)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
	(supports instrument49 thermograph4)
	(calibration_target instrument49 Star0)
	(supports instrument50 thermograph1)
	(calibration_target instrument50 Star2)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon3)
	(supports instrument51 image0)
	(calibration_target instrument51 GroundStation1)
	(supports instrument52 image0)
	(supports instrument52 thermograph4)
	(calibration_target instrument52 Star2)
	(supports instrument53 infrared3)
	(calibration_target instrument53 Star0)
	(supports instrument54 infrared3)
	(calibration_target instrument54 Star2)
	(supports instrument55 thermograph2)
	(supports instrument55 infrared3)
	(supports instrument55 thermograph4)
	(calibration_target instrument55 GroundStation1)
	(supports instrument56 thermograph1)
	(calibration_target instrument56 Star0)
	(supports instrument57 thermograph4)
	(supports instrument57 thermograph1)
	(calibration_target instrument57 Star2)
	(supports instrument58 thermograph4)
	(calibration_target instrument58 Star0)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon4)
)
(:goal (and
	(pointing satellite0 Phenomenon3)
	(pointing satellite1 Star2)
	(pointing satellite2 Phenomenon3)
	(pointing satellite7 Phenomenon4)
	(have_image Phenomenon3 thermograph4)
	(have_image Phenomenon4 image0)
))

)
