(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite3 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite4 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite5 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite6 - satellite
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	satellite7 - satellite
	instrument46 - instrument
	satellite8 - satellite
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	satellite9 - satellite
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	instrument59 - instrument
	instrument60 - instrument
	thermograph4 - mode
	infrared2 - mode
	image3 - mode
	spectrograph1 - mode
	infrared0 - mode
	Star0 - direction
	GroundStation1 - direction
	GroundStation2 - direction
	Star3 - direction
	Star4 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 infrared2)
	(supports instrument0 spectrograph1)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 thermograph4)
	(supports instrument1 spectrograph1)
	(calibration_target instrument1 Star0)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star4)
	(supports instrument3 spectrograph1)
	(supports instrument3 infrared0)
	(supports instrument3 infrared2)
	(calibration_target instrument3 Star0)
	(supports instrument4 infrared0)
	(calibration_target instrument4 GroundStation2)
	(supports instrument5 spectrograph1)
	(supports instrument5 thermograph4)
	(supports instrument5 image3)
	(calibration_target instrument5 Star0)
	(supports instrument6 infrared2)
	(calibration_target instrument6 Star0)
	(supports instrument7 spectrograph1)
	(supports instrument7 image3)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 GroundStation2)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star3)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 Star0)
	(supports instrument9 infrared0)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 infrared2)
	(supports instrument10 spectrograph1)
	(supports instrument10 infrared0)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 thermograph4)
	(supports instrument11 image3)
	(calibration_target instrument11 GroundStation1)
	(supports instrument12 infrared0)
	(supports instrument12 thermograph4)
	(supports instrument12 infrared2)
	(calibration_target instrument12 GroundStation2)
	(supports instrument13 spectrograph1)
	(supports instrument13 infrared0)
	(supports instrument13 image3)
	(calibration_target instrument13 GroundStation1)
	(supports instrument14 spectrograph1)
	(supports instrument14 thermograph4)
	(supports instrument14 infrared2)
	(calibration_target instrument14 GroundStation2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument15 infrared0)
	(supports instrument15 spectrograph1)
	(supports instrument15 thermograph4)
	(calibration_target instrument15 GroundStation2)
	(supports instrument16 image3)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 Star0)
	(supports instrument17 image3)
	(supports instrument17 spectrograph1)
	(supports instrument17 infrared2)
	(calibration_target instrument17 Star0)
	(supports instrument18 spectrograph1)
	(supports instrument18 thermograph4)
	(supports instrument18 infrared2)
	(calibration_target instrument18 GroundStation2)
	(supports instrument19 infrared2)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 spectrograph1)
	(supports instrument20 infrared0)
	(supports instrument20 thermograph4)
	(calibration_target instrument20 GroundStation1)
	(supports instrument21 spectrograph1)
	(supports instrument21 image3)
	(calibration_target instrument21 Star0)
	(supports instrument22 infrared2)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 Star0)
	(supports instrument23 spectrograph1)
	(supports instrument23 thermograph4)
	(supports instrument23 image3)
	(calibration_target instrument23 GroundStation2)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star3)
	(supports instrument24 image3)
	(calibration_target instrument24 Star0)
	(supports instrument25 infrared2)
	(supports instrument25 spectrograph1)
	(calibration_target instrument25 GroundStation2)
	(supports instrument26 image3)
	(supports instrument26 spectrograph1)
	(supports instrument26 infrared2)
	(calibration_target instrument26 GroundStation1)
	(supports instrument27 image3)
	(supports instrument27 infrared0)
	(supports instrument27 spectrograph1)
	(calibration_target instrument27 GroundStation2)
	(supports instrument28 image3)
	(supports instrument28 spectrograph1)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 Star0)
	(supports instrument29 infrared2)
	(supports instrument29 spectrograph1)
	(calibration_target instrument29 Star0)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star4)
	(supports instrument30 image3)
	(supports instrument30 infrared2)
	(supports instrument30 thermograph4)
	(calibration_target instrument30 Star0)
	(supports instrument31 image3)
	(calibration_target instrument31 GroundStation1)
	(supports instrument32 infrared2)
	(calibration_target instrument32 GroundStation2)
	(supports instrument33 image3)
	(calibration_target instrument33 GroundStation2)
	(supports instrument34 thermograph4)
	(supports instrument34 infrared0)
	(supports instrument34 image3)
	(calibration_target instrument34 Star0)
	(supports instrument35 infrared0)
	(supports instrument35 infrared2)
	(supports instrument35 spectrograph1)
	(calibration_target instrument35 Star0)
	(supports instrument36 infrared2)
	(calibration_target instrument36 GroundStation1)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star0)
	(supports instrument37 thermograph4)
	(supports instrument37 infrared2)
	(supports instrument37 spectrograph1)
	(calibration_target instrument37 GroundStation1)
	(supports instrument38 spectrograph1)
	(supports instrument38 thermograph4)
	(supports instrument38 image3)
	(calibration_target instrument38 GroundStation1)
	(supports instrument39 infrared0)
	(calibration_target instrument39 GroundStation2)
	(supports instrument40 infrared0)
	(supports instrument40 spectrograph1)
	(calibration_target instrument40 Star0)
	(supports instrument41 thermograph4)
	(supports instrument41 infrared0)
	(calibration_target instrument41 GroundStation1)
	(supports instrument42 infrared0)
	(calibration_target instrument42 Star0)
	(supports instrument43 thermograph4)
	(calibration_target instrument43 Star0)
	(supports instrument44 infrared0)
	(supports instrument44 image3)
	(calibration_target instrument44 Star0)
	(supports instrument45 infrared2)
	(supports instrument45 thermograph4)
	(supports instrument45 image3)
	(calibration_target instrument45 GroundStation2)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation1)
	(supports instrument46 infrared0)
	(supports instrument46 thermograph4)
	(supports instrument46 image3)
	(calibration_target instrument46 Star0)
	(on_board instrument46 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation1)
	(supports instrument47 spectrograph1)
	(supports instrument47 infrared2)
	(supports instrument47 infrared0)
	(calibration_target instrument47 GroundStation2)
	(supports instrument48 spectrograph1)
	(calibration_target instrument48 GroundStation1)
	(supports instrument49 spectrograph1)
	(supports instrument49 thermograph4)
	(supports instrument49 image3)
	(calibration_target instrument49 Star0)
	(supports instrument50 thermograph4)
	(supports instrument50 infrared2)
	(calibration_target instrument50 GroundStation1)
	(supports instrument51 thermograph4)
	(supports instrument51 image3)
	(supports instrument51 spectrograph1)
	(calibration_target instrument51 GroundStation1)
	(supports instrument52 infrared0)
	(calibration_target instrument52 GroundStation2)
	(supports instrument53 image3)
	(calibration_target instrument53 GroundStation1)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(on_board instrument51 satellite8)
	(on_board instrument52 satellite8)
	(on_board instrument53 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star4)
	(supports instrument54 spectrograph1)
	(supports instrument54 thermograph4)
	(supports instrument54 infrared0)
	(calibration_target instrument54 GroundStation1)
	(supports instrument55 spectrograph1)
	(calibration_target instrument55 GroundStation2)
	(supports instrument56 infrared2)
	(supports instrument56 image3)
	(supports instrument56 spectrograph1)
	(calibration_target instrument56 GroundStation1)
	(supports instrument57 infrared0)
	(supports instrument57 spectrograph1)
	(calibration_target instrument57 GroundStation1)
	(supports instrument58 image3)
	(calibration_target instrument58 GroundStation2)
	(supports instrument59 spectrograph1)
	(calibration_target instrument59 GroundStation1)
	(supports instrument60 infrared0)
	(calibration_target instrument60 GroundStation2)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(on_board instrument59 satellite9)
	(on_board instrument60 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star3)
)
(:goal (and
	(pointing satellite4 GroundStation2)
	(pointing satellite7 Star4)
	(have_image Star3 spectrograph1)
	(have_image Star4 thermograph4)
))

)
