(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite1 - satellite
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite3 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite4 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite5 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	satellite6 - satellite
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	satellite7 - satellite
	instrument46 - instrument
	instrument47 - instrument
	satellite8 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	satellite9 - satellite
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	spectrograph1 - mode
	image2 - mode
	thermograph4 - mode
	spectrograph3 - mode
	thermograph0 - mode
	Star2 - direction
	GroundStation1 - direction
	Star0 - direction
	Star3 - direction
	Star4 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 image2)
	(calibration_target instrument0 Star2)
	(supports instrument1 thermograph0)
	(supports instrument1 image2)
	(calibration_target instrument1 Star2)
	(supports instrument2 spectrograph1)
	(supports instrument2 spectrograph3)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 Star2)
	(supports instrument3 spectrograph3)
	(supports instrument3 spectrograph1)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 spectrograph1)
	(supports instrument4 spectrograph3)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 Star0)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 GroundStation1)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 GroundStation1)
	(supports instrument7 image2)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 Star0)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 Star0)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(on_board instrument9 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star3)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 GroundStation1)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star2)
	(supports instrument11 spectrograph3)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 Star0)
	(supports instrument12 spectrograph1)
	(supports instrument12 thermograph4)
	(supports instrument12 image2)
	(calibration_target instrument12 GroundStation1)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument13 spectrograph3)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 GroundStation1)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation1)
	(supports instrument15 thermograph0)
	(supports instrument15 thermograph4)
	(supports instrument15 spectrograph3)
	(calibration_target instrument15 Star2)
	(supports instrument16 thermograph4)
	(supports instrument16 thermograph0)
	(supports instrument16 spectrograph3)
	(calibration_target instrument16 GroundStation1)
	(supports instrument17 thermograph4)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 Star0)
	(supports instrument18 spectrograph3)
	(calibration_target instrument18 Star2)
	(supports instrument19 spectrograph1)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 GroundStation1)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star3)
	(supports instrument20 spectrograph1)
	(supports instrument20 spectrograph3)
	(supports instrument20 thermograph0)
	(calibration_target instrument20 Star0)
	(supports instrument21 image2)
	(supports instrument21 spectrograph1)
	(calibration_target instrument21 Star2)
	(supports instrument22 image2)
	(calibration_target instrument22 Star0)
	(supports instrument23 spectrograph1)
	(supports instrument23 spectrograph3)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 thermograph0)
	(supports instrument24 spectrograph1)
	(calibration_target instrument24 Star2)
	(supports instrument25 spectrograph1)
	(supports instrument25 thermograph4)
	(supports instrument25 spectrograph3)
	(calibration_target instrument25 Star0)
	(supports instrument26 thermograph4)
	(calibration_target instrument26 Star0)
	(supports instrument27 spectrograph3)
	(calibration_target instrument27 Star0)
	(supports instrument28 thermograph4)
	(supports instrument28 spectrograph3)
	(supports instrument28 thermograph0)
	(calibration_target instrument28 Star0)
	(supports instrument29 thermograph0)
	(calibration_target instrument29 GroundStation1)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star2)
	(supports instrument30 image2)
	(supports instrument30 thermograph0)
	(calibration_target instrument30 GroundStation1)
	(supports instrument31 image2)
	(supports instrument31 spectrograph3)
	(calibration_target instrument31 Star0)
	(supports instrument32 thermograph0)
	(supports instrument32 spectrograph3)
	(calibration_target instrument32 Star0)
	(supports instrument33 spectrograph1)
	(calibration_target instrument33 Star2)
	(supports instrument34 spectrograph1)
	(calibration_target instrument34 GroundStation1)
	(supports instrument35 thermograph0)
	(calibration_target instrument35 GroundStation1)
	(supports instrument36 thermograph4)
	(calibration_target instrument36 Star0)
	(supports instrument37 spectrograph1)
	(calibration_target instrument37 Star0)
	(supports instrument38 thermograph0)
	(supports instrument38 image2)
	(calibration_target instrument38 Star2)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(on_board instrument37 satellite5)
	(on_board instrument38 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(supports instrument39 thermograph4)
	(supports instrument39 spectrograph3)
	(calibration_target instrument39 Star2)
	(supports instrument40 thermograph0)
	(supports instrument40 thermograph4)
	(calibration_target instrument40 GroundStation1)
	(supports instrument41 image2)
	(calibration_target instrument41 Star2)
	(supports instrument42 image2)
	(calibration_target instrument42 Star0)
	(supports instrument43 spectrograph1)
	(calibration_target instrument43 Star2)
	(supports instrument44 spectrograph3)
	(supports instrument44 spectrograph1)
	(calibration_target instrument44 Star0)
	(supports instrument45 thermograph0)
	(supports instrument45 spectrograph3)
	(calibration_target instrument45 Star0)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star3)
	(supports instrument46 thermograph4)
	(calibration_target instrument46 Star0)
	(supports instrument47 spectrograph1)
	(supports instrument47 thermograph4)
	(calibration_target instrument47 GroundStation1)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star2)
	(supports instrument48 spectrograph3)
	(supports instrument48 image2)
	(supports instrument48 spectrograph1)
	(calibration_target instrument48 Star0)
	(supports instrument49 thermograph0)
	(supports instrument49 spectrograph1)
	(calibration_target instrument49 Star0)
	(supports instrument50 thermograph4)
	(calibration_target instrument50 Star2)
	(on_board instrument48 satellite8)
	(on_board instrument49 satellite8)
	(on_board instrument50 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation1)
	(supports instrument51 spectrograph1)
	(supports instrument51 thermograph0)
	(calibration_target instrument51 Star0)
	(supports instrument52 thermograph0)
	(supports instrument52 image2)
	(calibration_target instrument52 Star0)
	(supports instrument53 spectrograph3)
	(supports instrument53 image2)
	(calibration_target instrument53 GroundStation1)
	(supports instrument54 thermograph4)
	(calibration_target instrument54 GroundStation1)
	(supports instrument55 thermograph0)
	(supports instrument55 spectrograph3)
	(calibration_target instrument55 Star0)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation1)
)
(:goal (and
	(pointing satellite0 Star3)
	(pointing satellite2 GroundStation1)
	(pointing satellite3 Star0)
	(pointing satellite8 Star2)
	(have_image Star3 thermograph0)
	(have_image Star4 thermograph4)
))

)
