(define (problem pb1)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (on block1 block6) (on block2 block4) (clear block2) (ontable block3) (on block4 block3) (on block5 block7) (clear block5) (ontable block6) (on block7 block1) (handempty))
	(:goal (and (ontable block1) (on block2 block1) (on block3 block6) (clear block3) (on block4 block2) (on block5 block4) (clear block5) (on block6 block7) (ontable block7))))