(define (problem pb7)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (ontable block1) (clear block1) (on block2 block4) (ontable block3) (clear block3) (on block4 block7) (on block5 block2) (clear block5) (ontable block6) (on block7 block6) (handempty))
	(:goal (and (on block1 block3) (on block2 block4) (clear block2) (on block3 block7) (ontable block4) (ontable block5) (clear block5) (on block6 block1) (clear block6) (ontable block7))))