(define (problem pb4)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (on block1 block7) (on block2 block6) (clear block2) (on block3 block1) (clear block3) (ontable block4) (on block5 block4) (on block6 block5) (ontable block7) (handempty))
	(:goal (and (on block1 block2) (clear block1) (ontable block2) (ontable block3) (clear block3) (ontable block4) (clear block4) (on block5 block6) (ontable block6) (on block7 block5) (clear block7))))