(define (problem pb2)
	(:domain blocks)
	(:objects block1 block2 block3 block4 block5 block6 block7)
	(:init (on block1 block4) (on block2 block1) (clear block2) (on block3 block5) (ontable block4) (ontable block5) (on block6 block7) (clear block6) (on block7 block3) (handempty))
	(:goal (and (on block1 block2) (clear block1) (on block2 block4) (ontable block3) (ontable block4) (on block5 block6) (on block6 block3) (on block7 block5) (clear block7))))