(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite2 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite3 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite4 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite5 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite6 - satellite
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	satellite7 - satellite
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	satellite8 - satellite
	instrument55 - instrument
	instrument56 - instrument
	satellite9 - satellite
	instrument57 - instrument
	infrared3 - mode
	spectrograph0 - mode
	thermograph2 - mode
	image1 - mode
	spectrograph4 - mode
	Star6 - direction
	GroundStation1 - direction
	Star0 - direction
	Star4 - direction
	Star5 - direction
	Star2 - direction
	Star3 - direction
	Planet7 - direction
	Planet8 - direction
)
(:init
	(supports instrument0 spectrograph4)
	(calibration_target instrument0 Star2)
	(supports instrument1 spectrograph0)
	(supports instrument1 image1)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 infrared3)
	(calibration_target instrument2 GroundStation1)
	(calibration_target instrument2 Star5)
	(supports instrument3 thermograph2)
	(supports instrument3 image1)
	(calibration_target instrument3 Star4)
	(calibration_target instrument3 Star3)
	(supports instrument4 infrared3)
	(supports instrument4 thermograph2)
	(supports instrument4 image1)
	(calibration_target instrument4 Star2)
	(supports instrument5 infrared3)
	(supports instrument5 thermograph2)
	(supports instrument5 image1)
	(calibration_target instrument5 Star5)
	(calibration_target instrument5 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star2)
	(supports instrument6 spectrograph0)
	(supports instrument6 infrared3)
	(supports instrument6 image1)
	(calibration_target instrument6 Star4)
	(supports instrument7 thermograph2)
	(supports instrument7 infrared3)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 Star5)
	(supports instrument8 spectrograph0)
	(supports instrument8 spectrograph4)
	(calibration_target instrument8 GroundStation1)
	(supports instrument9 infrared3)
	(supports instrument9 image1)
	(supports instrument9 thermograph2)
	(calibration_target instrument9 Star6)
	(calibration_target instrument9 Star2)
	(supports instrument10 spectrograph4)
	(supports instrument10 spectrograph0)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 thermograph2)
	(supports instrument11 spectrograph4)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 Star4)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(supports instrument12 thermograph2)
	(supports instrument12 spectrograph4)
	(supports instrument12 image1)
	(calibration_target instrument12 Star5)
	(calibration_target instrument12 Star3)
	(supports instrument13 image1)
	(calibration_target instrument13 Star2)
	(calibration_target instrument13 Star5)
	(supports instrument14 image1)
	(supports instrument14 spectrograph4)
	(calibration_target instrument14 Star5)
	(supports instrument15 image1)
	(calibration_target instrument15 Star6)
	(calibration_target instrument15 Star5)
	(supports instrument16 thermograph2)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 Star3)
	(supports instrument17 spectrograph0)
	(supports instrument17 spectrograph4)
	(calibration_target instrument17 Star2)
	(calibration_target instrument17 Star5)
	(supports instrument18 infrared3)
	(supports instrument18 spectrograph0)
	(supports instrument18 thermograph2)
	(calibration_target instrument18 Star5)
	(supports instrument19 spectrograph0)
	(supports instrument19 image1)
	(supports instrument19 infrared3)
	(calibration_target instrument19 Star2)
	(calibration_target instrument19 Star0)
	(supports instrument20 spectrograph4)
	(supports instrument20 thermograph2)
	(supports instrument20 infrared3)
	(calibration_target instrument20 Star5)
	(calibration_target instrument20 Star3)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument21 spectrograph4)
	(supports instrument21 thermograph2)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 Star4)
	(calibration_target instrument21 Star6)
	(supports instrument22 spectrograph4)
	(calibration_target instrument22 Star0)
	(supports instrument23 spectrograph4)
	(supports instrument23 infrared3)
	(calibration_target instrument23 Star0)
	(calibration_target instrument23 Star6)
	(supports instrument24 infrared3)
	(supports instrument24 thermograph2)
	(supports instrument24 spectrograph0)
	(calibration_target instrument24 Star3)
	(calibration_target instrument24 Star2)
	(supports instrument25 spectrograph0)
	(calibration_target instrument25 Star6)
	(calibration_target instrument25 Star5)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star2)
	(supports instrument26 image1)
	(supports instrument26 spectrograph0)
	(supports instrument26 infrared3)
	(calibration_target instrument26 Star3)
	(supports instrument27 thermograph2)
	(supports instrument27 spectrograph0)
	(supports instrument27 infrared3)
	(calibration_target instrument27 Star0)
	(calibration_target instrument27 Star6)
	(supports instrument28 spectrograph4)
	(supports instrument28 infrared3)
	(calibration_target instrument28 Star6)
	(supports instrument29 thermograph2)
	(calibration_target instrument29 Star2)
	(supports instrument30 spectrograph4)
	(supports instrument30 infrared3)
	(calibration_target instrument30 Star3)
	(supports instrument31 spectrograph0)
	(calibration_target instrument31 Star6)
	(calibration_target instrument31 Star4)
	(supports instrument32 image1)
	(supports instrument32 spectrograph0)
	(supports instrument32 thermograph2)
	(calibration_target instrument32 Star6)
	(calibration_target instrument32 Star5)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star4)
	(supports instrument33 image1)
	(calibration_target instrument33 Star5)
	(calibration_target instrument33 Star3)
	(supports instrument34 image1)
	(calibration_target instrument34 Star0)
	(calibration_target instrument34 Star6)
	(supports instrument35 spectrograph0)
	(supports instrument35 image1)
	(supports instrument35 spectrograph4)
	(calibration_target instrument35 Star6)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(on_board instrument35 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star4)
	(supports instrument36 image1)
	(supports instrument36 thermograph2)
	(supports instrument36 spectrograph0)
	(calibration_target instrument36 GroundStation1)
	(calibration_target instrument36 Star5)
	(supports instrument37 spectrograph4)
	(supports instrument37 image1)
	(supports instrument37 spectrograph0)
	(calibration_target instrument37 Star0)
	(calibration_target instrument37 Star4)
	(supports instrument38 spectrograph0)
	(supports instrument38 spectrograph4)
	(supports instrument38 image1)
	(calibration_target instrument38 Star6)
	(supports instrument39 spectrograph0)
	(supports instrument39 spectrograph4)
	(calibration_target instrument39 Star5)
	(supports instrument40 infrared3)
	(calibration_target instrument40 Star5)
	(supports instrument41 spectrograph4)
	(calibration_target instrument41 Star2)
	(calibration_target instrument41 Star4)
	(supports instrument42 spectrograph0)
	(supports instrument42 image1)
	(supports instrument42 thermograph2)
	(calibration_target instrument42 Star4)
	(supports instrument43 image1)
	(supports instrument43 spectrograph0)
	(calibration_target instrument43 Star3)
	(calibration_target instrument43 GroundStation1)
	(supports instrument44 spectrograph0)
	(supports instrument44 spectrograph4)
	(supports instrument44 image1)
	(calibration_target instrument44 Star5)
	(calibration_target instrument44 Star3)
	(supports instrument45 thermograph2)
	(calibration_target instrument45 Star6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(on_board instrument43 satellite6)
	(on_board instrument44 satellite6)
	(on_board instrument45 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star2)
	(supports instrument46 spectrograph0)
	(supports instrument46 image1)
	(calibration_target instrument46 GroundStation1)
	(supports instrument47 thermograph2)
	(calibration_target instrument47 Star2)
	(supports instrument48 image1)
	(calibration_target instrument48 Star2)
	(supports instrument49 spectrograph0)
	(calibration_target instrument49 Star4)
	(calibration_target instrument49 GroundStation1)
	(supports instrument50 thermograph2)
	(supports instrument50 image1)
	(calibration_target instrument50 Star5)
	(calibration_target instrument50 Star0)
	(supports instrument51 infrared3)
	(supports instrument51 image1)
	(calibration_target instrument51 Star4)
	(supports instrument52 spectrograph4)
	(supports instrument52 thermograph2)
	(calibration_target instrument52 Star0)
	(calibration_target instrument52 Star2)
	(supports instrument53 spectrograph0)
	(calibration_target instrument53 Star2)
	(calibration_target instrument53 Star0)
	(supports instrument54 thermograph2)
	(calibration_target instrument54 Star5)
	(calibration_target instrument54 Star3)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(on_board instrument53 satellite7)
	(on_board instrument54 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
	(supports instrument55 spectrograph0)
	(supports instrument55 spectrograph4)
	(calibration_target instrument55 Star5)
	(calibration_target instrument55 Star4)
	(supports instrument56 spectrograph0)
	(supports instrument56 thermograph2)
	(supports instrument56 spectrograph4)
	(calibration_target instrument56 Star3)
	(calibration_target instrument56 Star2)
	(on_board instrument55 satellite8)
	(on_board instrument56 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star0)
	(supports instrument57 spectrograph4)
	(supports instrument57 image1)
	(supports instrument57 thermograph2)
	(calibration_target instrument57 Star3)
	(on_board instrument57 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star4)
)
(:goal (and
	(pointing satellite0 GroundStation1)
	(pointing satellite1 Star6)
	(pointing satellite2 Star0)
	(pointing satellite4 Planet7)
	(have_image Planet7 spectrograph4)
	(have_image Planet8 spectrograph0)
))

)
