(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite3 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite4 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite5 - satellite
	instrument23 - instrument
	instrument24 - instrument
	satellite6 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite7 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite8 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	satellite9 - satellite
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	thermograph2 - mode
	infrared0 - mode
	image3 - mode
	thermograph1 - mode
	infrared4 - mode
	Star3 - direction
	GroundStation2 - direction
	GroundStation4 - direction
	Star6 - direction
	Star1 - direction
	GroundStation0 - direction
	Star5 - direction
	Star7 - direction
	Star8 - direction
)
(:init
	(supports instrument0 thermograph1)
	(supports instrument0 thermograph2)
	(supports instrument0 infrared4)
	(calibration_target instrument0 Star6)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 GroundStation0)
	(calibration_target instrument1 Star6)
	(supports instrument2 infrared4)
	(supports instrument2 infrared0)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 Star5)
	(calibration_target instrument2 GroundStation4)
	(supports instrument3 infrared0)
	(supports instrument3 image3)
	(calibration_target instrument3 GroundStation0)
	(calibration_target instrument3 Star3)
	(supports instrument4 infrared0)
	(supports instrument4 image3)
	(calibration_target instrument4 Star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star3)
	(supports instrument5 thermograph2)
	(supports instrument5 infrared0)
	(calibration_target instrument5 GroundStation0)
	(calibration_target instrument5 Star3)
	(supports instrument6 thermograph2)
	(supports instrument6 infrared0)
	(supports instrument6 infrared4)
	(calibration_target instrument6 GroundStation0)
	(supports instrument7 image3)
	(supports instrument7 infrared4)
	(calibration_target instrument7 Star6)
	(calibration_target instrument7 GroundStation4)
	(supports instrument8 infrared4)
	(calibration_target instrument8 GroundStation0)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument9 image3)
	(calibration_target instrument9 GroundStation4)
	(supports instrument10 infrared4)
	(calibration_target instrument10 Star5)
	(supports instrument11 image3)
	(supports instrument11 infrared4)
	(calibration_target instrument11 GroundStation0)
	(calibration_target instrument11 Star5)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star5)
	(supports instrument12 infrared0)
	(calibration_target instrument12 GroundStation4)
	(supports instrument13 infrared0)
	(supports instrument13 image3)
	(calibration_target instrument13 Star5)
	(calibration_target instrument13 Star6)
	(supports instrument14 thermograph1)
	(supports instrument14 infrared0)
	(supports instrument14 thermograph2)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 GroundStation2)
	(supports instrument15 thermograph2)
	(calibration_target instrument15 Star3)
	(calibration_target instrument15 Star1)
	(supports instrument16 image3)
	(supports instrument16 infrared4)
	(calibration_target instrument16 GroundStation2)
	(calibration_target instrument16 Star1)
	(supports instrument17 image3)
	(supports instrument17 thermograph2)
	(supports instrument17 thermograph1)
	(calibration_target instrument17 GroundStation4)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation2)
	(supports instrument18 thermograph2)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 Star5)
	(supports instrument19 image3)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 infrared0)
	(supports instrument20 thermograph2)
	(supports instrument20 image3)
	(calibration_target instrument20 Star1)
	(calibration_target instrument20 Star3)
	(supports instrument21 infrared4)
	(calibration_target instrument21 GroundStation4)
	(supports instrument22 infrared0)
	(supports instrument22 thermograph1)
	(supports instrument22 image3)
	(calibration_target instrument22 Star6)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(on_board instrument22 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star1)
	(supports instrument23 infrared0)
	(supports instrument23 thermograph2)
	(calibration_target instrument23 Star6)
	(supports instrument24 infrared0)
	(calibration_target instrument24 GroundStation4)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation4)
	(supports instrument25 thermograph2)
	(calibration_target instrument25 GroundStation2)
	(supports instrument26 thermograph2)
	(supports instrument26 infrared0)
	(calibration_target instrument26 Star3)
	(calibration_target instrument26 Star5)
	(supports instrument27 infrared4)
	(supports instrument27 infrared0)
	(supports instrument27 thermograph2)
	(calibration_target instrument27 GroundStation4)
	(calibration_target instrument27 GroundStation0)
	(on_board instrument25 satellite6)
	(on_board instrument26 satellite6)
	(on_board instrument27 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star7)
	(supports instrument28 infrared4)
	(supports instrument28 thermograph2)
	(supports instrument28 thermograph1)
	(calibration_target instrument28 GroundStation0)
	(supports instrument29 thermograph2)
	(supports instrument29 infrared0)
	(supports instrument29 thermograph1)
	(calibration_target instrument29 Star5)
	(supports instrument30 image3)
	(supports instrument30 infrared0)
	(supports instrument30 thermograph1)
	(calibration_target instrument30 Star3)
	(supports instrument31 thermograph2)
	(calibration_target instrument31 Star6)
	(on_board instrument28 satellite7)
	(on_board instrument29 satellite7)
	(on_board instrument30 satellite7)
	(on_board instrument31 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star7)
	(supports instrument32 infrared4)
	(calibration_target instrument32 Star6)
	(calibration_target instrument32 GroundStation0)
	(supports instrument33 infrared0)
	(supports instrument33 infrared4)
	(supports instrument33 image3)
	(calibration_target instrument33 Star5)
	(calibration_target instrument33 Star3)
	(supports instrument34 infrared0)
	(supports instrument34 image3)
	(supports instrument34 infrared4)
	(calibration_target instrument34 Star1)
	(supports instrument35 infrared0)
	(calibration_target instrument35 GroundStation2)
	(supports instrument36 image3)
	(supports instrument36 thermograph1)
	(supports instrument36 infrared0)
	(calibration_target instrument36 GroundStation4)
	(calibration_target instrument36 Star5)
	(supports instrument37 infrared4)
	(calibration_target instrument37 GroundStation0)
	(on_board instrument32 satellite8)
	(on_board instrument33 satellite8)
	(on_board instrument34 satellite8)
	(on_board instrument35 satellite8)
	(on_board instrument36 satellite8)
	(on_board instrument37 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star7)
	(supports instrument38 image3)
	(calibration_target instrument38 Star6)
	(calibration_target instrument38 GroundStation0)
	(supports instrument39 thermograph1)
	(calibration_target instrument39 GroundStation0)
	(calibration_target instrument39 Star1)
	(supports instrument40 infrared4)
	(calibration_target instrument40 Star5)
	(on_board instrument38 satellite9)
	(on_board instrument39 satellite9)
	(on_board instrument40 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star8)
)
(:goal (and
	(pointing satellite0 Star6)
	(pointing satellite1 Star1)
	(pointing satellite7 GroundStation4)
	(pointing satellite9 Star1)
	(have_image Star7 thermograph1)
	(have_image Star8 thermograph2)
))

)
