(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite2 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite3 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite4 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite5 - satellite
	instrument35 - instrument
	instrument36 - instrument
	satellite6 - satellite
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	satellite7 - satellite
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	satellite8 - satellite
	instrument53 - instrument
	satellite9 - satellite
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	thermograph4 - mode
	image1 - mode
	thermograph3 - mode
	thermograph2 - mode
	thermograph0 - mode
	Star4 - direction
	Star1 - direction
	GroundStation5 - direction
	GroundStation2 - direction
	Star3 - direction
	GroundStation6 - direction
	Star0 - direction
	Phenomenon7 - direction
	Planet8 - direction
)
(:init
	(supports instrument0 thermograph0)
	(calibration_target instrument0 Star3)
	(supports instrument1 thermograph3)
	(calibration_target instrument1 GroundStation2)
	(calibration_target instrument1 Star1)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 Star1)
	(supports instrument3 thermograph4)
	(supports instrument3 thermograph0)
	(supports instrument3 image1)
	(calibration_target instrument3 Star4)
	(calibration_target instrument3 Star0)
	(supports instrument4 thermograph3)
	(supports instrument4 thermograph0)
	(supports instrument4 thermograph2)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 GroundStation2)
	(supports instrument5 thermograph0)
	(supports instrument5 thermograph2)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 GroundStation2)
	(calibration_target instrument5 GroundStation6)
	(supports instrument6 image1)
	(calibration_target instrument6 Star4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet8)
	(supports instrument7 image1)
	(calibration_target instrument7 Star4)
	(supports instrument8 image1)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 Star3)
	(supports instrument9 thermograph3)
	(supports instrument9 thermograph0)
	(supports instrument9 thermograph2)
	(calibration_target instrument9 Star4)
	(supports instrument10 thermograph0)
	(supports instrument10 image1)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 Star4)
	(supports instrument11 image1)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 Star4)
	(supports instrument12 image1)
	(supports instrument12 thermograph0)
	(supports instrument12 thermograph3)
	(calibration_target instrument12 GroundStation5)
	(supports instrument13 thermograph4)
	(supports instrument13 thermograph0)
	(supports instrument13 thermograph2)
	(calibration_target instrument13 GroundStation6)
	(calibration_target instrument13 Star3)
	(supports instrument14 thermograph3)
	(calibration_target instrument14 GroundStation2)
	(calibration_target instrument14 GroundStation5)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 Star3)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument16 thermograph2)
	(supports instrument16 thermograph3)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 GroundStation6)
	(supports instrument17 thermograph3)
	(calibration_target instrument17 GroundStation5)
	(supports instrument18 thermograph2)
	(supports instrument18 thermograph0)
	(supports instrument18 image1)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 GroundStation6)
	(supports instrument19 thermograph2)
	(calibration_target instrument19 GroundStation5)
	(calibration_target instrument19 Star4)
	(supports instrument20 thermograph2)
	(calibration_target instrument20 Star1)
	(calibration_target instrument20 GroundStation2)
	(supports instrument21 thermograph0)
	(supports instrument21 thermograph3)
	(calibration_target instrument21 Star0)
	(calibration_target instrument21 GroundStation6)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation6)
	(supports instrument22 thermograph3)
	(supports instrument22 thermograph4)
	(supports instrument22 thermograph0)
	(calibration_target instrument22 GroundStation6)
	(supports instrument23 thermograph3)
	(supports instrument23 image1)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 GroundStation5)
	(calibration_target instrument23 GroundStation6)
	(supports instrument24 thermograph4)
	(supports instrument24 thermograph2)
	(calibration_target instrument24 GroundStation5)
	(supports instrument25 thermograph4)
	(supports instrument25 image1)
	(calibration_target instrument25 Star4)
	(supports instrument26 thermograph0)
	(supports instrument26 image1)
	(supports instrument26 thermograph2)
	(calibration_target instrument26 GroundStation5)
	(calibration_target instrument26 GroundStation2)
	(supports instrument27 thermograph3)
	(calibration_target instrument27 Star0)
	(supports instrument28 thermograph0)
	(supports instrument28 thermograph3)
	(supports instrument28 image1)
	(calibration_target instrument28 GroundStation6)
	(supports instrument29 thermograph3)
	(supports instrument29 thermograph2)
	(calibration_target instrument29 Star3)
	(supports instrument30 image1)
	(supports instrument30 thermograph0)
	(calibration_target instrument30 Star1)
	(supports instrument31 thermograph3)
	(supports instrument31 thermograph2)
	(supports instrument31 thermograph0)
	(calibration_target instrument31 Star0)
	(calibration_target instrument31 Star4)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(on_board instrument30 satellite3)
	(on_board instrument31 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation6)
	(supports instrument32 thermograph2)
	(calibration_target instrument32 Star0)
	(calibration_target instrument32 GroundStation6)
	(supports instrument33 thermograph4)
	(supports instrument33 thermograph2)
	(calibration_target instrument33 Star3)
	(calibration_target instrument33 GroundStation2)
	(supports instrument34 thermograph3)
	(calibration_target instrument34 Star0)
	(calibration_target instrument34 Star1)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation5)
	(supports instrument35 image1)
	(calibration_target instrument35 Star1)
	(supports instrument36 thermograph0)
	(supports instrument36 thermograph3)
	(calibration_target instrument36 GroundStation2)
	(calibration_target instrument36 Star3)
	(on_board instrument35 satellite5)
	(on_board instrument36 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation5)
	(supports instrument37 thermograph0)
	(calibration_target instrument37 GroundStation5)
	(supports instrument38 image1)
	(calibration_target instrument38 GroundStation2)
	(supports instrument39 image1)
	(supports instrument39 thermograph4)
	(calibration_target instrument39 Star3)
	(calibration_target instrument39 Star4)
	(supports instrument40 image1)
	(supports instrument40 thermograph3)
	(calibration_target instrument40 Star0)
	(supports instrument41 thermograph3)
	(calibration_target instrument41 Star3)
	(calibration_target instrument41 Star1)
	(supports instrument42 thermograph0)
	(supports instrument42 thermograph4)
	(calibration_target instrument42 GroundStation5)
	(calibration_target instrument42 Star0)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(on_board instrument42 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon7)
	(supports instrument43 thermograph0)
	(supports instrument43 thermograph3)
	(supports instrument43 thermograph2)
	(calibration_target instrument43 GroundStation6)
	(calibration_target instrument43 Star3)
	(supports instrument44 thermograph2)
	(supports instrument44 thermograph4)
	(calibration_target instrument44 Star3)
	(supports instrument45 image1)
	(supports instrument45 thermograph3)
	(supports instrument45 thermograph0)
	(calibration_target instrument45 Star4)
	(calibration_target instrument45 GroundStation5)
	(supports instrument46 thermograph4)
	(calibration_target instrument46 Star1)
	(supports instrument47 thermograph2)
	(supports instrument47 thermograph3)
	(supports instrument47 thermograph4)
	(calibration_target instrument47 GroundStation5)
	(calibration_target instrument47 Star0)
	(supports instrument48 thermograph4)
	(calibration_target instrument48 Star1)
	(calibration_target instrument48 GroundStation5)
	(supports instrument49 thermograph4)
	(supports instrument49 thermograph3)
	(supports instrument49 thermograph2)
	(calibration_target instrument49 GroundStation6)
	(calibration_target instrument49 Star1)
	(supports instrument50 thermograph2)
	(supports instrument50 thermograph4)
	(calibration_target instrument50 Star1)
	(calibration_target instrument50 Star0)
	(supports instrument51 image1)
	(supports instrument51 thermograph2)
	(supports instrument51 thermograph3)
	(calibration_target instrument51 Star0)
	(calibration_target instrument51 GroundStation6)
	(supports instrument52 thermograph3)
	(supports instrument52 thermograph0)
	(calibration_target instrument52 Star0)
	(calibration_target instrument52 GroundStation6)
	(on_board instrument43 satellite7)
	(on_board instrument44 satellite7)
	(on_board instrument45 satellite7)
	(on_board instrument46 satellite7)
	(on_board instrument47 satellite7)
	(on_board instrument48 satellite7)
	(on_board instrument49 satellite7)
	(on_board instrument50 satellite7)
	(on_board instrument51 satellite7)
	(on_board instrument52 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star4)
	(supports instrument53 image1)
	(supports instrument53 thermograph3)
	(supports instrument53 thermograph2)
	(calibration_target instrument53 GroundStation5)
	(on_board instrument53 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star1)
	(supports instrument54 thermograph2)
	(calibration_target instrument54 Star0)
	(supports instrument55 thermograph3)
	(supports instrument55 thermograph0)
	(supports instrument55 image1)
	(calibration_target instrument55 GroundStation2)
	(calibration_target instrument55 Star3)
	(supports instrument56 thermograph2)
	(calibration_target instrument56 GroundStation2)
	(calibration_target instrument56 Star0)
	(supports instrument57 thermograph2)
	(supports instrument57 thermograph3)
	(supports instrument57 thermograph0)
	(calibration_target instrument57 GroundStation6)
	(calibration_target instrument57 Star3)
	(supports instrument58 thermograph0)
	(supports instrument58 thermograph2)
	(supports instrument58 thermograph3)
	(calibration_target instrument58 Star0)
	(on_board instrument54 satellite9)
	(on_board instrument55 satellite9)
	(on_board instrument56 satellite9)
	(on_board instrument57 satellite9)
	(on_board instrument58 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star0)
)
(:goal (and
	(pointing satellite2 Phenomenon7)
	(pointing satellite8 GroundStation5)
	(have_image Phenomenon7 thermograph0)
	(have_image Planet8 thermograph2)
))

)
