(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite3 - satellite
	instrument15 - instrument
	instrument16 - instrument
	satellite4 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite5 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	satellite6 - satellite
	instrument31 - instrument
	instrument32 - instrument
	satellite7 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite8 - satellite
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	satellite9 - satellite
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	image2 - mode
	thermograph0 - mode
	spectrograph3 - mode
	spectrograph1 - mode
	thermograph4 - mode
	GroundStation4 - direction
	GroundStation1 - direction
	Star3 - direction
	Star2 - direction
	Star6 - direction
	Star0 - direction
	GroundStation5 - direction
	Star7 - direction
	Phenomenon8 - direction
)
(:init
	(supports instrument0 thermograph0)
	(supports instrument0 image2)
	(calibration_target instrument0 Star6)
	(supports instrument1 image2)
	(supports instrument1 thermograph0)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 Star2)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 GroundStation1)
	(supports instrument3 spectrograph3)
	(supports instrument3 image2)
	(supports instrument3 spectrograph1)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 GroundStation4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star2)
	(supports instrument4 image2)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 Star2)
	(supports instrument5 thermograph0)
	(supports instrument5 spectrograph1)
	(calibration_target instrument5 Star0)
	(supports instrument6 thermograph0)
	(supports instrument6 thermograph4)
	(supports instrument6 image2)
	(calibration_target instrument6 Star0)
	(supports instrument7 spectrograph3)
	(supports instrument7 thermograph0)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 Star3)
	(supports instrument8 thermograph0)
	(supports instrument8 spectrograph3)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 GroundStation4)
	(supports instrument9 thermograph0)
	(supports instrument9 spectrograph3)
	(calibration_target instrument9 Star6)
	(calibration_target instrument9 Star0)
	(supports instrument10 spectrograph1)
	(supports instrument10 image2)
	(calibration_target instrument10 Star2)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation4)
	(supports instrument11 thermograph4)
	(supports instrument11 spectrograph1)
	(supports instrument11 image2)
	(calibration_target instrument11 Star6)
	(calibration_target instrument11 Star3)
	(supports instrument12 spectrograph1)
	(supports instrument12 spectrograph3)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 GroundStation4)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 GroundStation4)
	(supports instrument14 thermograph0)
	(supports instrument14 image2)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 Star2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument15 image2)
	(calibration_target instrument15 Star2)
	(supports instrument16 thermograph4)
	(supports instrument16 spectrograph3)
	(supports instrument16 thermograph0)
	(calibration_target instrument16 Star3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation1)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 GroundStation1)
	(calibration_target instrument17 Star6)
	(supports instrument18 thermograph4)
	(supports instrument18 image2)
	(supports instrument18 spectrograph3)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 GroundStation5)
	(supports instrument19 thermograph4)
	(supports instrument19 thermograph0)
	(supports instrument19 image2)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 spectrograph3)
	(supports instrument20 image2)
	(supports instrument20 thermograph4)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 Star6)
	(supports instrument21 spectrograph1)
	(calibration_target instrument21 Star0)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star2)
	(supports instrument22 thermograph4)
	(supports instrument22 thermograph0)
	(supports instrument22 spectrograph3)
	(calibration_target instrument22 GroundStation1)
	(supports instrument23 spectrograph1)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 Star3)
	(supports instrument24 spectrograph3)
	(calibration_target instrument24 GroundStation1)
	(supports instrument25 spectrograph1)
	(supports instrument25 thermograph4)
	(calibration_target instrument25 GroundStation4)
	(calibration_target instrument25 Star0)
	(supports instrument26 thermograph4)
	(calibration_target instrument26 GroundStation1)
	(calibration_target instrument26 Star3)
	(supports instrument27 image2)
	(supports instrument27 thermograph0)
	(calibration_target instrument27 Star6)
	(supports instrument28 spectrograph1)
	(supports instrument28 spectrograph3)
	(calibration_target instrument28 GroundStation1)
	(calibration_target instrument28 GroundStation5)
	(supports instrument29 spectrograph1)
	(calibration_target instrument29 GroundStation5)
	(supports instrument30 spectrograph3)
	(calibration_target instrument30 Star3)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(on_board instrument26 satellite5)
	(on_board instrument27 satellite5)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star2)
	(supports instrument31 image2)
	(supports instrument31 thermograph0)
	(calibration_target instrument31 GroundStation5)
	(calibration_target instrument31 Star2)
	(supports instrument32 image2)
	(calibration_target instrument32 Star3)
	(calibration_target instrument32 GroundStation4)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star0)
	(supports instrument33 spectrograph1)
	(supports instrument33 thermograph0)
	(supports instrument33 thermograph4)
	(calibration_target instrument33 Star3)
	(supports instrument34 spectrograph3)
	(supports instrument34 thermograph4)
	(calibration_target instrument34 GroundStation1)
	(supports instrument35 spectrograph1)
	(supports instrument35 image2)
	(supports instrument35 thermograph0)
	(calibration_target instrument35 Star0)
	(calibration_target instrument35 GroundStation1)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation1)
	(supports instrument36 image2)
	(supports instrument36 thermograph0)
	(supports instrument36 spectrograph1)
	(calibration_target instrument36 GroundStation1)
	(supports instrument37 thermograph0)
	(supports instrument37 spectrograph1)
	(calibration_target instrument37 Star6)
	(supports instrument38 thermograph4)
	(supports instrument38 spectrograph1)
	(supports instrument38 spectrograph3)
	(calibration_target instrument38 Star0)
	(supports instrument39 spectrograph3)
	(calibration_target instrument39 Star3)
	(supports instrument40 image2)
	(supports instrument40 thermograph4)
	(calibration_target instrument40 Star6)
	(calibration_target instrument40 Star2)
	(supports instrument41 thermograph4)
	(supports instrument41 image2)
	(calibration_target instrument41 Star2)
	(on_board instrument36 satellite8)
	(on_board instrument37 satellite8)
	(on_board instrument38 satellite8)
	(on_board instrument39 satellite8)
	(on_board instrument40 satellite8)
	(on_board instrument41 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star7)
	(supports instrument42 spectrograph3)
	(supports instrument42 image2)
	(supports instrument42 thermograph0)
	(calibration_target instrument42 Star6)
	(calibration_target instrument42 Star2)
	(supports instrument43 thermograph0)
	(calibration_target instrument43 Star6)
	(supports instrument44 thermograph0)
	(calibration_target instrument44 Star0)
	(supports instrument45 thermograph4)
	(supports instrument45 spectrograph1)
	(supports instrument45 spectrograph3)
	(calibration_target instrument45 GroundStation5)
	(calibration_target instrument45 Star0)
	(on_board instrument42 satellite9)
	(on_board instrument43 satellite9)
	(on_board instrument44 satellite9)
	(on_board instrument45 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation1)
)
(:goal (and
	(pointing satellite1 GroundStation1)
	(pointing satellite2 GroundStation4)
	(pointing satellite3 Star2)
	(pointing satellite4 Star7)
	(pointing satellite7 Star3)
	(pointing satellite9 GroundStation4)
	(have_image Star7 spectrograph3)
))

)
