(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite3 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite4 - satellite
	instrument27 - instrument
	satellite5 - satellite
	instrument28 - instrument
	instrument29 - instrument
	satellite6 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	satellite7 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	satellite8 - satellite
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	satellite9 - satellite
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	infrared3 - mode
	image1 - mode
	infrared2 - mode
	infrared4 - mode
	image0 - mode
	GroundStation6 - direction
	GroundStation0 - direction
	Star3 - direction
	GroundStation5 - direction
	GroundStation2 - direction
	GroundStation4 - direction
	Star1 - direction
	Star7 - direction
	Star8 - direction
)
(:init
	(supports instrument0 infrared3)
	(supports instrument0 infrared2)
	(supports instrument0 infrared4)
	(calibration_target instrument0 Star1)
	(calibration_target instrument0 Star3)
	(supports instrument1 infrared4)
	(supports instrument1 image1)
	(calibration_target instrument1 GroundStation2)
	(calibration_target instrument1 GroundStation4)
	(supports instrument2 image1)
	(supports instrument2 infrared2)
	(calibration_target instrument2 GroundStation4)
	(supports instrument3 image1)
	(supports instrument3 image0)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 GroundStation5)
	(supports instrument4 image0)
	(calibration_target instrument4 GroundStation0)
	(calibration_target instrument4 GroundStation5)
	(supports instrument5 infrared4)
	(supports instrument5 image0)
	(supports instrument5 infrared2)
	(calibration_target instrument5 GroundStation2)
	(supports instrument6 image0)
	(supports instrument6 image1)
	(calibration_target instrument6 Star1)
	(supports instrument7 infrared3)
	(supports instrument7 infrared2)
	(calibration_target instrument7 Star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation5)
	(supports instrument8 image0)
	(calibration_target instrument8 GroundStation6)
	(calibration_target instrument8 Star3)
	(supports instrument9 image1)
	(supports instrument9 infrared3)
	(supports instrument9 infrared2)
	(calibration_target instrument9 GroundStation0)
	(calibration_target instrument9 GroundStation5)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument10 infrared4)
	(supports instrument10 infrared2)
	(supports instrument10 image0)
	(calibration_target instrument10 GroundStation6)
	(calibration_target instrument10 GroundStation5)
	(supports instrument11 image0)
	(supports instrument11 infrared4)
	(calibration_target instrument11 Star1)
	(supports instrument12 infrared2)
	(supports instrument12 image0)
	(calibration_target instrument12 Star3)
	(calibration_target instrument12 GroundStation2)
	(supports instrument13 image0)
	(supports instrument13 infrared3)
	(supports instrument13 infrared4)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 infrared3)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 GroundStation2)
	(supports instrument15 image1)
	(supports instrument15 image0)
	(supports instrument15 infrared2)
	(calibration_target instrument15 Star1)
	(supports instrument16 infrared2)
	(supports instrument16 image1)
	(supports instrument16 infrared4)
	(calibration_target instrument16 GroundStation6)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation5)
	(supports instrument17 infrared2)
	(supports instrument17 infrared4)
	(supports instrument17 infrared3)
	(calibration_target instrument17 GroundStation5)
	(calibration_target instrument17 Star3)
	(supports instrument18 image0)
	(supports instrument18 infrared2)
	(calibration_target instrument18 GroundStation0)
	(supports instrument19 infrared2)
	(supports instrument19 image1)
	(supports instrument19 infrared4)
	(calibration_target instrument19 Star1)
	(supports instrument20 infrared2)
	(calibration_target instrument20 GroundStation4)
	(supports instrument21 infrared4)
	(supports instrument21 infrared2)
	(supports instrument21 image0)
	(calibration_target instrument21 Star1)
	(calibration_target instrument21 GroundStation6)
	(supports instrument22 infrared3)
	(supports instrument22 infrared4)
	(calibration_target instrument22 GroundStation4)
	(supports instrument23 infrared3)
	(calibration_target instrument23 GroundStation0)
	(supports instrument24 infrared2)
	(supports instrument24 image1)
	(supports instrument24 infrared4)
	(calibration_target instrument24 GroundStation0)
	(calibration_target instrument24 Star1)
	(supports instrument25 image1)
	(supports instrument25 image0)
	(supports instrument25 infrared3)
	(calibration_target instrument25 GroundStation4)
	(calibration_target instrument25 Star1)
	(supports instrument26 image0)
	(calibration_target instrument26 GroundStation5)
	(calibration_target instrument26 GroundStation0)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star1)
	(supports instrument27 infrared3)
	(calibration_target instrument27 GroundStation2)
	(on_board instrument27 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star3)
	(supports instrument28 image1)
	(calibration_target instrument28 GroundStation4)
	(calibration_target instrument28 Star1)
	(supports instrument29 infrared3)
	(calibration_target instrument29 Star3)
	(calibration_target instrument29 GroundStation2)
	(on_board instrument28 satellite5)
	(on_board instrument29 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation2)
	(supports instrument30 image0)
	(calibration_target instrument30 GroundStation5)
	(calibration_target instrument30 Star1)
	(supports instrument31 infrared4)
	(supports instrument31 image1)
	(supports instrument31 infrared2)
	(calibration_target instrument31 GroundStation4)
	(calibration_target instrument31 GroundStation2)
	(supports instrument32 infrared3)
	(supports instrument32 infrared2)
	(calibration_target instrument32 GroundStation0)
	(supports instrument33 infrared4)
	(calibration_target instrument33 GroundStation2)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation4)
	(supports instrument34 infrared4)
	(supports instrument34 image1)
	(supports instrument34 image0)
	(calibration_target instrument34 GroundStation5)
	(calibration_target instrument34 Star1)
	(supports instrument35 infrared3)
	(supports instrument35 infrared2)
	(supports instrument35 image1)
	(calibration_target instrument35 Star3)
	(supports instrument36 image1)
	(supports instrument36 infrared4)
	(calibration_target instrument36 Star3)
	(calibration_target instrument36 GroundStation2)
	(supports instrument37 infrared4)
	(supports instrument37 infrared3)
	(calibration_target instrument37 GroundStation6)
	(calibration_target instrument37 GroundStation0)
	(supports instrument38 infrared4)
	(calibration_target instrument38 GroundStation4)
	(calibration_target instrument38 GroundStation2)
	(supports instrument39 image0)
	(supports instrument39 image1)
	(calibration_target instrument39 GroundStation0)
	(calibration_target instrument39 GroundStation5)
	(supports instrument40 infrared3)
	(supports instrument40 image1)
	(supports instrument40 infrared4)
	(calibration_target instrument40 GroundStation6)
	(supports instrument41 image1)
	(supports instrument41 image0)
	(supports instrument41 infrared4)
	(calibration_target instrument41 GroundStation4)
	(calibration_target instrument41 GroundStation0)
	(supports instrument42 infrared2)
	(supports instrument42 infrared4)
	(supports instrument42 image1)
	(calibration_target instrument42 GroundStation6)
	(calibration_target instrument42 GroundStation0)
	(supports instrument43 infrared4)
	(calibration_target instrument43 GroundStation2)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(on_board instrument36 satellite7)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(on_board instrument39 satellite7)
	(on_board instrument40 satellite7)
	(on_board instrument41 satellite7)
	(on_board instrument42 satellite7)
	(on_board instrument43 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star7)
	(supports instrument44 infrared4)
	(supports instrument44 infrared3)
	(calibration_target instrument44 GroundStation5)
	(calibration_target instrument44 GroundStation6)
	(supports instrument45 infrared2)
	(supports instrument45 infrared4)
	(supports instrument45 image0)
	(calibration_target instrument45 GroundStation2)
	(calibration_target instrument45 GroundStation0)
	(supports instrument46 image1)
	(supports instrument46 image0)
	(calibration_target instrument46 GroundStation4)
	(supports instrument47 image1)
	(supports instrument47 image0)
	(calibration_target instrument47 Star1)
	(supports instrument48 infrared2)
	(calibration_target instrument48 Star3)
	(calibration_target instrument48 GroundStation4)
	(on_board instrument44 satellite8)
	(on_board instrument45 satellite8)
	(on_board instrument46 satellite8)
	(on_board instrument47 satellite8)
	(on_board instrument48 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star3)
	(supports instrument49 infrared2)
	(supports instrument49 image1)
	(supports instrument49 infrared3)
	(calibration_target instrument49 GroundStation2)
	(supports instrument50 infrared3)
	(supports instrument50 infrared2)
	(calibration_target instrument50 GroundStation5)
	(supports instrument51 image1)
	(calibration_target instrument51 GroundStation4)
	(calibration_target instrument51 GroundStation2)
	(supports instrument52 image1)
	(supports instrument52 infrared3)
	(supports instrument52 image0)
	(calibration_target instrument52 Star1)
	(supports instrument53 image0)
	(supports instrument53 infrared4)
	(supports instrument53 infrared2)
	(calibration_target instrument53 Star1)
	(on_board instrument49 satellite9)
	(on_board instrument50 satellite9)
	(on_board instrument51 satellite9)
	(on_board instrument52 satellite9)
	(on_board instrument53 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star1)
)
(:goal (and
	(pointing satellite0 GroundStation5)
	(pointing satellite1 GroundStation4)
	(pointing satellite9 GroundStation0)
	(have_image Star7 image0)
	(have_image Star8 infrared4)
))

)
