(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite3 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite4 - satellite
	instrument20 - instrument
	satellite5 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite6 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite7 - satellite
	instrument29 - instrument
	satellite8 - satellite
	instrument30 - instrument
	instrument31 - instrument
	satellite9 - satellite
	instrument32 - instrument
	instrument33 - instrument
	spectrograph3 - mode
	infrared1 - mode
	thermograph4 - mode
	image2 - mode
	infrared0 - mode
	Star1 - direction
	Star6 - direction
	GroundStation4 - direction
	Star2 - direction
	Star3 - direction
	GroundStation5 - direction
	Star0 - direction
	Star7 - direction
	Phenomenon8 - direction
)
(:init
	(supports instrument0 spectrograph3)
	(supports instrument0 image2)
	(supports instrument0 infrared1)
	(calibration_target instrument0 Star2)
	(calibration_target instrument0 GroundStation4)
	(supports instrument1 thermograph4)
	(supports instrument1 infrared1)
	(calibration_target instrument1 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star6)
	(supports instrument2 infrared0)
	(supports instrument2 infrared1)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 Star2)
	(calibration_target instrument2 Star3)
	(supports instrument3 spectrograph3)
	(calibration_target instrument3 GroundStation5)
	(supports instrument4 spectrograph3)
	(supports instrument4 infrared0)
	(supports instrument4 image2)
	(calibration_target instrument4 Star6)
	(calibration_target instrument4 Star3)
	(supports instrument5 image2)
	(supports instrument5 spectrograph3)
	(calibration_target instrument5 Star6)
	(calibration_target instrument5 Star0)
	(supports instrument6 thermograph4)
	(calibration_target instrument6 Star6)
	(calibration_target instrument6 Star0)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star6)
	(supports instrument7 infrared1)
	(supports instrument7 infrared0)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation5)
	(supports instrument8 thermograph4)
	(supports instrument8 spectrograph3)
	(supports instrument8 infrared0)
	(calibration_target instrument8 Star1)
	(supports instrument9 infrared0)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 Star6)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star7)
	(supports instrument10 spectrograph3)
	(supports instrument10 infrared1)
	(supports instrument10 infrared0)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 GroundStation5)
	(supports instrument11 spectrograph3)
	(calibration_target instrument11 Star2)
	(calibration_target instrument11 Star3)
	(supports instrument12 spectrograph3)
	(supports instrument12 infrared1)
	(supports instrument12 thermograph4)
	(calibration_target instrument12 Star6)
	(supports instrument13 infrared1)
	(supports instrument13 infrared0)
	(supports instrument13 spectrograph3)
	(calibration_target instrument13 Star6)
	(supports instrument14 infrared0)
	(calibration_target instrument14 GroundStation5)
	(calibration_target instrument14 Star3)
	(supports instrument15 spectrograph3)
	(supports instrument15 thermograph4)
	(supports instrument15 image2)
	(calibration_target instrument15 GroundStation4)
	(supports instrument16 thermograph4)
	(supports instrument16 image2)
	(supports instrument16 spectrograph3)
	(calibration_target instrument16 Star6)
	(calibration_target instrument16 Star0)
	(supports instrument17 image2)
	(supports instrument17 spectrograph3)
	(calibration_target instrument17 GroundStation5)
	(calibration_target instrument17 Star0)
	(supports instrument18 thermograph4)
	(supports instrument18 infrared0)
	(supports instrument18 infrared1)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 GroundStation4)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 Star1)
	(calibration_target instrument19 Star2)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation4)
	(supports instrument20 spectrograph3)
	(calibration_target instrument20 Star1)
	(calibration_target instrument20 GroundStation4)
	(on_board instrument20 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation5)
	(supports instrument21 spectrograph3)
	(calibration_target instrument21 Star3)
	(calibration_target instrument21 Star1)
	(supports instrument22 image2)
	(supports instrument22 spectrograph3)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 GroundStation5)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 Star6)
	(calibration_target instrument23 Star1)
	(supports instrument24 thermograph4)
	(calibration_target instrument24 GroundStation4)
	(calibration_target instrument24 Star6)
	(supports instrument25 image2)
	(supports instrument25 infrared0)
	(calibration_target instrument25 Star1)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star6)
	(supports instrument26 spectrograph3)
	(calibration_target instrument26 Star0)
	(supports instrument27 infrared1)
	(supports instrument27 infrared0)
	(supports instrument27 image2)
	(calibration_target instrument27 GroundStation5)
	(calibration_target instrument27 GroundStation4)
	(supports instrument28 spectrograph3)
	(supports instrument28 infrared0)
	(supports instrument28 infrared1)
	(calibration_target instrument28 Star6)
	(calibration_target instrument28 Star1)
	(on_board instrument26 satellite6)
	(on_board instrument27 satellite6)
	(on_board instrument28 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation5)
	(supports instrument29 spectrograph3)
	(supports instrument29 image2)
	(calibration_target instrument29 Star2)
	(calibration_target instrument29 GroundStation4)
	(on_board instrument29 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation5)
	(supports instrument30 infrared1)
	(supports instrument30 spectrograph3)
	(supports instrument30 image2)
	(calibration_target instrument30 Star3)
	(supports instrument31 infrared1)
	(calibration_target instrument31 Star3)
	(calibration_target instrument31 GroundStation5)
	(on_board instrument30 satellite8)
	(on_board instrument31 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star7)
	(supports instrument32 thermograph4)
	(supports instrument32 infrared0)
	(supports instrument32 infrared1)
	(calibration_target instrument32 GroundStation5)
	(supports instrument33 infrared0)
	(supports instrument33 image2)
	(calibration_target instrument33 Star0)
	(on_board instrument32 satellite9)
	(on_board instrument33 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star0)
)
(:goal (and
	(pointing satellite1 Star3)
	(pointing satellite5 Star2)
	(pointing satellite7 Star3)
	(pointing satellite9 Star0)
	(have_image Star7 infrared0)
	(have_image Phenomenon8 thermograph4)
))

)
