(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite2 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite3 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	satellite4 - satellite
	instrument28 - instrument
	satellite5 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite6 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	satellite7 - satellite
	instrument37 - instrument
	instrument38 - instrument
	satellite8 - satellite
	instrument39 - instrument
	satellite9 - satellite
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	spectrograph1 - mode
	thermograph4 - mode
	spectrograph0 - mode
	infrared3 - mode
	spectrograph2 - mode
	GroundStation4 - direction
	GroundStation5 - direction
	Star6 - direction
	Star0 - direction
	GroundStation3 - direction
	Star1 - direction
	GroundStation2 - direction
	Phenomenon7 - direction
	Star8 - direction
)
(:init
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 Star0)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 spectrograph1)
	(supports instrument1 spectrograph2)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 GroundStation4)
	(supports instrument2 infrared3)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 GroundStation4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation2)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 GroundStation3)
	(supports instrument4 spectrograph2)
	(supports instrument4 infrared3)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 Star1)
	(supports instrument5 spectrograph2)
	(calibration_target instrument5 Star1)
	(supports instrument6 infrared3)
	(supports instrument6 thermograph4)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star1)
	(calibration_target instrument6 Star6)
	(supports instrument7 spectrograph0)
	(supports instrument7 infrared3)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 Star0)
	(calibration_target instrument7 GroundStation3)
	(supports instrument8 spectrograph0)
	(supports instrument8 spectrograph2)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 GroundStation5)
	(supports instrument9 spectrograph1)
	(supports instrument9 spectrograph0)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 GroundStation4)
	(supports instrument10 spectrograph0)
	(supports instrument10 thermograph4)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 GroundStation2)
	(supports instrument11 thermograph4)
	(supports instrument11 spectrograph0)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 Star0)
	(supports instrument12 thermograph4)
	(supports instrument12 spectrograph1)
	(calibration_target instrument12 GroundStation4)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star6)
	(supports instrument13 spectrograph0)
	(supports instrument13 infrared3)
	(supports instrument13 spectrograph2)
	(calibration_target instrument13 Star6)
	(supports instrument14 infrared3)
	(supports instrument14 spectrograph0)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation2)
	(calibration_target instrument14 GroundStation5)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 GroundStation2)
	(supports instrument16 thermograph4)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 Star1)
	(calibration_target instrument16 GroundStation2)
	(supports instrument17 thermograph4)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 Star0)
	(calibration_target instrument17 GroundStation5)
	(supports instrument18 thermograph4)
	(supports instrument18 spectrograph2)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 GroundStation2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation3)
	(supports instrument19 infrared3)
	(supports instrument19 spectrograph1)
	(calibration_target instrument19 GroundStation3)
	(supports instrument20 spectrograph2)
	(supports instrument20 spectrograph0)
	(supports instrument20 spectrograph1)
	(calibration_target instrument20 Star0)
	(supports instrument21 infrared3)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 Star6)
	(supports instrument22 infrared3)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 Star6)
	(calibration_target instrument22 Star0)
	(supports instrument23 spectrograph2)
	(supports instrument23 spectrograph0)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 Star0)
	(calibration_target instrument23 GroundStation3)
	(supports instrument24 spectrograph2)
	(supports instrument24 spectrograph1)
	(supports instrument24 infrared3)
	(calibration_target instrument24 GroundStation5)
	(supports instrument25 spectrograph1)
	(supports instrument25 thermograph4)
	(supports instrument25 spectrograph0)
	(calibration_target instrument25 Star1)
	(supports instrument26 infrared3)
	(supports instrument26 spectrograph1)
	(calibration_target instrument26 GroundStation4)
	(supports instrument27 spectrograph1)
	(supports instrument27 thermograph4)
	(supports instrument27 spectrograph2)
	(calibration_target instrument27 Star6)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star8)
	(supports instrument28 infrared3)
	(supports instrument28 spectrograph2)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 GroundStation3)
	(on_board instrument28 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star6)
	(supports instrument29 spectrograph0)
	(supports instrument29 spectrograph1)
	(calibration_target instrument29 Star6)
	(supports instrument30 spectrograph0)
	(supports instrument30 spectrograph1)
	(calibration_target instrument30 Star6)
	(calibration_target instrument30 GroundStation4)
	(supports instrument31 spectrograph2)
	(supports instrument31 spectrograph0)
	(calibration_target instrument31 GroundStation3)
	(on_board instrument29 satellite5)
	(on_board instrument30 satellite5)
	(on_board instrument31 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation5)
	(supports instrument32 spectrograph2)
	(supports instrument32 infrared3)
	(calibration_target instrument32 Star0)
	(calibration_target instrument32 Star1)
	(supports instrument33 spectrograph1)
	(calibration_target instrument33 GroundStation5)
	(supports instrument34 thermograph4)
	(calibration_target instrument34 GroundStation4)
	(calibration_target instrument34 GroundStation2)
	(supports instrument35 thermograph4)
	(supports instrument35 spectrograph0)
	(supports instrument35 infrared3)
	(calibration_target instrument35 GroundStation4)
	(supports instrument36 spectrograph2)
	(supports instrument36 spectrograph0)
	(calibration_target instrument36 GroundStation5)
	(on_board instrument32 satellite6)
	(on_board instrument33 satellite6)
	(on_board instrument34 satellite6)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star6)
	(supports instrument37 thermograph4)
	(supports instrument37 infrared3)
	(calibration_target instrument37 GroundStation2)
	(calibration_target instrument37 Star0)
	(supports instrument38 spectrograph1)
	(supports instrument38 spectrograph2)
	(calibration_target instrument38 Star6)
	(calibration_target instrument38 GroundStation4)
	(on_board instrument37 satellite7)
	(on_board instrument38 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star1)
	(supports instrument39 spectrograph0)
	(supports instrument39 thermograph4)
	(calibration_target instrument39 GroundStation3)
	(on_board instrument39 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star0)
	(supports instrument40 spectrograph0)
	(calibration_target instrument40 Star6)
	(calibration_target instrument40 GroundStation3)
	(supports instrument41 spectrograph2)
	(supports instrument41 infrared3)
	(supports instrument41 spectrograph1)
	(calibration_target instrument41 GroundStation2)
	(calibration_target instrument41 GroundStation4)
	(supports instrument42 spectrograph0)
	(supports instrument42 thermograph4)
	(calibration_target instrument42 Star6)
	(calibration_target instrument42 GroundStation5)
	(supports instrument43 spectrograph0)
	(supports instrument43 thermograph4)
	(supports instrument43 spectrograph2)
	(calibration_target instrument43 Star0)
	(calibration_target instrument43 GroundStation2)
	(supports instrument44 spectrograph2)
	(calibration_target instrument44 Star0)
	(supports instrument45 infrared3)
	(calibration_target instrument45 Star1)
	(calibration_target instrument45 GroundStation3)
	(supports instrument46 spectrograph2)
	(calibration_target instrument46 GroundStation2)
	(on_board instrument40 satellite9)
	(on_board instrument41 satellite9)
	(on_board instrument42 satellite9)
	(on_board instrument43 satellite9)
	(on_board instrument44 satellite9)
	(on_board instrument45 satellite9)
	(on_board instrument46 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation5)
)
(:goal (and
	(pointing satellite0 Star6)
	(pointing satellite6 GroundStation4)
	(pointing satellite7 GroundStation5)
	(pointing satellite8 Star0)
	(have_image Phenomenon7 spectrograph1)
	(have_image Star8 spectrograph1)
))

)
