(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite4 - satellite
	instrument13 - instrument
	instrument14 - instrument
	satellite5 - satellite
	instrument15 - instrument
	satellite6 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite7 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite8 - satellite
	instrument27 - instrument
	instrument28 - instrument
	satellite9 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	infrared2 - mode
	infrared4 - mode
	image3 - mode
	thermograph0 - mode
	infrared1 - mode
	Star0 - direction
	Star3 - direction
	Star6 - direction
	GroundStation4 - direction
	Star5 - direction
	Star1 - direction
	GroundStation2 - direction
	Phenomenon7 - direction
	Phenomenon8 - direction
)
(:init
	(supports instrument0 infrared4)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 Star3)
	(supports instrument1 image3)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 Star0)
	(supports instrument2 infrared1)
	(supports instrument2 infrared2)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 Star3)
	(supports instrument3 infrared1)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 GroundStation4)
	(supports instrument4 infrared4)
	(supports instrument4 image3)
	(calibration_target instrument4 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(supports instrument5 infrared1)
	(calibration_target instrument5 Star1)
	(calibration_target instrument5 Star0)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star1)
	(supports instrument6 image3)
	(supports instrument6 infrared2)
	(calibration_target instrument6 Star5)
	(supports instrument7 infrared1)
	(calibration_target instrument7 Star1)
	(calibration_target instrument7 Star0)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation4)
	(supports instrument8 infrared1)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 GroundStation4)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 infrared2)
	(supports instrument10 thermograph0)
	(supports instrument10 infrared1)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 Star1)
	(supports instrument11 infrared1)
	(calibration_target instrument11 Star6)
	(supports instrument12 infrared1)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon8)
	(supports instrument13 image3)
	(calibration_target instrument13 Star3)
	(supports instrument14 thermograph0)
	(supports instrument14 infrared2)
	(supports instrument14 infrared1)
	(calibration_target instrument14 GroundStation2)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation4)
	(supports instrument15 thermograph0)
	(supports instrument15 infrared2)
	(calibration_target instrument15 Star5)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon7)
	(supports instrument16 image3)
	(supports instrument16 infrared1)
	(supports instrument16 infrared4)
	(calibration_target instrument16 GroundStation4)
	(supports instrument17 thermograph0)
	(supports instrument17 image3)
	(calibration_target instrument17 Star1)
	(supports instrument18 infrared1)
	(supports instrument18 infrared4)
	(supports instrument18 infrared2)
	(calibration_target instrument18 Star1)
	(supports instrument19 image3)
	(calibration_target instrument19 GroundStation4)
	(supports instrument20 image3)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 Star6)
	(supports instrument21 thermograph0)
	(supports instrument21 infrared4)
	(calibration_target instrument21 Star0)
	(calibration_target instrument21 GroundStation2)
	(supports instrument22 image3)
	(supports instrument22 infrared4)
	(supports instrument22 infrared2)
	(calibration_target instrument22 Star0)
	(supports instrument23 infrared2)
	(supports instrument23 thermograph0)
	(calibration_target instrument23 Star6)
	(calibration_target instrument23 Star1)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(on_board instrument20 satellite6)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(on_board instrument23 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation2)
	(supports instrument24 infrared2)
	(supports instrument24 infrared4)
	(supports instrument24 image3)
	(calibration_target instrument24 GroundStation2)
	(supports instrument25 infrared2)
	(supports instrument25 thermograph0)
	(supports instrument25 infrared1)
	(calibration_target instrument25 GroundStation4)
	(supports instrument26 thermograph0)
	(supports instrument26 infrared2)
	(calibration_target instrument26 Star3)
	(calibration_target instrument26 Star6)
	(on_board instrument24 satellite7)
	(on_board instrument25 satellite7)
	(on_board instrument26 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon7)
	(supports instrument27 infrared4)
	(supports instrument27 image3)
	(supports instrument27 thermograph0)
	(calibration_target instrument27 GroundStation4)
	(calibration_target instrument27 Star0)
	(supports instrument28 infrared1)
	(supports instrument28 thermograph0)
	(supports instrument28 infrared2)
	(calibration_target instrument28 Star3)
	(calibration_target instrument28 Star6)
	(on_board instrument27 satellite8)
	(on_board instrument28 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star5)
	(supports instrument29 infrared2)
	(supports instrument29 image3)
	(calibration_target instrument29 GroundStation4)
	(calibration_target instrument29 Star1)
	(supports instrument30 image3)
	(calibration_target instrument30 GroundStation4)
	(calibration_target instrument30 Star3)
	(supports instrument31 infrared4)
	(supports instrument31 thermograph0)
	(supports instrument31 image3)
	(calibration_target instrument31 GroundStation4)
	(calibration_target instrument31 Star6)
	(supports instrument32 infrared4)
	(calibration_target instrument32 Star5)
	(calibration_target instrument32 Star1)
	(supports instrument33 thermograph0)
	(supports instrument33 image3)
	(supports instrument33 infrared4)
	(calibration_target instrument33 Star1)
	(supports instrument34 infrared1)
	(calibration_target instrument34 GroundStation2)
	(on_board instrument29 satellite9)
	(on_board instrument30 satellite9)
	(on_board instrument31 satellite9)
	(on_board instrument32 satellite9)
	(on_board instrument33 satellite9)
	(on_board instrument34 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star3)
)
(:goal (and
	(pointing satellite0 Star6)
	(pointing satellite1 Star0)
	(pointing satellite3 Star1)
	(pointing satellite4 Star6)
	(pointing satellite5 Star1)
	(have_image Phenomenon7 image3)
	(have_image Phenomenon8 infrared1)
))

)
