(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite3 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite4 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	satellite6 - satellite
	instrument18 - instrument
	satellite7 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite8 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite9 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	spectrograph1 - mode
	spectrograph2 - mode
	image0 - mode
	image3 - mode
	thermograph4 - mode
	Star33 - direction
	Star31 - direction
	GroundStation26 - direction
	Star7 - direction
	GroundStation13 - direction
	GroundStation18 - direction
	GroundStation21 - direction
	GroundStation29 - direction
	GroundStation23 - direction
	GroundStation10 - direction
	Star27 - direction
	GroundStation3 - direction
	Star19 - direction
	Star11 - direction
	Star17 - direction
	Star1 - direction
	GroundStation15 - direction
	GroundStation8 - direction
	GroundStation20 - direction
	GroundStation24 - direction
	Star5 - direction
	GroundStation6 - direction
	Star12 - direction
	Star25 - direction
	GroundStation0 - direction
	GroundStation4 - direction
	GroundStation16 - direction
	Star22 - direction
	Star30 - direction
	GroundStation2 - direction
	Star9 - direction
	Star14 - direction
	Star32 - direction
	GroundStation28 - direction
	Star34 - direction
	Star35 - direction
)
(:init
	(supports instrument0 image3)
	(supports instrument0 thermograph4)
	(calibration_target instrument0 GroundStation24)
	(supports instrument1 image0)
	(calibration_target instrument1 GroundStation21)
	(calibration_target instrument1 GroundStation16)
	(calibration_target instrument1 Star31)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 GroundStation18)
	(calibration_target instrument1 Star12)
	(calibration_target instrument1 GroundStation8)
	(supports instrument2 thermograph4)
	(supports instrument2 spectrograph2)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 Star19)
	(calibration_target instrument2 Star7)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 GroundStation16)
	(calibration_target instrument2 GroundStation18)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 GroundStation0)
	(calibration_target instrument2 GroundStation26)
	(calibration_target instrument2 GroundStation21)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation28)
	(supports instrument3 image0)
	(supports instrument3 thermograph4)
	(supports instrument3 image3)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 Star33)
	(calibration_target instrument3 GroundStation18)
	(calibration_target instrument3 GroundStation21)
	(calibration_target instrument3 GroundStation29)
	(calibration_target instrument3 Star31)
	(calibration_target instrument3 Star32)
	(calibration_target instrument3 GroundStation28)
	(supports instrument4 image0)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 GroundStation16)
	(calibration_target instrument4 GroundStation28)
	(calibration_target instrument4 Star11)
	(calibration_target instrument4 Star19)
	(calibration_target instrument4 GroundStation13)
	(calibration_target instrument4 Star12)
	(calibration_target instrument4 Star27)
	(calibration_target instrument4 GroundStation26)
	(calibration_target instrument4 Star22)
	(calibration_target instrument4 GroundStation2)
	(calibration_target instrument4 Star14)
	(supports instrument5 image3)
	(calibration_target instrument5 Star25)
	(calibration_target instrument5 Star11)
	(calibration_target instrument5 GroundStation21)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 GroundStation24)
	(calibration_target instrument5 GroundStation29)
	(calibration_target instrument5 Star27)
	(calibration_target instrument5 Star5)
	(calibration_target instrument5 Star22)
	(calibration_target instrument5 Star31)
	(calibration_target instrument5 Star30)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 GroundStation8)
	(calibration_target instrument6 GroundStation0)
	(calibration_target instrument6 GroundStation16)
	(calibration_target instrument6 GroundStation28)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation6)
	(supports instrument7 spectrograph2)
	(supports instrument7 image3)
	(calibration_target instrument7 Star32)
	(calibration_target instrument7 GroundStation26)
	(calibration_target instrument7 Star17)
	(calibration_target instrument7 Star30)
	(calibration_target instrument7 GroundStation6)
	(calibration_target instrument7 GroundStation15)
	(supports instrument8 image0)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 GroundStation8)
	(calibration_target instrument8 GroundStation24)
	(supports instrument9 image3)
	(supports instrument9 spectrograph1)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 GroundStation20)
	(calibration_target instrument9 Star32)
	(supports instrument10 spectrograph2)
	(supports instrument10 image3)
	(supports instrument10 image0)
	(calibration_target instrument10 Star19)
	(calibration_target instrument10 GroundStation13)
	(calibration_target instrument10 Star31)
	(supports instrument11 spectrograph1)
	(supports instrument11 image3)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 Star17)
	(calibration_target instrument11 GroundStation10)
	(calibration_target instrument11 GroundStation2)
	(calibration_target instrument11 Star5)
	(calibration_target instrument11 Star14)
	(calibration_target instrument11 GroundStation16)
	(calibration_target instrument11 GroundStation23)
	(calibration_target instrument11 Star25)
	(calibration_target instrument11 GroundStation26)
	(calibration_target instrument11 GroundStation15)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation10)
	(supports instrument12 thermograph4)
	(supports instrument12 image3)
	(supports instrument12 spectrograph1)
	(calibration_target instrument12 Star14)
	(calibration_target instrument12 GroundStation3)
	(calibration_target instrument12 GroundStation20)
	(calibration_target instrument12 GroundStation0)
	(supports instrument13 thermograph4)
	(supports instrument13 spectrograph2)
	(calibration_target instrument13 GroundStation28)
	(calibration_target instrument13 Star31)
	(calibration_target instrument13 Star7)
	(calibration_target instrument13 Star19)
	(calibration_target instrument13 Star17)
	(calibration_target instrument13 GroundStation15)
	(calibration_target instrument13 Star33)
	(calibration_target instrument13 Star32)
	(calibration_target instrument13 Star30)
	(calibration_target instrument13 Star14)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star14)
	(supports instrument14 image3)
	(calibration_target instrument14 Star19)
	(calibration_target instrument14 Star30)
	(calibration_target instrument14 GroundStation28)
	(calibration_target instrument14 Star31)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 Star14)
	(supports instrument15 thermograph4)
	(supports instrument15 spectrograph1)
	(calibration_target instrument15 Star22)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 GroundStation20)
	(calibration_target instrument16 Star11)
	(calibration_target instrument16 Star7)
	(calibration_target instrument16 GroundStation4)
	(calibration_target instrument16 GroundStation3)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation8)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 Star14)
	(calibration_target instrument17 GroundStation6)
	(calibration_target instrument17 GroundStation10)
	(calibration_target instrument17 Star25)
	(calibration_target instrument17 Star1)
	(calibration_target instrument17 Star32)
	(calibration_target instrument17 GroundStation2)
	(calibration_target instrument17 Star9)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 GroundStation26)
	(calibration_target instrument17 Star7)
	(on_board instrument17 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation10)
	(supports instrument18 thermograph4)
	(supports instrument18 image3)
	(supports instrument18 spectrograph2)
	(calibration_target instrument18 Star12)
	(calibration_target instrument18 Star30)
	(calibration_target instrument18 Star1)
	(calibration_target instrument18 Star19)
	(on_board instrument18 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation16)
	(supports instrument19 image0)
	(supports instrument19 spectrograph1)
	(calibration_target instrument19 GroundStation24)
	(calibration_target instrument19 GroundStation0)
	(calibration_target instrument19 Star7)
	(calibration_target instrument19 Star12)
	(calibration_target instrument19 GroundStation8)
	(calibration_target instrument19 GroundStation28)
	(calibration_target instrument19 GroundStation18)
	(calibration_target instrument19 Star1)
	(supports instrument20 spectrograph2)
	(supports instrument20 image3)
	(supports instrument20 image0)
	(calibration_target instrument20 Star25)
	(calibration_target instrument20 Star17)
	(calibration_target instrument20 GroundStation24)
	(calibration_target instrument20 Star5)
	(supports instrument21 spectrograph1)
	(supports instrument21 spectrograph2)
	(calibration_target instrument21 Star5)
	(calibration_target instrument21 GroundStation24)
	(calibration_target instrument21 GroundStation0)
	(calibration_target instrument21 Star22)
	(calibration_target instrument21 Star17)
	(calibration_target instrument21 GroundStation28)
	(calibration_target instrument21 Star32)
	(calibration_target instrument21 Star19)
	(calibration_target instrument21 GroundStation15)
	(supports instrument22 spectrograph2)
	(supports instrument22 thermograph4)
	(supports instrument22 spectrograph1)
	(calibration_target instrument22 Star32)
	(calibration_target instrument22 Star9)
	(calibration_target instrument22 GroundStation10)
	(calibration_target instrument22 GroundStation8)
	(calibration_target instrument22 Star22)
	(calibration_target instrument22 GroundStation15)
	(calibration_target instrument22 Star30)
	(calibration_target instrument22 GroundStation18)
	(calibration_target instrument22 Star12)
	(calibration_target instrument22 GroundStation2)
	(supports instrument23 spectrograph1)
	(calibration_target instrument23 Star9)
	(calibration_target instrument23 Star17)
	(calibration_target instrument23 Star5)
	(calibration_target instrument23 GroundStation8)
	(calibration_target instrument23 GroundStation3)
	(calibration_target instrument23 Star12)
	(calibration_target instrument23 GroundStation15)
	(calibration_target instrument23 GroundStation13)
	(calibration_target instrument23 Star7)
	(calibration_target instrument23 Star11)
	(calibration_target instrument23 Star19)
	(on_board instrument19 satellite7)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(on_board instrument23 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star31)
	(supports instrument24 image3)
	(calibration_target instrument24 Star5)
	(calibration_target instrument24 Star27)
	(calibration_target instrument24 GroundStation0)
	(calibration_target instrument24 GroundStation20)
	(calibration_target instrument24 GroundStation13)
	(calibration_target instrument24 Star14)
	(supports instrument25 thermograph4)
	(calibration_target instrument25 GroundStation24)
	(calibration_target instrument25 GroundStation15)
	(calibration_target instrument25 GroundStation21)
	(calibration_target instrument25 GroundStation18)
	(calibration_target instrument25 GroundStation10)
	(calibration_target instrument25 GroundStation20)
	(calibration_target instrument25 GroundStation29)
	(calibration_target instrument25 Star22)
	(supports instrument26 image0)
	(supports instrument26 thermograph4)
	(calibration_target instrument26 GroundStation10)
	(calibration_target instrument26 GroundStation6)
	(calibration_target instrument26 GroundStation23)
	(calibration_target instrument26 Star25)
	(calibration_target instrument26 GroundStation29)
	(calibration_target instrument26 GroundStation15)
	(calibration_target instrument26 Star27)
	(calibration_target instrument26 Star17)
	(supports instrument27 spectrograph2)
	(calibration_target instrument27 GroundStation0)
	(calibration_target instrument27 Star12)
	(calibration_target instrument27 GroundStation6)
	(calibration_target instrument27 Star19)
	(calibration_target instrument27 Star32)
	(calibration_target instrument27 Star9)
	(calibration_target instrument27 GroundStation3)
	(calibration_target instrument27 Star27)
	(calibration_target instrument27 Star25)
	(supports instrument28 image3)
	(supports instrument28 spectrograph2)
	(calibration_target instrument28 Star17)
	(calibration_target instrument28 Star5)
	(calibration_target instrument28 Star11)
	(calibration_target instrument28 GroundStation6)
	(calibration_target instrument28 GroundStation20)
	(calibration_target instrument28 GroundStation24)
	(supports instrument29 thermograph4)
	(supports instrument29 spectrograph2)
	(supports instrument29 image0)
	(calibration_target instrument29 Star25)
	(on_board instrument24 satellite8)
	(on_board instrument25 satellite8)
	(on_board instrument26 satellite8)
	(on_board instrument27 satellite8)
	(on_board instrument28 satellite8)
	(on_board instrument29 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star27)
	(supports instrument30 image3)
	(calibration_target instrument30 GroundStation16)
	(calibration_target instrument30 GroundStation20)
	(calibration_target instrument30 GroundStation8)
	(calibration_target instrument30 GroundStation15)
	(calibration_target instrument30 Star1)
	(calibration_target instrument30 Star30)
	(calibration_target instrument30 Star17)
	(calibration_target instrument30 Star32)
	(supports instrument31 image0)
	(supports instrument31 image3)
	(supports instrument31 spectrograph2)
	(calibration_target instrument31 GroundStation6)
	(calibration_target instrument31 Star5)
	(calibration_target instrument31 GroundStation24)
	(calibration_target instrument31 Star22)
	(supports instrument32 thermograph4)
	(supports instrument32 image3)
	(supports instrument32 image0)
	(calibration_target instrument32 GroundStation28)
	(calibration_target instrument32 Star22)
	(calibration_target instrument32 GroundStation16)
	(calibration_target instrument32 GroundStation4)
	(calibration_target instrument32 GroundStation0)
	(calibration_target instrument32 Star14)
	(calibration_target instrument32 Star25)
	(calibration_target instrument32 Star12)
	(supports instrument33 thermograph4)
	(calibration_target instrument33 GroundStation28)
	(calibration_target instrument33 Star32)
	(calibration_target instrument33 Star14)
	(calibration_target instrument33 Star9)
	(calibration_target instrument33 GroundStation2)
	(calibration_target instrument33 Star30)
	(on_board instrument30 satellite9)
	(on_board instrument31 satellite9)
	(on_board instrument32 satellite9)
	(on_board instrument33 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star1)
)
(:goal (and
	(pointing satellite1 Star14)
	(pointing satellite3 GroundStation10)
	(pointing satellite4 GroundStation23)
	(have_image Star34 image3)
	(have_image Star35 thermograph4)
))

)
