(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	satellite6 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite7 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite8 - satellite
	instrument23 - instrument
	instrument24 - instrument
	satellite9 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	thermograph4 - mode
	spectrograph0 - mode
	infrared3 - mode
	spectrograph1 - mode
	spectrograph2 - mode
	GroundStation21 - direction
	GroundStation9 - direction
	Star23 - direction
	GroundStation26 - direction
	Star20 - direction
	Star25 - direction
	Star39 - direction
	Star6 - direction
	GroundStation18 - direction
	GroundStation24 - direction
	GroundStation28 - direction
	Star30 - direction
	GroundStation17 - direction
	Star38 - direction
	Star15 - direction
	Star32 - direction
	GroundStation16 - direction
	Star10 - direction
	Star35 - direction
	Star13 - direction
	GroundStation3 - direction
	GroundStation5 - direction
	GroundStation2 - direction
	GroundStation22 - direction
	GroundStation37 - direction
	Star0 - direction
	Star7 - direction
	GroundStation14 - direction
	GroundStation34 - direction
	Star29 - direction
	Star19 - direction
	GroundStation4 - direction
	Star1 - direction
	GroundStation36 - direction
	GroundStation33 - direction
	Star8 - direction
	GroundStation12 - direction
	Star11 - direction
	GroundStation31 - direction
	GroundStation27 - direction
	Star40 - direction
	Star41 - direction
)
(:init
	(supports instrument0 infrared3)
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 GroundStation27)
	(supports instrument1 spectrograph0)
	(supports instrument1 spectrograph1)
	(calibration_target instrument1 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star30)
	(supports instrument2 thermograph4)
	(supports instrument2 spectrograph0)
	(supports instrument2 spectrograph2)
	(calibration_target instrument2 GroundStation22)
	(calibration_target instrument2 GroundStation37)
	(calibration_target instrument2 Star29)
	(calibration_target instrument2 GroundStation9)
	(calibration_target instrument2 Star19)
	(calibration_target instrument2 Star15)
	(calibration_target instrument2 GroundStation16)
	(calibration_target instrument2 Star38)
	(calibration_target instrument2 GroundStation5)
	(calibration_target instrument2 GroundStation27)
	(calibration_target instrument2 Star39)
	(calibration_target instrument2 Star32)
	(supports instrument3 thermograph4)
	(supports instrument3 spectrograph2)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 GroundStation36)
	(calibration_target instrument3 Star38)
	(calibration_target instrument3 Star7)
	(calibration_target instrument3 Star30)
	(calibration_target instrument3 GroundStation26)
	(calibration_target instrument3 GroundStation18)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 Star19)
	(supports instrument4 thermograph4)
	(supports instrument4 spectrograph2)
	(supports instrument4 spectrograph0)
	(calibration_target instrument4 GroundStation9)
	(supports instrument5 spectrograph1)
	(supports instrument5 infrared3)
	(calibration_target instrument5 GroundStation3)
	(calibration_target instrument5 GroundStation22)
	(calibration_target instrument5 GroundStation31)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 GroundStation28)
	(calibration_target instrument5 GroundStation14)
	(calibration_target instrument5 Star1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star35)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 GroundStation17)
	(calibration_target instrument6 Star7)
	(calibration_target instrument6 GroundStation34)
	(calibration_target instrument6 GroundStation9)
	(calibration_target instrument6 GroundStation31)
	(calibration_target instrument6 GroundStation16)
	(calibration_target instrument6 GroundStation21)
	(calibration_target instrument6 GroundStation22)
	(calibration_target instrument6 GroundStation24)
	(calibration_target instrument6 GroundStation26)
	(calibration_target instrument6 Star15)
	(calibration_target instrument6 Star30)
	(supports instrument7 thermograph4)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 Star32)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 Star19)
	(calibration_target instrument7 Star1)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 GroundStation31)
	(calibration_target instrument7 Star35)
	(calibration_target instrument7 Star25)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star29)
	(supports instrument8 infrared3)
	(supports instrument8 spectrograph2)
	(calibration_target instrument8 Star25)
	(calibration_target instrument8 GroundStation27)
	(supports instrument9 thermograph4)
	(supports instrument9 infrared3)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 GroundStation17)
	(calibration_target instrument9 GroundStation22)
	(calibration_target instrument9 Star11)
	(calibration_target instrument9 Star13)
	(calibration_target instrument9 Star29)
	(calibration_target instrument9 GroundStation14)
	(calibration_target instrument9 Star32)
	(calibration_target instrument9 GroundStation9)
	(calibration_target instrument9 Star39)
	(calibration_target instrument9 GroundStation28)
	(calibration_target instrument9 GroundStation4)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star20)
	(supports instrument10 spectrograph0)
	(supports instrument10 thermograph4)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 Star25)
	(calibration_target instrument10 GroundStation22)
	(calibration_target instrument10 Star13)
	(calibration_target instrument10 Star15)
	(calibration_target instrument10 Star38)
	(calibration_target instrument10 GroundStation26)
	(calibration_target instrument10 GroundStation16)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation9)
	(supports instrument11 spectrograph0)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 Star30)
	(calibration_target instrument11 Star15)
	(on_board instrument11 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star8)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 GroundStation28)
	(calibration_target instrument12 Star6)
	(calibration_target instrument12 GroundStation17)
	(supports instrument13 thermograph4)
	(supports instrument13 spectrograph1)
	(supports instrument13 spectrograph2)
	(calibration_target instrument13 Star10)
	(calibration_target instrument13 GroundStation14)
	(calibration_target instrument13 Star13)
	(calibration_target instrument13 Star30)
	(calibration_target instrument13 Star29)
	(calibration_target instrument13 Star15)
	(on_board instrument12 satellite6)
	(on_board instrument13 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation37)
	(supports instrument14 spectrograph1)
	(supports instrument14 thermograph4)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 GroundStation2)
	(calibration_target instrument14 Star13)
	(calibration_target instrument14 GroundStation34)
	(calibration_target instrument14 Star10)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 Star23)
	(calibration_target instrument15 Star15)
	(calibration_target instrument15 Star30)
	(calibration_target instrument15 GroundStation9)
	(supports instrument16 spectrograph0)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 Star39)
	(supports instrument17 thermograph4)
	(supports instrument17 infrared3)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 Star0)
	(calibration_target instrument17 Star39)
	(calibration_target instrument17 Star20)
	(calibration_target instrument17 GroundStation22)
	(calibration_target instrument17 Star6)
	(calibration_target instrument17 Star8)
	(calibration_target instrument17 Star23)
	(calibration_target instrument17 GroundStation31)
	(calibration_target instrument17 Star38)
	(calibration_target instrument17 GroundStation24)
	(supports instrument18 spectrograph1)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 Star10)
	(calibration_target instrument18 GroundStation3)
	(calibration_target instrument18 GroundStation27)
	(calibration_target instrument18 GroundStation31)
	(calibration_target instrument18 GroundStation16)
	(calibration_target instrument18 Star11)
	(calibration_target instrument18 Star13)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 Star32)
	(supports instrument19 spectrograph0)
	(calibration_target instrument19 Star20)
	(calibration_target instrument19 Star13)
	(calibration_target instrument19 GroundStation14)
	(calibration_target instrument19 Star8)
	(calibration_target instrument19 Star23)
	(calibration_target instrument19 Star15)
	(calibration_target instrument19 Star1)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 GroundStation17)
	(calibration_target instrument19 GroundStation31)
	(calibration_target instrument19 Star25)
	(calibration_target instrument19 GroundStation4)
	(supports instrument20 infrared3)
	(calibration_target instrument20 GroundStation24)
	(calibration_target instrument20 GroundStation28)
	(calibration_target instrument20 GroundStation31)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 GroundStation12)
	(calibration_target instrument20 GroundStation16)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 GroundStation4)
	(calibration_target instrument20 GroundStation26)
	(calibration_target instrument20 Star30)
	(supports instrument21 spectrograph2)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 GroundStation3)
	(calibration_target instrument21 Star32)
	(calibration_target instrument21 GroundStation4)
	(calibration_target instrument21 Star11)
	(calibration_target instrument21 Star8)
	(calibration_target instrument21 GroundStation37)
	(calibration_target instrument21 Star35)
	(calibration_target instrument21 GroundStation36)
	(calibration_target instrument21 Star6)
	(calibration_target instrument21 GroundStation31)
	(calibration_target instrument21 Star10)
	(supports instrument22 spectrograph2)
	(supports instrument22 thermograph4)
	(supports instrument22 spectrograph0)
	(calibration_target instrument22 Star15)
	(calibration_target instrument22 GroundStation33)
	(calibration_target instrument22 Star7)
	(calibration_target instrument22 Star38)
	(calibration_target instrument22 Star30)
	(calibration_target instrument22 Star20)
	(calibration_target instrument22 GroundStation3)
	(calibration_target instrument22 Star11)
	(on_board instrument14 satellite7)
	(on_board instrument15 satellite7)
	(on_board instrument16 satellite7)
	(on_board instrument17 satellite7)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation34)
	(supports instrument23 thermograph4)
	(supports instrument23 spectrograph0)
	(supports instrument23 spectrograph2)
	(calibration_target instrument23 GroundStation24)
	(calibration_target instrument23 Star6)
	(calibration_target instrument23 Star39)
	(calibration_target instrument23 Star15)
	(calibration_target instrument23 GroundStation31)
	(calibration_target instrument23 Star25)
	(calibration_target instrument23 GroundStation34)
	(calibration_target instrument23 GroundStation5)
	(calibration_target instrument23 GroundStation4)
	(supports instrument24 spectrograph0)
	(calibration_target instrument24 GroundStation24)
	(calibration_target instrument24 Star15)
	(calibration_target instrument24 Star19)
	(calibration_target instrument24 GroundStation33)
	(calibration_target instrument24 GroundStation22)
	(calibration_target instrument24 GroundStation18)
	(calibration_target instrument24 GroundStation36)
	(calibration_target instrument24 GroundStation3)
	(on_board instrument23 satellite8)
	(on_board instrument24 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star20)
	(supports instrument25 infrared3)
	(calibration_target instrument25 GroundStation28)
	(calibration_target instrument25 GroundStation24)
	(calibration_target instrument25 Star32)
	(calibration_target instrument25 Star15)
	(supports instrument26 spectrograph1)
	(calibration_target instrument26 GroundStation3)
	(calibration_target instrument26 GroundStation31)
	(calibration_target instrument26 GroundStation16)
	(calibration_target instrument26 Star32)
	(calibration_target instrument26 Star15)
	(calibration_target instrument26 Star38)
	(calibration_target instrument26 Star0)
	(calibration_target instrument26 GroundStation17)
	(calibration_target instrument26 Star30)
	(supports instrument27 spectrograph2)
	(supports instrument27 spectrograph0)
	(supports instrument27 spectrograph1)
	(calibration_target instrument27 GroundStation2)
	(calibration_target instrument27 GroundStation5)
	(calibration_target instrument27 GroundStation3)
	(calibration_target instrument27 Star13)
	(calibration_target instrument27 GroundStation27)
	(calibration_target instrument27 Star35)
	(calibration_target instrument27 Star10)
	(supports instrument28 thermograph4)
	(calibration_target instrument28 GroundStation37)
	(calibration_target instrument28 GroundStation22)
	(supports instrument29 spectrograph0)
	(supports instrument29 infrared3)
	(calibration_target instrument29 GroundStation34)
	(calibration_target instrument29 GroundStation14)
	(calibration_target instrument29 Star7)
	(calibration_target instrument29 Star0)
	(supports instrument30 spectrograph1)
	(supports instrument30 infrared3)
	(supports instrument30 spectrograph2)
	(calibration_target instrument30 GroundStation36)
	(calibration_target instrument30 Star1)
	(calibration_target instrument30 GroundStation4)
	(calibration_target instrument30 Star19)
	(calibration_target instrument30 Star29)
	(supports instrument31 infrared3)
	(supports instrument31 spectrograph1)
	(calibration_target instrument31 Star8)
	(calibration_target instrument31 GroundStation33)
	(supports instrument32 spectrograph2)
	(supports instrument32 spectrograph1)
	(calibration_target instrument32 GroundStation27)
	(calibration_target instrument32 GroundStation31)
	(calibration_target instrument32 Star11)
	(calibration_target instrument32 GroundStation12)
	(on_board instrument25 satellite9)
	(on_board instrument26 satellite9)
	(on_board instrument27 satellite9)
	(on_board instrument28 satellite9)
	(on_board instrument29 satellite9)
	(on_board instrument30 satellite9)
	(on_board instrument31 satellite9)
	(on_board instrument32 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation9)
)
(:goal (and
	(pointing satellite2 GroundStation2)
	(pointing satellite9 Star20)
	(have_image Star40 infrared3)
	(have_image Star41 thermograph4)
))

)
